package com.turborep.turbotracker.product.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ConvertInventory generated by hbm2java
 */
@Entity
@Table(name = "convert_inventory", catalog = "")
public class ConvertInventory implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private ConvertInventoryId id;

	public ConvertInventory() {
	}

	public ConvertInventory(ConvertInventoryId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "itemCode", column = @Column(name = "ItemCode")),
			@AttributeOverride(name = "vendor", column = @Column(name = "Vendor")),
			@AttributeOverride(name = "description", column = @Column(name = "Description")),
			@AttributeOverride(name = "averageCost", column = @Column(name = "AverageCost", precision = 22, scale = 0)) })
	public ConvertInventoryId getId() {
		return this.id;
	}

	public void setId(ConvertInventoryId id) {
		this.id = id;
	}

}
