package com.turborep.turbotracker.product.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Prcategory generated by hbm2java
 */
@Entity
@Table(name = "prCategory", catalog = "")
public class PrCategory implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer prCategoryId;
	private String description;
	private Boolean inActive;
	private boolean markupCost;
	private BigDecimal markupAmount;

	public PrCategory() {
	}

	public PrCategory(boolean markupCost) {
		this.markupCost = markupCost;
	}

	public PrCategory(String description, Boolean inActive, boolean markupCost,
			BigDecimal markupAmount) {
		this.description = description;
		this.inActive = inActive;
		this.markupCost = markupCost;
		this.markupAmount = markupAmount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "prCategoryID", unique = true, nullable = false)
	public Integer getPrCategoryId() {
		return this.prCategoryId;
	}

	public void setPrCategoryId(Integer prCategoryId) {
		this.prCategoryId = prCategoryId;
	}

	@Column(name = "Description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "InActive")
	public Boolean getInActive() {
		return this.inActive;
	}

	public void setInActive(Boolean inActive) {
		this.inActive = inActive;
	}

	@Column(name = "MarkupCost", nullable = false)
	public boolean isMarkupCost() {
		return this.markupCost;
	}

	public void setMarkupCost(boolean markupCost) {
		this.markupCost = markupCost;
	}

	@Column(name = "MarkupAmount", scale = 4)
	public BigDecimal getMarkupAmount() {
		return this.markupAmount;
	}

	public void setMarkupAmount(BigDecimal markupAmount) {
		this.markupAmount = markupAmount;
	}

}
