package com.turborep.turbotracker.product.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Prinventorycount generated by hbm2java
 */
@Entity
@Table(name = "prInventoryCount", catalog = "")
public class Prinventorycount implements java.io.Serializable {

	private int prMasterId;
	private Integer prDepartmentId;
	private String itemCode;
	private String description;
	private BigDecimal systemOnHand;
	private BigDecimal countedOnHand;
	private Integer prwarehouseInventoryID;
	
	
	
	public Prinventorycount() {
	}

	public Prinventorycount(int prMasterId) {
		this.prMasterId = prMasterId;
	}

	public Prinventorycount(int prMasterId, Integer prDepartmentId,
			String itemCode, String description, BigDecimal systemOnHand,
			BigDecimal countedOnHand) {
		this.prMasterId = prMasterId;
		this.prDepartmentId = prDepartmentId;
		this.itemCode = itemCode;
		this.description = description;
		this.systemOnHand = systemOnHand;
		this.countedOnHand = countedOnHand;
	}

	@Id
	@Column(name = "prMasterID", unique = true, nullable = false)
	public int getPrMasterId() {
		return this.prMasterId;
	}

	public void setPrMasterId(int prMasterId) {
		this.prMasterId = prMasterId;
	}

	@Column(name = "prDepartmentID")
	public Integer getPrDepartmentId() {
		return this.prDepartmentId;
	}

	public void setPrDepartmentId(Integer prDepartmentId) {
		this.prDepartmentId = prDepartmentId;
	}

	@Column(name = "ItemCode", length = 20)
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	@Column(name = "Description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SystemOnHand", scale = 4)
	public BigDecimal getSystemOnHand() {
		return this.systemOnHand;
	}

	public void setSystemOnHand(BigDecimal systemOnHand) {
		this.systemOnHand = systemOnHand;
	}

	@Column(name = "CountedOnHand", scale = 4)
	public BigDecimal getCountedOnHand() {
		return this.countedOnHand;
	}

	public void setCountedOnHand(BigDecimal countedOnHand) {
		this.countedOnHand = countedOnHand;
	}

	@Transient
	public Integer getPrwarehouseInventoryID() {
		return prwarehouseInventoryID;
	}

	public void setPrwarehouseInventoryID(Integer prwarehouseInventoryID) {
		this.prwarehouseInventoryID = prwarehouseInventoryID;
	}

}
