package com.turborep.turbotracker.product.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Prmaster generated by hbm2java
 */
@Entity
@Table(name = "prMaster", catalog = "")
public class Prmaster implements java.io.Serializable {
	
	private Integer prMasterId;
	private Integer prDepartmentId;
	private Integer prCategoryId;
	private String itemCode;
	private String description;
	private Byte inActive;
	private Byte isInventory;
	private Byte isTaxable;
	private Byte printOnPos;
	private Byte printOnSos;
	private BigDecimal purchasingUnitMultiplier;
	private String purchasingUnitOfMeasure;
	private BigDecimal salesUnitMultiplier;
	private String salesUnitOfMeasure;
	private Integer rxMasterIdprimaryVendor;
	private String vendorItemNumber;
	private BigDecimal newPrice;
	private BigDecimal oldPrice;
	private BigDecimal lastCost;
	private BigDecimal salesPrice00;
	private BigDecimal salesPrice01;
	private BigDecimal salesPrice02;
	private BigDecimal salesPrice03;
	private BigDecimal salesPrice04;
	private BigDecimal salesPrice05;
	private BigDecimal salesPrice10;
	private BigDecimal salesPrice11;
	private BigDecimal salesPrice12;
	private BigDecimal salesPrice13;
	private BigDecimal salesPrice14;
	private BigDecimal salesPrice15;
	private BigDecimal salesPrice20;
	private BigDecimal salesPrice21;
	private BigDecimal salesPrice22;
	private BigDecimal salesPrice23;
	private BigDecimal salesPrice24;
	private BigDecimal salesPrice25;
	private BigDecimal salesPrice30;
	private BigDecimal salesPrice31;
	private BigDecimal salesPrice32;
	private BigDecimal salesPrice33;
	private BigDecimal salesPrice34;
	private BigDecimal salesPrice35;
	private BigDecimal salesPrice40;
	private BigDecimal salesPrice41;
	private BigDecimal salesPrice42;
	private BigDecimal salesPrice43;
	private BigDecimal salesPrice44;
	private BigDecimal salesPrice45;
	private BigDecimal salesPrice50;
	private BigDecimal salesPrice51;
	private BigDecimal salesPrice52;
	private BigDecimal salesPrice53;
	private BigDecimal salesPrice54;
	private BigDecimal salesPrice55;
	private BigDecimal initialCost;
	private BigDecimal averageCost;
	private BigDecimal oldAerageCost;
	private BigDecimal inventoryOnHand;
	private BigDecimal inventoryAllocated;
	private BigDecimal inventoryOnOrder;
	private BigDecimal inventoryOrderPoint;
	private BigDecimal inventoryOrderQuantity;
	private BigDecimal quantityBreak0;
	private BigDecimal quantityBreak1;
	private BigDecimal quantityBreak2;
	private BigDecimal quantityBreak3;
	private BigDecimal quantityBreak4;
	private BigDecimal quantityBreak5;
	private Byte singleItemTax;
	private Byte hasInitialCost;
	private Date costAsOf;
	private BigDecimal initialOnHand;
	private BigDecimal weight;
	private BigDecimal poCost;
	private BigDecimal boxQty;
	private Date createdOn;
	private Integer createdById;
	private String webSite;
	private BigDecimal salesPrice00_Old;
	private BigDecimal salesPrice00_New;
	private Date salesPrice00_Changed;
	private BigDecimal salesPrice10_Old;
	private BigDecimal salesPrice10_New;
	private Date salesPrice10_Changed;
	private BigDecimal salesPrice20_Old;
	private BigDecimal salesPrice20_New;
	private Date salesPrice20_Changed;
	private BigDecimal salesPrice30_Old;
	private BigDecimal salesPrice30_New;
	private Date salesPrice30_Changed;
	private BigDecimal salesPrice40_Old;
	private BigDecimal salesPrice40_New;
	private Date salesPrice40_Changed;
	private BigDecimal salesPrice50_Old;
	private BigDecimal salesPrice50_New;
	private Date salesPrice50_Changed;
	private BigDecimal averageCost_Old;
	private BigDecimal averageCost_New;
	private Date averageCost_Changed;
	private BigDecimal POCost_Old;
	private BigDecimal POCost_New;
	private Date POCost_Changed;
	private BigDecimal POMult;
	private String SOPopup;
	private Byte consignment;
	private String POPopup;
	private String CUPopup;
	private Byte printOnCUs;
	private Byte printOnPTs;
	private Byte labor;
	private Byte autoAssemble;
	private Integer rxMasterIDSecondaryVendor01;
	private Integer rxMasterIDSecondaryVendor02;
	private Integer rxMasterIDSecondaryVendor03;
	private Integer rxMasterIDSecondaryVendor04;
	private Integer rxMasterIDSecondaryVendor05;
	private Integer vendorItemNumber01;
	private Integer vendorItemNumber02;
	private Integer vendorItemNumber03;
	private Integer vendorItemNumber04;
	private Integer vendorItemNumber05;
	private Byte serialized;
	private BigDecimal submitted;
	private String vendorName;
	private String prCategory;
	private String prDepartment;
	private BigDecimal inventoryAvailable;
	private String primaryVendorName;
	private BigDecimal inventoryCounted;
	private Integer prWarehouseInventoryID;
	private BigDecimal totalCost;
	private BigDecimal inventorySuggestedOrder;
	private Integer ytd;
	private BigDecimal inventoryProjected;
	
	@Transient
	public BigDecimal getTotalCost() {
		return totalCost;
	}

	public void setTotalCost(BigDecimal totalCost) {
		this.totalCost = totalCost;
	}

	@Transient
	public BigDecimal getInventorySuggestedOrder() {
		return inventorySuggestedOrder;
	}

	public void setInventorySuggestedOrder(BigDecimal inventorySuggestedOrder) {
		this.inventorySuggestedOrder = inventorySuggestedOrder;
	}

	@Transient
	public Integer getYtd() {
		return ytd;
	}

	public void setYtd(Integer ytd) {
		this.ytd = ytd;
	}

	@Transient
	public BigDecimal getInventoryProjected() {
		return inventoryProjected;
	}

	public void setInventoryProjected(BigDecimal inventoryProjected) {
		this.inventoryProjected = inventoryProjected;
	}
	
	public Prmaster() {
	}	

	public Prmaster(Byte singleItemTax, Byte hasInitialCost) {
		this.singleItemTax = singleItemTax;
		this.hasInitialCost = hasInitialCost;
	}

	public Prmaster(Integer prDepartmentId, Integer prCategoryId,
			String itemCode, String description, Byte inActive,
			Byte isInventory, Byte isTaxable, Byte printOnPos,
			Byte printOnSos, BigDecimal purchasingUnitMultiplier,
			String purchasingUnitOfMeasure, BigDecimal salesUnitMultiplier,
			String salesUnitOfMeasure, Integer rxMasterIdprimaryVendor,
			String vendorItemNumber, BigDecimal salesPrice00,
			BigDecimal salesPrice01, BigDecimal salesPrice02,
			BigDecimal salesPrice03, BigDecimal salesPrice04,
			BigDecimal salesPrice05, BigDecimal salesPrice10,
			BigDecimal salesPrice11, BigDecimal salesPrice12,
			BigDecimal salesPrice13, BigDecimal salesPrice14,
			BigDecimal salesPrice15, BigDecimal salesPrice20,
			BigDecimal salesPrice21, BigDecimal salesPrice22,
			BigDecimal salesPrice23, BigDecimal salesPrice24,
			BigDecimal salesPrice25, BigDecimal salesPrice30,
			BigDecimal salesPrice31, BigDecimal salesPrice32,
			BigDecimal salesPrice33, BigDecimal salesPrice34,
			BigDecimal salesPrice35, BigDecimal salesPrice40,
			BigDecimal salesPrice41, BigDecimal salesPrice42,
			BigDecimal salesPrice43, BigDecimal salesPrice44,
			BigDecimal salesPrice45, BigDecimal salesPrice50,
			BigDecimal salesPrice51, BigDecimal salesPrice52,
			BigDecimal salesPrice53, BigDecimal salesPrice54,
			BigDecimal salesPrice55, BigDecimal initialCost,
			BigDecimal averageCost, BigDecimal inventoryOnHand,
			BigDecimal inventoryAllocated, BigDecimal inventoryOnOrder,
			BigDecimal inventoryOrderPoint, BigDecimal inventoryOrderQuantity,
			BigDecimal quantityBreak0, BigDecimal quantityBreak1,
			BigDecimal quantityBreak2, BigDecimal quantityBreak3,
			BigDecimal quantityBreak4, BigDecimal quantityBreak5,
			BigDecimal newPrice, BigDecimal oldPrice, BigDecimal lastCost, BigDecimal oldAerageCost,
			BigDecimal weight, BigDecimal poCost,	BigDecimal boxQty, Date createdOn, Integer createdById,
			String webSite,	BigDecimal salesPrice00_Old, BigDecimal salesPrice00_New, Date salesPrice00_Changed,
			BigDecimal salesPrice10_Old, BigDecimal salesPrice10_New, Date salesPrice10_Changed,
			BigDecimal salesPrice20_Old, BigDecimal salesPrice20_New, Date salesPrice20_Changed, BigDecimal salesPrice30_Old,
			BigDecimal salesPrice30_New, Date salesPrice30_Changed, BigDecimal salesPrice40_Old, BigDecimal salesPrice40_New,
			Date salesPrice40_Changed, BigDecimal salesPrice50_Old, BigDecimal salesPrice50_New, Date salesPrice50_Changed,
			BigDecimal averageCost_Old, BigDecimal averageCost_New, Date averageCost_Changed, BigDecimal POCost_Old,
			BigDecimal POCost_New, Date POCost_Changed, BigDecimal POMult, String SOPopup, Byte consignment, String POPopup, String CUPopup,
			Byte printOnCUs, Byte printOnPTs, Byte labor, Byte autoAssemble, Integer rxMasterIDSecondaryVendor01,
			Integer rxMasterIDSecondaryVendor02, Integer rxMasterIDSecondaryVendor03,
			Integer rxMasterIDSecondaryVendor04, Integer rxMasterIDSecondaryVendor05, Integer vendorItemNumber01,
			Integer vendorItemNumber02, Integer vendorItemNumber03, Integer vendorItemNumber04, Integer vendorItemNumber05,
			Byte serialized,	BigDecimal submitted, Byte singleItemTax, Byte hasInitialCost, Date costAsOf,
			BigDecimal initialOnHand) {
		this.prDepartmentId = prDepartmentId;
		this.prCategoryId = prCategoryId;
		this.itemCode = itemCode;
		this.description = description;
		this.inActive = inActive;
		this.isInventory = isInventory;
		this.isTaxable = isTaxable;
		this.printOnPos = printOnPos;
		this.printOnSos = printOnSos;
		this.purchasingUnitMultiplier = purchasingUnitMultiplier;
		this.purchasingUnitOfMeasure = purchasingUnitOfMeasure;
		this.salesUnitMultiplier = salesUnitMultiplier;
		this.salesUnitOfMeasure = salesUnitOfMeasure;
		this.rxMasterIdprimaryVendor = rxMasterIdprimaryVendor;
		this.vendorItemNumber = vendorItemNumber;
		this.salesPrice00 = salesPrice00;
		this.salesPrice01 = salesPrice01;
		this.salesPrice02 = salesPrice02;
		this.salesPrice03 = salesPrice03;
		this.salesPrice04 = salesPrice04;
		this.salesPrice05 = salesPrice05;
		this.salesPrice10 = salesPrice10;
		this.salesPrice11 = salesPrice11;
		this.salesPrice12 = salesPrice12;
		this.salesPrice13 = salesPrice13;
		this.salesPrice14 = salesPrice14;
		this.salesPrice15 = salesPrice15;
		this.salesPrice20 = salesPrice20;
		this.salesPrice21 = salesPrice21;
		this.salesPrice22 = salesPrice22;
		this.salesPrice23 = salesPrice23;
		this.salesPrice24 = salesPrice24;
		this.salesPrice25 = salesPrice25;
		this.salesPrice30 = salesPrice30;
		this.salesPrice31 = salesPrice31;
		this.salesPrice32 = salesPrice32;
		this.salesPrice33 = salesPrice33;
		this.salesPrice34 = salesPrice34;
		this.salesPrice35 = salesPrice35;
		this.salesPrice40 = salesPrice40;
		this.salesPrice41 = salesPrice41;
		this.salesPrice42 = salesPrice42;
		this.salesPrice43 = salesPrice43;
		this.salesPrice44 = salesPrice44;
		this.salesPrice45 = salesPrice45;
		this.salesPrice50 = salesPrice50;
		this.salesPrice51 = salesPrice51;
		this.salesPrice52 = salesPrice52;
		this.salesPrice53 = salesPrice53;
		this.salesPrice54 = salesPrice54;
		this.salesPrice55 = salesPrice55;
		this.initialCost = initialCost;
		this.averageCost = averageCost;
		this.inventoryOnHand = inventoryOnHand;
		this.inventoryAllocated = inventoryAllocated;
		this.inventoryOnOrder = inventoryOnOrder;
		this.inventoryOrderPoint = inventoryOrderPoint;
		this.inventoryOrderQuantity = inventoryOrderQuantity;
		this.quantityBreak0 = quantityBreak0;
		this.quantityBreak1 = quantityBreak1;
		this.quantityBreak2 = quantityBreak2;
		this.quantityBreak3 = quantityBreak3;
		this.quantityBreak4 = quantityBreak4;
		this.quantityBreak5 = quantityBreak5;
		this.singleItemTax = singleItemTax;
		this.hasInitialCost = hasInitialCost;
		this.costAsOf = costAsOf;
		this.initialOnHand = initialOnHand;
		this.autoAssemble = autoAssemble;
		this.averageCost = averageCost;
		this.averageCost_Changed = averageCost_Changed;
		this.averageCost_New = averageCost_New;
		this.averageCost_Old = averageCost_Old;
		this.boxQty = boxQty;
		this.consignment = consignment;
		this.costAsOf = costAsOf;
		this.createdById = createdById;
		this.createdOn = createdOn;
		this.CUPopup = CUPopup;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "prMasterID", unique = true, nullable = false)
	public Integer getPrMasterId() {
		return this.prMasterId;
	}

	public void setPrMasterId(Integer prMasterId) {
		this.prMasterId = prMasterId;
	}

	@Column(name = "prDepartmentID")
	public Integer getPrDepartmentId() {
		return this.prDepartmentId;
	}

	public void setPrDepartmentId(Integer prDepartmentId) {
		this.prDepartmentId = prDepartmentId;
	}

	@Column(name = "prCategoryID")
	public Integer getPrCategoryId() {
		return this.prCategoryId;
	}

	public void setPrCategoryId(Integer prCategoryId) {
		this.prCategoryId = prCategoryId;
	}

	@Column(name = "ItemCode", length = 20)
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	@Column(name = "Description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "InActive")
	public Byte getInActive() {
		return this.inActive;
	}

	public void setInActive(Byte inActive) {
		this.inActive = inActive;
	}

	@Column(name = "IsInventory")
	public Byte getIsInventory() {
		return this.isInventory;
	}

	public void setIsInventory(Byte isInventory) {
		this.isInventory = isInventory;
	}

	@Column(name = "IsTaxable")
	public Byte getIsTaxable() {
		return this.isTaxable;
	}

	public void setIsTaxable(Byte isTaxable) {
		this.isTaxable = isTaxable;
	}

	@Column(name = "PrintOnPOs")
	public Byte getPrintOnPos() {
		return this.printOnPos;
	}

	public void setPrintOnPos(Byte printOnPos) {
		this.printOnPos = printOnPos;
	}

	@Column(name = "PrintOnSOs")
	public Byte getPrintOnSos() {
		return this.printOnSos;
	}

	public void setPrintOnSos(Byte printOnSos) {
		this.printOnSos = printOnSos;
	}

	@Column(name = "PurchasingUnitMultiplier", scale = 4)
	public BigDecimal getPurchasingUnitMultiplier() {
		return this.purchasingUnitMultiplier;
	}

	public void setPurchasingUnitMultiplier(BigDecimal purchasingUnitMultiplier) {
		this.purchasingUnitMultiplier = purchasingUnitMultiplier;
	}

	@Column(name = "PurchasingUnitOfMeasure", length = 6)
	public String getPurchasingUnitOfMeasure() {
		return this.purchasingUnitOfMeasure;
	}

	public void setPurchasingUnitOfMeasure(String purchasingUnitOfMeasure) {
		this.purchasingUnitOfMeasure = purchasingUnitOfMeasure;
	}

	@Column(name = "SalesUnitMultiplier", scale = 4)
	public BigDecimal getSalesUnitMultiplier() {
		return this.salesUnitMultiplier;
	}

	public void setSalesUnitMultiplier(BigDecimal salesUnitMultiplier) {
		this.salesUnitMultiplier = salesUnitMultiplier;
	}

	@Column(name = "SalesUnitOfMeasure", length = 6)
	public String getSalesUnitOfMeasure() {
		return this.salesUnitOfMeasure;
	}

	public void setSalesUnitOfMeasure(String salesUnitOfMeasure) {
		this.salesUnitOfMeasure = salesUnitOfMeasure;
	}

	@Column(name = "rxMasterIDPrimaryVendor")
	public Integer getRxMasterIdprimaryVendor() {
		return this.rxMasterIdprimaryVendor;
	}

	public void setRxMasterIdprimaryVendor(Integer rxMasterIdprimaryVendor) {
		this.rxMasterIdprimaryVendor = rxMasterIdprimaryVendor;
	}

	@Column(name = "VendorItemNumber", length = 20)
	public String getVendorItemNumber() {
		return this.vendorItemNumber;
	}

	public void setVendorItemNumber(String vendorItemNumber) {
		this.vendorItemNumber = vendorItemNumber;
	}

	@Column(name = "SalesPrice00", scale = 4)
	public BigDecimal getSalesPrice00() {
		return this.salesPrice00;
	}

	public void setSalesPrice00(BigDecimal salesPrice00) {
		this.salesPrice00 = salesPrice00;
	}

	@Column(name = "SalesPrice01", scale = 4)
	public BigDecimal getSalesPrice01() {
		return this.salesPrice01;
	}

	public void setSalesPrice01(BigDecimal salesPrice01) {
		this.salesPrice01 = salesPrice01;
	}

	@Column(name = "SalesPrice02", scale = 4)
	public BigDecimal getSalesPrice02() {
		return this.salesPrice02;
	}

	public void setSalesPrice02(BigDecimal salesPrice02) {
		this.salesPrice02 = salesPrice02;
	}

	@Column(name = "SalesPrice03", scale = 4)
	public BigDecimal getSalesPrice03() {
		return this.salesPrice03;
	}

	public void setSalesPrice03(BigDecimal salesPrice03) {
		this.salesPrice03 = salesPrice03;
	}

	@Column(name = "SalesPrice04", scale = 4)
	public BigDecimal getSalesPrice04() {
		return this.salesPrice04;
	}

	public void setSalesPrice04(BigDecimal salesPrice04) {
		this.salesPrice04 = salesPrice04;
	}

	@Column(name = "SalesPrice05", scale = 4)
	public BigDecimal getSalesPrice05() {
		return this.salesPrice05;
	}

	public void setSalesPrice05(BigDecimal salesPrice05) {
		this.salesPrice05 = salesPrice05;
	}

	@Column(name = "SalesPrice10", scale = 4)
	public BigDecimal getSalesPrice10() {
		return this.salesPrice10;
	}

	public void setSalesPrice10(BigDecimal salesPrice10) {
		this.salesPrice10 = salesPrice10;
	}

	@Column(name = "SalesPrice11", scale = 4)
	public BigDecimal getSalesPrice11() {
		return this.salesPrice11;
	}

	public void setSalesPrice11(BigDecimal salesPrice11) {
		this.salesPrice11 = salesPrice11;
	}

	@Column(name = "SalesPrice12", scale = 4)
	public BigDecimal getSalesPrice12() {
		return this.salesPrice12;
	}

	public void setSalesPrice12(BigDecimal salesPrice12) {
		this.salesPrice12 = salesPrice12;
	}

	@Column(name = "SalesPrice13", scale = 4)
	public BigDecimal getSalesPrice13() {
		return this.salesPrice13;
	}

	public void setSalesPrice13(BigDecimal salesPrice13) {
		this.salesPrice13 = salesPrice13;
	}

	@Column(name = "SalesPrice14", scale = 4)
	public BigDecimal getSalesPrice14() {
		return this.salesPrice14;
	}

	public void setSalesPrice14(BigDecimal salesPrice14) {
		this.salesPrice14 = salesPrice14;
	}

	@Column(name = "SalesPrice15", scale = 4)
	public BigDecimal getSalesPrice15() {
		return this.salesPrice15;
	}

	public void setSalesPrice15(BigDecimal salesPrice15) {
		this.salesPrice15 = salesPrice15;
	}

	@Column(name = "SalesPrice20", scale = 4)
	public BigDecimal getSalesPrice20() {
		return this.salesPrice20;
	}

	public void setSalesPrice20(BigDecimal salesPrice20) {
		this.salesPrice20 = salesPrice20;
	}

	@Column(name = "SalesPrice21", scale = 4)
	public BigDecimal getSalesPrice21() {
		return this.salesPrice21;
	}

	public void setSalesPrice21(BigDecimal salesPrice21) {
		this.salesPrice21 = salesPrice21;
	}

	@Column(name = "SalesPrice22", scale = 4)
	public BigDecimal getSalesPrice22() {
		return this.salesPrice22;
	}

	public void setSalesPrice22(BigDecimal salesPrice22) {
		this.salesPrice22 = salesPrice22;
	}

	@Column(name = "SalesPrice23", scale = 4)
	public BigDecimal getSalesPrice23() {
		return this.salesPrice23;
	}

	public void setSalesPrice23(BigDecimal salesPrice23) {
		this.salesPrice23 = salesPrice23;
	}

	@Column(name = "SalesPrice24", scale = 4)
	public BigDecimal getSalesPrice24() {
		return this.salesPrice24;
	}

	public void setSalesPrice24(BigDecimal salesPrice24) {
		this.salesPrice24 = salesPrice24;
	}

	@Column(name = "SalesPrice25", scale = 4)
	public BigDecimal getSalesPrice25() {
		return this.salesPrice25;
	}

	public void setSalesPrice25(BigDecimal salesPrice25) {
		this.salesPrice25 = salesPrice25;
	}

	@Column(name = "SalesPrice30", scale = 4)
	public BigDecimal getSalesPrice30() {
		return this.salesPrice30;
	}

	public void setSalesPrice30(BigDecimal salesPrice30) {
		this.salesPrice30 = salesPrice30;
	}

	@Column(name = "SalesPrice31", scale = 4)
	public BigDecimal getSalesPrice31() {
		return this.salesPrice31;
	}

	public void setSalesPrice31(BigDecimal salesPrice31) {
		this.salesPrice31 = salesPrice31;
	}

	@Column(name = "SalesPrice32", scale = 4)
	public BigDecimal getSalesPrice32() {
		return this.salesPrice32;
	}

	public void setSalesPrice32(BigDecimal salesPrice32) {
		this.salesPrice32 = salesPrice32;
	}

	@Column(name = "SalesPrice33", scale = 4)
	public BigDecimal getSalesPrice33() {
		return this.salesPrice33;
	}

	public void setSalesPrice33(BigDecimal salesPrice33) {
		this.salesPrice33 = salesPrice33;
	}

	@Column(name = "SalesPrice34", scale = 4)
	public BigDecimal getSalesPrice34() {
		return this.salesPrice34;
	}

	public void setSalesPrice34(BigDecimal salesPrice34) {
		this.salesPrice34 = salesPrice34;
	}

	@Column(name = "SalesPrice35", scale = 4)
	public BigDecimal getSalesPrice35() {
		return this.salesPrice35;
	}

	public void setSalesPrice35(BigDecimal salesPrice35) {
		this.salesPrice35 = salesPrice35;
	}

	@Column(name = "SalesPrice40", scale = 4)
	public BigDecimal getSalesPrice40() {
		return this.salesPrice40;
	}

	public void setSalesPrice40(BigDecimal salesPrice40) {
		this.salesPrice40 = salesPrice40;
	}

	@Column(name = "SalesPrice41", scale = 4)
	public BigDecimal getSalesPrice41() {
		return this.salesPrice41;
	}

	public void setSalesPrice41(BigDecimal salesPrice41) {
		this.salesPrice41 = salesPrice41;
	}

	@Column(name = "SalesPrice42", scale = 4)
	public BigDecimal getSalesPrice42() {
		return this.salesPrice42;
	}

	public void setSalesPrice42(BigDecimal salesPrice42) {
		this.salesPrice42 = salesPrice42;
	}

	@Column(name = "SalesPrice43", scale = 4)
	public BigDecimal getSalesPrice43() {
		return this.salesPrice43;
	}

	public void setSalesPrice43(BigDecimal salesPrice43) {
		this.salesPrice43 = salesPrice43;
	}

	@Column(name = "SalesPrice44", scale = 4)
	public BigDecimal getSalesPrice44() {
		return this.salesPrice44;
	}

	public void setSalesPrice44(BigDecimal salesPrice44) {
		this.salesPrice44 = salesPrice44;
	}

	@Column(name = "SalesPrice45", scale = 4)
	public BigDecimal getSalesPrice45() {
		return this.salesPrice45;
	}

	public void setSalesPrice45(BigDecimal salesPrice45) {
		this.salesPrice45 = salesPrice45;
	}

	@Column(name = "SalesPrice50", scale = 4)
	public BigDecimal getSalesPrice50() {
		return this.salesPrice50;
	}

	public void setSalesPrice50(BigDecimal salesPrice50) {
		this.salesPrice50 = salesPrice50;
	}

	@Column(name = "SalesPrice51", scale = 4)
	public BigDecimal getSalesPrice51() {
		return this.salesPrice51;
	}

	public void setSalesPrice51(BigDecimal salesPrice51) {
		this.salesPrice51 = salesPrice51;
	}

	@Column(name = "SalesPrice52", scale = 4)
	public BigDecimal getSalesPrice52() {
		return this.salesPrice52;
	}

	public void setSalesPrice52(BigDecimal salesPrice52) {
		this.salesPrice52 = salesPrice52;
	}

	@Column(name = "SalesPrice53", scale = 4)
	public BigDecimal getSalesPrice53() {
		return this.salesPrice53;
	}

	public void setSalesPrice53(BigDecimal salesPrice53) {
		this.salesPrice53 = salesPrice53;
	}

	@Column(name = "SalesPrice54", scale = 4)
	public BigDecimal getSalesPrice54() {
		return this.salesPrice54;
	}

	public void setSalesPrice54(BigDecimal salesPrice54) {
		this.salesPrice54 = salesPrice54;
	}

	@Column(name = "SalesPrice55", scale = 4)
	public BigDecimal getSalesPrice55() {
		return this.salesPrice55;
	}

	public void setSalesPrice55(BigDecimal salesPrice55) {
		this.salesPrice55 = salesPrice55;
	}

	@Column(name = "InitialCost", scale = 4)
	public BigDecimal getInitialCost() {
		return this.initialCost;
	}

	public void setInitialCost(BigDecimal initialCost) {
		this.initialCost = initialCost;
	}

	@Column(name = "AverageCost", scale = 4)
	public BigDecimal getAverageCost() {
		return this.averageCost;
	}

	public void setAverageCost(BigDecimal averageCost) {
		this.averageCost = averageCost;
	}

	@Column(name = "InventoryOnHand", scale = 4)
	public BigDecimal getInventoryOnHand() {
		return this.inventoryOnHand;
	}

	public void setInventoryOnHand(BigDecimal inventoryOnHand) {
		this.inventoryOnHand = inventoryOnHand;
	}

	@Column(name = "InventoryAllocated", scale = 4)
	public BigDecimal getInventoryAllocated() {
		return this.inventoryAllocated;
	}

	public void setInventoryAllocated(BigDecimal inventoryAllocated) {
		this.inventoryAllocated = inventoryAllocated;
	}

	@Column(name = "InventoryOnOrder", scale = 4)
	public BigDecimal getInventoryOnOrder() {
		return this.inventoryOnOrder;
	}

	public void setInventoryOnOrder(BigDecimal inventoryOnOrder) {
		this.inventoryOnOrder = inventoryOnOrder;
	}

	@Column(name = "InventoryOrderPoint", scale = 4)
	public BigDecimal getInventoryOrderPoint() {
		return this.inventoryOrderPoint;
	}

	public void setInventoryOrderPoint(BigDecimal inventoryOrderPoint) {
		this.inventoryOrderPoint = inventoryOrderPoint;
	}

	@Column(name = "InventoryOrderQuantity", scale = 4)
	public BigDecimal getInventoryOrderQuantity() {
		return this.inventoryOrderQuantity;
	}

	public void setInventoryOrderQuantity(BigDecimal inventoryOrderQuantity) {
		this.inventoryOrderQuantity = inventoryOrderQuantity;
	}

	@Column(name = "QuantityBreak0", scale = 4)
	public BigDecimal getQuantityBreak0() {
		return this.quantityBreak0;
	}

	public void setQuantityBreak0(BigDecimal quantityBreak0) {
		this.quantityBreak0 = quantityBreak0;
	}

	@Column(name = "QuantityBreak1", scale = 4)
	public BigDecimal getQuantityBreak1() {
		return this.quantityBreak1;
	}

	public void setQuantityBreak1(BigDecimal quantityBreak1) {
		this.quantityBreak1 = quantityBreak1;
	}

	@Column(name = "QuantityBreak2", scale = 4)
	public BigDecimal getQuantityBreak2() {
		return this.quantityBreak2;
	}

	public void setQuantityBreak2(BigDecimal quantityBreak2) {
		this.quantityBreak2 = quantityBreak2;
	}

	@Column(name = "QuantityBreak3", scale = 4)
	public BigDecimal getQuantityBreak3() {
		return this.quantityBreak3;
	}

	public void setQuantityBreak3(BigDecimal quantityBreak3) {
		this.quantityBreak3 = quantityBreak3;
	}

	@Column(name = "QuantityBreak4", scale = 4)
	public BigDecimal getQuantityBreak4() {
		return this.quantityBreak4;
	}

	public void setQuantityBreak4(BigDecimal quantityBreak4) {
		this.quantityBreak4 = quantityBreak4;
	}

	@Column(name = "QuantityBreak5", scale = 4)
	public BigDecimal getQuantityBreak5() {
		return this.quantityBreak5;
	}

	public void setQuantityBreak5(BigDecimal quantityBreak5) {
		this.quantityBreak5 = quantityBreak5;
	}

	@Column(name = "SingleItemTax", nullable = false)
	public Byte getSingleItemTax() {
		return this.singleItemTax;
	}

	public void setSingleItemTax(Byte singleItemTax) {
		this.singleItemTax = singleItemTax;
	}

	@Column(name = "HasInitialCost", nullable = false)
	public Byte isHasInitialCost() {
		return this.hasInitialCost;
	}

	public void setHasInitialCost(Byte hasInitialCost) {
		this.hasInitialCost = hasInitialCost;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CostAsOf", length = 0)
	public Date getCostAsOf() {
		return this.costAsOf;
	}

	public void setCostAsOf(Date costAsOf) {
		this.costAsOf = costAsOf;
	}

	@Column(name = "InitialOnHand", scale = 4)
	public BigDecimal getInitialOnHand() {
		return this.initialOnHand;
	}

	public void setInitialOnHand(BigDecimal initialOnHand) {
		this.initialOnHand = initialOnHand;
	}
	
	@Column(name = "NewPrice", scale = 4)
	public BigDecimal getNewPrice() {
		return newPrice;
	}

	public void setNewPrice(BigDecimal newPrice) {
		this.newPrice = newPrice;
	}

	@Column(name = "OldPrice", scale = 4)
	public BigDecimal getOldPrice() {
		return oldPrice;
	}

	public void setOldPrice(BigDecimal oldPrice) {
		this.oldPrice = oldPrice;
	}

	@Column(name = "LastCost", scale = 4)
	public BigDecimal getLastCost() {
		return lastCost;
	}

	public void setLastCost(BigDecimal lastCost) {
		this.lastCost = lastCost;
	}

	@Column(name = "oldAverageCost", scale = 4)
	public BigDecimal getOldAerageCost() {
		return oldAerageCost;
	}

	public void setOldAerageCost(BigDecimal oldAerageCost) {
		this.oldAerageCost = oldAerageCost;
	}

	@Column(name = "Weight", scale = 4)
	public BigDecimal getWeight() {
		return weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	@Column(name = "POCost", scale = 4)
	public BigDecimal getPoCost() {
		return poCost;
	}

	public void setPoCost(BigDecimal poCost) {
		this.poCost = poCost;
	}

	@Column(name = "BoxQty", scale = 4)
	public BigDecimal getBoxQty() {
		return boxQty;
	}

	public void setBoxQty(BigDecimal boxQty) {
		this.boxQty = boxQty;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 0)
	public Date getCreatedOn() {
		return createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "CreatedByID")
	public Integer getCreatedById() {
		return createdById;
	}

	public void setCreatedById(Integer createdById) {
		this.createdById = createdById;
	}

	@Column(name = "Website")
	public String getWebSite() {
		return webSite;
	}

	public void setWebSite(String webSite) {
		this.webSite = webSite;
	}

	@Column(name = "SalesPrice00_Old", scale = 4)
	public BigDecimal getSalesPrice00_Old() {
		return salesPrice00_Old;
	}

	public void setSalesPrice00_Old(BigDecimal salesPrice00_Old) {
		this.salesPrice00_Old = salesPrice00_Old;
	}

	@Column(name = "SalesPrice00_New", scale = 4)
	public BigDecimal getSalesPrice00_New() {
		return salesPrice00_New;
	}

	public void setSalesPrice00_New(BigDecimal salesPrice00_New) {
		this.salesPrice00_New = salesPrice00_New;
	}

	@Column(name = "SalesPrice00_Changed", scale = 4)
	public Date getSalesPrice00_Changed() {
		return salesPrice00_Changed;
	}

	public void setSalesPrice00_Changed(Date salesPrice00_Changed) {
		this.salesPrice00_Changed = salesPrice00_Changed;
	}

	@Column(name = "SalesPrice10_Old", scale = 4)
	public BigDecimal getSalesPrice10_Old() {
		return salesPrice10_Old;
	}

	public void setSalesPrice10_Old(BigDecimal salesPrice10_Old) {
		this.salesPrice10_Old = salesPrice10_Old;
	}

	@Column(name = "SalesPrice10_New", scale = 4)
	public BigDecimal getSalesPrice10_New() {
		return salesPrice10_New;
	}

	public void setSalesPrice10_New(BigDecimal salesPrice10_New) {
		this.salesPrice10_New = salesPrice10_New;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SalesPrice10_Changed", length = 0)
	public Date getSalesPrice10_Changed() {
		return salesPrice10_Changed;
	}

	public void setSalesPrice10_Changed(Date salesPrice10_Changed) {
		this.salesPrice10_Changed = salesPrice10_Changed;
	}

	@Column(name = "SalesPrice20_Old", scale = 4)
	public BigDecimal getSalesPrice20_Old() {
		return salesPrice20_Old;
	}

	public void setSalesPrice20_Old(BigDecimal salesPrice20_Old) {
		this.salesPrice20_Old = salesPrice20_Old;
	}

	@Column(name = "SalesPrice20_New", scale = 4)
	public BigDecimal getSalesPrice20_New() {
		return salesPrice20_New;
	}

	public void setSalesPrice20_New(BigDecimal salesPrice20_New) {
		this.salesPrice20_New = salesPrice20_New;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SalesPrice20_Changed", length = 0)
	public Date getSalesPrice20_Changed() {
		return salesPrice20_Changed;
	}

	public void setSalesPrice20_Changed(Date salesPrice20_Changed) {
		this.salesPrice20_Changed = salesPrice20_Changed;
	}

	@Column(name = "SalesPrice30_Old", scale = 4)
	public BigDecimal getSalesPrice30_Old() {
		return salesPrice30_Old;
	}

	public void setSalesPrice30_Old(BigDecimal salesPrice30_Old) {
		this.salesPrice30_Old = salesPrice30_Old;
	}

	@Column(name = "SalesPrice30_New", scale = 4)
	public BigDecimal getSalesPrice30_New() {
		return salesPrice30_New;
	}

	public void setSalesPrice30_New(BigDecimal salesPrice30_New) {
		this.salesPrice30_New = salesPrice30_New;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SalesPrice30_Changed", length = 0)
	public Date getSalesPrice30_Changed() {
		return salesPrice30_Changed;
	}

	public void setSalesPrice30_Changed(Date salesPrice30_Changed) {
		this.salesPrice30_Changed = salesPrice30_Changed;
	}

	@Column(name = "SalesPrice40_Old", scale = 4)
	public BigDecimal getSalesPrice40_Old() {
		return salesPrice40_Old;
	}

	public void setSalesPrice40_Old(BigDecimal salesPrice40_Old) {
		this.salesPrice40_Old = salesPrice40_Old;
	}

	@Column(name = "SalesPrice40_New", scale = 4)
	public BigDecimal getSalesPrice40_New() {
		return salesPrice40_New;
	}

	public void setSalesPrice40_New(BigDecimal salesPrice40_New) {
		this.salesPrice40_New = salesPrice40_New;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SalesPrice40_Changed", length = 0)
	public Date getSalesPrice40_Changed() {
		return salesPrice40_Changed;
	}

	public void setSalesPrice40_Changed(Date salesPrice40_Changed) {
		this.salesPrice40_Changed = salesPrice40_Changed;
	}

	@Column(name = "SalesPrice50_Old", scale = 4)
	public BigDecimal getSalesPrice50_Old() {
		return salesPrice50_Old;
	}

	public void setSalesPrice50_Old(BigDecimal salesPrice50_Old) {
		this.salesPrice50_Old = salesPrice50_Old;
	}

	@Column(name = "SalesPrice50_New", scale = 4)
	public BigDecimal getSalesPrice50_New() {
		return salesPrice50_New;
	}

	public void setSalesPrice50_New(BigDecimal salesPrice50_New) {
		this.salesPrice50_New = salesPrice50_New;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SalesPrice50_Changed", length = 0)
	public Date getSalesPrice50_Changed() {
		return salesPrice50_Changed;
	}

	public void setSalesPrice50_Changed(Date salesPrice50_Changed) {
		this.salesPrice50_Changed = salesPrice50_Changed;
	}

	@Column(name = "AverageCost_Old", scale = 4)
	public BigDecimal getAverageCost_Old() {
		return averageCost_Old;
	}

	public void setAverageCost_Old(BigDecimal averageCost_Old) {
		this.averageCost_Old = averageCost_Old;
	}

	@Column(name = "AverageCost_New", scale = 4)
	public BigDecimal getAverageCost_New() {
		return averageCost_New;
	}

	public void setAverageCost_New(BigDecimal averageCost_New) {
		this.averageCost_New = averageCost_New;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AverageCost_Changed", length = 0)
	public Date getAverageCost_Changed() {
		return averageCost_Changed;
	}

	public void setAverageCost_Changed(Date averageCost_Changed) {
		this.averageCost_Changed = averageCost_Changed;
	}
	
	@Column(name = "POCost_Old", scale = 4)
	public BigDecimal getPOCost_Old() {
		return POCost_Old;
	}

	public void setPOCost_Old(BigDecimal pOCost_Old) {
		POCost_Old = pOCost_Old;
	}

	@Column(name = "POCost_New", scale = 4)
	public BigDecimal getPOCost_New() {
		return POCost_New;
	}

	public void setPOCost_New(BigDecimal pOCost_New) {
		POCost_New = pOCost_New;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "POCost_Changed", length = 0)
	public Date getPOCost_Changed() {
		return POCost_Changed;
	}

	public void setPOCost_Changed(Date pOCost_Changed) {
		POCost_Changed = pOCost_Changed;
	}

	@Column(name = "POMult", scale = 4)
	public BigDecimal getPOMult() {
		return POMult;
	}

	public void setPOMult(BigDecimal pOMult) {
		POMult = pOMult;
	}

	@Column(name = "SOPopup", scale = 4)
	public String getSOPopup() {
		return SOPopup;
	}

	public void setSOPopup(String sOPopup) {
		SOPopup = sOPopup;
	}

	@Column(name = "Consignment", nullable = false)
	public Byte getConsignment() {
		return consignment;
	}

	public void setConsignment(Byte consignment) {
		this.consignment = consignment;
	}

	@Column(name = "POPopup")
	public String getPOPopup() {
		return POPopup;
	}

	public void setPOPopup(String pOPopup) {
		POPopup = pOPopup;
	}

	@Column(name = "CUPopup")
	public String getCUPopup() {
		return CUPopup;
	}

	public void setCUPopup(String cUPopup) {
		CUPopup = cUPopup;
	}

	@Column(name = "PrintOnCUs", nullable = false)
	public Byte getPrintOnCUs() {
		return printOnCUs;
	}

	public void setPrintOnCUs(Byte printOnCUs) {
		this.printOnCUs = printOnCUs;
	}

	@Column(name = "PrintOnPTs", nullable = false)
	public Byte getPrintOnPTs() {
		return printOnPTs;
	}

	public void setPrintOnPTs(Byte printOnPTs) {
		this.printOnPTs = printOnPTs;
	}

	@Column(name = "Labor", nullable = false)
	public Byte getLabor() {
		return labor;
	}

	public void setLabor(Byte labor) {
		this.labor = labor;
	}

	@Column(name = "AutoAssemble", nullable = false)
	public Byte getAutoAssemble() {
		return autoAssemble;
	}

	public void setAutoAssemble(Byte autoAssemble) {
		this.autoAssemble = autoAssemble;
	}

	@Column(name = "rxMasterIDSecondaryVendor01")
	public Integer getRxMasterIDSecondaryVendor01() {
		return rxMasterIDSecondaryVendor01;
	}

	public void setRxMasterIDSecondaryVendor01(Integer rxMasterIDSecondaryVendor01) {
		this.rxMasterIDSecondaryVendor01 = rxMasterIDSecondaryVendor01;
	}

	@Column(name = "rxMasterIDSecondaryVendor02")
	public Integer getRxMasterIDSecondaryVendor02() {
		return rxMasterIDSecondaryVendor02;
	}

	public void setRxMasterIDSecondaryVendor02(Integer rxMasterIDSecondaryVendor02) {
		this.rxMasterIDSecondaryVendor02 = rxMasterIDSecondaryVendor02;
	}

	@Column(name = "rxMasterIDSecondaryVendor03")
	public Integer getRxMasterIDSecondaryVendor03() {
		return rxMasterIDSecondaryVendor03;
	}

	public void setRxMasterIDSecondaryVendor03(Integer rxMasterIDSecondaryVendor03) {
		this.rxMasterIDSecondaryVendor03 = rxMasterIDSecondaryVendor03;
	}

	@Column(name = "rxMasterIDSecondaryVendor04")
	public Integer getRxMasterIDSecondaryVendor04() {
		return rxMasterIDSecondaryVendor04;
	}

	public void setRxMasterIDSecondaryVendor04(Integer rxMasterIDSecondaryVendor04) {
		this.rxMasterIDSecondaryVendor04 = rxMasterIDSecondaryVendor04;
	}

	@Column(name = "rxMasterIDSecondaryVendor05")
	public Integer getRxMasterIDSecondaryVendor05() {
		return rxMasterIDSecondaryVendor05;
	}

	public void setRxMasterIDSecondaryVendor05(Integer rxMasterIDSecondaryVendor05) {
		this.rxMasterIDSecondaryVendor05 = rxMasterIDSecondaryVendor05;
	}

	@Column(name = "VendorItemNumber01")
	public Integer getVendorItemNumber01() {
		return vendorItemNumber01;
	}

	public void setVendorItemNumber01(Integer vendorItemNumber01) {
		this.vendorItemNumber01 = vendorItemNumber01;
	}

	@Column(name = "VendorItemNumber02")
	public Integer getVendorItemNumber02() {
		return vendorItemNumber02;
	}

	public void setVendorItemNumber02(Integer vendorItemNumber02) {
		this.vendorItemNumber02 = vendorItemNumber02;
	}

	@Column(name = "VendorItemNumber03")
	public Integer getVendorItemNumber03() {
		return vendorItemNumber03;
	}

	public void setVendorItemNumber03(Integer vendorItemNumber03) {
		this.vendorItemNumber03 = vendorItemNumber03;
	}

	@Column(name = "VendorItemNumber04")
	public Integer getVendorItemNumber04() {
		return vendorItemNumber04;
	}

	public void setVendorItemNumber04(Integer vendorItemNumber04) {
		this.vendorItemNumber04 = vendorItemNumber04;
	}

	@Column(name = "VendorItemNumber05")
	public Integer getVendorItemNumber05() {
		return vendorItemNumber05;
	}

	public void setVendorItemNumber05(Integer vendorItemNumber05) {
		this.vendorItemNumber05 = vendorItemNumber05;
	}

	@Column(name = "Serialized", nullable = false)
	public Byte getSerialized() {
		return serialized;
	}

	public void setSerialized(Byte serialized) {
		this.serialized = serialized;
	}
	 
	@Column(name = "Submitted", scale = 4)
	public BigDecimal getSubmitted() {
		return submitted;
	}

	public void setSubmitted(BigDecimal submitted) {
		this.submitted = submitted;
	}

	/**
	 * @return the vendorName
	 */
	@Transient
	public String getVendorName() {
		return vendorName;
	}

	/**
	 * @param vendorName the vendorName to set
	 */
	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}
	
	@Transient
	public String getPrCategory() {
		return prCategory;
	}

	public void setPrCategory(String prCategory) {
		this.prCategory = prCategory;
	}

	@Transient
	public String getPrDepartment() {
		return prDepartment;
	}

	public void setPrDepartment(String prDepartment) {
		this.prDepartment = prDepartment;
	}

	@Transient
	public BigDecimal getInventoryAvailable() {
		return inventoryAvailable;
	}

	public void setInventoryAvailable(BigDecimal inventoryAvailable) {
		this.inventoryAvailable = inventoryAvailable;
	}
	
	@Transient
	public String getPrimaryVendorName() {
		return primaryVendorName;
	}

	public void setPrimaryVendorName(String primaryVendorName) {
		this.primaryVendorName = primaryVendorName;
	}
	@Transient
	public BigDecimal getInventoryCounted() {
		return inventoryCounted;
	}

	public void setInventoryCounted(BigDecimal inventoryCounted) {
		this.inventoryCounted = inventoryCounted;
	}

	@Transient
	public Integer getPrWarehouseInventoryID() {
		return prWarehouseInventoryID;
	}

	public void setPrWarehouseInventoryID(Integer prWarehouseInventoryID) {
		this.prWarehouseInventoryID = prWarehouseInventoryID;
	}
}
