package com.turborep.turbotracker.product.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Prtransferdetailworkfile generated by hbm2java
 */
@Entity
@Table(name = "prtransferdetailworkfile", catalog = "")
public class Prtransferdetailworkfile implements java.io.Serializable {

	private Integer prTransferDetailWorkFileId;
	private Integer prTransferId;
	private Integer prMasterId;
	private String description;
	private BigDecimal quantityTransfered;

	public Prtransferdetailworkfile() {
	}

	public Prtransferdetailworkfile(Integer prTransferId, Integer prMasterId,
			String description, BigDecimal quantityTransfered) {
		this.prTransferId = prTransferId;
		this.prMasterId = prMasterId;
		this.description = description;
		this.quantityTransfered = quantityTransfered;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "prTransferDetailWorkFileID", unique = true, nullable = false)
	public Integer getPrTransferDetailWorkFileId() {
		return this.prTransferDetailWorkFileId;
	}

	public void setPrTransferDetailWorkFileId(Integer prTransferDetailWorkFileId) {
		this.prTransferDetailWorkFileId = prTransferDetailWorkFileId;
	}

	@Column(name = "prTransferID")
	public Integer getPrTransferId() {
		return this.prTransferId;
	}

	public void setPrTransferId(Integer prTransferId) {
		this.prTransferId = prTransferId;
	}

	@Column(name = "prMasterID")
	public Integer getPrMasterId() {
		return this.prMasterId;
	}

	public void setPrMasterId(Integer prMasterId) {
		this.prMasterId = prMasterId;
	}

	@Column(name = "Description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "QuantityTransfered", scale = 4)
	public BigDecimal getQuantityTransfered() {
		return this.quantityTransfered;
	}

	public void setQuantityTransfered(BigDecimal quantityTransfered) {
		this.quantityTransfered = quantityTransfered;
	}

}
