package com.turborep.turbotracker.product.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Prtransfer generated by hbm2java
 */
@Entity
@Table(name = "prTransfer", catalog = "")
public class Prtransfer implements java.io.Serializable {

	private Integer prTransferId;
	private Date transferDate;
	private Integer prFromWarehouseId;
	private Integer prToWarehouseId;
	private String description;

	public Prtransfer() {
	}

	public Prtransfer(Date transferDate, Integer prFromWarehouseId,
			Integer prToWarehouseId, String description) {
		this.transferDate = transferDate;
		this.prFromWarehouseId = prFromWarehouseId;
		this.prToWarehouseId = prToWarehouseId;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "prTransferID", unique = true, nullable = false)
	public Integer getPrTransferId() {
		return this.prTransferId;
	}

	public void setPrTransferId(Integer prTransferId) {
		this.prTransferId = prTransferId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TransferDate", length = 0)
	public Date getTransferDate() {
		return this.transferDate;
	}

	public void setTransferDate(Date transferDate) {
		this.transferDate = transferDate;
	}

	@Column(name = "prFromWarehouseID")
	public Integer getPrFromWarehouseId() {
		return this.prFromWarehouseId;
	}

	public void setPrFromWarehouseId(Integer prFromWarehouseId) {
		this.prFromWarehouseId = prFromWarehouseId;
	}

	@Column(name = "prToWarehouseID")
	public Integer getPrToWarehouseId() {
		return this.prToWarehouseId;
	}

	public void setPrToWarehouseId(Integer prToWarehouseId) {
		this.prToWarehouseId = prToWarehouseId;
	}

	@Column(name = "Description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
