package com.turborep.turbotracker.product.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Prwarehouse generated by hbm2java
 */
@Entity
@Table(name = "prWarehouse", catalog = "")
public class Prwarehouse implements java.io.Serializable {

	private Integer prWarehouseId;
	private String searchName;
	private String description;
	private Boolean inActive;
	private String address1;
	private String address2;
	private String city;
	private String state;
	private String zip;
	private Integer coAccountIdasset;
	private Integer coTaxTerritoryId;
	private String printerName;
	private String email;
	private Boolean isLaser;
	private String PickTicketInfo;
	private Integer PrinterCopies;
	private Integer adjustCogAccountID;
	
	
	public Prwarehouse() {
	}

	public Prwarehouse(String searchName, String description, Boolean inActive,
			String address1, String address2, String city, String state,
			String zip, Integer coAccountIdasset, Integer coTaxTerritoryId,
			String printerName) {
		this.searchName = searchName;
		this.description = description;
		this.inActive = inActive;
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.coAccountIdasset = coAccountIdasset;
		this.coTaxTerritoryId = coTaxTerritoryId;
		this.printerName = printerName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "prWarehouseID", unique = true, nullable = false)
	public Integer getPrWarehouseId() {
		return this.prWarehouseId;
	}

	public void setPrWarehouseId(Integer prWarehouseId) {
		this.prWarehouseId = prWarehouseId;
	}

	@Column(name = "SearchName", length = 50)
	public String getSearchName() {
		return this.searchName;
	}

	public void setSearchName(String searchName) {
		this.searchName = searchName;
	}

	@Column(name = "Description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "InActive")
	public Boolean getInActive() {
		return this.inActive;
	}

	public void setInActive(Boolean inActive) {
		this.inActive = inActive;
	}

	@Column(name = "Address1", length = 40)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "Address2", length = 40)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "City", length = 30)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "State", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "Zip", length = 10)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "coAccountIDAsset")
	public Integer getCoAccountIdasset() {
		return this.coAccountIdasset;
	}

	public void setCoAccountIdasset(Integer coAccountIdasset) {
		this.coAccountIdasset = coAccountIdasset;
	}

	@Column(name = "coTaxTerritoryID")
	public Integer getCoTaxTerritoryId() {
		return this.coTaxTerritoryId;
	}

	public void setCoTaxTerritoryId(Integer coTaxTerritoryId) {
		this.coTaxTerritoryId = coTaxTerritoryId;
	}

	@Column(name = "PrinterName", length = 50)
	public String getPrinterName() {
		return this.printerName;
	}

	public void setPrinterName(String printerName) {
		this.printerName = printerName;
	}
	@Column(name = "EMail", length = 50)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	@Column(name = "PickTicketInfo", length = 50)
	public String getPickTicketInfo() {
		return PickTicketInfo;
	}

	public void setPickTicketInfo(String pickTicketInfo) {
		PickTicketInfo = pickTicketInfo;
	}
	@Column(name = "IsLaserPrinter")
	public Boolean getIsLaser() {
		return isLaser;
	}

	public void setIsLaser(Boolean isLaser) {
		this.isLaser = isLaser;
	}
	@Column(name = "PrinterCopies")
	public Integer getPrinterCopies() {
		return PrinterCopies;
	}

	public void setPrinterCopies(Integer printerCopies) {
		PrinterCopies = printerCopies;
	}
	//@Column(name = "adjustCogAccountID")
	public Integer getAdjustCogAccountID() {
		return adjustCogAccountID;
	}

	public void setAdjustCogAccountID(Integer adjustCogAccountID) {
		this.adjustCogAccountID = adjustCogAccountID;
	}


}
