package com.turborep.turbotracker.product.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Prwarehouseinventory generated by hbm2java
 */
@Entity
@Table(name = "prWarehouseInventory", catalog = "")
public class Prwarehouseinventory implements java.io.Serializable {

	private Integer prWarehouseInventoryId;
	private Integer prMasterId;
	private Integer prWarehouseId;
	private BigDecimal inventoryOnHand;
	private BigDecimal inventoryAllocated;
	private BigDecimal inventoryOnOrder;
	private String bin;
	private Byte hasInitialCost; 
	private BigDecimal initialCost;
	private Date costAsof;
	private BigDecimal averageCost; 
	private BigDecimal salePrice00;
	private BigDecimal salePrice01;
	private BigDecimal salePrice02;
	private BigDecimal salePrice03;
	private BigDecimal salePrice04;
	private BigDecimal salePrice05;
	private BigDecimal initialOnHand;
	
	public Prwarehouseinventory() {
	}

	public Prwarehouseinventory(Integer prMasterId, Integer prWarehouseId,
			BigDecimal inventoryOnHand, BigDecimal inventoryAllocated,
			BigDecimal inventoryOnOrder) {
		this.prMasterId = prMasterId;
		this.prWarehouseId = prWarehouseId;
		this.inventoryOnHand = inventoryOnHand;
		this.inventoryAllocated = inventoryAllocated;
		this.inventoryOnOrder = inventoryOnOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "prWarehouseInventoryID", unique = true, nullable = false)
	public Integer getPrWarehouseInventoryId() {
		return this.prWarehouseInventoryId;
	}

	public void setPrWarehouseInventoryId(Integer prWarehouseInventoryId) {
		this.prWarehouseInventoryId = prWarehouseInventoryId;
	}

	@Column(name = "prMasterID")
	public Integer getPrMasterId() {
		return this.prMasterId;
	}

	public void setPrMasterId(Integer prMasterId) {
		this.prMasterId = prMasterId;
	}

	@Column(name = "prWarehouseID")
	public Integer getPrWarehouseId() {
		return this.prWarehouseId;
	}

	public void setPrWarehouseId(Integer prWarehouseId) {
		this.prWarehouseId = prWarehouseId;
	}

	@Column(name = "InventoryOnHand", scale = 4)
	public BigDecimal getInventoryOnHand() {
		return this.inventoryOnHand;
	}

	public void setInventoryOnHand(BigDecimal inventoryOnHand) {
		this.inventoryOnHand = inventoryOnHand;
	}

	@Column(name = "InventoryAllocated", scale = 4)
	public BigDecimal getInventoryAllocated() {
		return this.inventoryAllocated;
	}

	public void setInventoryAllocated(BigDecimal inventoryAllocated) {
		this.inventoryAllocated = inventoryAllocated;
	}

	@Column(name = "InventoryOnOrder", scale = 4)
	public BigDecimal getInventoryOnOrder() {
		return this.inventoryOnOrder;
	}

	public void setInventoryOnOrder(BigDecimal inventoryOnOrder) {
		this.inventoryOnOrder = inventoryOnOrder;
	}

	@Column(name = "Bin", length = 50)
	public String getBin() {
		return bin;
	}

	public void setBin(String bin) {
		this.bin = bin;
	}

	@Column(name = "HasInitialCost", nullable = false)
	public Byte getHasInitialCost() {
		return hasInitialCost;
	}

	public void setHasInitialCost(Byte hasInitialCost) {
		this.hasInitialCost = hasInitialCost;
	}

	@Column(name = "InitialCost", scale = 4)
	public BigDecimal getInitialCost() {
		return initialCost;
	}

	public void setInitialCost(BigDecimal initialCost) {
		this.initialCost = initialCost;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CostAsof", length = 0)
	public Date getCostAsof() {
		return costAsof;
	}

	public void setCostAsof(Date costAsof) {
		this.costAsof = costAsof;
	}

	@Column(name = "", scale = 4)
	public BigDecimal getAverageCost() {
		return averageCost;
	}

	public void setAverageCost(BigDecimal averageCost) {
		this.averageCost = averageCost;
	}

	@Column(name = "SalePrice00", scale = 4)
	public BigDecimal getSalePrice00() {
		return salePrice00;
	}

	public void setSalePrice00(BigDecimal salePrice00) {
		this.salePrice00 = salePrice00;
	}

	@Column(name = "SalePrice01", scale = 4)
	public BigDecimal getSalePrice01() {
		return salePrice01;
	}

	public void setSalePrice01(BigDecimal salePrice01) {
		this.salePrice01 = salePrice01;
	}

	@Column(name = "SalePrice02", scale = 4)
	public BigDecimal getSalePrice02() {
		return salePrice02;
	}

	public void setSalePrice02(BigDecimal salePrice02) {
		this.salePrice02 = salePrice02;
	}

	@Column(name = "SalePrice03", scale = 4)
	public BigDecimal getSalePrice03() {
		return salePrice03;
	}

	public void setSalePrice03(BigDecimal salePrice03) {
		this.salePrice03 = salePrice03;
	}

	@Column(name = "SalePrice04", scale = 4)
	public BigDecimal getSalePrice04() {
		return salePrice04;
	}

	public void setSalePrice04(BigDecimal salePrice04) {
		this.salePrice04 = salePrice04;
	}

	@Column(name = "SalePrice05", scale = 4)
	public BigDecimal getSalePrice05() {
		return salePrice05;
	}

	public void setSalePrice05(BigDecimal salePrice05) {
		this.salePrice05 = salePrice05;
	}

	@Column(name = "InitialOnHand", scale = 4)
	public BigDecimal getInitialOnHand() {
		return initialOnHand;
	}

	public void setInitialOnHand(BigDecimal initialOnHand) {
		this.initialOnHand = initialOnHand;
	}
}
