package com.turborep.turbotracker.system.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sysaccountlinkage generated by hbm2java
 */
@Entity
@Table(name = "sysAccountLinkage", catalog = "")
public class SysAccountLinkage implements java.io.Serializable {

	private int sysAccountLinkageId;
	private Integer coAccountIdnetSales;
	private Integer coAccountIdpl;
	private Integer coAccountIdcurEarnings;
	private Integer coAccountIdretainedEarnings;
	private Integer coAccountIdar;
	private Integer coAccountIddiscounts;
	private Integer coAccountIdsalesTaxInv;
	private Integer coAccountIdshipping;
	private Integer coAccountIdotherCharges;
	private Integer coAccountIdpayments;
	private Integer coAccountIdap;
	private Integer coAccountIdfreight;
	private Integer coAccountIdsalesTaxPaid;
	private Integer coAccountIddiscountsTaken;
	private Integer coAccountIdmisc;
	private String coRangeAsset1;
	private String coRangeAsset2;
	private String coRangeLiability1;
	private String coRangeLiability2;
	private String coRangeEquity1;
	private String coRangeEquity2;
	private String coRangeIncome1;
	private String coRangeIncome2;
	private String coRangeExpense1;
	private String coRangeExpense2;
    private Short coAccountIdshipInventory;
    private Short coAccountIdinventoryAdjustment;

	public SysAccountLinkage() {
	}

	public SysAccountLinkage(int sysAccountLinkageId) {
		this.sysAccountLinkageId = sysAccountLinkageId;
	}

	public SysAccountLinkage(int sysAccountLinkageId,
			Integer coAccountIdnetSales, Integer coAccountIdpl,
			Integer coAccountIdcurEarnings,
			Integer coAccountIdretainedEarnings, Integer coAccountIdar,
			Integer coAccountIddiscounts, Integer coAccountIdsalesTaxInv,
			Integer coAccountIdshipping, Integer coAccountIdotherCharges,
			Integer coAccountIdpayments, Integer coAccountIdap,
			Integer coAccountIdfreight, Integer coAccountIdsalesTaxPaid,
			Integer coAccountIddiscountsTaken, Integer coAccountIdmisc,
			String coRangeAsset1, String coRangeAsset2,
			String coRangeLiability1, String coRangeLiability2,
			String coRangeEquity1, String coRangeEquity2,
			String coRangeIncome1, String coRangeIncome2,
			String coRangeExpense1, String coRangeExpense2,
			Short coAccountIdshipInventory,
			Short coAccountIdinventoryAdjustment) {
		this.sysAccountLinkageId = sysAccountLinkageId;
		this.coAccountIdnetSales = coAccountIdnetSales;
		this.coAccountIdpl = coAccountIdpl;
		this.coAccountIdcurEarnings = coAccountIdcurEarnings;
		this.coAccountIdretainedEarnings = coAccountIdretainedEarnings;
		this.coAccountIdar = coAccountIdar;
		this.coAccountIddiscounts = coAccountIddiscounts;
		this.coAccountIdsalesTaxInv = coAccountIdsalesTaxInv;
		this.coAccountIdshipping = coAccountIdshipping;
		this.coAccountIdotherCharges = coAccountIdotherCharges;
		this.coAccountIdpayments = coAccountIdpayments;
		this.coAccountIdap = coAccountIdap;
		this.coAccountIdfreight = coAccountIdfreight;
		this.coAccountIdsalesTaxPaid = coAccountIdsalesTaxPaid;
		this.coAccountIddiscountsTaken = coAccountIddiscountsTaken;
		this.coAccountIdmisc = coAccountIdmisc;
		this.coRangeAsset1 = coRangeAsset1;
		this.coRangeAsset2 = coRangeAsset2;
		this.coRangeLiability1 = coRangeLiability1;
		this.coRangeLiability2 = coRangeLiability2;
		this.coRangeEquity1 = coRangeEquity1;
		this.coRangeEquity2 = coRangeEquity2;
		this.coRangeIncome1 = coRangeIncome1;
		this.coRangeIncome2 = coRangeIncome2;
		this.coRangeExpense1 = coRangeExpense1;
		this.coRangeExpense2 = coRangeExpense2;
		this.coAccountIdshipInventory = coAccountIdshipInventory;
		this.coAccountIdinventoryAdjustment = coAccountIdinventoryAdjustment;
	}

	@Id
	@Column(name = "sysAccountLinkageID", unique = true, nullable = false)
	public int getSysAccountLinkageId() {
		return this.sysAccountLinkageId;
	}

	public void setSysAccountLinkageId(int sysAccountLinkageId) {
		this.sysAccountLinkageId = sysAccountLinkageId;
	}

	@Column(name = "coAccountIDNetSales")
	public Integer getCoAccountIdnetSales() {
		return this.coAccountIdnetSales;
	}

	public void setCoAccountIdnetSales(Integer coAccountIdnetSales) {
		this.coAccountIdnetSales = coAccountIdnetSales;
	}

	@Column(name = "coAccountIDPL")
	public Integer getCoAccountIdpl() {
		return this.coAccountIdpl;
	}

	public void setCoAccountIdpl(Integer coAccountIdpl) {
		this.coAccountIdpl = coAccountIdpl;
	}

	@Column(name = "coAccountIDCurEarnings")
	public Integer getCoAccountIdcurEarnings() {
		return this.coAccountIdcurEarnings;
	}

	public void setCoAccountIdcurEarnings(Integer coAccountIdcurEarnings) {
		this.coAccountIdcurEarnings = coAccountIdcurEarnings;
	}

	@Column(name = "coAccountIDRetainedEarnings")
	public Integer getCoAccountIdretainedEarnings() {
		return this.coAccountIdretainedEarnings;
	}

	public void setCoAccountIdretainedEarnings(
			Integer coAccountIdretainedEarnings) {
		this.coAccountIdretainedEarnings = coAccountIdretainedEarnings;
	}

	@Column(name = "coAccountIDAR")
	public Integer getCoAccountIdar() {
		return this.coAccountIdar;
	}

	public void setCoAccountIdar(Integer coAccountIdar) {
		this.coAccountIdar = coAccountIdar;
	}

	@Column(name = "coAccountIDDiscounts")
	public Integer getCoAccountIddiscounts() {
		return this.coAccountIddiscounts;
	}

	public void setCoAccountIddiscounts(Integer coAccountIddiscounts) {
		this.coAccountIddiscounts = coAccountIddiscounts;
	}

	@Column(name = "coAccountIDSalesTaxInv")
	public Integer getCoAccountIdsalesTaxInv() {
		return this.coAccountIdsalesTaxInv;
	}

	public void setCoAccountIdsalesTaxInv(Integer coAccountIdsalesTaxInv) {
		this.coAccountIdsalesTaxInv = coAccountIdsalesTaxInv;
	}

	@Column(name = "coAccountIDShipping")
	public Integer getCoAccountIdshipping() {
		return this.coAccountIdshipping;
	}

	public void setCoAccountIdshipping(Integer coAccountIdshipping) {
		this.coAccountIdshipping = coAccountIdshipping;
	}

	@Column(name = "coAccountIDOtherCharges")
	public Integer getCoAccountIdotherCharges() {
		return this.coAccountIdotherCharges;
	}

	public void setCoAccountIdotherCharges(Integer coAccountIdotherCharges) {
		this.coAccountIdotherCharges = coAccountIdotherCharges;
	}

	@Column(name = "coAccountIDPayments")
	public Integer getCoAccountIdpayments() {
		return this.coAccountIdpayments;
	}

	public void setCoAccountIdpayments(Integer coAccountIdpayments) {
		this.coAccountIdpayments = coAccountIdpayments;
	}

	@Column(name = "coAccountIDAP")
	public Integer getCoAccountIdap() {
		return this.coAccountIdap;
	}

	public void setCoAccountIdap(Integer coAccountIdap) {
		this.coAccountIdap = coAccountIdap;
	}

	@Column(name = "coAccountIDFreight")
	public Integer getCoAccountIdfreight() {
		return this.coAccountIdfreight;
	}

	public void setCoAccountIdfreight(Integer coAccountIdfreight) {
		this.coAccountIdfreight = coAccountIdfreight;
	}

	@Column(name = "coAccountIDSalesTaxPaid")
	public Integer getCoAccountIdsalesTaxPaid() {
		return this.coAccountIdsalesTaxPaid;
	}

	public void setCoAccountIdsalesTaxPaid(Integer coAccountIdsalesTaxPaid) {
		this.coAccountIdsalesTaxPaid = coAccountIdsalesTaxPaid;
	}

	@Column(name = "coAccountIDDiscountsTaken")
	public Integer getCoAccountIddiscountsTaken() {
		return this.coAccountIddiscountsTaken;
	}

	public void setCoAccountIddiscountsTaken(Integer coAccountIddiscountsTaken) {
		this.coAccountIddiscountsTaken = coAccountIddiscountsTaken;
	}

	@Column(name = "coAccountIDMisc")
	public Integer getCoAccountIdmisc() {
		return this.coAccountIdmisc;
	}

	public void setCoAccountIdmisc(Integer coAccountIdmisc) {
		this.coAccountIdmisc = coAccountIdmisc;
	}

	@Column(name = "coRangeAsset1", length = 12)
	public String getCoRangeAsset1() {
		return this.coRangeAsset1;
	}

	public void setCoRangeAsset1(String coRangeAsset1) {
		this.coRangeAsset1 = coRangeAsset1;
	}

	@Column(name = "coRangeAsset2", length = 12)
	public String getCoRangeAsset2() {
		return this.coRangeAsset2;
	}

	public void setCoRangeAsset2(String coRangeAsset2) {
		this.coRangeAsset2 = coRangeAsset2;
	}

	@Column(name = "coRangeLiability1", length = 12)
	public String getCoRangeLiability1() {
		return this.coRangeLiability1;
	}

	public void setCoRangeLiability1(String coRangeLiability1) {
		this.coRangeLiability1 = coRangeLiability1;
	}

	@Column(name = "coRangeLiability2", length = 12)
	public String getCoRangeLiability2() {
		return this.coRangeLiability2;
	}

	public void setCoRangeLiability2(String coRangeLiability2) {
		this.coRangeLiability2 = coRangeLiability2;
	}

	@Column(name = "coRangeEquity1", length = 12)
	public String getCoRangeEquity1() {
		return this.coRangeEquity1;
	}

	public void setCoRangeEquity1(String coRangeEquity1) {
		this.coRangeEquity1 = coRangeEquity1;
	}

	@Column(name = "coRangeEquity2", length = 12)
	public String getCoRangeEquity2() {
		return this.coRangeEquity2;
	}

	public void setCoRangeEquity2(String coRangeEquity2) {
		this.coRangeEquity2 = coRangeEquity2;
	}

	@Column(name = "coRangeIncome1", length = 12)
	public String getCoRangeIncome1() {
		return this.coRangeIncome1;
	}

	public void setCoRangeIncome1(String coRangeIncome1) {
		this.coRangeIncome1 = coRangeIncome1;
	}

	@Column(name = "coRangeIncome2", length = 12)
	public String getCoRangeIncome2() {
		return this.coRangeIncome2;
	}

	public void setCoRangeIncome2(String coRangeIncome2) {
		this.coRangeIncome2 = coRangeIncome2;
	}

	@Column(name = "coRangeExpense1", length = 12)
	public String getCoRangeExpense1() {
		return this.coRangeExpense1;
	}

	public void setCoRangeExpense1(String coRangeExpense1) {
		this.coRangeExpense1 = coRangeExpense1;
	}

	@Column(name = "coRangeExpense2", length = 12)
	public String getCoRangeExpense2() {
		return this.coRangeExpense2;
	}

	public void setCoRangeExpense2(String coRangeExpense2) {
		this.coRangeExpense2 = coRangeExpense2;
	}

    @Column(name="coAccountIDShipInventory")
    public Short getCoAccountIdshipInventory() {
        return this.coAccountIdshipInventory;
    }
    
    public void setCoAccountIdshipInventory(Short coAccountIdshipInventory) {
        this.coAccountIdshipInventory = coAccountIdshipInventory;
    }

    
    @Column(name="coAccountIDInventoryAdjustment")
    public Short getCoAccountIdinventoryAdjustment() {
        return this.coAccountIdinventoryAdjustment;
    }
    
    public void setCoAccountIdinventoryAdjustment(Short coAccountIdinventoryAdjustment) {
        this.coAccountIdinventoryAdjustment = coAccountIdinventoryAdjustment;
    }
}
