package com.turborep.turbotracker.system.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Sysassignment generated by hbm2java
 */
@Entity
@Table(name = "sysAssignment", catalog = "")
public class Sysassignment implements java.io.Serializable {

	private byte sysAssignmentId;
	private String title;
	private Integer defaultId;
	private Boolean allowCustomerChange;
	private Boolean allowTransactionChange;
	private Boolean transDefaultLogin;
	private BigDecimal allocatePctJob;
	private BigDecimal allocatePctSales;
	private BigDecimal allocatePctProfit;
	private byte customerCategoryId1;
	private byte customerCategoryId2;
	private byte customerCategoryId3;
	private byte customerCategoryId4;
	private byte customerCategoryId5;
	private String customerCategory1;
	private String customerCategory2;
	private String customerCategory3;
	private String customerCategory4;
	private String customerCategory5;
	public Sysassignment() {
	}

	public Sysassignment(byte sysAssignmentId) {
		this.sysAssignmentId = sysAssignmentId;
	}

	public Sysassignment(byte sysAssignmentId, String title, Integer defaultId,
			Boolean allowCustomerChange, Boolean allowTransactionChange,
			Boolean transDefaultLogin, BigDecimal allocatePctJob,
			BigDecimal allocatePctSales, BigDecimal allocatePctProfit) {
		this.sysAssignmentId = sysAssignmentId;
		this.title = title;
		this.defaultId = defaultId;
		this.allowCustomerChange = allowCustomerChange;
		this.allowTransactionChange = allowTransactionChange;
		this.transDefaultLogin = transDefaultLogin;
		this.allocatePctJob = allocatePctJob;
		this.allocatePctSales = allocatePctSales;
		this.allocatePctProfit = allocatePctProfit;
	}

	@Id
	@Column(name = "sysAssignmentID", unique = true, nullable = false)
	public byte getSysAssignmentId() {
		return this.sysAssignmentId;
	}

	public void setSysAssignmentId(byte sysAssignmentId) {
		this.sysAssignmentId = sysAssignmentId;
	}

	@Column(name = "Title", length = 12)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "DefaultID")
	public Integer getDefaultId() {
		return this.defaultId;
	}

	public void setDefaultId(Integer defaultId) {
		this.defaultId = defaultId;
	}

	@Column(name = "AllowCustomerChange")
	public Boolean getAllowCustomerChange() {
		return this.allowCustomerChange;
	}

	public void setAllowCustomerChange(Boolean allowCustomerChange) {
		this.allowCustomerChange = allowCustomerChange;
	}

	@Column(name = "AllowTransactionChange")
	public Boolean getAllowTransactionChange() {
		return this.allowTransactionChange;
	}

	public void setAllowTransactionChange(Boolean allowTransactionChange) {
		this.allowTransactionChange = allowTransactionChange;
	}

	@Column(name = "TransDefaultLogin")
	public Boolean getTransDefaultLogin() {
		return this.transDefaultLogin;
	}

	public void setTransDefaultLogin(Boolean transDefaultLogin) {
		this.transDefaultLogin = transDefaultLogin;
	}

	@Column(name = "AllocatePctJob", scale = 4)
	public BigDecimal getAllocatePctJob() {
		return this.allocatePctJob;
	}

	public void setAllocatePctJob(BigDecimal allocatePctJob) {
		this.allocatePctJob = allocatePctJob;
	}

	@Column(name = "AllocatePctSales", scale = 4)
	public BigDecimal getAllocatePctSales() {
		return this.allocatePctSales;
	}

	public void setAllocatePctSales(BigDecimal allocatePctSales) {
		this.allocatePctSales = allocatePctSales;
	}

	@Column(name = "AllocatePctProfit", scale = 4)
	public BigDecimal getAllocatePctProfit() {
		return this.allocatePctProfit;
	}

	public void setAllocatePctProfit(BigDecimal allocatePctProfit) {
		this.allocatePctProfit = allocatePctProfit;
	}
	@Transient
	public byte getCustomerCategoryId1() {
		return customerCategoryId1;
	}

	public void setCustomerCategoryId1(byte customerCategoryId1) {
		this.customerCategoryId1 = customerCategoryId1;
	}
	@Transient
	public byte getCustomerCategoryId2() {
		return customerCategoryId2;
	}

	public void setCustomerCategoryId2(byte customerCategoryId2) {
		this.customerCategoryId2 = customerCategoryId2;
	}
	@Transient
	public byte getCustomerCategoryId3() {
		return customerCategoryId3;
	}

	public void setCustomerCategoryId3(byte customerCategoryId3) {
		this.customerCategoryId3 = customerCategoryId3;
	}
	@Transient
	public byte getCustomerCategoryId4() {
		return customerCategoryId4;
	}

	public void setCustomerCategoryId4(byte customerCategoryId4) {
		this.customerCategoryId4 = customerCategoryId4;
	}
	@Transient
	public byte getCustomerCategoryId5() {
		return customerCategoryId5;
	}

	public void setCustomerCategoryId5(byte customerCategoryId5) {
		this.customerCategoryId5 = customerCategoryId5;
	}
	@Transient
	public String getCustomerCategory1() {
		return customerCategory1;
	}

	public void setCustomerCategory1(String customerCategory1) {
		this.customerCategory1 = customerCategory1;
	}
	@Transient
	public String getCustomerCategory2() {
		return customerCategory2;
	}

	public void setCustomerCategory2(String customerCategory2) {
		this.customerCategory2 = customerCategory2;
	}
	@Transient
	public String getCustomerCategory3() {
		return customerCategory3;
	}

	public void setCustomerCategory3(String customerCategory3) {
		this.customerCategory3 = customerCategory3;
	}
	@Transient
	public String getCustomerCategory4() {
		return customerCategory4;
	}

	public void setCustomerCategory4(String customerCategory4) {
		this.customerCategory4 = customerCategory4;
	}
    @Transient
	public String getCustomerCategory5() {
		return customerCategory5;
	}

	public void setCustomerCategory5(String customerCategory5) {
		this.customerCategory5 = customerCategory5;
	}

}
