package com.turborep.turbotracker.system.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sysinfo generated by hbm2java
 */
@Entity
@Table(name = "sysInfo", catalog = "")
public class Sysinfo implements java.io.Serializable {

	private int sysInfoId;
	private int dataMark;
	private Integer dbrequiresMajor;
	private Integer dbrequiresMinor;
	private Integer dbrequiresRevision;
	private Integer latestMajor;
	private Integer latestMinor;
	private Integer latestRevision;
	private Boolean locked;
	private String lockedReason;
	private Boolean cashBasisAccounting;
	private Integer currentFiscalYearId;
	private Integer currentPeriodId;
	private Boolean cashBasis;
	private String rxMasterCategory1desc;
	private String rxMasterCategory2desc;
	private String rxMasterCategory3desc;
	private String rxMasterCategory4desc;
	private String rxMasterCategory5desc;
	private String rxMasterCategory6desc;
	private String rxMasterCategory7desc;
	private String rxMasterCategory8desc;
	private String coCompanyNameAddress0;
	private String coCompanyNameAddress1;
	private String coCompanyNameAddress2;
	private String coCompanyNameAddress3;
	private String coCompanyNameAddress4;
	private String prPriceLevel0;
	private String prPriceLevel1;
	private String prPriceLevel2;
	private String prPriceLevel3;
	private String prPriceLevel4;
	private String prPriceLevel5;
	private String prPriceLevel6;
	private Integer billPayAccountId;
	private String pobillToName;
	private String pobillToAddress1;
	private String pobillToAddress2;
	private String pobillToCity;
	private String pobillToState;
	private String pobillToZip;
	private String poshipToName;
	private String poshipToAddress1;
	private String poshipToAddress2;
	private String poshipToCity;
	private String poshipToState;
	private String poshipToZip;
	private String joSource1desc;
	private String joSource2desc;
	private String joSource3desc;
	private String joSource4desc;
	private Integer quotedPriceId;
	private String repDeduct1desc;
	private String repDeduct2desc;
	private String repDeduct3desc;
	private String repDeduct4desc;
	private Integer salesMgrId;
	private BigDecimal commissionOverride;
	private String salesTaxDist1;
	private String salesTaxDist2;
	private String salesTaxDist3;
	private String salesTaxDist4;
	private String salesTaxDist5;
	private String salesTaxDist6;
	private String salesTaxDist7;
	private String salesTaxDist8;

	public Sysinfo() {
	}

	public Sysinfo(int sysInfoId, int dataMark) {
		this.sysInfoId = sysInfoId;
		this.dataMark = dataMark;
	}

	public Sysinfo(int sysInfoId, int dataMark, Integer dbrequiresMajor,
			Integer dbrequiresMinor, Integer dbrequiresRevision,
			Integer latestMajor, Integer latestMinor, Integer latestRevision,
			Boolean locked, String lockedReason, Boolean cashBasisAccounting,
			Integer currentFiscalYearId, Integer currentPeriodId,
			Boolean cashBasis, String rxMasterCategory1desc,
			String rxMasterCategory2desc, String rxMasterCategory3desc,
			String rxMasterCategory4desc, String rxMasterCategory5desc,
			String rxMasterCategory6desc, String coCompanyNameAddress0,
			String coCompanyNameAddress1, String coCompanyNameAddress2,
			String coCompanyNameAddress3, String coCompanyNameAddress4,
			String prPriceLevel0, String prPriceLevel1, String prPriceLevel2,
			String prPriceLevel3, String prPriceLevel4, String prPriceLevel5,
			String prPriceLevel6, Integer billPayAccountId,
			String pobillToName, String pobillToAddress1,
			String pobillToAddress2, String pobillToCity, String pobillToState,
			String pobillToZip, String poshipToName, String poshipToAddress1,
			String poshipToAddress2, String poshipToCity, String poshipToState,
			String poshipToZip, String joSource1desc, String joSource2desc,
			String joSource3desc, String joSource4desc, Integer quotedPriceId,
			String repDeduct1desc, String repDeduct2desc,
			String repDeduct3desc, String repDeduct4desc, Integer salesMgrId,
			BigDecimal commissionOverride, String salesTaxDist1,
			String salesTaxDist2, String salesTaxDist3, String salesTaxDist4,
			String salesTaxDist5, String salesTaxDist6, String salesTaxDist7,
			String salesTaxDist8) {
		this.sysInfoId = sysInfoId;
		this.dataMark = dataMark;
		this.dbrequiresMajor = dbrequiresMajor;
		this.dbrequiresMinor = dbrequiresMinor;
		this.dbrequiresRevision = dbrequiresRevision;
		this.latestMajor = latestMajor;
		this.latestMinor = latestMinor;
		this.latestRevision = latestRevision;
		this.locked = locked;
		this.lockedReason = lockedReason;
		this.cashBasisAccounting = cashBasisAccounting;
		this.currentFiscalYearId = currentFiscalYearId;
		this.currentPeriodId = currentPeriodId;
		this.cashBasis = cashBasis;
		this.rxMasterCategory1desc = rxMasterCategory1desc;
		this.rxMasterCategory2desc = rxMasterCategory2desc;
		this.rxMasterCategory3desc = rxMasterCategory3desc;
		this.rxMasterCategory4desc = rxMasterCategory4desc;
		this.rxMasterCategory5desc = rxMasterCategory5desc;
		this.rxMasterCategory6desc = rxMasterCategory6desc;
		this.coCompanyNameAddress0 = coCompanyNameAddress0;
		this.coCompanyNameAddress1 = coCompanyNameAddress1;
		this.coCompanyNameAddress2 = coCompanyNameAddress2;
		this.coCompanyNameAddress3 = coCompanyNameAddress3;
		this.coCompanyNameAddress4 = coCompanyNameAddress4;
		this.prPriceLevel0 = prPriceLevel0;
		this.prPriceLevel1 = prPriceLevel1;
		this.prPriceLevel2 = prPriceLevel2;
		this.prPriceLevel3 = prPriceLevel3;
		this.prPriceLevel4 = prPriceLevel4;
		this.prPriceLevel5 = prPriceLevel5;
		this.prPriceLevel6 = prPriceLevel6;
		this.billPayAccountId = billPayAccountId;
		this.pobillToName = pobillToName;
		this.pobillToAddress1 = pobillToAddress1;
		this.pobillToAddress2 = pobillToAddress2;
		this.pobillToCity = pobillToCity;
		this.pobillToState = pobillToState;
		this.pobillToZip = pobillToZip;
		this.poshipToName = poshipToName;
		this.poshipToAddress1 = poshipToAddress1;
		this.poshipToAddress2 = poshipToAddress2;
		this.poshipToCity = poshipToCity;
		this.poshipToState = poshipToState;
		this.poshipToZip = poshipToZip;
		this.joSource1desc = joSource1desc;
		this.joSource2desc = joSource2desc;
		this.joSource3desc = joSource3desc;
		this.joSource4desc = joSource4desc;
		this.quotedPriceId = quotedPriceId;
		this.repDeduct1desc = repDeduct1desc;
		this.repDeduct2desc = repDeduct2desc;
		this.repDeduct3desc = repDeduct3desc;
		this.repDeduct4desc = repDeduct4desc;
		this.salesMgrId = salesMgrId;
		this.commissionOverride = commissionOverride;
		this.salesTaxDist1 = salesTaxDist1;
		this.salesTaxDist2 = salesTaxDist2;
		this.salesTaxDist3 = salesTaxDist3;
		this.salesTaxDist4 = salesTaxDist4;
		this.salesTaxDist5 = salesTaxDist5;
		this.salesTaxDist6 = salesTaxDist6;
		this.salesTaxDist7 = salesTaxDist7;
		this.salesTaxDist8 = salesTaxDist8;
	}

	@Id
	@Column(name = "sysInfoID", unique = true, nullable = false)
	public int getSysInfoId() {
		return this.sysInfoId;
	}

	public void setSysInfoId(int sysInfoId) {
		this.sysInfoId = sysInfoId;
	}

	@Column(name = "DataMark", nullable = false)
	public int getDataMark() {
		return this.dataMark;
	}

	public void setDataMark(int dataMark) {
		this.dataMark = dataMark;
	}

	@Column(name = "DBRequiresMajor")
	public Integer getDbrequiresMajor() {
		return this.dbrequiresMajor;
	}

	public void setDbrequiresMajor(Integer dbrequiresMajor) {
		this.dbrequiresMajor = dbrequiresMajor;
	}

	@Column(name = "DBRequiresMinor")
	public Integer getDbrequiresMinor() {
		return this.dbrequiresMinor;
	}

	public void setDbrequiresMinor(Integer dbrequiresMinor) {
		this.dbrequiresMinor = dbrequiresMinor;
	}

	@Column(name = "DBRequiresRevision")
	public Integer getDbrequiresRevision() {
		return this.dbrequiresRevision;
	}

	public void setDbrequiresRevision(Integer dbrequiresRevision) {
		this.dbrequiresRevision = dbrequiresRevision;
	}

	@Column(name = "LatestMajor")
	public Integer getLatestMajor() {
		return this.latestMajor;
	}

	public void setLatestMajor(Integer latestMajor) {
		this.latestMajor = latestMajor;
	}

	@Column(name = "LatestMinor")
	public Integer getLatestMinor() {
		return this.latestMinor;
	}

	public void setLatestMinor(Integer latestMinor) {
		this.latestMinor = latestMinor;
	}

	@Column(name = "LatestRevision")
	public Integer getLatestRevision() {
		return this.latestRevision;
	}

	public void setLatestRevision(Integer latestRevision) {
		this.latestRevision = latestRevision;
	}

	@Column(name = "Locked")
	public Boolean getLocked() {
		return this.locked;
	}

	public void setLocked(Boolean locked) {
		this.locked = locked;
	}

	@Column(name = "LockedReason", length = 200)
	public String getLockedReason() {
		return this.lockedReason;
	}

	public void setLockedReason(String lockedReason) {
		this.lockedReason = lockedReason;
	}

	@Column(name = "CashBasisAccounting")
	public Boolean getCashBasisAccounting() {
		return this.cashBasisAccounting;
	}

	public void setCashBasisAccounting(Boolean cashBasisAccounting) {
		this.cashBasisAccounting = cashBasisAccounting;
	}

	@Column(name = "CurrentFiscalYearID")
	public Integer getCurrentFiscalYearId() {
		return this.currentFiscalYearId;
	}

	public void setCurrentFiscalYearId(Integer currentFiscalYearId) {
		this.currentFiscalYearId = currentFiscalYearId;
	}

	@Column(name = "CurrentPeriodID")
	public Integer getCurrentPeriodId() {
		return this.currentPeriodId;
	}

	public void setCurrentPeriodId(Integer currentPeriodId) {
		this.currentPeriodId = currentPeriodId;
	}

	@Column(name = "CashBasis")
	public Boolean getCashBasis() {
		return this.cashBasis;
	}

	public void setCashBasis(Boolean cashBasis) {
		this.cashBasis = cashBasis;
	}

	@Column(name = "rxMasterCategory1Desc", length = 12)
	public String getRxMasterCategory1desc() {
		return this.rxMasterCategory1desc;
	}

	public void setRxMasterCategory1desc(String rxMasterCategory1desc) {
		this.rxMasterCategory1desc = rxMasterCategory1desc;
	}

	@Column(name = "rxMasterCategory2Desc", length = 12)
	public String getRxMasterCategory2desc() {
		return this.rxMasterCategory2desc;
	}

	public void setRxMasterCategory2desc(String rxMasterCategory2desc) {
		this.rxMasterCategory2desc = rxMasterCategory2desc;
	}

	@Column(name = "rxMasterCategory3Desc", length = 12)
	public String getRxMasterCategory3desc() {
		return this.rxMasterCategory3desc;
	}

	public void setRxMasterCategory3desc(String rxMasterCategory3desc) {
		this.rxMasterCategory3desc = rxMasterCategory3desc;
	}

	@Column(name = "rxMasterCategory4Desc", length = 12)
	public String getRxMasterCategory4desc() {
		return this.rxMasterCategory4desc;
	}

	public void setRxMasterCategory4desc(String rxMasterCategory4desc) {
		this.rxMasterCategory4desc = rxMasterCategory4desc;
	}

	@Column(name = "rxMasterCategory5Desc", length = 12)
	public String getRxMasterCategory5desc() {
		return this.rxMasterCategory5desc;
	}

	public void setRxMasterCategory5desc(String rxMasterCategory5desc) {
		this.rxMasterCategory5desc = rxMasterCategory5desc;
	}

	@Column(name = "rxMasterCategory6Desc", length = 12)
	public String getRxMasterCategory6desc() {
		return this.rxMasterCategory6desc;
	}

	public void setRxMasterCategory6desc(String rxMasterCategory6desc) {
		this.rxMasterCategory6desc = rxMasterCategory6desc;
	}

	@Column(name = "coCompanyNameAddress0", length = 50)
	public String getCoCompanyNameAddress0() {
		return this.coCompanyNameAddress0;
	}

	public void setCoCompanyNameAddress0(String coCompanyNameAddress0) {
		this.coCompanyNameAddress0 = coCompanyNameAddress0;
	}

	@Column(name = "coCompanyNameAddress1", length = 50)
	public String getCoCompanyNameAddress1() {
		return this.coCompanyNameAddress1;
	}

	public void setCoCompanyNameAddress1(String coCompanyNameAddress1) {
		this.coCompanyNameAddress1 = coCompanyNameAddress1;
	}

	@Column(name = "coCompanyNameAddress2", length = 50)
	public String getCoCompanyNameAddress2() {
		return this.coCompanyNameAddress2;
	}

	public void setCoCompanyNameAddress2(String coCompanyNameAddress2) {
		this.coCompanyNameAddress2 = coCompanyNameAddress2;
	}

	@Column(name = "coCompanyNameAddress3", length = 50)
	public String getCoCompanyNameAddress3() {
		return this.coCompanyNameAddress3;
	}

	public void setCoCompanyNameAddress3(String coCompanyNameAddress3) {
		this.coCompanyNameAddress3 = coCompanyNameAddress3;
	}

	@Column(name = "coCompanyNameAddress4", length = 50)
	public String getCoCompanyNameAddress4() {
		return this.coCompanyNameAddress4;
	}

	public void setCoCompanyNameAddress4(String coCompanyNameAddress4) {
		this.coCompanyNameAddress4 = coCompanyNameAddress4;
	}

	@Column(name = "prPriceLevel0", length = 12)
	public String getPrPriceLevel0() {
		return this.prPriceLevel0;
	}

	public void setPrPriceLevel0(String prPriceLevel0) {
		this.prPriceLevel0 = prPriceLevel0;
	}

	@Column(name = "prPriceLevel1", length = 12)
	public String getPrPriceLevel1() {
		return this.prPriceLevel1;
	}

	public void setPrPriceLevel1(String prPriceLevel1) {
		this.prPriceLevel1 = prPriceLevel1;
	}

	@Column(name = "prPriceLevel2", length = 12)
	public String getPrPriceLevel2() {
		return this.prPriceLevel2;
	}

	public void setPrPriceLevel2(String prPriceLevel2) {
		this.prPriceLevel2 = prPriceLevel2;
	}

	@Column(name = "prPriceLevel3", length = 12)
	public String getPrPriceLevel3() {
		return this.prPriceLevel3;
	}

	public void setPrPriceLevel3(String prPriceLevel3) {
		this.prPriceLevel3 = prPriceLevel3;
	}

	@Column(name = "prPriceLevel4", length = 12)
	public String getPrPriceLevel4() {
		return this.prPriceLevel4;
	}

	public void setPrPriceLevel4(String prPriceLevel4) {
		this.prPriceLevel4 = prPriceLevel4;
	}

	@Column(name = "prPriceLevel5", length = 12)
	public String getPrPriceLevel5() {
		return this.prPriceLevel5;
	}

	public void setPrPriceLevel5(String prPriceLevel5) {
		this.prPriceLevel5 = prPriceLevel5;
	}

	@Column(name = "prPriceLevel6", length = 12)
	public String getPrPriceLevel6() {
		return this.prPriceLevel6;
	}

	public void setPrPriceLevel6(String prPriceLevel6) {
		this.prPriceLevel6 = prPriceLevel6;
	}

	@Column(name = "BillPayAccountID")
	public Integer getBillPayAccountId() {
		return this.billPayAccountId;
	}

	public void setBillPayAccountId(Integer billPayAccountId) {
		this.billPayAccountId = billPayAccountId;
	}

	@Column(name = "POBillTo_Name", length = 40)
	public String getPobillToName() {
		return this.pobillToName;
	}

	public void setPobillToName(String pobillToName) {
		this.pobillToName = pobillToName;
	}

	@Column(name = "POBillTo_Address1", length = 40)
	public String getPobillToAddress1() {
		return this.pobillToAddress1;
	}

	public void setPobillToAddress1(String pobillToAddress1) {
		this.pobillToAddress1 = pobillToAddress1;
	}

	@Column(name = "POBillTo_Address2", length = 40)
	public String getPobillToAddress2() {
		return this.pobillToAddress2;
	}

	public void setPobillToAddress2(String pobillToAddress2) {
		this.pobillToAddress2 = pobillToAddress2;
	}

	@Column(name = "POBillTo_City", length = 30)
	public String getPobillToCity() {
		return this.pobillToCity;
	}

	public void setPobillToCity(String pobillToCity) {
		this.pobillToCity = pobillToCity;
	}

	@Column(name = "POBillTo_State", length = 2)
	public String getPobillToState() {
		return this.pobillToState;
	}

	public void setPobillToState(String pobillToState) {
		this.pobillToState = pobillToState;
	}

	@Column(name = "POBillTo_Zip", length = 10)
	public String getPobillToZip() {
		return this.pobillToZip;
	}

	public void setPobillToZip(String pobillToZip) {
		this.pobillToZip = pobillToZip;
	}

	@Column(name = "POShipTo_Name", length = 40)
	public String getPoshipToName() {
		return this.poshipToName;
	}

	public void setPoshipToName(String poshipToName) {
		this.poshipToName = poshipToName;
	}

	@Column(name = "POShipTo_Address1", length = 40)
	public String getPoshipToAddress1() {
		return this.poshipToAddress1;
	}

	public void setPoshipToAddress1(String poshipToAddress1) {
		this.poshipToAddress1 = poshipToAddress1;
	}

	@Column(name = "POShipTo_Address2", length = 40)
	public String getPoshipToAddress2() {
		return this.poshipToAddress2;
	}

	public void setPoshipToAddress2(String poshipToAddress2) {
		this.poshipToAddress2 = poshipToAddress2;
	}

	@Column(name = "POShipTo_City", length = 30)
	public String getPoshipToCity() {
		return this.poshipToCity;
	}

	public void setPoshipToCity(String poshipToCity) {
		this.poshipToCity = poshipToCity;
	}

	@Column(name = "POShipTo_State", length = 2)
	public String getPoshipToState() {
		return this.poshipToState;
	}

	public void setPoshipToState(String poshipToState) {
		this.poshipToState = poshipToState;
	}

	@Column(name = "POShipTo_Zip", length = 10)
	public String getPoshipToZip() {
		return this.poshipToZip;
	}

	public void setPoshipToZip(String poshipToZip) {
		this.poshipToZip = poshipToZip;
	}

	@Column(name = "joSource1Desc", length = 8)
	public String getJoSource1desc() {
		return this.joSource1desc;
	}

	public void setJoSource1desc(String joSource1desc) {
		this.joSource1desc = joSource1desc;
	}

	@Column(name = "joSource2Desc", length = 8)
	public String getJoSource2desc() {
		return this.joSource2desc;
	}

	public void setJoSource2desc(String joSource2desc) {
		this.joSource2desc = joSource2desc;
	}

	@Column(name = "joSource3Desc", length = 8)
	public String getJoSource3desc() {
		return this.joSource3desc;
	}

	public void setJoSource3desc(String joSource3desc) {
		this.joSource3desc = joSource3desc;
	}

	@Column(name = "joSource4Desc", length = 8)
	public String getJoSource4desc() {
		return this.joSource4desc;
	}

	public void setJoSource4desc(String joSource4desc) {
		this.joSource4desc = joSource4desc;
	}

	@Column(name = "QuotedPriceID")
	public Integer getQuotedPriceId() {
		return this.quotedPriceId;
	}

	public void setQuotedPriceId(Integer quotedPriceId) {
		this.quotedPriceId = quotedPriceId;
	}

	@Column(name = "RepDeduct1Desc", length = 15)
	public String getRepDeduct1desc() {
		return this.repDeduct1desc;
	}

	public void setRepDeduct1desc(String repDeduct1desc) {
		this.repDeduct1desc = repDeduct1desc;
	}

	@Column(name = "RepDeduct2Desc", length = 15)
	public String getRepDeduct2desc() {
		return this.repDeduct2desc;
	}

	public void setRepDeduct2desc(String repDeduct2desc) {
		this.repDeduct2desc = repDeduct2desc;
	}

	@Column(name = "RepDeduct3Desc", length = 15)
	public String getRepDeduct3desc() {
		return this.repDeduct3desc;
	}

	public void setRepDeduct3desc(String repDeduct3desc) {
		this.repDeduct3desc = repDeduct3desc;
	}

	@Column(name = "RepDeduct4Desc", length = 15)
	public String getRepDeduct4desc() {
		return this.repDeduct4desc;
	}

	public void setRepDeduct4desc(String repDeduct4desc) {
		this.repDeduct4desc = repDeduct4desc;
	}

	@Column(name = "SalesMgrID")
	public Integer getSalesMgrId() {
		return this.salesMgrId;
	}

	public void setSalesMgrId(Integer salesMgrId) {
		this.salesMgrId = salesMgrId;
	}

	@Column(name = "CommissionOverride", scale = 4)
	public BigDecimal getCommissionOverride() {
		return this.commissionOverride;
	}

	public void setCommissionOverride(BigDecimal commissionOverride) {
		this.commissionOverride = commissionOverride;
	}

	@Column(name = "SalesTaxDist1", length = 15)
	public String getSalesTaxDist1() {
		return this.salesTaxDist1;
	}

	public void setSalesTaxDist1(String salesTaxDist1) {
		this.salesTaxDist1 = salesTaxDist1;
	}

	@Column(name = "SalesTaxDist2", length = 15)
	public String getSalesTaxDist2() {
		return this.salesTaxDist2;
	}

	public void setSalesTaxDist2(String salesTaxDist2) {
		this.salesTaxDist2 = salesTaxDist2;
	}

	@Column(name = "SalesTaxDist3", length = 15)
	public String getSalesTaxDist3() {
		return this.salesTaxDist3;
	}

	public void setSalesTaxDist3(String salesTaxDist3) {
		this.salesTaxDist3 = salesTaxDist3;
	}

	@Column(name = "SalesTaxDist4", length = 15)
	public String getSalesTaxDist4() {
		return this.salesTaxDist4;
	}

	public void setSalesTaxDist4(String salesTaxDist4) {
		this.salesTaxDist4 = salesTaxDist4;
	}

	@Column(name = "SalesTaxDist5", length = 15)
	public String getSalesTaxDist5() {
		return this.salesTaxDist5;
	}

	public void setSalesTaxDist5(String salesTaxDist5) {
		this.salesTaxDist5 = salesTaxDist5;
	}

	@Column(name = "SalesTaxDist6", length = 15)
	public String getSalesTaxDist6() {
		return this.salesTaxDist6;
	}

	public void setSalesTaxDist6(String salesTaxDist6) {
		this.salesTaxDist6 = salesTaxDist6;
	}

	@Column(name = "SalesTaxDist7", length = 15)
	public String getSalesTaxDist7() {
		return this.salesTaxDist7;
	}

	public void setSalesTaxDist7(String salesTaxDist7) {
		this.salesTaxDist7 = salesTaxDist7;
	}

	@Column(name = "SalesTaxDist8", length = 15)
	public String getSalesTaxDist8() {
		return this.salesTaxDist8;
	}

	public void setSalesTaxDist8(String salesTaxDist8) {
		this.salesTaxDist8 = salesTaxDist8;
	}

	public String getRxMasterCategory7desc() {
		return rxMasterCategory7desc;
	}

	public void setRxMasterCategory7desc(String rxMasterCategory7desc) {
		this.rxMasterCategory7desc = rxMasterCategory7desc;
	}

	public String getRxMasterCategory8desc() {
		return rxMasterCategory8desc;
	}

	public void setRxMasterCategory8desc(String rxMasterCategory8desc) {
		this.rxMasterCategory8desc = rxMasterCategory8desc;
	}

}
