package com.turborep.turbotracker.system.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sysprivilege generated by hbm2java
 */
@Entity
@Table(name = "sysPrivilege", catalog = "")
public class Sysprivilege implements java.io.Serializable {

	private Integer sysPrivilegeId;
	private Integer accessProcedureId;
	private Integer userLoginId;
	private Integer userGroupId;
	private Integer privilegeValue;
	private String procedureName;

	public Sysprivilege() {
	}

	public Sysprivilege(Integer accessProcedureId, Integer userLoginId,
			Integer userGroupId, Integer privilegeValue) {
		this.accessProcedureId = accessProcedureId;
		this.userLoginId = userLoginId;
		this.userGroupId = userGroupId;
		this.privilegeValue = privilegeValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sysPrivilegeID", unique = true, nullable = false)
	public Integer getSysPrivilegeId() {
		return this.sysPrivilegeId;
	}

	public void setSysPrivilegeId(Integer sysPrivilegeId) {
		this.sysPrivilegeId = sysPrivilegeId;
	}

	@Column(name = "AccessProcedureID")
	public Integer getAccessProcedureId() {
		return this.accessProcedureId;
	}

	public void setAccessProcedureId(Integer accessProcedureId) {
		this.accessProcedureId = accessProcedureId;
	}

	@Column(name = "UserLoginID")
	public Integer getUserLoginId() {
		return this.userLoginId;
	}

	public void setUserLoginId(Integer userLoginId) {
		this.userLoginId = userLoginId;
	}

	@Column(name = "UserGroupID")
	public Integer getUserGroupId() {
		return this.userGroupId;
	}

	public void setUserGroupId(Integer userGroupId) {
		this.userGroupId = userGroupId;
	}

	@Column(name = "PrivilegeValue")
	public Integer getPrivilegeValue() {
		return this.privilegeValue;
	}

	public void setPrivilegeValue(Integer privilegeValue) {
		this.privilegeValue = privilegeValue;
	}
	
	@Transient
	public String getProcedureName() {
		return procedureName;
	}

	public void setProcedureName(String procedureName) {
		this.procedureName = procedureName;
	}

}
