package com.turborep.turbotracker.system.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Systablelock generated by hbm2java
 */
@Entity
@Table(name = "systablelock", catalog = "")
public class Systablelock implements java.io.Serializable {

	private String sysTableLockKey;
	private Date lockTime;
	private Integer userLoginId;
	private Integer workstationId;

	public Systablelock() {
	}

	public Systablelock(String sysTableLockKey) {
		this.sysTableLockKey = sysTableLockKey;
	}

	public Systablelock(String sysTableLockKey, Date lockTime,
			Integer userLoginId, Integer workstationId) {
		this.sysTableLockKey = sysTableLockKey;
		this.lockTime = lockTime;
		this.userLoginId = userLoginId;
		this.workstationId = workstationId;
	}

	@Id
	@Column(name = "sysTableLockKey", unique = true, nullable = false, length = 50)
	public String getSysTableLockKey() {
		return this.sysTableLockKey;
	}

	public void setSysTableLockKey(String sysTableLockKey) {
		this.sysTableLockKey = sysTableLockKey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LockTime", length = 0)
	public Date getLockTime() {
		return this.lockTime;
	}

	public void setLockTime(Date lockTime) {
		this.lockTime = lockTime;
	}

	@Column(name = "UserLoginID")
	public Integer getUserLoginId() {
		return this.userLoginId;
	}

	public void setUserLoginId(Integer userLoginId) {
		this.userLoginId = userLoginId;
	}

	@Column(name = "WorkstationID")
	public Integer getWorkstationId() {
		return this.workstationId;
	}

	public void setWorkstationId(Integer workstationId) {
		this.workstationId = workstationId;
	}

}
