package com.turborep.turbotracker.system.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sysvariable generated by hbm2java
 */
@Entity
@Table(name = "sysVariable", catalog = "")
public class Sysvariable implements java.io.Serializable {

	private int sysVariableId;
	private Integer valueLong;
	private BigDecimal valueCurrency;
	private String valueString;
	private Date valueDate;
	private String valueMemo;

	public Sysvariable() {
	}

	public Sysvariable(int sysVariableId) {
		this.sysVariableId = sysVariableId;
	}

	public Sysvariable(int sysVariableId, Integer valueLong,
			BigDecimal valueCurrency, String valueString, Date valueDate,
			String valueMemo) {
		this.sysVariableId = sysVariableId;
		this.valueLong = valueLong;
		this.valueCurrency = valueCurrency;
		this.valueString = valueString;
		this.valueDate = valueDate;
		this.valueMemo = valueMemo;
	}

	@Id
	@Column(name = "sysVariableID", unique = true, nullable = false)
	public int getSysVariableId() {
		return this.sysVariableId;
	}

	public void setSysVariableId(int sysVariableId) {
		this.sysVariableId = sysVariableId;
	}

	@Column(name = "ValueLong")
	public Integer getValueLong() {
		return this.valueLong;
	}

	public void setValueLong(Integer valueLong) {
		this.valueLong = valueLong;
	}

	@Column(name = "ValueCurrency", scale = 4)
	public BigDecimal getValueCurrency() {
		return this.valueCurrency;
	}

	public void setValueCurrency(BigDecimal valueCurrency) {
		this.valueCurrency = valueCurrency;
	}

	@Column(name = "ValueString")
	public String getValueString() {
		return this.valueString;
	}

	public void setValueString(String valueString) {
		this.valueString = valueString;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ValueDate", length = 0)
	public Date getValueDate() {
		return this.valueDate;
	}

	public void setValueDate(Date valueDate) {
		this.valueDate = valueDate;
	}

	@Column(name = "ValueMemo")
	public String getValueMemo() {
		return this.valueMemo;
	}

	public void setValueMemo(String valueMemo) {
		this.valueMemo = valueMemo;
	}

}
