/**
 * Copyright (c) 2013 A & E Specialties, Inc.  All rights reserved.
 * This software is the confidential and proprietary information of A & E Specialties, Inc.
 * You shall not disclose such Confidential Information and shall use it only in
 * accordance with the terms of the license agreement you entered into with A & E Specialties, Inc.
 * 
 * @author vish_pepala
 */
package com.turborep.turbotracker.banking.dao;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Molinkagedetail generated by hbm2java
 */
@Entity
@Table(name = "moLinkageDetail", catalog = "")
public class Molinkagedetail implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer moLinkageDetailId;
	private Integer veBillId;
	private Integer moTransactionId;
	private Integer moLinkageId;
	private BigDecimal amount;
	private BigDecimal discount;

	public Molinkagedetail() {
	}

	public Molinkagedetail(Integer veBillId, Integer moTransactionId,
			Integer moLinkageId, BigDecimal amount, BigDecimal discount) {
		this.veBillId = veBillId;
		this.moTransactionId = moTransactionId;
		this.moLinkageId = moLinkageId;
		this.amount = amount;
		this.discount = discount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "moLinkageDetailID", unique = true, nullable = false)
	public Integer getMoLinkageDetailId() {
		return this.moLinkageDetailId;
	}

	public void setMoLinkageDetailId(Integer moLinkageDetailId) {
		this.moLinkageDetailId = moLinkageDetailId;
	}

	@Column(name = "veBillID")
	public Integer getVeBillId() {
		return this.veBillId;
	}

	public void setVeBillId(Integer veBillId) {
		this.veBillId = veBillId;
	}

	@Column(name = "moTransactionID")
	public Integer getMoTransactionId() {
		return this.moTransactionId;
	}

	public void setMoTransactionId(Integer moTransactionId) {
		this.moTransactionId = moTransactionId;
	}

	@Column(name = "moLinkageID")
	public Integer getMoLinkageId() {
		return this.moLinkageId;
	}

	public void setMoLinkageId(Integer moLinkageId) {
		this.moLinkageId = moLinkageId;
	}

	@Column(name = "Amount", scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "Discount", scale = 4)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

}
