/**
 * Copyright (c) 2013 A & E Specialties, Inc.  All rights reserved.
 * This software is the confidential and proprietary information of A & E Specialties, Inc.
 * You shall not disclose such Confidential Information and shall use it only in
 * accordance with the terms of the license agreement you entered into with A & E Specialties, Inc.
 * 
 * @author vish_pepala
 */
package com.turborep.turbotracker.banking.dao;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Mopayrollchecktemp generated by hbm2java
 */
@Entity
@Table(name = "mopayrollchecktemp", catalog = "")
public class Mopayrollchecktemp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer moPayrollCheckTempId;
	private Integer moTransactionId;

	public Mopayrollchecktemp() {
	}

	public Mopayrollchecktemp(Integer moTransactionId) {
		this.moTransactionId = moTransactionId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "moPayrollCheckTempID", unique = true, nullable = false)
	public Integer getMoPayrollCheckTempId() {
		return this.moPayrollCheckTempId;
	}

	public void setMoPayrollCheckTempId(Integer moPayrollCheckTempId) {
		this.moPayrollCheckTempId = moPayrollCheckTempId;
	}

	@Column(name = "moTransactionID")
	public Integer getMoTransactionId() {
		return this.moTransactionId;
	}

	public void setMoTransactionId(Integer moTransactionId) {
		this.moTransactionId = moTransactionId;
	}

}
