/**
 * Copyright (c) 2013 A & E Specialties, Inc.  All rights reserved.
 * This software is the confidential and proprietary information of A & E Specialties, Inc.
 * You shall not disclose such Confidential Information and shall use it only in
 * accordance with the terms of the license agreement you entered into with A & E Specialties, Inc.
 * 
 * @author vish_pepala
 */
package com.turborep.turbotracker.banking.dao;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Motransactiontype generated by hbm2java
 */
@Entity
@Table(name = "motransactiontype", catalog = "")
public class Motransactiontype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private byte moTransactionTypeId;
	private String description;

	public Motransactiontype() {
	}

	public Motransactiontype(byte moTransactionTypeId) {
		this.moTransactionTypeId = moTransactionTypeId;
	}

	public Motransactiontype(byte moTransactionTypeId, String description) {
		this.moTransactionTypeId = moTransactionTypeId;
		this.description = description;
	}

	@Id
	@Column(name = "moTransactionTypeID", unique = true, nullable = false)
	public byte getMoTransactionTypeId() {
		return this.moTransactionTypeId;
	}

	public void setMoTransactionTypeId(byte moTransactionTypeId) {
		this.moTransactionTypeId = moTransactionTypeId;
	}

	@Column(name = "Description", length = 12)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
