package com.turborep.turbotracker.quickbooks.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Qbpo generated by hbm2java
 */
@Entity
@Table(name = "qbConfig", catalog = "")
public class QbConfig implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Integer qbID;
	private String qbUserName;
	private String qbPassword;
	private String qbUserKey;
	private String qbHost;
	private String tpUserName;
	private String qbEnabled;

	public QbConfig() {
	}

	public QbConfig(Integer qbID, String qbUserName, String qbPassword,
			String qbHost, String qbUserKey) {
		this.qbID = qbID;
		this.qbUserName = qbUserName;
		this.qbPassword = qbPassword;
		this.qbUserKey = qbUserKey;
		this.qbHost = qbHost;
	}
	
	public QbConfig(String qbUserName, String qbPassword, String qbUserKey,
			String qbHost, String tpUserName, String qbEnabled) {
		this.qbUserName = qbUserName;
		this.qbPassword = qbPassword;
		this.qbUserKey = qbUserKey;
		this.qbHost = qbHost;
		this.tpUserName = tpUserName;
		this.qbEnabled = qbEnabled;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "qbID", unique = true, nullable = false)
	public Integer getQbID() {
		return qbID;
	}

	public void setQbID(Integer qbID) {
		this.qbID = qbID;
	}

	@Column(name = "qbUserName")
	public String getQbUserName() {
		return qbUserName;
	}

	public void setQbUserName(String qbUserName) {
		this.qbUserName = qbUserName;
	}

	@Column(name = "qbPassword")
	public String getQbPassword() {
		return qbPassword;
	}

	public void setQbPassword(String qbPassword) {
		this.qbPassword = qbPassword;
	}

	@Column(name = "qbUserKey")
	public String getQbUserKey() {
		return qbUserKey;
	}

	public void setQbUserKey(String qbUserKey) {
		this.qbUserKey = qbUserKey;
	}

	@Column(name = "qbHost")
	public String getQbHost() {
		return qbHost;
	}

	public void setQbHost(String qbHost) {
		this.qbHost = qbHost;
	}
	
	@Column(name = "tpUserName")
	public String getTpUserName() {
		return tpUserName;
	}

	public void setTpUserName(String tpUserName) {
		this.tpUserName = tpUserName;
	}

	public String getQbEnabled() {
		return qbEnabled;
	}

	public void setQbEnabled(String qbEnabled) {
		this.qbEnabled = qbEnabled;
	}

	

}
