package com.turborep.turbotracker.company.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cobalance generated by hbm2java
 */
@Entity
@Table(name = "coBalance", catalog = "")
public class Cobalance implements java.io.Serializable {

	private Integer coBalanceId;
	private Integer coAccountId;
	private Integer coFiscalPeriodId;
	private BigDecimal yearOpening;
	private BigDecimal yearDebits;
	private BigDecimal yearCredits;
	private BigDecimal quarterOpening;
	private BigDecimal quarterDebits;
	private BigDecimal quarterCredits;
	private BigDecimal periodOpening;
	private BigDecimal periodDebits;
	private BigDecimal periodCredits;

	public Cobalance() {
	}

	public Cobalance(Integer coAccountId, Integer coFiscalPeriodId,
			BigDecimal yearOpening, BigDecimal yearDebits,
			BigDecimal yearCredits, BigDecimal quarterOpening,
			BigDecimal quarterDebits, BigDecimal quarterCredits,
			BigDecimal periodOpening, BigDecimal periodDebits,
			BigDecimal periodCredits) {
		this.coAccountId = coAccountId;
		this.coFiscalPeriodId = coFiscalPeriodId;
		this.yearOpening = yearOpening;
		this.yearDebits = yearDebits;
		this.yearCredits = yearCredits;
		this.quarterOpening = quarterOpening;
		this.quarterDebits = quarterDebits;
		this.quarterCredits = quarterCredits;
		this.periodOpening = periodOpening;
		this.periodDebits = periodDebits;
		this.periodCredits = periodCredits;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "coBalanceID", unique = true, nullable = false)
	public Integer getCoBalanceId() {
		return this.coBalanceId;
	}

	public void setCoBalanceId(Integer coBalanceId) {
		this.coBalanceId = coBalanceId;
	}

	@Column(name = "coAccountID")
	public Integer getCoAccountId() {
		return this.coAccountId;
	}

	public void setCoAccountId(Integer coAccountId) {
		this.coAccountId = coAccountId;
	}

	@Column(name = "coFiscalPeriodID")
	public Integer getCoFiscalPeriodId() {
		return this.coFiscalPeriodId;
	}

	public void setCoFiscalPeriodId(Integer coFiscalPeriodId) {
		this.coFiscalPeriodId = coFiscalPeriodId;
	}

	@Column(name = "YearOpening", scale = 4)
	public BigDecimal getYearOpening() {
		return this.yearOpening;
	}

	public void setYearOpening(BigDecimal yearOpening) {
		this.yearOpening = yearOpening;
	}

	@Column(name = "YearDebits", scale = 4)
	public BigDecimal getYearDebits() {
		return this.yearDebits;
	}

	public void setYearDebits(BigDecimal yearDebits) {
		this.yearDebits = yearDebits;
	}

	@Column(name = "YearCredits", scale = 4)
	public BigDecimal getYearCredits() {
		return this.yearCredits;
	}

	public void setYearCredits(BigDecimal yearCredits) {
		this.yearCredits = yearCredits;
	}

	@Column(name = "QuarterOpening", scale = 4)
	public BigDecimal getQuarterOpening() {
		return this.quarterOpening;
	}

	public void setQuarterOpening(BigDecimal quarterOpening) {
		this.quarterOpening = quarterOpening;
	}

	@Column(name = "QuarterDebits", scale = 4)
	public BigDecimal getQuarterDebits() {
		return this.quarterDebits;
	}

	public void setQuarterDebits(BigDecimal quarterDebits) {
		this.quarterDebits = quarterDebits;
	}

	@Column(name = "QuarterCredits", scale = 4)
	public BigDecimal getQuarterCredits() {
		return this.quarterCredits;
	}

	public void setQuarterCredits(BigDecimal quarterCredits) {
		this.quarterCredits = quarterCredits;
	}

	@Column(name = "PeriodOpening", scale = 4)
	public BigDecimal getPeriodOpening() {
		return this.periodOpening;
	}

	public void setPeriodOpening(BigDecimal periodOpening) {
		this.periodOpening = periodOpening;
	}

	@Column(name = "PeriodDebits", scale = 4)
	public BigDecimal getPeriodDebits() {
		return this.periodDebits;
	}

	public void setPeriodDebits(BigDecimal periodDebits) {
		this.periodDebits = periodDebits;
	}

	@Column(name = "PeriodCredits", scale = 4)
	public BigDecimal getPeriodCredits() {
		return this.periodCredits;
	}

	public void setPeriodCredits(BigDecimal periodCredits) {
		this.periodCredits = periodCredits;
	}

}
