package com.turborep.turbotracker.company.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Codivision generated by hbm2java
 */
@Entity
@Table(name = "coDivision", catalog = "")
public class Codivision implements java.io.Serializable {

	private Integer coDivisionId;
	private String description;
	private String code;
	private boolean inActive;
	private boolean useInvoiceSeqNo;
	private Integer invoiceSeqNo;
	private boolean addressQuote;
	private String address1;
	private String address2;
	private String address3;
	private String subAccount;
	private BigDecimal accountDistribution;
	private String additional1;
	private String additional2;
	private String additional3;
	private String address4;

	public Codivision() {
	}

	public Codivision(boolean inActive, boolean useInvoiceSeqNo,
			boolean addressQuote) {
		this.inActive = inActive;
		this.useInvoiceSeqNo = useInvoiceSeqNo;
		this.addressQuote = addressQuote;
	}

	public Codivision(String description, String code, boolean inActive,
			boolean useInvoiceSeqNo, Integer invoiceSeqNo,
			boolean addressQuote, String address1, String address2,
			String address3) {
		this.description = description;
		this.code = code;
		this.inActive = inActive;
		this.useInvoiceSeqNo = useInvoiceSeqNo;
		this.invoiceSeqNo = invoiceSeqNo;
		this.addressQuote = addressQuote;
		this.address1 = address1;
		this.address2 = address2;
		this.address3 = address3;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "coDivisionID", unique = true, nullable = false)
	public Integer getCoDivisionId() {
		return this.coDivisionId;
	}

	public void setCoDivisionId(Integer coDivisionId) {
		this.coDivisionId = coDivisionId;
	}

	@Column(name = "Description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Code", length = 6)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "InActive", nullable = false)
	public boolean isInActive() {
		return this.inActive;
	}

	public void setInActive(boolean inActive) {
		this.inActive = inActive;
	}

	@Column(name = "UseInvoiceSeqNo", nullable = false)
	public boolean isUseInvoiceSeqNo() {
		return this.useInvoiceSeqNo;
	}

	public void setUseInvoiceSeqNo(boolean useInvoiceSeqNo) {
		this.useInvoiceSeqNo = useInvoiceSeqNo;
	}

	@Column(name = "InvoiceSeqNo",nullable = true)
	public Integer getInvoiceSeqNo() {
		return this.invoiceSeqNo;
	}

	public void setInvoiceSeqNo(Integer invoiceSeqNo) {
		this.invoiceSeqNo = invoiceSeqNo;
	}

	@Column(name = "AddressQuote", nullable = false)
	public boolean isAddressQuote() {
		return this.addressQuote;
	}

	public void setAddressQuote(boolean addressQuote) {
		this.addressQuote = addressQuote;
	}

	@Column(name = "Address1", length = 40)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "Address2", length = 40)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "Address3", length = 40)
	public String getAddress3() {
		return this.address3;
	}

	public void setAddress3(String address3) {
		this.address3 = address3;
	}
	
	@Column(name = "Address4", length = 40)
	public String getAddress4() {
		return this.address4;
	}

	public void setAddress4(String address4) {
		this.address4 = address4;
	}
	
	@Column(name = "SubAccount")
	public String getSubAccount() {
		return this.subAccount;
	}

	public void setSubAccount(String subAccount) {
		this.subAccount = subAccount;
	}
	
	@Column(name = "AccountDistribution")
	public BigDecimal getAccountDistribution() {
		return this.accountDistribution;
	}

	public void setAccountDistribution(BigDecimal aObj) {
		this.accountDistribution = aObj;
	}
	
	@Column(name = "Additional1")
	public String getAdditional1() {
		return this.additional1;
	}

	public void setAdditional1(String additional1) {
		this.additional1 = additional1;
	}
	
	@Column(name = "Additional2")
	public String getAdditional2() {
		return this.additional2;
	}

	public void setAdditional2(String additional2) {
		this.additional2 = additional2;
	}
	
	@Column(name = "Additional3", length = 40)
	public String getAdditional3() {
		return this.additional3;
	}

	public void setAdditional3(String additional3) {
		this.additional3 = additional3;
	}	

}
