package com.turborep.turbotracker.company.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigInteger;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Cofiscalperiod generated by hbm2java
 */
@Entity
@Table(name = "coFiscalPeriod", catalog = "")
public class Cofiscalperiod implements java.io.Serializable {

	private Integer coFiscalPeriodId;
	private Integer coFiscalYearId;
	private Date startDate;
	private Date endDate;
	private Boolean startNewQuarter;
	private Integer period;
	private String strdate;
	private BigInteger activityCount;
	private Boolean openStatus;
	private String authStatus;
	private Integer currentPeriodid;
	private Integer currentYearid;
	
	public Cofiscalperiod() {
	}

	public Cofiscalperiod(Integer coFiscalYearId, Date startDate, Date endDate,
			Boolean startNewQuarter) {
		this.coFiscalYearId = coFiscalYearId;
		this.startDate = startDate;
		this.endDate = endDate;
		this.startNewQuarter = startNewQuarter;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "coFiscalPeriodID", unique = true, nullable = false)
	public Integer getCoFiscalPeriodId() {
		return this.coFiscalPeriodId;
	}

	public void setCoFiscalPeriodId(Integer coFiscalPeriodId) {
		this.coFiscalPeriodId = coFiscalPeriodId;
	}

	@Column(name = "coFiscalYearID")
	public Integer getCoFiscalYearId() {
		return this.coFiscalYearId;
	}

	public void setCoFiscalYearId(Integer coFiscalYearId) {
		this.coFiscalYearId = coFiscalYearId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartDate", length = 0)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndDate", length = 0)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "StartNewQuarter")
	public Boolean getStartNewQuarter() {
		return this.startNewQuarter;
	}

	public void setStartNewQuarter(Boolean startNewQuarter) {
		this.startNewQuarter = startNewQuarter;
	}
	@Column(name = "period")
	public Integer getPeriod() {
		return period;
	}

	public void setPeriod(Integer period) {
		this.period = period;
	}
	@Transient
	public String getStrdate() {
		return strdate;
	}

	public void setStrdate(String strdate) {
		this.strdate = strdate;
	}

	@Transient
	public BigInteger getActivityCount() {
		return activityCount;
	}

	public void setActivityCount(BigInteger activityCount) {
		this.activityCount = activityCount;
	}

	@Column(name = "openStatus")
	public Boolean getOpenStatus() {
		return openStatus;
	}

	public void setOpenStatus(Boolean openStatus) {
		this.openStatus = openStatus;
	}

	@Transient
	public String getAuthStatus() {
		return authStatus;
	}

	public void setAuthStatus(String authStatus) {
		this.authStatus = authStatus;
	}

	@Transient
	public Integer getCurrentPeriodid() {
		return currentPeriodid;
	}

	public void setCurrentPeriodid(Integer currentPeriodid) {
		this.currentPeriodid = currentPeriodid;
	}

	@Transient
	public Integer getCurrentYearid() {
		return currentYearid;
	}

	public void setCurrentYearid(Integer currentYearid) {
		this.currentYearid = currentYearid;
	}

	
	
	
}
