package com.turborep.turbotracker.company.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cofiscalyear generated by hbm2java
 */
@Entity
@Table(name = "coFiscalYear", catalog = "")
public class Cofiscalyear implements java.io.Serializable {

	private Integer coFiscalYearId;
	private Date startDate;
	private Date endDate;
	private String fiscalYear;
	private String description;
	private Boolean closedStatus; 

	public Cofiscalyear() {
	}

	public Cofiscalyear(Date startDate, Date endDate) {
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "coFiscalYearID", unique = true, nullable = false)
	public Integer getCoFiscalYearId() {
		return this.coFiscalYearId;
	}

	public void setCoFiscalYearId(Integer coFiscalYearId) {
		this.coFiscalYearId = coFiscalYearId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartDate", length = 0)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndDate", length = 0)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	@Column(name = "fiscalYear")
	public String getFiscalYear() {
		return fiscalYear;
	}

	public void setFiscalYear(String fiscalYear) {
		this.fiscalYear = fiscalYear;
	}

	@Column(name = "Description")
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "closedStatus")
	public Boolean getClosedStatus() {
		return closedStatus;
	}

	public void setClosedStatus(Boolean closedStatus) {
		this.closedStatus = closedStatus;
	}
	
}
