package com.turborep.turbotracker.company.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Coledgerpostingerrors generated by hbm2java
 */
@Entity
@Table(name = "coledgerpostingerrors", catalog = "")
public class Coledgerpostingerrors implements java.io.Serializable {

	private Integer coLedgerPostingErrorsId;
	private Integer coLedgerSourceId;
	private Byte sourceNo;
	private Integer transactionReferenceId;
	private Date postDate;
	private String description;
	private String reference;
	private String errorDescription;
	private Boolean criticalError;

	public Coledgerpostingerrors() {
	}

	public Coledgerpostingerrors(Integer coLedgerSourceId, Byte sourceNo,
			Integer transactionReferenceId, Date postDate, String description,
			String reference, String errorDescription, Boolean criticalError) {
		this.coLedgerSourceId = coLedgerSourceId;
		this.sourceNo = sourceNo;
		this.transactionReferenceId = transactionReferenceId;
		this.postDate = postDate;
		this.description = description;
		this.reference = reference;
		this.errorDescription = errorDescription;
		this.criticalError = criticalError;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "coLedgerPostingErrorsID", unique = true, nullable = false)
	public Integer getCoLedgerPostingErrorsId() {
		return this.coLedgerPostingErrorsId;
	}

	public void setCoLedgerPostingErrorsId(Integer coLedgerPostingErrorsId) {
		this.coLedgerPostingErrorsId = coLedgerPostingErrorsId;
	}

	@Column(name = "coLedgerSourceID")
	public Integer getCoLedgerSourceId() {
		return this.coLedgerSourceId;
	}

	public void setCoLedgerSourceId(Integer coLedgerSourceId) {
		this.coLedgerSourceId = coLedgerSourceId;
	}

	@Column(name = "SourceNo")
	public Byte getSourceNo() {
		return this.sourceNo;
	}

	public void setSourceNo(Byte sourceNo) {
		this.sourceNo = sourceNo;
	}

	@Column(name = "TransactionReferenceID")
	public Integer getTransactionReferenceId() {
		return this.transactionReferenceId;
	}

	public void setTransactionReferenceId(Integer transactionReferenceId) {
		this.transactionReferenceId = transactionReferenceId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PostDate", length = 0)
	public Date getPostDate() {
		return this.postDate;
	}

	public void setPostDate(Date postDate) {
		this.postDate = postDate;
	}

	@Column(name = "Description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Reference", length = 15)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "ErrorDescription", length = 50)
	public String getErrorDescription() {
		return this.errorDescription;
	}

	public void setErrorDescription(String errorDescription) {
		this.errorDescription = errorDescription;
	}

	@Column(name = "CriticalError")
	public Boolean getCriticalError() {
		return this.criticalError;
	}

	public void setCriticalError(Boolean criticalError) {
		this.criticalError = criticalError;
	}

}
