package com.turborep.turbotracker.company.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Coledgerheader generated by hbm2java
 */
@Entity
@Table(name = "coLedgerHeader", catalog = "")
public class Coledgerheader implements java.io.Serializable {

	private Integer coLedgerHeaderId;
	private Integer coFiscalPeriodId;
	private Integer coLedgerSourceId;
	private Byte sourceNo;
	private Integer transactionReferenceId;
	private Date postDate;
	private String description;
	private String reference;
	private Boolean posted;
	private String accountID;
	private String creditAmount;
	private String debitAmount;
	private String ledgerDetailID;
	public Coledgerheader() {
	}

	public Coledgerheader(Integer coFiscalPeriodId, Integer coLedgerSourceId,
			Byte sourceNo, Integer transactionReferenceId, Date postDate,
			String description, String reference, Boolean posted) {
		this.coFiscalPeriodId = coFiscalPeriodId;
		this.coLedgerSourceId = coLedgerSourceId;
		this.sourceNo = sourceNo;
		this.transactionReferenceId = transactionReferenceId;
		this.postDate = postDate;
		this.description = description;
		this.reference = reference;
		this.posted = posted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "coLedgerHeaderID", unique = true, nullable = false)
	public Integer getCoLedgerHeaderId() {
		return this.coLedgerHeaderId;
	}

	public void setCoLedgerHeaderId(Integer coLedgerHeaderId) {
		this.coLedgerHeaderId = coLedgerHeaderId;
	}

	@Column(name = "coFiscalPeriodID")
	public Integer getCoFiscalPeriodId() {
		return this.coFiscalPeriodId;
	}

	public void setCoFiscalPeriodId(Integer coFiscalPeriodId) {
		this.coFiscalPeriodId = coFiscalPeriodId;
	}

	@Column(name = "coLedgerSourceID")
	public Integer getCoLedgerSourceId() {
		return this.coLedgerSourceId;
	}

	public void setCoLedgerSourceId(Integer coLedgerSourceId) {
		this.coLedgerSourceId = coLedgerSourceId;
	}

	@Column(name = "SourceNo")
	public Byte getSourceNo() {
		return this.sourceNo;
	}

	public void setSourceNo(Byte sourceNo) {
		this.sourceNo = sourceNo;
	}

	@Column(name = "TransactionReferenceID")
	public Integer getTransactionReferenceId() {
		return this.transactionReferenceId;
	}

	public void setTransactionReferenceId(Integer transactionReferenceId) {
		this.transactionReferenceId = transactionReferenceId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PostDate", length = 0)
	public Date getPostDate() {
		return this.postDate;
	}

	public void setPostDate(Date postDate) {
		this.postDate = postDate;
	}

	@Column(name = "Description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Reference", length = 20)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "Posted")
	public Boolean getPosted() {
		return this.posted;
	}

	public void setPosted(Boolean posted) {
		this.posted = posted;
	}
	
	@Transient
	public String getAccountID() {
		return accountID;
	}

	public void setAccountID(String accountID) {
		this.accountID = accountID;
	}
	@Transient
	public String getCreditAmount() {
		return creditAmount;
	}

	public void setCreditAmount(String creditAmount) {
		this.creditAmount = creditAmount;
	}
	@Transient
	public String getDebitAmount() {
		return debitAmount;
	}

	public void setDebitAmount(String debitAmount) {
		this.debitAmount = debitAmount;
	}
	@Transient
	public String getLedgerDetailID() {
		return ledgerDetailID;
	}

	public void setLedgerDetailID(String ledgerDetailID) {
		this.ledgerDetailID = ledgerDetailID;
	}

}
