package com.turborep.turbotracker.company.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Coledgerdetail generated by hbm2java
 */
@Entity
@Table(name = "coLedgerDetail", catalog = "")
public class Coledgerdetail implements java.io.Serializable {

	private Integer coLedgerDetailId;
	private Integer coLedgerHeaderId;
	private Integer coAccountId;
	private BigDecimal amount;

	public Coledgerdetail() {
	}

	public Coledgerdetail(Integer coLedgerHeaderId, Integer coAccountId,
			BigDecimal amount) {
		this.coLedgerHeaderId = coLedgerHeaderId;
		this.coAccountId = coAccountId;
		this.amount = amount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "coLedgerDetailID", unique = true, nullable = false)
	public Integer getCoLedgerDetailId() {
		return this.coLedgerDetailId;
	}

	public void setCoLedgerDetailId(Integer coLedgerDetailId) {
		this.coLedgerDetailId = coLedgerDetailId;
	}

	@Column(name = "coLedgerHeaderID")
	public Integer getCoLedgerHeaderId() {
		return this.coLedgerHeaderId;
	}

	public void setCoLedgerHeaderId(Integer coLedgerHeaderId) {
		this.coLedgerHeaderId = coLedgerHeaderId;
	}

	@Column(name = "coAccountID")
	public Integer getCoAccountId() {
		return this.coAccountId;
	}

	public void setCoAccountId(Integer coAccountId) {
		this.coAccountId = coAccountId;
	}

	@Column(name = "Amount", scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

}
