package com.turborep.turbotracker.company.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Coledgerdetailworkfile generated by hbm2java
 */
@Entity
@Table(name = "coledgerdetailworkfile", catalog = "", uniqueConstraints = @UniqueConstraint(columnNames = "Number"))
public class Coledgerdetailworkfile implements java.io.Serializable {

	private Integer coLedgerDetailWorkFile;
	private String number;
	private String description;
	private BigDecimal debit;
	private BigDecimal credit;

	public Coledgerdetailworkfile() {
	}

	public Coledgerdetailworkfile(String number, String description,
			BigDecimal debit, BigDecimal credit) {
		this.number = number;
		this.description = description;
		this.debit = debit;
		this.credit = credit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "coLedgerDetailWorkFile", unique = true, nullable = false)
	public Integer getCoLedgerDetailWorkFile() {
		return this.coLedgerDetailWorkFile;
	}

	public void setCoLedgerDetailWorkFile(Integer coLedgerDetailWorkFile) {
		this.coLedgerDetailWorkFile = coLedgerDetailWorkFile;
	}

	@Column(name = "Number", unique = true, length = 12)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "Description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Debit", scale = 4)
	public BigDecimal getDebit() {
		return this.debit;
	}

	public void setDebit(BigDecimal debit) {
		this.debit = debit;
	}

	@Column(name = "Credit", scale = 4)
	public BigDecimal getCredit() {
		return this.credit;
	}

	public void setCredit(BigDecimal credit) {
		this.credit = credit;
	}

}
