package com.turborep.turbotracker.company.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConvertCoaId generated by hbm2java
 */
@Embeddable
public class ConvertCoaId implements java.io.Serializable {

	private String account;
	private String description;

	public ConvertCoaId() {
	}

	public ConvertCoaId(String account, String description) {
		this.account = account;
		this.description = description;
	}

	@Column(name = "Account")
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "Description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConvertCoaId))
			return false;
		ConvertCoaId castOther = (ConvertCoaId) other;

		return ((this.getAccount() == castOther.getAccount()) || (this
				.getAccount() != null && castOther.getAccount() != null && this
				.getAccount().equals(castOther.getAccount())))
				&& ((this.getDescription() == castOther.getDescription()) || (this
						.getDescription() != null
						&& castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAccount() == null ? 0 : this.getAccount().hashCode());
		result = 37
				* result
				+ (getDescription() == null ? 0 : this.getDescription()
						.hashCode());
		return result;
	}

}
