package com.turborep.turbotracker.company.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Costate generated by hbm2java
 */
@Entity
@Table(name = "coState", catalog = "")
public class Costate implements java.io.Serializable {

	private int coStateId;
	private String state;
	private String description;

	public Costate() {
	}

	public Costate(int coStateId) {
		this.coStateId = coStateId;
	}

	public Costate(int coStateId, String state, String description) {
		this.coStateId = coStateId;
		this.state = state;
		this.description = description;
	}

	@Id
	@Column(name = "coStateID", unique = true, nullable = false)
	public int getCoStateId() {
		return this.coStateId;
	}

	public void setCoStateId(int coStateId) {
		this.coStateId = coStateId;
	}

	@Column(name = "State", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "Description", length = 20)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
