package com.turborep.turbotracker.company.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cotaxterritory generated by hbm2java
 */
@Entity
@Table(name = "coTaxTerritory", catalog = "")
public class CoTaxTerritory implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer coTaxTerritoryId;
	private String county;
	private String state;
	private String countyCode;
	private BigDecimal taxRate;
	private BigDecimal distribution1;
	private BigDecimal distribution2;
	private BigDecimal distribution3;
	private BigDecimal distribution4;
	private BigDecimal distribution5;
	private BigDecimal distribution6;
	private BigDecimal distribution7;
	private BigDecimal distribution8;
	private Boolean hasSurtax;
	private BigDecimal surtaxCap;
	private BigDecimal surtaxRate;
	private Boolean multiRate;
	private BigDecimal rate2;
	private BigDecimal from2;
	private BigDecimal rate3;
	private BigDecimal from3;
	private BigDecimal rate4;
	private BigDecimal from4;
	private BigDecimal rate5;
	private BigDecimal from5;
	private BigDecimal rate6;
	private BigDecimal from6;
	private boolean taxShipping;
    private String distDesc1;
    private String distDesc2;
    private String distDesc3;
    private String distDesc4;
    private String distDesc5;
    private String distDesc6;
    private String distDesc7;
    private String distDesc8;
    private Date gRDate;
    private BigDecimal gRTaxRate;
    private BigDecimal gRDistribution1;
    private BigDecimal gRDistribution2;
    private BigDecimal gRDistribution3;
    private BigDecimal gRDistribution4;
    private BigDecimal gRDistribution5;
    private BigDecimal gRDistribution6;
    private BigDecimal gRDistribution7;
    private BigDecimal gRDistribution8;
    private BigDecimal gRSurtaxCap;
    private BigDecimal gRSurtaxRate;
    private BigDecimal gRRate1;
    private BigDecimal gRRate2;
    private BigDecimal gRRate3;
    private BigDecimal gRRate4;
    private BigDecimal gRRate5;
    private BigDecimal gRRate6;
	private byte inactive;
	private byte taxfreight;
	

	public CoTaxTerritory() {
		setMultiRate(false);
		setTaxShipping(false);
	}

	public CoTaxTerritory(boolean taxShipping) {
		this.taxShipping = taxShipping;
	}

	public CoTaxTerritory(String county, String state, String countyCode,
			BigDecimal taxRate, BigDecimal distribution1,
			BigDecimal distribution2, BigDecimal distribution3,
			BigDecimal distribution4, BigDecimal distribution5,
			BigDecimal distribution6, BigDecimal distribution7,
			BigDecimal distribution8, Boolean hasSurtax, BigDecimal surtaxCap,
			BigDecimal surtaxRate, Boolean multiRate, BigDecimal rate2,
			BigDecimal from2, BigDecimal rate3, BigDecimal from3,
			BigDecimal rate4, BigDecimal from4, BigDecimal rate5,
			BigDecimal from5, BigDecimal rate6, BigDecimal from6,
			boolean taxShipping) {
		this.county = county;
		this.state = state;
		this.countyCode = countyCode;
		this.taxRate = taxRate;
		this.distribution1 = distribution1;
		this.distribution2 = distribution2;
		this.distribution3 = distribution3;
		this.distribution4 = distribution4;
		this.distribution5 = distribution5;
		this.distribution6 = distribution6;
		this.distribution7 = distribution7;
		this.distribution8 = distribution8;
		this.hasSurtax = hasSurtax;
		this.surtaxCap = surtaxCap;
		this.surtaxRate = surtaxRate;
		this.multiRate = multiRate;
		this.rate2 = rate2;
		this.from2 = from2;
		this.rate3 = rate3;
		this.from3 = from3;
		this.rate4 = rate4;
		this.from4 = from4;
		this.rate5 = rate5;
		this.from5 = from5;
		this.rate6 = rate6;
		this.from6 = from6;
		this.taxShipping = taxShipping;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "coTaxTerritoryID", unique = true, nullable = false)
	public Integer getCoTaxTerritoryId() {
		return this.coTaxTerritoryId;
	}

	public void setCoTaxTerritoryId(Integer coTaxTerritoryId) {
		this.coTaxTerritoryId = coTaxTerritoryId;
	}

	@Column(name = "County", length = 50)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "State", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "CountyCode", length = 6)
	public String getCountyCode() {
		return this.countyCode;
	}

	public void setCountyCode(String countyCode) {
		this.countyCode = countyCode;
	}

	@Column(name = "TaxRate", scale = 4)
	public BigDecimal getTaxRate() {
		return this.taxRate;
	}

	public void setTaxRate(BigDecimal taxRate) {
		this.taxRate = taxRate;
	}

	@Column(name = "Distribution1", scale = 4)
	public BigDecimal getDistribution1() {
		return this.distribution1;
	}

	public void setDistribution1(BigDecimal distribution1) {
		this.distribution1 = distribution1;
	}

	@Column(name = "Distribution2", scale = 4)
	public BigDecimal getDistribution2() {
		return this.distribution2;
	}

	public void setDistribution2(BigDecimal distribution2) {
		this.distribution2 = distribution2;
	}

	@Column(name = "Distribution3", scale = 4)
	public BigDecimal getDistribution3() {
		return this.distribution3;
	}

	public void setDistribution3(BigDecimal distribution3) {
		this.distribution3 = distribution3;
	}

	@Column(name = "Distribution4", scale = 4)
	public BigDecimal getDistribution4() {
		return this.distribution4;
	}

	public void setDistribution4(BigDecimal distribution4) {
		this.distribution4 = distribution4;
	}

	@Column(name = "Distribution5", scale = 4)
	public BigDecimal getDistribution5() {
		return this.distribution5;
	}

	public void setDistribution5(BigDecimal distribution5) {
		this.distribution5 = distribution5;
	}

	@Column(name = "Distribution6", scale = 4)
	public BigDecimal getDistribution6() {
		return this.distribution6;
	}

	public void setDistribution6(BigDecimal distribution6) {
		this.distribution6 = distribution6;
	}

	@Column(name = "Distribution7", scale = 4)
	public BigDecimal getDistribution7() {
		return this.distribution7;
	}

	public void setDistribution7(BigDecimal distribution7) {
		this.distribution7 = distribution7;
	}

	@Column(name = "Distribution8", scale = 4)
	public BigDecimal getDistribution8() {
		return this.distribution8;
	}

	public void setDistribution8(BigDecimal distribution8) {
		this.distribution8 = distribution8;
	}

	@Column(name = "HasSurtax")
	public Boolean getHasSurtax() {
		return this.hasSurtax;
	}

	public void setHasSurtax(Boolean hasSurtax) {
		this.hasSurtax = hasSurtax;
	}

	@Column(name = "SurtaxCap", scale = 4)
	public BigDecimal getSurtaxCap() {
		return this.surtaxCap;
	}

	public void setSurtaxCap(BigDecimal surtaxCap) {
		this.surtaxCap = surtaxCap;
	}

	@Column(name = "SurtaxRate", scale = 4)
	public BigDecimal getSurtaxRate() {
		return this.surtaxRate;
	}

	public void setSurtaxRate(BigDecimal surtaxRate) {
		this.surtaxRate = surtaxRate;
	}

	@Column(name = "MultiRate")
	public Boolean getMultiRate() {
		return this.multiRate;
	}

	public void setMultiRate(Boolean multiRate) {
		this.multiRate = multiRate;
	}

	@Column(name = "Rate2", scale = 4)
	public BigDecimal getRate2() {
		return this.rate2;
	}

	public void setRate2(BigDecimal rate2) {
		this.rate2 = rate2;
	}

	@Column(name = "From2", scale = 4)
	public BigDecimal getFrom2() {
		return this.from2;
	}

	public void setFrom2(BigDecimal from2) {
		this.from2 = from2;
	}

	@Column(name = "Rate3", scale = 4)
	public BigDecimal getRate3() {
		return this.rate3;
	}

	public void setRate3(BigDecimal rate3) {
		this.rate3 = rate3;
	}

	@Column(name = "From3", scale = 4)
	public BigDecimal getFrom3() {
		return this.from3;
	}

	public void setFrom3(BigDecimal from3) {
		this.from3 = from3;
	}

	@Column(name = "Rate4", scale = 4)
	public BigDecimal getRate4() {
		return this.rate4;
	}

	public void setRate4(BigDecimal rate4) {
		this.rate4 = rate4;
	}

	@Column(name = "From4", scale = 4)
	public BigDecimal getFrom4() {
		return this.from4;
	}

	public void setFrom4(BigDecimal from4) {
		this.from4 = from4;
	}

	@Column(name = "Rate5", scale = 4)
	public BigDecimal getRate5() {
		return this.rate5;
	}

	public void setRate5(BigDecimal rate5) {
		this.rate5 = rate5;
	}

	@Column(name = "From5", scale = 4)
	public BigDecimal getFrom5() {
		return this.from5;
	}

	public void setFrom5(BigDecimal from5) {
		this.from5 = from5;
	}

	@Column(name = "Rate6", scale = 4)
	public BigDecimal getRate6() {
		return this.rate6;
	}

	public void setRate6(BigDecimal rate6) {
		this.rate6 = rate6;
	}

	@Column(name = "From6", scale = 4)
	public BigDecimal getFrom6() {
		return this.from6;
	}

	public void setFrom6(BigDecimal from6) {
		this.from6 = from6;
	}

	@Column(name = "TaxShipping", nullable = false)
	public boolean isTaxShipping() {
		return this.taxShipping;
	}

	public void setTaxShipping(boolean taxShipping) {
		this.taxShipping = taxShipping;
	}

	@Column(name = "DistDesc1", length = 80)
	public String getDistDesc1() {
		return distDesc1;
	}

	public void setDistDesc1(String distDesc1) {
		this.distDesc1 = distDesc1;
	}

	@Column(name = "DistDesc2", length = 80)
	public String getDistDesc2() {
		return distDesc2;
	}

	public void setDistDesc2(String distDesc2) {
		this.distDesc2 = distDesc2;
	}

	@Column(name = "DistDesc3", length = 80)
	public String getDistDesc3() {
		return distDesc3;
	}

	public void setDistDesc3(String distDesc3) {
		this.distDesc3 = distDesc3;
	}

	@Column(name = "DistDesc4", length = 80)
	public String getDistDesc4() {
		return distDesc4;
	}

	public void setDistDesc4(String distDesc4) {
		this.distDesc4 = distDesc4;
	}

	@Column(name = "DistDesc5", length = 80)
	public String getDistDesc5() {
		return distDesc5;
	}

	public void setDistDesc5(String distDesc5) {
		this.distDesc5 = distDesc5;
	}

	@Column(name = "DistDesc6", length = 80)
	public String getDistDesc6() {
		return distDesc6;
	}

	public void setDistDesc6(String distDesc6) {
		this.distDesc6 = distDesc6;
	}
	@Column(name = "DistDesc7", length = 80)
	public String getDistDesc7() {
		return distDesc7;
	}

	public void setDistDesc7(String distDesc7) {
		this.distDesc7 = distDesc7;
	}

	@Column(name = "DistDesc8", length = 80)
	public String getDistDesc8() {
		return distDesc8;
	}

	public void setDistDesc8(String distDesc8) {
		this.distDesc8 = distDesc8;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GRDate", length = 0)
	public Date getgRDate() {
		return gRDate;
	}

	public void setgRDate(Date gRDate) {
		this.gRDate = gRDate;
	}

	@Column(name = "GRTaxRate", scale = 4)
	public BigDecimal getgRTaxRate() {
		return gRTaxRate;
	}

	public void setgRTaxRate(BigDecimal gRTaxRate) {
		this.gRTaxRate = gRTaxRate;
	}

	@Column(name = "GRDistribution1", scale = 4)
	public BigDecimal getgRDistribution1() {
		return gRDistribution1;
	}

	public void setgRDistribution1(BigDecimal gRDistribution1) {
		this.gRDistribution1 = gRDistribution1;
	}

	@Column(name = "GRDistribution2", scale = 4)
	public BigDecimal getgRDistribution2() {
		return gRDistribution2;
	}

	public void setgRDistribution2(BigDecimal gRDistribution2) {
		this.gRDistribution2 = gRDistribution2;
	}

	@Column(name = "GRDistribution3", scale = 4)
	public BigDecimal getgRDistribution3() {
		return gRDistribution3;
	}

	public void setgRDistribution3(BigDecimal gRDistribution3) {
		this.gRDistribution3 = gRDistribution3;
	}

	@Column(name = "GRDistribution4", scale = 4)
	public BigDecimal getgRDistribution4() {
		return gRDistribution4;
	}

	public void setgRDistribution4(BigDecimal gRDistribution4) {
		this.gRDistribution4 = gRDistribution4;
	}

	@Column(name = "GRDistribution5", scale = 4)
	public BigDecimal getgRDistribution5() {
		return gRDistribution5;
	}

	public void setgRDistribution5(BigDecimal gRDistribution5) {
		this.gRDistribution5 = gRDistribution5;
	}

	@Column(name = "GRDistribution6", scale = 4)
	public BigDecimal getgRDistribution6() {
		return gRDistribution6;
	}

	public void setgRDistribution6(BigDecimal gRDistribution6) {
		this.gRDistribution6 = gRDistribution6;
	}

	@Column(name = "GRDistribution7", scale = 4)
	public BigDecimal getgRDistribution7() {
		return gRDistribution7;
	}

	public void setgRDistribution7(BigDecimal gRDistribution7) {
		this.gRDistribution7 = gRDistribution7;
	}

	@Column(name = "GRDistribution8", scale = 4)
	public BigDecimal getgRDistribution8() {
		return gRDistribution8;
	}

	public void setgRDistribution8(BigDecimal gRDistribution8) {
		this.gRDistribution8 = gRDistribution8;
	}

	@Column(name = "GRSurtaxCap", scale = 4)
	public BigDecimal getgRSurtaxCap() {
		return gRSurtaxCap;
	}

	public void setgRSurtaxCap(BigDecimal gRSurtaxCap) {
		this.gRSurtaxCap = gRSurtaxCap;
	}

	@Column(name = "GRSurtaxRate", scale = 4)
	public BigDecimal getgRSurtaxRate() {
		return gRSurtaxRate;
	}

	public void setgRSurtaxRate(BigDecimal gRSurtaxRate) {
		this.gRSurtaxRate = gRSurtaxRate;
	}

	@Column(name = "GRRate1", scale = 4)
	public BigDecimal getgRRate1() {
		return gRRate1;
	}

	public void setgRRate1(BigDecimal gRRate1) {
		this.gRRate1 = gRRate1;
	}

	@Column(name = "GRRate2", scale = 4)
	public BigDecimal getgRRate2() {
		return gRRate2;
	}

	public void setgRRate2(BigDecimal gRRate2) {
		this.gRRate2 = gRRate2;
	}

	@Column(name = "GRRate3", scale = 4)
	public BigDecimal getgRRate3() {
		return gRRate3;
	}

	public void setgRRate3(BigDecimal gRRate3) {
		this.gRRate3 = gRRate3;
	}

	@Column(name = "GRRate4", scale = 4)
	public BigDecimal getgRRate4() {
		return gRRate4;
	}

	public void setgRRate4(BigDecimal gRRate4) {
		this.gRRate4 = gRRate4;
	}

	@Column(name = "GRRate5", scale = 4)
	public BigDecimal getgRRate5() {
		return gRRate5;
	}

	public void setgRRate5(BigDecimal gRRate5) {
		this.gRRate5 = gRRate5;
	}

	@Column(name = "GRRate6", scale = 4)
	public BigDecimal getgRRate6() {
		return gRRate6;
	}

	public void setgRRate6(BigDecimal gRRate6) {
		this.gRRate6 = gRRate6;
	}

    @Column(name="inActive", nullable=false)
    public byte getInactive() {
        return this.inactive;
    }

	public void setInactive(byte inactive) {
		this.inactive = inactive;
	}
	
	@Column(name="taxfreight")
	public byte getTaxfreight() {
		return taxfreight;
	}

	public void setTaxfreight(byte taxfreight) {
		this.taxfreight = taxfreight;
	}
}
