package com.turborep.turbotracker.company.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rxjournalworkfile generated by hbm2java
 */
@Entity
@Table(name = "rxjournalworkfile", catalog = "")
public class Rxjournalworkfile implements java.io.Serializable {

	private Integer rxJournalWorkFileId;
	private Integer rxJournalId;
	private Integer rxMasterId;
	private Boolean alreadyExists;
	private Integer rxJournalTypeId;
	private Byte isDeleted;
	private Integer userLoginId;
	private Date entryDate;
	private String entryMemo;

	public Rxjournalworkfile() {
	}

	public Rxjournalworkfile(Integer rxJournalId, Integer rxMasterId,
			Boolean alreadyExists, Integer rxJournalTypeId, Byte isDeleted,
			Integer userLoginId, Date entryDate, String entryMemo) {
		this.rxJournalId = rxJournalId;
		this.rxMasterId = rxMasterId;
		this.alreadyExists = alreadyExists;
		this.rxJournalTypeId = rxJournalTypeId;
		this.isDeleted = isDeleted;
		this.userLoginId = userLoginId;
		this.entryDate = entryDate;
		this.entryMemo = entryMemo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "rxJournalWorkFileID", unique = true, nullable = false)
	public Integer getRxJournalWorkFileId() {
		return this.rxJournalWorkFileId;
	}

	public void setRxJournalWorkFileId(Integer rxJournalWorkFileId) {
		this.rxJournalWorkFileId = rxJournalWorkFileId;
	}

	@Column(name = "rxJournalID")
	public Integer getRxJournalId() {
		return this.rxJournalId;
	}

	public void setRxJournalId(Integer rxJournalId) {
		this.rxJournalId = rxJournalId;
	}

	@Column(name = "rxMasterID")
	public Integer getRxMasterId() {
		return this.rxMasterId;
	}

	public void setRxMasterId(Integer rxMasterId) {
		this.rxMasterId = rxMasterId;
	}

	@Column(name = "AlreadyExists")
	public Boolean getAlreadyExists() {
		return this.alreadyExists;
	}

	public void setAlreadyExists(Boolean alreadyExists) {
		this.alreadyExists = alreadyExists;
	}

	@Column(name = "rxJournalTypeID")
	public Integer getRxJournalTypeId() {
		return this.rxJournalTypeId;
	}

	public void setRxJournalTypeId(Integer rxJournalTypeId) {
		this.rxJournalTypeId = rxJournalTypeId;
	}

	@Column(name = "IsDeleted")
	public Byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "UserLoginID")
	public Integer getUserLoginId() {
		return this.userLoginId;
	}

	public void setUserLoginId(Integer userLoginId) {
		this.userLoginId = userLoginId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EntryDate", length = 0)
	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	@Column(name = "EntryMemo")
	public String getEntryMemo() {
		return this.entryMemo;
	}

	public void setEntryMemo(String entryMemo) {
		this.entryMemo = entryMemo;
	}

}
