package com.turborep.turbotracker.job.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Jobchanges generated by hbm2java
 */
@Entity
@Table(name = "jobchanges", catalog = "")
public class Jobchanges implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer joMasterId;
	private Integer createdById;
	private Date createdOn;
	private Integer changedById;
	private Date changedOn;
	private String jobNumber;
	private Integer rxCustomerId;
	private String description;
	private String locationName;
	private String locationAddress1;
	private String locationAddress2;
	private String locationCity;
	private String locationState;
	private String locationZip;
	private Integer rxCategory1;
	private Integer rxCategory2;
	private Integer rxCategory3;
	private Integer rxCategory4;
	private Integer rxCategory5;
	private Integer cuAssignmentId0;
	private Integer cuAssignmentId1;
	private Integer cuAssignmentId2;
	private Integer cuAssignmentId3;
	private Integer cuAssignmentId4;
	private boolean planAndSpecJob;
	private boolean priorApprovalRequired;
	private boolean priorApprovalDone;
	private Date priorApprovalDoneDate;
	private boolean priorApprovalGranted;
	private Date priorApprovalGrantedDate;
	private boolean source1;
	private boolean source2;
	private boolean source3;
	private boolean source4;
	private boolean submittalSent;
	private boolean submittalApproved;
	private boolean submittalResent;
	private Date submittalSentDate;
	private Date submittalApprovedDate;
	private Date submittalResentDate;
	private String addendumReceived;
	private String addendumQuotedThru;
	private Date bidDate;
	private String bidTime;
	private String customerPonumber;
	private Date bookedDate;
	private Date closedDate;
	private BigDecimal entireJobContractAmount;
	private BigDecimal contractAmount;
	private BigDecimal estimatedCost;
	private BigDecimal estimatedProfit;
	private BigDecimal closeOutActualProfit;
	private Integer jobStatus;
	private Byte creditStatus;
	private Byte creditType;
	private boolean jobBonded;
	private boolean requestedNoc;
	private Date requestedNocdate;
	private boolean receivedNoc;
	private Date receivedNocdate;
	private boolean sentNtc;
	private Date sentNtcdate;
	private boolean lienWaverSigned;
	private Date lienWaverSignedDate;
	private boolean lienWaverThrough;
	private Date lienWaverThroughDate;
	private BigDecimal lienWaverThroughAmount;
	private boolean lienWaverThroughFinal;
	private Integer coTaxTerritoryId;
	private Boolean notice24;
	private Boolean notice48;
	private String noticeCall;
	private Integer who0;
	private Integer who1;
	private Integer who2;
	private Integer who3;
	private Integer who4;
	private Integer who5;
	private Integer who6;
	private Integer who7;
	private Date creditStatusDate;
	private Date creditTypeDate;
	private Date claimFiledDate;
	private Integer creditContact0;
	private Integer creditContact1;
	private Integer creditContact2;
	private Byte claimFiled;
	private String creditNotes;

	public Jobchanges() {
	}

	public Jobchanges(boolean planAndSpecJob, boolean priorApprovalRequired,
			boolean priorApprovalDone, boolean priorApprovalGranted,
			boolean source1, boolean source2, boolean source3, boolean source4,
			boolean submittalSent, boolean submittalApproved,
			boolean submittalResent, boolean jobBonded, boolean requestedNoc,
			boolean receivedNoc, boolean sentNtc, boolean lienWaverSigned,
			boolean lienWaverThrough, boolean lienWaverThroughFinal) {
		this.planAndSpecJob = planAndSpecJob;
		this.priorApprovalRequired = priorApprovalRequired;
		this.priorApprovalDone = priorApprovalDone;
		this.priorApprovalGranted = priorApprovalGranted;
		this.source1 = source1;
		this.source2 = source2;
		this.source3 = source3;
		this.source4 = source4;
		this.submittalSent = submittalSent;
		this.submittalApproved = submittalApproved;
		this.submittalResent = submittalResent;
		this.jobBonded = jobBonded;
		this.requestedNoc = requestedNoc;
		this.receivedNoc = receivedNoc;
		this.sentNtc = sentNtc;
		this.lienWaverSigned = lienWaverSigned;
		this.lienWaverThrough = lienWaverThrough;
		this.lienWaverThroughFinal = lienWaverThroughFinal;
	}

	public Jobchanges(Integer createdById, Date createdOn, Integer changedById,
			Date changedOn, String jobNumber, Integer rxCustomerId,
			String description, String locationName, String locationAddress1,
			String locationAddress2, String locationCity, String locationState,
			String locationZip, Integer rxCategory1, Integer rxCategory2,
			Integer rxCategory3, Integer rxCategory4, Integer rxCategory5,
			Integer cuAssignmentId0, Integer cuAssignmentId1,
			Integer cuAssignmentId2, Integer cuAssignmentId3,
			Integer cuAssignmentId4, boolean planAndSpecJob,
			boolean priorApprovalRequired, boolean priorApprovalDone,
			Date priorApprovalDoneDate, boolean priorApprovalGranted,
			Date priorApprovalGrantedDate, boolean source1, boolean source2,
			boolean source3, boolean source4, boolean submittalSent,
			boolean submittalApproved, boolean submittalResent,
			Date submittalSentDate, Date submittalApprovedDate,
			Date submittalResentDate, String addendumReceived,
			String addendumQuotedThru, Date bidDate, String bidTime,
			String customerPonumber, Date bookedDate, Date closedDate,
			BigDecimal entireJobContractAmount, BigDecimal contractAmount,
			BigDecimal estimatedCost, BigDecimal estimatedProfit,
			BigDecimal closeOutActualProfit, Integer jobStatus,
			Byte creditStatus, Byte creditType, boolean jobBonded,
			boolean requestedNoc, Date requestedNocdate, boolean receivedNoc,
			Date receivedNocdate, boolean sentNtc, Date sentNtcdate,
			boolean lienWaverSigned, Date lienWaverSignedDate,
			boolean lienWaverThrough, Date lienWaverThroughDate,
			BigDecimal lienWaverThroughAmount, boolean lienWaverThroughFinal,
			Integer coTaxTerritoryId, Boolean notice24, Boolean notice48,
			String noticeCall, Integer who0, Integer who1, Integer who2,
			Integer who3, Integer who4, Integer who5, Integer who6,
			Integer who7, Date creditStatusDate, Date creditTypeDate,
			Date claimFiledDate, Integer creditContact0,
			Integer creditContact1, Integer creditContact2, Byte claimFiled,
			String creditNotes) {
		this.createdById = createdById;
		this.createdOn = createdOn;
		this.changedById = changedById;
		this.changedOn = changedOn;
		this.jobNumber = jobNumber;
		this.rxCustomerId = rxCustomerId;
		this.description = description;
		this.locationName = locationName;
		this.locationAddress1 = locationAddress1;
		this.locationAddress2 = locationAddress2;
		this.locationCity = locationCity;
		this.locationState = locationState;
		this.locationZip = locationZip;
		this.rxCategory1 = rxCategory1;
		this.rxCategory2 = rxCategory2;
		this.rxCategory3 = rxCategory3;
		this.rxCategory4 = rxCategory4;
		this.rxCategory5 = rxCategory5;
		this.cuAssignmentId0 = cuAssignmentId0;
		this.cuAssignmentId1 = cuAssignmentId1;
		this.cuAssignmentId2 = cuAssignmentId2;
		this.cuAssignmentId3 = cuAssignmentId3;
		this.cuAssignmentId4 = cuAssignmentId4;
		this.planAndSpecJob = planAndSpecJob;
		this.priorApprovalRequired = priorApprovalRequired;
		this.priorApprovalDone = priorApprovalDone;
		this.priorApprovalDoneDate = priorApprovalDoneDate;
		this.priorApprovalGranted = priorApprovalGranted;
		this.priorApprovalGrantedDate = priorApprovalGrantedDate;
		this.source1 = source1;
		this.source2 = source2;
		this.source3 = source3;
		this.source4 = source4;
		this.submittalSent = submittalSent;
		this.submittalApproved = submittalApproved;
		this.submittalResent = submittalResent;
		this.submittalSentDate = submittalSentDate;
		this.submittalApprovedDate = submittalApprovedDate;
		this.submittalResentDate = submittalResentDate;
		this.addendumReceived = addendumReceived;
		this.addendumQuotedThru = addendumQuotedThru;
		this.bidDate = bidDate;
		this.bidTime = bidTime;
		this.customerPonumber = customerPonumber;
		this.bookedDate = bookedDate;
		this.closedDate = closedDate;
		this.entireJobContractAmount = entireJobContractAmount;
		this.contractAmount = contractAmount;
		this.estimatedCost = estimatedCost;
		this.estimatedProfit = estimatedProfit;
		this.closeOutActualProfit = closeOutActualProfit;
		this.jobStatus = jobStatus;
		this.creditStatus = creditStatus;
		this.creditType = creditType;
		this.jobBonded = jobBonded;
		this.requestedNoc = requestedNoc;
		this.requestedNocdate = requestedNocdate;
		this.receivedNoc = receivedNoc;
		this.receivedNocdate = receivedNocdate;
		this.sentNtc = sentNtc;
		this.sentNtcdate = sentNtcdate;
		this.lienWaverSigned = lienWaverSigned;
		this.lienWaverSignedDate = lienWaverSignedDate;
		this.lienWaverThrough = lienWaverThrough;
		this.lienWaverThroughDate = lienWaverThroughDate;
		this.lienWaverThroughAmount = lienWaverThroughAmount;
		this.lienWaverThroughFinal = lienWaverThroughFinal;
		this.coTaxTerritoryId = coTaxTerritoryId;
		this.notice24 = notice24;
		this.notice48 = notice48;
		this.noticeCall = noticeCall;
		this.who0 = who0;
		this.who1 = who1;
		this.who2 = who2;
		this.who3 = who3;
		this.who4 = who4;
		this.who5 = who5;
		this.who6 = who6;
		this.who7 = who7;
		this.creditStatusDate = creditStatusDate;
		this.creditTypeDate = creditTypeDate;
		this.claimFiledDate = claimFiledDate;
		this.creditContact0 = creditContact0;
		this.creditContact1 = creditContact1;
		this.creditContact2 = creditContact2;
		this.claimFiled = claimFiled;
		this.creditNotes = creditNotes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "joMasterID", unique = true, nullable = false)
	public Integer getJoMasterId() {
		return this.joMasterId;
	}

	public void setJoMasterId(Integer joMasterId) {
		this.joMasterId = joMasterId;
	}

	@Column(name = "CreatedByID")
	public Integer getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(Integer createdById) {
		this.createdById = createdById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 0)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "ChangedByID")
	public Integer getChangedById() {
		return this.changedById;
	}

	public void setChangedById(Integer changedById) {
		this.changedById = changedById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ChangedOn", length = 0)
	public Date getChangedOn() {
		return this.changedOn;
	}

	public void setChangedOn(Date changedOn) {
		this.changedOn = changedOn;
	}

	@Column(name = "JobNumber", length = 10)
	public String getJobNumber() {
		return this.jobNumber;
	}

	public void setJobNumber(String jobNumber) {
		this.jobNumber = jobNumber;
	}

	@Column(name = "rxCustomerID")
	public Integer getRxCustomerId() {
		return this.rxCustomerId;
	}

	public void setRxCustomerId(Integer rxCustomerId) {
		this.rxCustomerId = rxCustomerId;
	}

	@Column(name = "Description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "LocationName", length = 40)
	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	@Column(name = "LocationAddress1", length = 40)
	public String getLocationAddress1() {
		return this.locationAddress1;
	}

	public void setLocationAddress1(String locationAddress1) {
		this.locationAddress1 = locationAddress1;
	}

	@Column(name = "LocationAddress2", length = 40)
	public String getLocationAddress2() {
		return this.locationAddress2;
	}

	public void setLocationAddress2(String locationAddress2) {
		this.locationAddress2 = locationAddress2;
	}

	@Column(name = "LocationCity", length = 30)
	public String getLocationCity() {
		return this.locationCity;
	}

	public void setLocationCity(String locationCity) {
		this.locationCity = locationCity;
	}

	@Column(name = "LocationState", length = 2)
	public String getLocationState() {
		return this.locationState;
	}

	public void setLocationState(String locationState) {
		this.locationState = locationState;
	}

	@Column(name = "LocationZip", length = 10)
	public String getLocationZip() {
		return this.locationZip;
	}

	public void setLocationZip(String locationZip) {
		this.locationZip = locationZip;
	}

	@Column(name = "rxCategory1")
	public Integer getRxCategory1() {
		return this.rxCategory1;
	}

	public void setRxCategory1(Integer rxCategory1) {
		this.rxCategory1 = rxCategory1;
	}

	@Column(name = "rxCategory2")
	public Integer getRxCategory2() {
		return this.rxCategory2;
	}

	public void setRxCategory2(Integer rxCategory2) {
		this.rxCategory2 = rxCategory2;
	}

	@Column(name = "rxCategory3")
	public Integer getRxCategory3() {
		return this.rxCategory3;
	}

	public void setRxCategory3(Integer rxCategory3) {
		this.rxCategory3 = rxCategory3;
	}

	@Column(name = "rxCategory4")
	public Integer getRxCategory4() {
		return this.rxCategory4;
	}

	public void setRxCategory4(Integer rxCategory4) {
		this.rxCategory4 = rxCategory4;
	}

	@Column(name = "rxCategory5")
	public Integer getRxCategory5() {
		return this.rxCategory5;
	}

	public void setRxCategory5(Integer rxCategory5) {
		this.rxCategory5 = rxCategory5;
	}

	@Column(name = "cuAssignmentID0")
	public Integer getCuAssignmentId0() {
		return this.cuAssignmentId0;
	}

	public void setCuAssignmentId0(Integer cuAssignmentId0) {
		this.cuAssignmentId0 = cuAssignmentId0;
	}

	@Column(name = "cuAssignmentID1")
	public Integer getCuAssignmentId1() {
		return this.cuAssignmentId1;
	}

	public void setCuAssignmentId1(Integer cuAssignmentId1) {
		this.cuAssignmentId1 = cuAssignmentId1;
	}

	@Column(name = "cuAssignmentID2")
	public Integer getCuAssignmentId2() {
		return this.cuAssignmentId2;
	}

	public void setCuAssignmentId2(Integer cuAssignmentId2) {
		this.cuAssignmentId2 = cuAssignmentId2;
	}

	@Column(name = "cuAssignmentID3")
	public Integer getCuAssignmentId3() {
		return this.cuAssignmentId3;
	}

	public void setCuAssignmentId3(Integer cuAssignmentId3) {
		this.cuAssignmentId3 = cuAssignmentId3;
	}

	@Column(name = "cuAssignmentID4")
	public Integer getCuAssignmentId4() {
		return this.cuAssignmentId4;
	}

	public void setCuAssignmentId4(Integer cuAssignmentId4) {
		this.cuAssignmentId4 = cuAssignmentId4;
	}

	@Column(name = "PlanAndSpecJob", nullable = false)
	public boolean isPlanAndSpecJob() {
		return this.planAndSpecJob;
	}

	public void setPlanAndSpecJob(boolean planAndSpecJob) {
		this.planAndSpecJob = planAndSpecJob;
	}

	@Column(name = "PriorApprovalRequired", nullable = false)
	public boolean isPriorApprovalRequired() {
		return this.priorApprovalRequired;
	}

	public void setPriorApprovalRequired(boolean priorApprovalRequired) {
		this.priorApprovalRequired = priorApprovalRequired;
	}

	@Column(name = "PriorApprovalDone", nullable = false)
	public boolean isPriorApprovalDone() {
		return this.priorApprovalDone;
	}

	public void setPriorApprovalDone(boolean priorApprovalDone) {
		this.priorApprovalDone = priorApprovalDone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PriorApprovalDoneDate", length = 0)
	public Date getPriorApprovalDoneDate() {
		return this.priorApprovalDoneDate;
	}

	public void setPriorApprovalDoneDate(Date priorApprovalDoneDate) {
		this.priorApprovalDoneDate = priorApprovalDoneDate;
	}

	@Column(name = "PriorApprovalGranted", nullable = false)
	public boolean isPriorApprovalGranted() {
		return this.priorApprovalGranted;
	}

	public void setPriorApprovalGranted(boolean priorApprovalGranted) {
		this.priorApprovalGranted = priorApprovalGranted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PriorApprovalGrantedDate", length = 0)
	public Date getPriorApprovalGrantedDate() {
		return this.priorApprovalGrantedDate;
	}

	public void setPriorApprovalGrantedDate(Date priorApprovalGrantedDate) {
		this.priorApprovalGrantedDate = priorApprovalGrantedDate;
	}

	@Column(name = "Source1", nullable = false)
	public boolean isSource1() {
		return this.source1;
	}

	public void setSource1(boolean source1) {
		this.source1 = source1;
	}

	@Column(name = "Source2", nullable = false)
	public boolean isSource2() {
		return this.source2;
	}

	public void setSource2(boolean source2) {
		this.source2 = source2;
	}

	@Column(name = "Source3", nullable = false)
	public boolean isSource3() {
		return this.source3;
	}

	public void setSource3(boolean source3) {
		this.source3 = source3;
	}

	@Column(name = "Source4", nullable = false)
	public boolean isSource4() {
		return this.source4;
	}

	public void setSource4(boolean source4) {
		this.source4 = source4;
	}

	@Column(name = "SubmittalSent", nullable = false)
	public boolean isSubmittalSent() {
		return this.submittalSent;
	}

	public void setSubmittalSent(boolean submittalSent) {
		this.submittalSent = submittalSent;
	}

	@Column(name = "SubmittalApproved", nullable = false)
	public boolean isSubmittalApproved() {
		return this.submittalApproved;
	}

	public void setSubmittalApproved(boolean submittalApproved) {
		this.submittalApproved = submittalApproved;
	}

	@Column(name = "SubmittalResent", nullable = false)
	public boolean isSubmittalResent() {
		return this.submittalResent;
	}

	public void setSubmittalResent(boolean submittalResent) {
		this.submittalResent = submittalResent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SubmittalSentDate", length = 0)
	public Date getSubmittalSentDate() {
		return this.submittalSentDate;
	}

	public void setSubmittalSentDate(Date submittalSentDate) {
		this.submittalSentDate = submittalSentDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SubmittalApprovedDate", length = 0)
	public Date getSubmittalApprovedDate() {
		return this.submittalApprovedDate;
	}

	public void setSubmittalApprovedDate(Date submittalApprovedDate) {
		this.submittalApprovedDate = submittalApprovedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SubmittalResentDate", length = 0)
	public Date getSubmittalResentDate() {
		return this.submittalResentDate;
	}

	public void setSubmittalResentDate(Date submittalResentDate) {
		this.submittalResentDate = submittalResentDate;
	}

	@Column(name = "AddendumReceived", length = 1)
	public String getAddendumReceived() {
		return this.addendumReceived;
	}

	public void setAddendumReceived(String addendumReceived) {
		this.addendumReceived = addendumReceived;
	}

	@Column(name = "AddendumQuotedThru", length = 1)
	public String getAddendumQuotedThru() {
		return this.addendumQuotedThru;
	}

	public void setAddendumQuotedThru(String addendumQuotedThru) {
		this.addendumQuotedThru = addendumQuotedThru;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BidDate", length = 0)
	public Date getBidDate() {
		return this.bidDate;
	}

	public void setBidDate(Date bidDate) {
		this.bidDate = bidDate;
	}

	@Column(name = "BidTime", length = 8)
	public String getBidTime() {
		return this.bidTime;
	}

	public void setBidTime(String bidTime) {
		this.bidTime = bidTime;
	}

	@Column(name = "CustomerPONumber", length = 20)
	public String getCustomerPonumber() {
		return this.customerPonumber;
	}

	public void setCustomerPonumber(String customerPonumber) {
		this.customerPonumber = customerPonumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BookedDate", length = 0)
	public Date getBookedDate() {
		return this.bookedDate;
	}

	public void setBookedDate(Date bookedDate) {
		this.bookedDate = bookedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ClosedDate", length = 0)
	public Date getClosedDate() {
		return this.closedDate;
	}

	public void setClosedDate(Date closedDate) {
		this.closedDate = closedDate;
	}

	@Column(name = "EntireJobContractAmount", scale = 4)
	public BigDecimal getEntireJobContractAmount() {
		return this.entireJobContractAmount;
	}

	public void setEntireJobContractAmount(BigDecimal entireJobContractAmount) {
		this.entireJobContractAmount = entireJobContractAmount;
	}

	@Column(name = "ContractAmount", scale = 4)
	public BigDecimal getContractAmount() {
		return this.contractAmount;
	}

	public void setContractAmount(BigDecimal contractAmount) {
		this.contractAmount = contractAmount;
	}

	@Column(name = "EstimatedCost", scale = 4)
	public BigDecimal getEstimatedCost() {
		return this.estimatedCost;
	}

	public void setEstimatedCost(BigDecimal estimatedCost) {
		this.estimatedCost = estimatedCost;
	}

	@Column(name = "EstimatedProfit", scale = 4)
	public BigDecimal getEstimatedProfit() {
		return this.estimatedProfit;
	}

	public void setEstimatedProfit(BigDecimal estimatedProfit) {
		this.estimatedProfit = estimatedProfit;
	}

	@Column(name = "CloseOutActualProfit", scale = 4)
	public BigDecimal getCloseOutActualProfit() {
		return this.closeOutActualProfit;
	}

	public void setCloseOutActualProfit(BigDecimal closeOutActualProfit) {
		this.closeOutActualProfit = closeOutActualProfit;
	}

	@Column(name = "JobStatus")
	public Integer getJobStatus() {
		return this.jobStatus;
	}

	public void setJobStatus(Integer jobStatus) {
		this.jobStatus = jobStatus;
	}

	@Column(name = "CreditStatus")
	public Byte getCreditStatus() {
		return this.creditStatus;
	}

	public void setCreditStatus(Byte creditStatus) {
		this.creditStatus = creditStatus;
	}

	@Column(name = "CreditType")
	public Byte getCreditType() {
		return this.creditType;
	}

	public void setCreditType(Byte creditType) {
		this.creditType = creditType;
	}

	@Column(name = "JobBonded", nullable = false)
	public boolean isJobBonded() {
		return this.jobBonded;
	}

	public void setJobBonded(boolean jobBonded) {
		this.jobBonded = jobBonded;
	}

	@Column(name = "RequestedNOC", nullable = false)
	public boolean isRequestedNoc() {
		return this.requestedNoc;
	}

	public void setRequestedNoc(boolean requestedNoc) {
		this.requestedNoc = requestedNoc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RequestedNOCDate", length = 0)
	public Date getRequestedNocdate() {
		return this.requestedNocdate;
	}

	public void setRequestedNocdate(Date requestedNocdate) {
		this.requestedNocdate = requestedNocdate;
	}

	@Column(name = "ReceivedNOC", nullable = false)
	public boolean isReceivedNoc() {
		return this.receivedNoc;
	}

	public void setReceivedNoc(boolean receivedNoc) {
		this.receivedNoc = receivedNoc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ReceivedNOCDate", length = 0)
	public Date getReceivedNocdate() {
		return this.receivedNocdate;
	}

	public void setReceivedNocdate(Date receivedNocdate) {
		this.receivedNocdate = receivedNocdate;
	}

	@Column(name = "SentNTC", nullable = false)
	public boolean isSentNtc() {
		return this.sentNtc;
	}

	public void setSentNtc(boolean sentNtc) {
		this.sentNtc = sentNtc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SentNTCDate", length = 0)
	public Date getSentNtcdate() {
		return this.sentNtcdate;
	}

	public void setSentNtcdate(Date sentNtcdate) {
		this.sentNtcdate = sentNtcdate;
	}

	@Column(name = "LienWaverSigned", nullable = false)
	public boolean isLienWaverSigned() {
		return this.lienWaverSigned;
	}

	public void setLienWaverSigned(boolean lienWaverSigned) {
		this.lienWaverSigned = lienWaverSigned;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LienWaverSignedDate", length = 0)
	public Date getLienWaverSignedDate() {
		return this.lienWaverSignedDate;
	}

	public void setLienWaverSignedDate(Date lienWaverSignedDate) {
		this.lienWaverSignedDate = lienWaverSignedDate;
	}

	@Column(name = "LienWaverThrough", nullable = false)
	public boolean isLienWaverThrough() {
		return this.lienWaverThrough;
	}

	public void setLienWaverThrough(boolean lienWaverThrough) {
		this.lienWaverThrough = lienWaverThrough;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LienWaverThroughDate", length = 0)
	public Date getLienWaverThroughDate() {
		return this.lienWaverThroughDate;
	}

	public void setLienWaverThroughDate(Date lienWaverThroughDate) {
		this.lienWaverThroughDate = lienWaverThroughDate;
	}

	@Column(name = "LienWaverThroughAmount", scale = 4)
	public BigDecimal getLienWaverThroughAmount() {
		return this.lienWaverThroughAmount;
	}

	public void setLienWaverThroughAmount(BigDecimal lienWaverThroughAmount) {
		this.lienWaverThroughAmount = lienWaverThroughAmount;
	}

	@Column(name = "LienWaverThroughFinal", nullable = false)
	public boolean isLienWaverThroughFinal() {
		return this.lienWaverThroughFinal;
	}

	public void setLienWaverThroughFinal(boolean lienWaverThroughFinal) {
		this.lienWaverThroughFinal = lienWaverThroughFinal;
	}

	@Column(name = "coTaxTerritoryID")
	public Integer getCoTaxTerritoryId() {
		return this.coTaxTerritoryId;
	}

	public void setCoTaxTerritoryId(Integer coTaxTerritoryId) {
		this.coTaxTerritoryId = coTaxTerritoryId;
	}

	@Column(name = "Notice24")
	public Boolean getNotice24() {
		return this.notice24;
	}

	public void setNotice24(Boolean notice24) {
		this.notice24 = notice24;
	}

	@Column(name = "Notice48")
	public Boolean getNotice48() {
		return this.notice48;
	}

	public void setNotice48(Boolean notice48) {
		this.notice48 = notice48;
	}

	@Column(name = "NoticeCall", length = 35)
	public String getNoticeCall() {
		return this.noticeCall;
	}

	public void setNoticeCall(String noticeCall) {
		this.noticeCall = noticeCall;
	}

	@Column(name = "who0")
	public Integer getWho0() {
		return this.who0;
	}

	public void setWho0(Integer who0) {
		this.who0 = who0;
	}

	@Column(name = "who1")
	public Integer getWho1() {
		return this.who1;
	}

	public void setWho1(Integer who1) {
		this.who1 = who1;
	}

	@Column(name = "who2")
	public Integer getWho2() {
		return this.who2;
	}

	public void setWho2(Integer who2) {
		this.who2 = who2;
	}

	@Column(name = "who3")
	public Integer getWho3() {
		return this.who3;
	}

	public void setWho3(Integer who3) {
		this.who3 = who3;
	}

	@Column(name = "who4")
	public Integer getWho4() {
		return this.who4;
	}

	public void setWho4(Integer who4) {
		this.who4 = who4;
	}

	@Column(name = "who5")
	public Integer getWho5() {
		return this.who5;
	}

	public void setWho5(Integer who5) {
		this.who5 = who5;
	}

	@Column(name = "who6")
	public Integer getWho6() {
		return this.who6;
	}

	public void setWho6(Integer who6) {
		this.who6 = who6;
	}

	@Column(name = "who7")
	public Integer getWho7() {
		return this.who7;
	}

	public void setWho7(Integer who7) {
		this.who7 = who7;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreditStatusDate", length = 0)
	public Date getCreditStatusDate() {
		return this.creditStatusDate;
	}

	public void setCreditStatusDate(Date creditStatusDate) {
		this.creditStatusDate = creditStatusDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreditTypeDate", length = 0)
	public Date getCreditTypeDate() {
		return this.creditTypeDate;
	}

	public void setCreditTypeDate(Date creditTypeDate) {
		this.creditTypeDate = creditTypeDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ClaimFiledDate", length = 0)
	public Date getClaimFiledDate() {
		return this.claimFiledDate;
	}

	public void setClaimFiledDate(Date claimFiledDate) {
		this.claimFiledDate = claimFiledDate;
	}

	@Column(name = "CreditContact0")
	public Integer getCreditContact0() {
		return this.creditContact0;
	}

	public void setCreditContact0(Integer creditContact0) {
		this.creditContact0 = creditContact0;
	}

	@Column(name = "CreditContact1")
	public Integer getCreditContact1() {
		return this.creditContact1;
	}

	public void setCreditContact1(Integer creditContact1) {
		this.creditContact1 = creditContact1;
	}

	@Column(name = "CreditContact2")
	public Integer getCreditContact2() {
		return this.creditContact2;
	}

	public void setCreditContact2(Integer creditContact2) {
		this.creditContact2 = creditContact2;
	}

	@Column(name = "ClaimFiled")
	public Byte getClaimFiled() {
		return this.claimFiled;
	}

	public void setClaimFiled(Byte claimFiled) {
		this.claimFiled = claimFiled;
	}

	@Column(name = "CreditNotes")
	public String getCreditNotes() {
		return this.creditNotes;
	}

	public void setCreditNotes(String creditNotes) {
		this.creditNotes = creditNotes;
	}

}
