package com.turborep.turbotracker.job.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Jobidder generated by hbm2java
 */
@Entity
@Table(name = "joBidder", catalog = "")
public class Jobidder implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer joBidderId;
	private Integer joMasterId;
	private Integer rxMasterId;
	private Integer rxContactId;
	private Integer cuMasterTypeId;
	private boolean lowBid;
	private boolean noChance;
	private String quoteRev;
	private Date quoteDate;
	private byte quoteStatus;
	private Integer userLoginID;
	private Integer quoteemailstatus=0;
	
	public Jobidder() {
	}

	public Jobidder(boolean lowBid, boolean noChance, byte quoteStatus) {
		this.lowBid = lowBid;
		this.noChance = noChance;
		this.quoteStatus = quoteStatus;
	}

	public Jobidder(Integer joMasterId, Integer rxMasterId,
			Integer rxContactId, Integer cuMasterTypeId, boolean lowBid,
			boolean noChance, String quoteRev, Date quoteDate, byte quoteStatus) {
		this.joMasterId = joMasterId;
		this.rxMasterId = rxMasterId;
		this.rxContactId = rxContactId;
		this.cuMasterTypeId = cuMasterTypeId;
		this.lowBid = lowBid;
		this.noChance = noChance;
		this.quoteRev = quoteRev;
		this.quoteDate = quoteDate;
		this.quoteStatus = quoteStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "joBidderID", unique = true, nullable = false)
	public Integer getJoBidderId() {
		return this.joBidderId;
	}

	public void setJoBidderId(Integer joBidderId) {
		this.joBidderId = joBidderId;
	}

	@Column(name = "joMasterID")
	public Integer getJoMasterId() {
		return this.joMasterId;
	}

	public void setJoMasterId(Integer joMasterId) {
		this.joMasterId = joMasterId;
	}

	@Column(name = "rxMasterID")
	public Integer getRxMasterId() {
		return this.rxMasterId;
	}

	public void setRxMasterId(Integer rxMasterId) {
		this.rxMasterId = rxMasterId;
	}

	@Column(name = "rxContactID")
	public Integer getRxContactId() {
		return this.rxContactId;
	}

	public void setRxContactId(Integer rxContactId) {
		this.rxContactId = rxContactId;
	}

	@Column(name = "cuMasterTypeID")
	public Integer getCuMasterTypeId() {
		return this.cuMasterTypeId;
	}

	public void setCuMasterTypeId(Integer cuMasterTypeId) {
		this.cuMasterTypeId = cuMasterTypeId;
	}

	@Column(name = "LowBid", nullable = false)
	public boolean isLowBid() {
		return this.lowBid;
	}

	public void setLowBid(boolean lowBid) {
		this.lowBid = lowBid;
	}

	@Column(name = "NoChance", nullable = false)
	public boolean isNoChance() {
		return this.noChance;
	}

	public void setNoChance(boolean noChance) {
		this.noChance = noChance;
	}

	@Column(name = "QuoteRev", length = 3)
	public String getQuoteRev() {
		return this.quoteRev;
	}

	public void setQuoteRev(String quoteRev) {
		this.quoteRev = quoteRev;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QuoteDate", length = 0)
	public Date getQuoteDate() {
		return this.quoteDate;
	}

	public void setQuoteDate(Date quoteDate) {
		this.quoteDate = quoteDate;
	}

	@Column(name = "QuoteStatus", nullable = false)
	public byte getQuoteStatus() {
		return this.quoteStatus;
	}

	public void setQuoteStatus(byte quoteStatus) {
		this.quoteStatus = quoteStatus;
	}

	@Column(name = "UserLoginID")
	public Integer getUserLoginID() {
		return userLoginID;
	}

	public void setUserLoginID(Integer userLoginID) {
		this.userLoginID = userLoginID;
	}
	@Column(name = "quoteemailstatus")
	public Integer getQuoteemailstatus() {
		return quoteemailstatus;
	}

	public void setQuoteemailstatus(Integer quoteemailstatus) {
		this.quoteemailstatus = quoteemailstatus;
	}

}
