package com.turborep.turbotracker.job.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Jocustpo generated by hbm2java
 */
@Entity
@Table(name = "joCustPO", catalog = "")
public class JoCustPO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer joCustPoid;
	private Integer joMasterId;
	private String podesc0;
	private String podesc1;
	private String podesc2;
	private String podesc3;
	private String podesc4;
	private String podesc5;
	private String customerPonumber1;
	private String customerPonumber2;
	private String customerPonumber3;
	private String customerPonumber4;
	private String customerPonumber5;
	private BigDecimal poamount0;
	private BigDecimal poamount1;
	private BigDecimal poamount2;
	private BigDecimal poamount3;
	private BigDecimal poamount4;
	private BigDecimal poamount5;
	private String oper;

	public JoCustPO() {
	}

	public JoCustPO(Integer joMasterId, String podesc0, String podesc1,
			String podesc2, String podesc3, String podesc4, String podesc5,
			String customerPonumber1, String customerPonumber2,
			String customerPonumber3, String customerPonumber4,
			String customerPonumber5, BigDecimal poamount0,
			BigDecimal poamount1, BigDecimal poamount2, BigDecimal poamount3,
			BigDecimal poamount4, BigDecimal poamount5) {
		this.joMasterId = joMasterId;
		this.podesc0 = podesc0;
		this.podesc1 = podesc1;
		this.podesc2 = podesc2;
		this.podesc3 = podesc3;
		this.podesc4 = podesc4;
		this.podesc5 = podesc5;
		this.customerPonumber1 = customerPonumber1;
		this.customerPonumber2 = customerPonumber2;
		this.customerPonumber3 = customerPonumber3;
		this.customerPonumber4 = customerPonumber4;
		this.customerPonumber5 = customerPonumber5;
		this.poamount0 = poamount0;
		this.poamount1 = poamount1;
		this.poamount2 = poamount2;
		this.poamount3 = poamount3;
		this.poamount4 = poamount4;
		this.poamount5 = poamount5;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "joCustPOID", unique = true, nullable = false)
	public Integer getJoCustPoid() {
		return this.joCustPoid;
	}

	public void setJoCustPoid(Integer joCustPoid) {
		this.joCustPoid = joCustPoid;
	}

	@Column(name = "joMasterID")
	public Integer getJoMasterId() {
		return this.joMasterId;
	}

	public void setJoMasterId(Integer joMasterId) {
		this.joMasterId = joMasterId;
	}

	@Column(name = "PODesc0", length = 64)
	public String getPodesc0() {
		return this.podesc0;
	}

	public void setPodesc0(String podesc0) {
		this.podesc0 = podesc0;
	}

	@Column(name = "PODesc1", length = 64)
	public String getPodesc1() {
		return this.podesc1;
	}

	public void setPodesc1(String podesc1) {
		this.podesc1 = podesc1;
	}

	@Column(name = "PODesc2", length = 64)
	public String getPodesc2() {
		return this.podesc2;
	}

	public void setPodesc2(String podesc2) {
		this.podesc2 = podesc2;
	}

	@Column(name = "PODesc3", length = 64)
	public String getPodesc3() {
		return this.podesc3;
	}

	public void setPodesc3(String podesc3) {
		this.podesc3 = podesc3;
	}

	@Column(name = "PODesc4", length = 64)
	public String getPodesc4() {
		return this.podesc4;
	}

	public void setPodesc4(String podesc4) {
		this.podesc4 = podesc4;
	}

	@Column(name = "PODesc5", length = 64)
	public String getPodesc5() {
		return this.podesc5;
	}

	public void setPodesc5(String podesc5) {
		this.podesc5 = podesc5;
	}

	@Column(name = "CustomerPONumber1", length = 20)
	public String getCustomerPonumber1() {
		return this.customerPonumber1;
	}

	public void setCustomerPonumber1(String customerPonumber1) {
		this.customerPonumber1 = customerPonumber1;
	}

	@Column(name = "CustomerPONumber2", length = 20)
	public String getCustomerPonumber2() {
		return this.customerPonumber2;
	}

	public void setCustomerPonumber2(String customerPonumber2) {
		this.customerPonumber2 = customerPonumber2;
	}

	@Column(name = "CustomerPONumber3", length = 20)
	public String getCustomerPonumber3() {
		return this.customerPonumber3;
	}

	public void setCustomerPonumber3(String customerPonumber3) {
		this.customerPonumber3 = customerPonumber3;
	}

	@Column(name = "CustomerPONumber4", length = 20)
	public String getCustomerPonumber4() {
		return this.customerPonumber4;
	}

	public void setCustomerPonumber4(String customerPonumber4) {
		this.customerPonumber4 = customerPonumber4;
	}

	@Column(name = "CustomerPONumber5", length = 20)
	public String getCustomerPonumber5() {
		return this.customerPonumber5;
	}

	public void setCustomerPonumber5(String customerPonumber5) {
		this.customerPonumber5 = customerPonumber5;
	}

	@Column(name = "POAmount0", scale = 4)
	public BigDecimal getPoamount0() {
		return this.poamount0;
	}

	public void setPoamount0(BigDecimal poamount0) {
		this.poamount0 = poamount0;
	}

	@Column(name = "POAmount1", scale = 4)
	public BigDecimal getPoamount1() {
		return this.poamount1;
	}

	public void setPoamount1(BigDecimal poamount1) {
		this.poamount1 = poamount1;
	}

	@Column(name = "POAmount2", scale = 4)
	public BigDecimal getPoamount2() {
		return this.poamount2;
	}

	public void setPoamount2(BigDecimal poamount2) {
		this.poamount2 = poamount2;
	}

	@Column(name = "POAmount3", scale = 4)
	public BigDecimal getPoamount3() {
		return this.poamount3;
	}

	public void setPoamount3(BigDecimal poamount3) {
		this.poamount3 = poamount3;
	}

	@Column(name = "POAmount4", scale = 4)
	public BigDecimal getPoamount4() {
		return this.poamount4;
	}

	public void setPoamount4(BigDecimal poamount4) {
		this.poamount4 = poamount4;
	}

	@Column(name = "POAmount5", scale = 4)
	public BigDecimal getPoamount5() {
		return this.poamount5;
	}

	public void setPoamount5(BigDecimal poamount5) {
		this.poamount5 = poamount5;
	}

	@Transient
	public String getOper() {
		return oper;
	}

	public void setOper(String oper) {
		this.oper = oper;
	}

}
