package com.turborep.turbotracker.job.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Jocustpoworkfile generated by hbm2java
 */
@Entity
@Table(name = "jocustpoworkfile", catalog = "")
public class Jocustpoworkfile implements java.io.Serializable {

	private JocustpoworkfileId id;

	public Jocustpoworkfile() {
	}

	public Jocustpoworkfile(JocustpoworkfileId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "joCustPoworkFileId", column = @Column(name = "joCustPOWorkFileID")),
			@AttributeOverride(name = "ponumber", column = @Column(name = "PONumber", length = 20)),
			@AttributeOverride(name = "description", column = @Column(name = "Description", length = 50)) })
	public JocustpoworkfileId getId() {
		return this.id;
	}

	public void setId(JocustpoworkfileId id) {
		this.id = id;
	}

}
