package com.turborep.turbotracker.job.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Jododgework generated by hbm2java
 */
@Entity
@Table(name = "jododgework", catalog = "")
public class Jododgework implements java.io.Serializable {

	private Integer joDodgeWorkId;
	private Boolean import_;
	private String fldPlans;
	private String fldProjectName;
	private String fldReportNo;
	private String fldVerd;
	private String fldBidDate;
	private String fldStage;
	private String fldProjectType;
	private String fldValuation;
	private String fldAddress;
	private String fldCity;
	private String fldCounty;
	private String fldState;
	private String fldZipCode;

	public Jododgework() {
	}

	public Jododgework(Boolean import_, String fldPlans, String fldProjectName,
			String fldReportNo, String fldVerd, String fldBidDate,
			String fldStage, String fldProjectType, String fldValuation,
			String fldAddress, String fldCity, String fldCounty,
			String fldState, String fldZipCode) {
		this.import_ = import_;
		this.fldPlans = fldPlans;
		this.fldProjectName = fldProjectName;
		this.fldReportNo = fldReportNo;
		this.fldVerd = fldVerd;
		this.fldBidDate = fldBidDate;
		this.fldStage = fldStage;
		this.fldProjectType = fldProjectType;
		this.fldValuation = fldValuation;
		this.fldAddress = fldAddress;
		this.fldCity = fldCity;
		this.fldCounty = fldCounty;
		this.fldState = fldState;
		this.fldZipCode = fldZipCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "joDodgeWorkID", unique = true, nullable = false)
	public Integer getJoDodgeWorkId() {
		return this.joDodgeWorkId;
	}

	public void setJoDodgeWorkId(Integer joDodgeWorkId) {
		this.joDodgeWorkId = joDodgeWorkId;
	}

	@Column(name = "Import")
	public Boolean getImport_() {
		return this.import_;
	}

	public void setImport_(Boolean import_) {
		this.import_ = import_;
	}

	@Column(name = "fldPlans", length = 50)
	public String getFldPlans() {
		return this.fldPlans;
	}

	public void setFldPlans(String fldPlans) {
		this.fldPlans = fldPlans;
	}

	@Column(name = "fldProjectName", length = 80)
	public String getFldProjectName() {
		return this.fldProjectName;
	}

	public void setFldProjectName(String fldProjectName) {
		this.fldProjectName = fldProjectName;
	}

	@Column(name = "fldReportNo", length = 10)
	public String getFldReportNo() {
		return this.fldReportNo;
	}

	public void setFldReportNo(String fldReportNo) {
		this.fldReportNo = fldReportNo;
	}

	@Column(name = "fldVerd", length = 50)
	public String getFldVerd() {
		return this.fldVerd;
	}

	public void setFldVerd(String fldVerd) {
		this.fldVerd = fldVerd;
	}

	@Column(name = "fldBidDate", length = 50)
	public String getFldBidDate() {
		return this.fldBidDate;
	}

	public void setFldBidDate(String fldBidDate) {
		this.fldBidDate = fldBidDate;
	}

	@Column(name = "fldStage", length = 50)
	public String getFldStage() {
		return this.fldStage;
	}

	public void setFldStage(String fldStage) {
		this.fldStage = fldStage;
	}

	@Column(name = "fldProjectType", length = 50)
	public String getFldProjectType() {
		return this.fldProjectType;
	}

	public void setFldProjectType(String fldProjectType) {
		this.fldProjectType = fldProjectType;
	}

	@Column(name = "fldValuation", length = 50)
	public String getFldValuation() {
		return this.fldValuation;
	}

	public void setFldValuation(String fldValuation) {
		this.fldValuation = fldValuation;
	}

	@Column(name = "fldAddress", length = 50)
	public String getFldAddress() {
		return this.fldAddress;
	}

	public void setFldAddress(String fldAddress) {
		this.fldAddress = fldAddress;
	}

	@Column(name = "fldCity", length = 50)
	public String getFldCity() {
		return this.fldCity;
	}

	public void setFldCity(String fldCity) {
		this.fldCity = fldCity;
	}

	@Column(name = "fldCounty", length = 50)
	public String getFldCounty() {
		return this.fldCounty;
	}

	public void setFldCounty(String fldCounty) {
		this.fldCounty = fldCounty;
	}

	@Column(name = "fldState", length = 50)
	public String getFldState() {
		return this.fldState;
	}

	public void setFldState(String fldState) {
		this.fldState = fldState;
	}

	@Column(name = "fldZipCode", length = 50)
	public String getFldZipCode() {
		return this.fldZipCode;
	}

	public void setFldZipCode(String fldZipCode) {
		this.fldZipCode = fldZipCode;
	}

}
