package com.turborep.turbotracker.job.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Jododgeexcludetype generated by hbm2java
 */
@Entity
@Table(name = "jododgeexcludetype", catalog = "")
public class Jododgeexcludetype implements java.io.Serializable {

	private String excludeType;

	public Jododgeexcludetype() {
	}

	public Jododgeexcludetype(String excludeType) {
		this.excludeType = excludeType;
	}

	@Id
	@Column(name = "ExcludeType", unique = true, nullable = false, length = 50)
	public String getExcludeType() {
		return this.excludeType;
	}

	public void setExcludeType(String excludeType) {
		this.excludeType = excludeType;
	}

}
