package com.turborep.turbotracker.job.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Joquotetemplatedetail generated by hbm2java
 */
@Entity
@Table(name = "joQuoteTemplateDetail", catalog = "")
public class JoQuoteTemplateDetail implements java.io.Serializable {

	private Integer joQuoteTemplateDetailId;
	private Integer joQuoteTemplateHeaderId;
	private String product;
	private String productNote;
	private String itemQuantity;
	private String paragraph;
	private Integer rxManufacturerId;
	private BigDecimal price;
	private String inlineNote;
	private BigDecimal cost;
	private String manufacturerName;
	private Short spec;
	private BigDecimal mult;
	private byte subTotal;
	private Integer detailSequenceId;
	private Short veFactoryId;
	private byte fmtBold;
	private byte fmtUnderline;
	private byte fmtItalic;
	private byte fmtLarge;
	private String pricingNote;
	private double position;
	private BigDecimal percentage;

	
	//transient variable
	private String itemClassName;
	private String qtyClassName;
	private String paraClassName;
	private String manfcClassName;
	private String specClassName;
	private String multClassName;
	private String priceClassName;
	private String inLineNoteImage;
	
	public JoQuoteTemplateDetail() {
	}

	public JoQuoteTemplateDetail(Integer joQuoteTemplateHeaderId,
			String product, String productNote, String itemQuantity,
			String paragraph, Integer rxManufacturerId, BigDecimal price,
			String inlineNote, BigDecimal cost) {
		this.joQuoteTemplateHeaderId = joQuoteTemplateHeaderId;
		this.product = product;
		this.productNote = productNote;
		this.itemQuantity = itemQuantity;
		this.paragraph = paragraph;
		this.rxManufacturerId = rxManufacturerId;
		this.price = price;
		this.inlineNote = inlineNote;
		this.cost = cost;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "joQuoteTemplateDetailID", unique = true, nullable = false)
	public Integer getJoQuoteTemplateDetailId() {
		return this.joQuoteTemplateDetailId;
	}

	public void setJoQuoteTemplateDetailId(Integer joQuoteTemplateDetailId) {
		this.joQuoteTemplateDetailId = joQuoteTemplateDetailId;
	}

	@Column(name = "joQuoteTemplateHeaderID")
	public Integer getJoQuoteTemplateHeaderId() {
		return this.joQuoteTemplateHeaderId;
	}

	public void setJoQuoteTemplateHeaderId(Integer joQuoteTemplateHeaderId) {
		this.joQuoteTemplateHeaderId = joQuoteTemplateHeaderId;
	}

	@Column(name = "Product")
	public String getProduct() {
		return this.product;
	}

	public void setProduct(String product) {
		this.product = product;
	}

	@Column(name = "ProductNote")
	public String getProductNote() {
		return this.productNote;
	}

	public void setProductNote(String productNote) {
		this.productNote = productNote;
	}

	@Column(name = "ItemQuantity", length = 8)
	public String getItemQuantity() {
		return this.itemQuantity;
	}

	public void setItemQuantity(String itemQuantity) {
		this.itemQuantity = itemQuantity;
	}

	@Column(name = "Paragraph", length = 16)
	public String getParagraph() {
		return this.paragraph;
	}

	public void setParagraph(String paragraph) {
		this.paragraph = paragraph;
	}

	@Column(name = "rxManufacturerID")
	public Integer getRxManufacturerId() {
		return this.rxManufacturerId;
	}

	public void setRxManufacturerId(Integer rxManufacturerId) {
		this.rxManufacturerId = rxManufacturerId;
	}

	@Column(name = "Price", scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "InlineNote")
	public String getInlineNote() {
		return this.inlineNote;
	}

	public void setInlineNote(String inlineNote) {
		this.inlineNote = inlineNote;
	}

	@Column(name = "Cost", scale = 4)
	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	@Column(name = "Spec", scale = 4)
	public Short getSpec() {
		return this.spec;
	}

	public void setSpec(Short spec) {
		this.spec = spec;
	}

	@Transient
	public String getManufacturerName() {
		return manufacturerName;
	}

	public void setManufacturerName(String manufacturerName) {
		this.manufacturerName = manufacturerName;
	}

	@Column(name = "Mult", scale = 4)
	public BigDecimal getMult() {
		return mult;
	}

	public void setMult(BigDecimal mult) {
		this.mult = mult;
	}
	
	@Column(name="veFactoryID")
	public Short getVeFactoryId() {
	    return this.veFactoryId;
	}
	
	public void setVeFactoryId(Short veFactoryId) {
	    this.veFactoryId = veFactoryId;
	}
		
	@Column(name="FmtBold", nullable=false)
	public byte getFmtBold() {
	    return this.fmtBold;
	}
	
	public void setFmtBold(byte fmtBold) {
	    this.fmtBold = fmtBold;
	}
	
	
	@Column(name="FmtUnderline", nullable=false)
	public byte getFmtUnderline() {
	    return this.fmtUnderline;
	}
	
	public void setFmtUnderline(byte fmtUnderline) {
	    this.fmtUnderline = fmtUnderline;
	}
	
	
	@Column(name="FmtItalic", nullable=false)
	public byte getFmtItalic() {
	    return this.fmtItalic;
	}
	
	public void setFmtItalic(byte fmtItalic) {
	    this.fmtItalic = fmtItalic;
	}
	
	
	@Column(name="FmtLarge", nullable=false)
	public byte getFmtLarge() {
	    return this.fmtLarge;
	}
	
	public void setFmtLarge(byte fmtLarge) {
	    this.fmtLarge = fmtLarge;
	}
	
	
	@Column(name="DetailSequenceID")
	public Integer getDetailSequenceId() {
	    return this.detailSequenceId;
	}
	
	public void setDetailSequenceId(Integer detailSequenceId) {
	    this.detailSequenceId = detailSequenceId;
	}
	
	
	@Column(name="PricingNote")
	public String getPricingNote() {
	    return this.pricingNote;
	}
	
	public void setPricingNote(String pricingNote) {
	    this.pricingNote = pricingNote;
	}

	@Column(name="position")
	public double getPosition() {
		return position;
	}


	public void setPosition(double position) {
		this.position = position;
	}

	@Column(name="Percentage")
	public BigDecimal getPercentage() {
		return percentage;
	}


	public void setPercentage(BigDecimal percentage) {
		this.percentage = percentage;
	}

	@Column(name="Subtotal")
	public byte getSubTotal() {
		return subTotal;
	}

	public void setSubTotal(byte subTotal) {
		this.subTotal = subTotal;
	}

	@Transient
	public String getItemClassName() {
		return itemClassName;
	}

	public void setItemClassName(String itemClassName) {
		this.itemClassName = itemClassName;
	}
	@Transient
	public String getQtyClassName() {
		return qtyClassName;
	}

	public void setQtyClassName(String qtyClassName) {
		this.qtyClassName = qtyClassName;
	}
	@Transient
	public String getParaClassName() {
		return paraClassName;
	}

	public void setParaClassName(String paraClassName) {
		this.paraClassName = paraClassName;
	}
	@Transient
	public String getManfcClassName() {
		return manfcClassName;
	}
	
	public void setManfcClassName(String manfcClassName) {
		this.manfcClassName = manfcClassName;
	}
	@Transient
	public String getSpecClassName() {
		return specClassName;
	}

	public void setSpecClassName(String specClassName) {
		this.specClassName = specClassName;
	}
	@Transient
	public String getMultClassName() {
		return multClassName;
	}

	public void setMultClassName(String multClassName) {
		this.multClassName = multClassName;
	}
	@Transient
	public String getPriceClassName() {
		return priceClassName;
	}

	public void setPriceClassName(String priceClassName) {
		this.priceClassName = priceClassName;
	}
	@Transient
	public String getInLineNoteImage() {
		return inLineNoteImage;
	}

	public void setInLineNoteImage(String inLineNoteImage) {
		this.inLineNoteImage = inLineNoteImage;
	}

}
