package com.turborep.turbotracker.job.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.springframework.web.bind.annotation.RequestParam;
/**
 * JoQuoteHeader generated by hbm2java
 */
@Entity
@Table(name="joQuoteHeader",catalog="")
public class JoQuoteHeader  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer joQuoteHeaderId;
	private Integer joMasterID;
	private Integer cuMasterTypeID;
	private String quoteRev;
	private BigDecimal quoteAmount;
	private BigDecimal discountedPrice;
	private Integer createdById;
	private String createdByName;
	private String remarks;
	private Byte quoteYesNo1;
	private Byte locked;
	private Date dateCreated;
	private byte displayQuantity;
	private byte displayParagraph;
	private byte displayManufacturer;
	private byte displayCost;
	private byte displayPrice;
	private byte printQuantity;
	private byte printParagraph;
	private byte printManufacturer;
	private byte printCost;
	private byte printPrice;
	private byte notesFullWidth;
	private byte lineNumbers;
	private byte printTotal;
	private BigDecimal costAmount;
	private byte displayMult;
	private byte displaySpec;
	private byte printMult;
	private byte printSpec;
	private byte hidePrice;
	private String internalNote;
	private byte primaryQuote;
	private byte bookedQuote;
	private String quoteStatus;
	private String quoteType;
	private String company;
	private String contact;
	private String quoteHistoryDate;
	private Integer rxContactID;
	private Integer joQuoteTemplateHeaderId;
	private Integer neworoldquote=1;
	
	private Short includeLSD;
	private Short donotQtyitem2and3;
	private Short showTotPriceonly;
	private BigDecimal LSDValue;
	
	
	public JoQuoteHeader() {
	}

	
	public JoQuoteHeader(byte displayQuantity, byte displayParagraph, byte displayManufacturer, byte displayCost, byte displayPrice, byte printQuantity, byte printParagraph, byte printManufacturer, byte printCost, byte printPrice, byte notesFullWidth, byte lineNumbers, byte printTotal, byte displayMult, byte displaySpec, byte printMult, byte printSpec, byte hidePrice, byte primaryQuote, byte bookedQuote) {
		this.displayQuantity = displayQuantity;
		this.displayParagraph = displayParagraph;
		this.displayManufacturer = displayManufacturer;
		this.displayCost = displayCost;
		this.displayPrice = displayPrice;
		this.printQuantity = printQuantity;
		this.printParagraph = printParagraph;
		this.printManufacturer = printManufacturer;
		this.printCost = printCost;
		this.printPrice = printPrice;
		this.notesFullWidth = notesFullWidth;
		this.lineNumbers = lineNumbers;
		this.printTotal = printTotal;
		this.displayMult = displayMult;
		this.displaySpec = displaySpec;
		this.printMult = printMult;
		this.printSpec = printSpec;
		this.hidePrice = hidePrice;
		this.primaryQuote = primaryQuote;
		this.bookedQuote = bookedQuote;
	}
	public JoQuoteHeader(String quoteRev, BigDecimal quoteAmount, BigDecimal discountedPrice, Integer createdById, String createdByName, String remarks, Byte quoteYesNo1, Byte locked, Date dateCreated, byte displayQuantity, byte displayParagraph, byte displayManufacturer, byte displayCost, byte displayPrice, byte printQuantity, byte printParagraph, byte printManufacturer, byte printCost, byte printPrice, byte notesFullWidth, byte lineNumbers, byte printTotal, BigDecimal costAmount, byte displayMult, byte displaySpec, byte printMult, byte printSpec, byte hidePrice, String internalNote, byte primaryQuote, byte bookedQuote) {
		this.quoteRev = quoteRev;
		this.quoteAmount = quoteAmount;
		this.discountedPrice = discountedPrice;
		this.createdById = createdById;
		this.createdByName = createdByName;
		this.remarks = remarks;
		this.quoteYesNo1 = quoteYesNo1;
		this.locked = locked;
		this.dateCreated = dateCreated;
		this.displayQuantity = displayQuantity;
		this.displayParagraph = displayParagraph;
		this.displayManufacturer = displayManufacturer;
		this.displayCost = displayCost;
		this.displayPrice = displayPrice;
		this.printQuantity = printQuantity;
		this.printParagraph = printParagraph;
		this.printManufacturer = printManufacturer;
		this.printCost = printCost;
		this.printPrice = printPrice;
		this.notesFullWidth = notesFullWidth;
		this.lineNumbers = lineNumbers;
		this.printTotal = printTotal;
		this.costAmount = costAmount;
		this.displayMult = displayMult;
		this.displaySpec = displaySpec;
		this.printMult = printMult;
		this.printSpec = printSpec;
		this.hidePrice = hidePrice;
		this.internalNote = internalNote;
		this.primaryQuote = primaryQuote;
		this.bookedQuote = bookedQuote;
	}
    
	@Id @GeneratedValue(strategy=IDENTITY)
	@Column(name="joQuoteHeaderID", unique=true, nullable=false)
	public Integer getJoQuoteHeaderId() {
		return this.joQuoteHeaderId;
	}
    
	public void setJoQuoteHeaderId(Integer joQuoteHeaderId) {
		this.joQuoteHeaderId = joQuoteHeaderId;
	}

	@Column(name="joMasterID")
	public Integer getJoMasterID() {
		return joMasterID;
	}
	public void setJoMasterID(Integer joMasterID) {
		this.joMasterID = joMasterID;
	}

	@Column(name="cuMasterTypeID")
	public Integer getCuMasterTypeID() {
		return cuMasterTypeID;
	}
	public void setCuMasterTypeID(Integer cuMasterTypeID) {
		this.cuMasterTypeID = cuMasterTypeID;
	}


	@Column(name="QuoteRev", length=3)
	public String getQuoteRev() {
		return this.quoteRev;
	}
    
	public void setQuoteRev(String quoteRev) {
		this.quoteRev = quoteRev;
	}
    
	@Column(name="QuoteAmount", scale=4)
	public BigDecimal getQuoteAmount() {
		return this.quoteAmount;
	}
    
	public void setQuoteAmount(BigDecimal quoteAmount) {
		this.quoteAmount = quoteAmount;
	}

	@Column(name="DiscountedPrice", scale=4)
	public BigDecimal getDiscountedPrice() {
		if (this.discountedPrice != null){
			return this.discountedPrice;
		} else {
			return new BigDecimal(0);
		}
	}

	public void setDiscountedPrice(BigDecimal discountedPrice) {
		this.discountedPrice = discountedPrice;
	}
   
    @Column(name="CreatedByID")
    public Integer getCreatedById() {
        return this.createdById;
    }
    
    public void setCreatedById(Integer createdById) {
        this.createdById = createdById;
    }

    
    @Column(name="CreatedByName", length=15)
    public String getCreatedByName() {
        return this.createdByName;
    }
    
    public void setCreatedByName(String createdByName) {
        this.createdByName = createdByName;
    }

    
    @Column(name="Remarks")
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    
    @Column(name="QuoteYesNo1")
    public Byte getQuoteYesNo1() {
        return this.quoteYesNo1;
    }
    
    public void setQuoteYesNo1(Byte quoteYesNo1) {
        this.quoteYesNo1 = quoteYesNo1;
    }

    
    @Column(name="Locked")
    public Byte getLocked() {
        return this.locked;
    }
    
    public void setLocked(Byte locked) {
        this.locked = locked;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateCreated", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    
    @Column(name="DisplayQuantity", nullable=false)
    public byte getDisplayQuantity() {
        return this.displayQuantity;
    }
    
    public void setDisplayQuantity(byte displayQuantity) {
        this.displayQuantity = displayQuantity;
    }

    
    @Column(name="DisplayParagraph", nullable=false)
    public byte getDisplayParagraph() {
        return this.displayParagraph;
    }
    
    public void setDisplayParagraph(byte displayParagraph) {
        this.displayParagraph = displayParagraph;
    }

    
    @Column(name="DisplayManufacturer", nullable=false)
    public byte getDisplayManufacturer() {
        return this.displayManufacturer;
    }
    
    public void setDisplayManufacturer(byte displayManufacturer) {
        this.displayManufacturer = displayManufacturer;
    }

    
    @Column(name="DisplayCost", nullable=false)
    public byte getDisplayCost() {
        return this.displayCost;
    }
    
    public void setDisplayCost(byte displayCost) {
        this.displayCost = displayCost;
    }

    
    @Column(name="DisplayPrice", nullable=false)
    public byte getDisplayPrice() {
        return this.displayPrice;
    }
    
    public void setDisplayPrice(byte displayPrice) {
        this.displayPrice = displayPrice;
    }

    
    @Column(name="PrintQuantity", nullable=false)
    public byte getPrintQuantity() {
        return this.printQuantity;
    }
    
    public void setPrintQuantity(byte printQuantity) {
        this.printQuantity = printQuantity;
    }

    
    @Column(name="PrintParagraph", nullable=false)
    public byte getPrintParagraph() {
        return this.printParagraph;
    }
    
    public void setPrintParagraph(byte printParagraph) {
        this.printParagraph = printParagraph;
    }

    
    @Column(name="PrintManufacturer", nullable=false)
    public byte getPrintManufacturer() {
        return this.printManufacturer;
    }
    
    public void setPrintManufacturer(byte printManufacturer) {
        this.printManufacturer = printManufacturer;
    }

    
    @Column(name="PrintCost", nullable=false)
    public byte getPrintCost() {
        return this.printCost;
    }
    
    public void setPrintCost(byte printCost) {
        this.printCost = printCost;
    }

    
    @Column(name="PrintPrice", nullable=false)
    public byte getPrintPrice() {
        return this.printPrice;
    }
    
    public void setPrintPrice(byte printPrice) {
        this.printPrice = printPrice;
    }

    
    @Column(name="NotesFullWidth", nullable=false)
    public byte getNotesFullWidth() {
        return this.notesFullWidth;
    }
    
    public void setNotesFullWidth(byte notesFullWidth) {
        this.notesFullWidth = notesFullWidth;
    }

    
    @Column(name="LineNumbers", nullable=false)
    public byte getLineNumbers() {
        return this.lineNumbers;
    }
    
    public void setLineNumbers(byte lineNumbers) {
        this.lineNumbers = lineNumbers;
    }

    
    @Column(name="PrintTotal", nullable=false)
    public byte getPrintTotal() {
        return this.printTotal;
    }
    
    public void setPrintTotal(byte printTotal) {
        this.printTotal = printTotal;
    }

    
    @Column(name="CostAmount", scale=4)
    public BigDecimal getCostAmount() {
        return this.costAmount;
    }
    
    public void setCostAmount(BigDecimal costAmount) {
        this.costAmount = costAmount;
    }

    
    @Column(name="DisplayMult", nullable=false)
    public byte getDisplayMult() {
        return this.displayMult;
    }
    
    public void setDisplayMult(byte displayMult) {
        this.displayMult = displayMult;
    }

    
    @Column(name="DisplaySpec", nullable=false)
    public byte getDisplaySpec() {
        return this.displaySpec;
    }
    
    public void setDisplaySpec(byte displaySpec) {
        this.displaySpec = displaySpec;
    }

    
    @Column(name="PrintMult", nullable=false)
    public byte getPrintMult() {
        return this.printMult;
    }
    
    public void setPrintMult(byte printMult) {
        this.printMult = printMult;
    }

    
    @Column(name="PrintSpec", nullable=false)
    public byte getPrintSpec() {
        return this.printSpec;
    }
    
    public void setPrintSpec(byte printSpec) {
        this.printSpec = printSpec;
    }

    
    @Column(name="HidePrice", nullable=false)
    public byte getHidePrice() {
        return this.hidePrice;
    }
    
    public void setHidePrice(byte hidePrice) {
        this.hidePrice = hidePrice;
    }

    
    @Column(name="InternalNote", length=100)
    public String getInternalNote() {
        return this.internalNote;
    }
    
    public void setInternalNote(String internalNote) {
        this.internalNote = internalNote;
    }

    
    @Column(name="PrimaryQuote", nullable=false)
    public byte getPrimaryQuote() {
        return this.primaryQuote;
    }
    
    public void setPrimaryQuote(byte primaryQuote) {
        this.primaryQuote = primaryQuote;
    }

    
    @Column(name="BookedQuote", nullable=false)
    public byte getBookedQuote() {
        return this.bookedQuote;
    }
    
    public void setBookedQuote(byte bookedQuote) {
        this.bookedQuote = bookedQuote;
    }

	@Transient
	public String getQuoteStatus() {
		return quoteStatus;
	}


	public void setQuoteStatus(String quoteStatus) {
		this.quoteStatus = quoteStatus;
	}

	@Transient
	public String getQuoteType() {
		return quoteType;
	}


	public void setQuoteType(String quoteType) {
		this.quoteType = quoteType;
	}

	@Transient
	public String getCompany() {
		return company;
	}


	public void setCompany(String company) {
		this.company = company;
	}

	@Transient
	public String getContact() {
		return contact;
	}


	public void setContact(String contact) {
		this.contact = contact;
	}

	@Transient
	public String getQuoteHistoryDate() {
		return quoteHistoryDate;
	}


	public void setQuoteHistoryDate(String quoteHistoryDate) {
		this.quoteHistoryDate = quoteHistoryDate;
	}

	@Transient
	public Integer getRxContactID() {
		return rxContactID;
	}


	public void setRxContactID(Integer rxContactID) {
		this.rxContactID = rxContactID;
	}

	@Transient
	public Integer getJoQuoteTemplateHeaderId() {
		return joQuoteTemplateHeaderId;
	}


	public void setJoQuoteTemplateHeaderId(Integer joQuoteTemplateHeaderId) {
		this.joQuoteTemplateHeaderId = joQuoteTemplateHeaderId;
	}

	@Column(name="neworoldquote")
	public Integer getNeworoldquote() {
		return neworoldquote;
	}


	public void setNeworoldquote(Integer neworoldquote) {
		this.neworoldquote = neworoldquote;
	}

	@Column(name="LSDStatus")
	public Short getIncludeLSD() {
		return includeLSD;
	}


	public void setIncludeLSD(Short includeLSD) {
		this.includeLSD = includeLSD;
	}

	@Column(name="DonotQty")
	public Short getDonotQtyitem2and3() {
		return donotQtyitem2and3;
	}


	public void setDonotQtyitem2and3(Short donotQtyitem2and3) {
		this.donotQtyitem2and3 = donotQtyitem2and3;
	}

	
	@Column(name="ShowTotOnly")
	public Short getShowTotPriceonly() {
		return showTotPriceonly;
	}


	public void setShowTotPriceonly(Short showTotPriceonly) {
		this.showTotPriceonly = showTotPriceonly;
	}


	@Column(name="LSDValue")
	public BigDecimal getLSDValue() {
		return LSDValue;
	}


	public void setLSDValue(BigDecimal lSDValue) {
		LSDValue = lSDValue;
	}


}