package com.turborep.turbotracker.job.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Joquotedetail generated by hbm2java
 */
@Entity
@Table(name = "joQuoteDetail", catalog = "")
public class JoQuoteDetail implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer joQuoteDetailId;
	private Integer joQuoteHeaderID; 
	private String product;
	private String productNote;
	private String itemQuantity;
	private String paragraph;
	private Integer rxManufacturerID;
	private BigDecimal price;
	private String inlineNote;
	private BigDecimal cost;
	private byte subtotal;
	private Short veFactoryId;
	private BigDecimal mult;
	private Short spec;
	private byte fmtBold;
	private byte fmtUnderline;
	private byte fmtItalic;
	private byte fmtLarge;
	private Integer detailSequenceId;
	private String pricingNote;
	private double position;
	private BigDecimal percentage;

	public JoQuoteDetail() {
	}

	
	public JoQuoteDetail(byte subtotal, byte fmtBold, byte fmtUnderline, byte fmtItalic, byte fmtLarge) {
		this.subtotal = subtotal;
		this.fmtBold = fmtBold;
		this.fmtUnderline = fmtUnderline;
		this.fmtItalic = fmtItalic;
		this.fmtLarge = fmtLarge;
	}
	public JoQuoteDetail(String product, String productNote, String itemQuantity, String paragraph, BigDecimal price, String inlineNote, BigDecimal cost, byte subtotal, Short veFactoryId, BigDecimal mult, Short spec, byte fmtBold, byte fmtUnderline, byte fmtItalic, byte fmtLarge, Integer detailSequenceId, String pricingNote) {
      this.product = product;
      this.productNote = productNote;
      this.itemQuantity = itemQuantity;
      this.paragraph = paragraph;
      this.price = price;
      this.inlineNote = inlineNote;
      this.cost = cost;
      this.subtotal = subtotal;
      this.veFactoryId = veFactoryId;
      this.mult = mult;
      this.spec = spec;
      this.fmtBold = fmtBold;
      this.fmtUnderline = fmtUnderline;
      this.fmtItalic = fmtItalic;
      this.fmtLarge = fmtLarge;
      this.detailSequenceId = detailSequenceId;
      this.pricingNote = pricingNote;
	}
  
	@Id @GeneratedValue(strategy=IDENTITY)
	@Column(name="joQuoteDetailID", unique=true, nullable=false)
	public Integer getJoQuoteDetailId() {
		return this.joQuoteDetailId;
	}
   
	public void setJoQuoteDetailId(Integer joQuoteDetailId) {
	    this.joQuoteDetailId = joQuoteDetailId;
	}
	
	@Column(name="joQuoteHeaderID")
	public Integer getJoQuoteHeaderID() {
	   return joQuoteHeaderID;
	}
	
	
	public void setJoQuoteHeaderID(Integer joQuoteHeaderID) {
	this.joQuoteHeaderID = joQuoteHeaderID;
	}
	
	
	@Column(name="Product")
	public String getProduct() {
	    return this.product;
	}
	
	public void setProduct(String product) {
	    this.product = product;
	}
	
	
	@Column(name="ProductNote")
	public String getProductNote() {
	    return this.productNote;
	}
	
	public void setProductNote(String productNote) {
	    this.productNote = productNote;
	}
	
	
	@Column(name="ItemQuantity", length=8)
	public String getItemQuantity() {
	    return this.itemQuantity;
	}
	
	public void setItemQuantity(String itemQuantity) {
	    this.itemQuantity = itemQuantity;
	}
	
	
	@Column(name="Paragraph", length=50)
	public String getParagraph() {
	    return this.paragraph;
	}
	
	public void setParagraph(String paragraph) {
	    this.paragraph = paragraph;
	}
	
	@Column(name="rxManufacturerID")
	public Integer getRxManufacturerID() {
	return rxManufacturerID;
	}
	
	
	public void setRxManufacturerID(Integer rxManufacturerID) {
		this.rxManufacturerID = rxManufacturerID;
	}
	
	
	@Column(name="Price", scale=4)
	public BigDecimal getPrice() {
	    return this.price;
	}
	
	public void setPrice(BigDecimal price) {
	    this.price = price;
	}
	
	
	@Column(name="InlineNote")
	public String getInlineNote() {
	    return this.inlineNote;
	}
	
	public void setInlineNote(String inlineNote) {
	    this.inlineNote = inlineNote;
	}
	
	
	@Column(name="Cost", scale=4)
	public BigDecimal getCost() {
	    return this.cost;
	}
	
	public void setCost(BigDecimal cost) {
	    this.cost = cost;
	}
	
	
	@Column(name="Subtotal", nullable=false)
	public byte getSubtotal() {
	    return this.subtotal;
	}
	
	public void setSubtotal(byte subtotal) {
	    this.subtotal = subtotal;
	}
	
	
	@Column(name="veFactoryID")
	public Short getVeFactoryId() {
	    return this.veFactoryId;
	}
	
	public void setVeFactoryId(Short veFactoryId) {
	    this.veFactoryId = veFactoryId;
	}
	
	
	@Column(name="Mult", scale=4)
	public BigDecimal getMult() {
	    return this.mult;
	}
	
	public void setMult(BigDecimal mult) {
	    this.mult = mult;
	}
	
	
	@Column(name="Spec")
	public Short getSpec() {
	    return this.spec;
	}
	
	public void setSpec(Short spec) {
	    this.spec = spec;
	}
	
	
	@Column(name="FmtBold", nullable=false)
	public byte getFmtBold() {
	    return this.fmtBold;
	}
	
	public void setFmtBold(byte fmtBold) {
	    this.fmtBold = fmtBold;
	}
	
	
	@Column(name="FmtUnderline", nullable=false)
	public byte getFmtUnderline() {
	    return this.fmtUnderline;
	}
	
	public void setFmtUnderline(byte fmtUnderline) {
	    this.fmtUnderline = fmtUnderline;
	}
	
	
	@Column(name="FmtItalic", nullable=false)
	public byte getFmtItalic() {
	    return this.fmtItalic;
	}
	
	public void setFmtItalic(byte fmtItalic) {
	    this.fmtItalic = fmtItalic;
	}
	
	
	@Column(name="FmtLarge", nullable=false)
	public byte getFmtLarge() {
	    return this.fmtLarge;
	}
	
	public void setFmtLarge(byte fmtLarge) {
	    this.fmtLarge = fmtLarge;
	}
	
	
	@Column(name="DetailSequenceID")
	public Integer getDetailSequenceId() {
	    return this.detailSequenceId;
	}
	
	public void setDetailSequenceId(Integer detailSequenceId) {
	    this.detailSequenceId = detailSequenceId;
	}
	
	
	@Column(name="PricingNote")
	public String getPricingNote() {
	    return this.pricingNote;
	}
	
	public void setPricingNote(String pricingNote) {
	    this.pricingNote = pricingNote;
	}

	@Column(name="position")
	public double getPosition() {
		return position;
	}


	public void setPosition(double position) {
		this.position = position;
	}

	@Column(name="Percentage")
	public BigDecimal getPercentage() {
		return percentage;
	}


	public void setPercentage(BigDecimal percentage) {
		this.percentage = percentage;
	}

}