/**
 * Copyright (c) 2013 A & E Specialties, Inc.  All rights reserved.
 * This software is the confidential and proprietary information of A & E Specialties, Inc.
 * You shall not disclose such Confidential Information and shall use it only in
 * accordance with the terms of the license agreement you entered into with A & E Specialties, Inc.
 * 
 * @author vish_pepala
 */
package com.turborep.turbotracker.job.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Joquotetemplateheader generated by hbm2java
 */
@Entity
@Table(name = "joQuoteTemplateHeader", catalog = "")
public class JoQuotetemplateHeader implements java.io.Serializable {

	private Integer joQuoteTemplateHeaderId;
	private Integer ownerId;
	private String templateName;
	private Integer cuMasterTypeId;
	private String quoteRev;
	private String remarks;
	private BigDecimal quoteAmount;
	private Boolean quoteYesNo1;
	private boolean displayQuantity;
	private boolean displayParagraph;
	private boolean displayManufacturer;
	private boolean displayCost;
	private boolean displayPrice;
	private boolean printQuantity;
	private boolean printParagraph;
	private boolean printManufacturer;
	private boolean printCost;
	private boolean printPrice;
	private boolean notesFullWidth;
	private boolean lineNumbers;
	private boolean globalTemplate;
	private BigDecimal costAmount;
	
	private BigDecimal discountedPrice;
	private Integer createdById;
	private String createdByName;
	private Byte locked;
	private Date dateCreated;
	private byte printTotal;
	private byte displayMult;
	private byte displaySpec;
	private byte printMult;
	private byte printSpec;
	private byte hidePrice;
	private String internalNote;
	private byte primaryQuote;
	private byte bookedQuote;
	private String quoteStatus;
	private String quoteType;
	private String company;
	private String contact;
	private String quoteHistoryDate;
	private Integer rxContactID;
	private Integer neworoldquote=1;

	public JoQuotetemplateHeader() {
	}

	public JoQuotetemplateHeader(boolean displayQuantity,
			boolean displayParagraph, boolean displayManufacturer,
			boolean displayCost, boolean displayPrice, boolean printQuantity,
			boolean printParagraph, boolean printManufacturer,
			boolean printCost, boolean printPrice, boolean notesFullWidth,
			boolean lineNumbers, boolean globalTemplate) {
		this.displayQuantity = displayQuantity;
		this.displayParagraph = displayParagraph;
		this.displayManufacturer = displayManufacturer;
		this.displayCost = displayCost;
		this.displayPrice = displayPrice;
		this.printQuantity = printQuantity;
		this.printParagraph = printParagraph;
		this.printManufacturer = printManufacturer;
		this.printCost = printCost;
		this.printPrice = printPrice;
		this.notesFullWidth = notesFullWidth;
		this.lineNumbers = lineNumbers;
		this.globalTemplate = globalTemplate;
	}

	public JoQuotetemplateHeader(Integer ownerId, String templateName,
			Integer cuMasterTypeId, String quoteRev, String remarks,
			BigDecimal quoteAmount, Boolean quoteYesNo1,
			boolean displayQuantity, boolean displayParagraph,
			boolean displayManufacturer, boolean displayCost,
			boolean displayPrice, boolean printQuantity,
			boolean printParagraph, boolean printManufacturer,
			boolean printCost, boolean printPrice, boolean notesFullWidth,
			boolean lineNumbers, boolean globalTemplate) {
		this.ownerId = ownerId;
		this.templateName = templateName;
		this.cuMasterTypeId = cuMasterTypeId;
		this.quoteRev = quoteRev;
		this.remarks = remarks;
		this.quoteAmount = quoteAmount;
		this.quoteYesNo1 = quoteYesNo1;
		this.displayQuantity = displayQuantity;
		this.displayParagraph = displayParagraph;
		this.displayManufacturer = displayManufacturer;
		this.displayCost = displayCost;
		this.displayPrice = displayPrice;
		this.printQuantity = printQuantity;
		this.printParagraph = printParagraph;
		this.printManufacturer = printManufacturer;
		this.printCost = printCost;
		this.printPrice = printPrice;
		this.notesFullWidth = notesFullWidth;
		this.lineNumbers = lineNumbers;
		this.globalTemplate = globalTemplate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "joQuoteTemplateHeaderID", unique = true, nullable = false)
	public Integer getJoQuoteTemplateHeaderId() {
		return this.joQuoteTemplateHeaderId;
	}

	public void setJoQuoteTemplateHeaderId(Integer joQuoteTemplateHeaderId) {
		this.joQuoteTemplateHeaderId = joQuoteTemplateHeaderId;
	}

	@Column(name = "OwnerID")
	public Integer getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	@Column(name = "TemplateName", length = 50)
	public String getTemplateName() {
		return this.templateName;
	}

	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	@Column(name = "cuMasterTypeID")
	public Integer getCuMasterTypeId() {
		return this.cuMasterTypeId;
	}

	public void setCuMasterTypeId(Integer cuMasterTypeId) {
		this.cuMasterTypeId = cuMasterTypeId;
	}

	@Column(name = "QuoteRev", length = 3)
	public String getQuoteRev() {
		return this.quoteRev;
	}

	public void setQuoteRev(String quoteRev) {
		this.quoteRev = quoteRev;
	}

	@Column(name = "Remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "QuoteAmount", scale = 4)
	public BigDecimal getQuoteAmount() {
		return this.quoteAmount;
	}

	public void setQuoteAmount(BigDecimal quoteAmount) {
		this.quoteAmount = quoteAmount;
	}

	@Column(name = "QuoteYesNo1")
	public Boolean getQuoteYesNo1() {
		return this.quoteYesNo1;
	}

	public void setQuoteYesNo1(Boolean quoteYesNo1) {
		this.quoteYesNo1 = quoteYesNo1;
	}

	@Column(name = "DisplayQuantity", nullable = false)
	public boolean isDisplayQuantity() {
		return this.displayQuantity;
	}

	public void setDisplayQuantity(boolean displayQuantity) {
		this.displayQuantity = displayQuantity;
	}

	@Column(name = "DisplayParagraph", nullable = false)
	public boolean isDisplayParagraph() {
		return this.displayParagraph;
	}

	public void setDisplayParagraph(boolean displayParagraph) {
		this.displayParagraph = displayParagraph;
	}

	@Column(name = "DisplayManufacturer", nullable = false)
	public boolean isDisplayManufacturer() {
		return this.displayManufacturer;
	}

	public void setDisplayManufacturer(boolean displayManufacturer) {
		this.displayManufacturer = displayManufacturer;
	}

	@Column(name = "DisplayCost", nullable = false)
	public boolean isDisplayCost() {
		return this.displayCost;
	}

	public void setDisplayCost(boolean displayCost) {
		this.displayCost = displayCost;
	}

	@Column(name = "DisplayPrice", nullable = false)
	public boolean isDisplayPrice() {
		return this.displayPrice;
	}

	public void setDisplayPrice(boolean displayPrice) {
		this.displayPrice = displayPrice;
	}

	@Column(name = "PrintQuantity", nullable = false)
	public boolean isPrintQuantity() {
		return this.printQuantity;
	}

	public void setPrintQuantity(boolean printQuantity) {
		this.printQuantity = printQuantity;
	}

	@Column(name = "PrintParagraph", nullable = false)
	public boolean isPrintParagraph() {
		return this.printParagraph;
	}

	public void setPrintParagraph(boolean printParagraph) {
		this.printParagraph = printParagraph;
	}

	@Column(name = "PrintManufacturer", nullable = false)
	public boolean isPrintManufacturer() {
		return this.printManufacturer;
	}

	public void setPrintManufacturer(boolean printManufacturer) {
		this.printManufacturer = printManufacturer;
	}

	@Column(name = "PrintCost", nullable = false)
	public boolean isPrintCost() {
		return this.printCost;
	}

	public void setPrintCost(boolean printCost) {
		this.printCost = printCost;
	}

	@Column(name = "PrintPrice", nullable = false)
	public boolean isPrintPrice() {
		return this.printPrice;
	}

	public void setPrintPrice(boolean printPrice) {
		this.printPrice = printPrice;
	}

	@Column(name = "NotesFullWidth", nullable = false)
	public boolean isNotesFullWidth() {
		return this.notesFullWidth;
	}

	public void setNotesFullWidth(boolean notesFullWidth) {
		this.notesFullWidth = notesFullWidth;
	}

	@Column(name = "LineNumbers", nullable = false)
	public boolean isLineNumbers() {
		return this.lineNumbers;
	}

	public void setLineNumbers(boolean lineNumbers) {
		this.lineNumbers = lineNumbers;
	}

	@Column(name = "GlobalTemplate", nullable = false)
	public boolean isGlobalTemplate() {
		return this.globalTemplate;
	}

	public void setGlobalTemplate(boolean globalTemplate) {
		this.globalTemplate = globalTemplate;
	}

	@Column(name = "CostAmount", nullable = true)
	public BigDecimal getCostAmount() {
		return costAmount;
	}

	public void setCostAmount(BigDecimal costAmount) {
		this.costAmount = costAmount;
	}

	@Column(name = "DiscountedPrice")
	public BigDecimal getDiscountedPrice() {
		return discountedPrice;
	}

	public void setDiscountedPrice(BigDecimal discountedPrice) {
		this.discountedPrice = discountedPrice;
	}

	@Column(name = "CreatedByID")
	public Integer getCreatedById() {
		return createdById;
	}

	public void setCreatedById(Integer createdById) {
		this.createdById = createdById;
	}

	@Transient
	public String getCreatedByName() {
		return createdByName;
	}

	public void setCreatedByName(String createdByName) {
		this.createdByName = createdByName;
	}

	@Transient
	public Byte getLocked() {
		return locked;
	}

	public void setLocked(Byte locked) {
		this.locked = locked;
	}

	@Transient
	public Date getDateCreated() {
		return dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "PrintTotal")
	public byte getPrintTotal() {
		return printTotal;
	}

	public void setPrintTotal(byte printTotal) {
		this.printTotal = printTotal;
	}

	@Transient
	public byte getDisplayMult() {
		return displayMult;
	}

	public void setDisplayMult(byte displayMult) {
		this.displayMult = displayMult;
	}

	@Transient
	public byte getDisplaySpec() {
		return displaySpec;
	}

	public void setDisplaySpec(byte displaySpec) {
		this.displaySpec = displaySpec;
	}

	@Transient
	public byte getPrintMult() {
		return printMult;
	}

	public void setPrintMult(byte printMult) {
		this.printMult = printMult;
	}

	@Transient
	public byte getPrintSpec() {
		return printSpec;
	}

	public void setPrintSpec(byte printSpec) {
		this.printSpec = printSpec;
	}

	@Transient
	public byte getHidePrice() {
		return hidePrice;
	}

	public void setHidePrice(byte hidePrice) {
		this.hidePrice = hidePrice;
	}

	@Transient
	public String getInternalNote() {
		return internalNote;
	}

	public void setInternalNote(String internalNote) {
		this.internalNote = internalNote;
	}

	@Transient
	public byte getPrimaryQuote() {
		return primaryQuote;
	}

	public void setPrimaryQuote(byte primaryQuote) {
		this.primaryQuote = primaryQuote;
	}

	@Transient
	public byte getBookedQuote() {
		return bookedQuote;
	}

	public void setBookedQuote(byte bookedQuote) {
		this.bookedQuote = bookedQuote;
	}

	@Transient
	public String getQuoteStatus() {
		return quoteStatus;
	}

	public void setQuoteStatus(String quoteStatus) {
		this.quoteStatus = quoteStatus;
	}

	@Transient
	public String getQuoteType() {
		return quoteType;
	}

	public void setQuoteType(String quoteType) {
		this.quoteType = quoteType;
	}

	@Transient
	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Transient
	public String getContact() {
		return contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Transient
	public String getQuoteHistoryDate() {
		return quoteHistoryDate;
	}

	public void setQuoteHistoryDate(String quoteHistoryDate) {
		this.quoteHistoryDate = quoteHistoryDate;
	}

	@Transient
	public Integer getRxContactID() {
		return rxContactID;
	}

	public void setRxContactID(Integer rxContactID) {
		this.rxContactID = rxContactID;
	}
	
	@Column(name="neworoldquote")
	public Integer getNeworoldquote() {
		return neworoldquote;
	}

	public void setNeworoldquote(Integer neworoldquote) {
		this.neworoldquote = neworoldquote;
	}

}
