package com.turborep.turbotracker.job.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Joreleasedetail generated by hbm2java
 */
@Entity
@Table(name = "joReleaseDetail", catalog = "")
public class JoReleaseDetail implements java.io.Serializable {

	private Integer itsJoReleaseDetailID;
	private Integer itsJoReleaseID;
	private Integer itsJoMasterId;
	private Date itsShipDate;
	private Date itsVendorInvoiceDate;
	private BigDecimal itsVendorInvoiceAmount;
	private Date itsCustomerInvoiceDate;
	private BigDecimal itsCustomerInvoiceAmount;
	private BigDecimal itsCustomerInvoiceCost;
	private BigDecimal itsBalanceDue;
	private Date itsPaymentDate;

	public JoReleaseDetail() {
	}

	public JoReleaseDetail(Integer joReleaseId, Integer joMasterId,
			Date shipDate, Date vendorInvoiceDate,
			BigDecimal vendorInvoiceAmount, Date customerInvoiceDate,
			BigDecimal customerInvoiceAmount, BigDecimal customerInvoiceCost,
			BigDecimal balanceDue, Date paymentDate) {
		this.itsJoReleaseID = joReleaseId;
		this.itsJoMasterId = joMasterId;
		this.itsShipDate = shipDate;
		this.itsVendorInvoiceDate = vendorInvoiceDate;
		this.itsVendorInvoiceAmount = vendorInvoiceAmount;
		this.itsCustomerInvoiceDate = customerInvoiceDate;
		this.itsCustomerInvoiceAmount = customerInvoiceAmount;
		this.itsCustomerInvoiceCost = customerInvoiceCost;
		this.itsBalanceDue = balanceDue;
		this.itsPaymentDate = paymentDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "joReleaseDetailID", unique = true, nullable = false)
	public Integer getJoReleaseDetailId() {
		return this.itsJoReleaseDetailID;
	}

	public void setJoReleaseDetailId(Integer joReleaseDetailId) {
		this.itsJoReleaseDetailID = joReleaseDetailId;
	}

	@Column(name = "joReleaseID")
	public Integer getJoReleaseId() {
		return this.itsJoReleaseID;
	}

	public void setJoReleaseId(Integer joReleaseId) {
		this.itsJoReleaseID = joReleaseId;
	}

	@Column(name = "joMasterID")
	public Integer getJoMasterId() {
		return this.itsJoMasterId;
	}

	public void setJoMasterId(Integer joMasterId) {
		this.itsJoMasterId = joMasterId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ShipDate", length = 0)
	public Date getShipDate() {
		return this.itsShipDate;
	}

	public void setShipDate(Date shipDate) {
		this.itsShipDate = shipDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VendorInvoiceDate", length = 0)
	public Date getVendorInvoiceDate() {
		return this.itsVendorInvoiceDate;
	}

	public void setVendorInvoiceDate(Date vendorInvoiceDate) {
		this.itsVendorInvoiceDate = vendorInvoiceDate;
	}

	@Column(name = "VendorInvoiceAmount", scale = 4)
	public BigDecimal getVendorInvoiceAmount() {
		return this.itsVendorInvoiceAmount;
	}

	public void setVendorInvoiceAmount(BigDecimal vendorInvoiceAmount) {
		this.itsVendorInvoiceAmount = vendorInvoiceAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CustomerInvoiceDate", length = 0)
	public Date getCustomerInvoiceDate() {
		return this.itsCustomerInvoiceDate;
	}

	public void setCustomerInvoiceDate(Date customerInvoiceDate) {
		this.itsCustomerInvoiceDate = customerInvoiceDate;
	}

	@Column(name = "CustomerInvoiceAmount", scale = 4)
	public BigDecimal getCustomerInvoiceAmount() {
		return this.itsCustomerInvoiceAmount;
	}

	public void setCustomerInvoiceAmount(BigDecimal customerInvoiceAmount) {
		this.itsCustomerInvoiceAmount = customerInvoiceAmount;
	}

	@Column(name = "CustomerInvoiceCost", scale = 4)
	public BigDecimal getCustomerInvoiceCost() {
		return this.itsCustomerInvoiceCost;
	}

	public void setCustomerInvoiceCost(BigDecimal customerInvoiceCost) {
		this.itsCustomerInvoiceCost = customerInvoiceCost;
	}

	@Column(name = "BalanceDue", scale = 4)
	public BigDecimal getBalanceDue() {
		return this.itsBalanceDue;
	}

	public void setBalanceDue(BigDecimal balanceDue) {
		this.itsBalanceDue = balanceDue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PaymentDate", length = 0)
	public Date getPaymentDate() {
		return this.itsPaymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.itsPaymentDate = paymentDate;
	}

}
