package com.turborep.turbotracker.job.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Jorelease generated by hbm2java
 */
@Entity
@Table(name = "joRelease", catalog = "")
public class JoRelease implements java.io.Serializable {

	private Integer itsJoReleaseID;
	private Integer itsJoMasterID;
	private Integer itsReleaseType;
	private Date itsReleaseDate;
	private BigDecimal itsEstimatedBilling;
	private String itsReleaseNote;
	private Boolean itsCommissionReceived;
	private Date itsCommissionDate;
	private BigDecimal itsCommissionAmount;
	private Boolean itsCancelled;
	private String POID;
	private String itsBillNote;
	private Integer seq_Number=0;
	private Integer release_status=0;

	public JoRelease() {
		this.itsCancelled = false;
		this.itsCommissionReceived=false;
	}

	public JoRelease(Integer joMasterId, Integer releaseType, Date releaseDate,
			BigDecimal estimatedBilling, String releaseNote,
			Boolean commissionReceived, Date commissionDate,
			BigDecimal commissionAmount, Boolean cancelled, String poid,
			String billNote) {
		this.itsJoMasterID = joMasterId;
		this.itsReleaseType = releaseType;
		this.itsReleaseDate = releaseDate;
		this.itsEstimatedBilling = estimatedBilling;
		this.itsReleaseNote = releaseNote;
		this.itsCommissionReceived = commissionReceived;
		this.itsCommissionDate = commissionDate;
		this.itsCommissionAmount = commissionAmount;
		this.itsCancelled = cancelled;
		this.POID = poid;
		this.itsBillNote = billNote;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "joReleaseID", unique = true, nullable = false)
	public Integer getJoReleaseId() {
		return this.itsJoReleaseID;
	}

	public void setJoReleaseId(Integer joReleaseId) {
		this.itsJoReleaseID = joReleaseId;
	}

	@Column(name = "joMasterID")
	public Integer getJoMasterId() {
		return this.itsJoMasterID;
	}

	public void setJoMasterId(Integer joMasterId) {
		this.itsJoMasterID = joMasterId;
	}

	@Column(name = "ReleaseType")
	public Integer getReleaseType() {
		return this.itsReleaseType;
	}

	public void setReleaseType(Integer releaseType) {
		this.itsReleaseType = releaseType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ReleaseDate", length = 0)
	public Date getReleaseDate() {
		return this.itsReleaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.itsReleaseDate = releaseDate;
	}

	@Column(name = "EstimatedBilling", scale = 4)
	public BigDecimal getEstimatedBilling() {
		return this.itsEstimatedBilling;
	}

	public void setEstimatedBilling(BigDecimal estimatedBilling) {
		this.itsEstimatedBilling = estimatedBilling;
	}

	@Column(name = "ReleaseNote", length = 50)
	public String getReleaseNote() {
		return this.itsReleaseNote;
	}

	public void setReleaseNote(String releaseNote) {
		this.itsReleaseNote = releaseNote;
	}

	@Column(name = "CommissionReceived")
	public Boolean getCommissionReceived() {
		return this.itsCommissionReceived;
	}

	public void setCommissionReceived(Boolean commissionReceived) {
		this.itsCommissionReceived = commissionReceived;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CommissionDate", length = 0)
	public Date getCommissionDate() {
		return this.itsCommissionDate;
	}

	public void setCommissionDate(Date commissionDate) {
		this.itsCommissionDate = commissionDate;
	}

	@Column(name = "CommissionAmount", scale = 4)
	public BigDecimal getCommissionAmount() {
		return this.itsCommissionAmount;
	}

	public void setCommissionAmount(BigDecimal commissionAmount) {
		this.itsCommissionAmount = commissionAmount;
	}

	@Column(name = "Cancelled")
	public Boolean getCancelled() {
		return this.itsCancelled;
	}

	public void setCancelled(Boolean cancelled) {
		this.itsCancelled = cancelled;
	}

	@Column(name = "POID")
	public String getPoid() {
		return this.POID;
	}

	public void setPoid(String poid) {
		this.POID = poid;
	}

	@Column(name = "BillNote")
	public String getBillNote() {
		return this.itsBillNote;
	}

	public void setBillNote(String billNote) {
		this.itsBillNote = billNote;
	}
	
	@Column(name = "seq_Number")
	public Integer getSeq_Number() {
		return seq_Number;
	}

	public void setSeq_Number(Integer seq_Number) {
		this.seq_Number = seq_Number;
	}
	@Column(name = "release_status")
	public Integer getRelease_status() {
		return release_status;
	}

	public void setRelease_status(Integer release_status) {
		this.release_status = release_status;
	}

}
