package com.turborep.turbotracker.job.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Joschedtempcolumn generated by hbm2java
 */
@Entity
@Table(name = "joSchedTempColumn", catalog = "")
public class Joschedtempcolumn implements java.io.Serializable {

	private Integer joSchedTempColumnId;
	private Integer joSchedTempHeaderId;
	private Integer columnNumber;
	private Integer joSchedTempColumnTypeId;
	private String displayText;
	private Integer displayWidth;
	private String printText;
	private Integer printWidth;
	private Boolean inactive;
	private Boolean copyDefaults;
	private Integer importToOrder;
	private String scheduleDescription;

	public Joschedtempcolumn() {
	}

	public Joschedtempcolumn(Integer joSchedTempHeaderId, Integer columnNumber,
			Integer joSchedTempColumnTypeId, String displayText,
			Integer displayWidth, String printText, Integer printWidth,
			Boolean inactive, Boolean copyDefaults, Integer importToOrder) {
		this.joSchedTempHeaderId = joSchedTempHeaderId;
		this.columnNumber = columnNumber;
		this.joSchedTempColumnTypeId = joSchedTempColumnTypeId;
		this.displayText = displayText;
		this.displayWidth = displayWidth;
		this.printText = printText;
		this.printWidth = printWidth;
		this.inactive = inactive;
		this.copyDefaults = copyDefaults;
		this.importToOrder = importToOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "joSchedTempColumnID", unique = true, nullable = false)
	public Integer getJoSchedTempColumnId() {
		return this.joSchedTempColumnId;
	}

	public void setJoSchedTempColumnId(Integer joSchedTempColumnId) {
		this.joSchedTempColumnId = joSchedTempColumnId;
	}

	@Column(name = "joSchedTempHeaderID")
	public Integer getJoSchedTempHeaderId() {
		return this.joSchedTempHeaderId;
	}

	public void setJoSchedTempHeaderId(Integer joSchedTempHeaderId) {
		this.joSchedTempHeaderId = joSchedTempHeaderId;
	}

	@Column(name = "ColumnNumber")
	public Integer getColumnNumber() {
		return this.columnNumber;
	}

	public void setColumnNumber(Integer columnNumber) {
		this.columnNumber = columnNumber;
	}

	@Column(name = "joSchedTempColumnTypeID")
	public Integer getJoSchedTempColumnTypeId() {
		return this.joSchedTempColumnTypeId;
	}

	public void setJoSchedTempColumnTypeId(Integer joSchedTempColumnTypeId) {
		this.joSchedTempColumnTypeId = joSchedTempColumnTypeId;
	}

	@Column(name = "DisplayText", length = 50)
	public String getDisplayText() {
		return this.displayText;
	}

	public void setDisplayText(String displayText) {
		this.displayText = displayText;
	}

	@Column(name = "DisplayWidth")
	public Integer getDisplayWidth() {
		return this.displayWidth;
	}

	public void setDisplayWidth(Integer displayWidth) {
		this.displayWidth = displayWidth;
	}

	@Column(name = "PrintText", length = 50)
	public String getPrintText() {
		return this.printText;
	}

	public void setPrintText(String printText) {
		this.printText = printText;
	}

	@Column(name = "PrintWidth")
	public Integer getPrintWidth() {
		return this.printWidth;
	}

	public void setPrintWidth(Integer printWidth) {
		this.printWidth = printWidth;
	}

	@Column(name = "Inactive")
	public Boolean getInactive() {
		return this.inactive;
	}

	public void setInactive(Boolean inactive) {
		this.inactive = inactive;
	}

	@Column(name = "CopyDefaults")
	public Boolean getCopyDefaults() {
		return this.copyDefaults;
	}

	public void setCopyDefaults(Boolean copyDefaults) {
		this.copyDefaults = copyDefaults;
	}

	@Column(name = "importToOrder", nullable = false)
	public Integer getImportToOrder() {
		return importToOrder;
	}

	public void setImportToOrder(Integer importToOrder) {
		this.importToOrder = importToOrder;
	}

	@Transient
	public String getScheduleDescription() {
		return scheduleDescription;
	}

	public void setScheduleDescription(String scheduleDescription) {
		this.scheduleDescription = scheduleDescription;
	}


}
