package com.turborep.turbotracker.job.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Joscheduledetail generated by hbm2java
 */
@Entity
@Table(name = "joScheduleDetail", catalog = "")
public class Joscheduledetail implements java.io.Serializable {

	private Integer joScheduleDetailId;
	private Integer joSubmittalDetailId;
	private Integer joLineNumber;
	private Integer joScheduleModelId;
	private BigDecimal quantity;
	private BigDecimal unitCost;
	private BigDecimal priceMultiplier;
	private String col01;
	private String col02;
	private String col03;
	private String col04;
	private String col05;
	private String col06;
	private String col07;
	private String col08;
	private String col09;
	private String col10;
	private String col11;
	private String col12;
	private String col13;
	private String col14;
	private String col15;
	private String col16;
	private String col17;
	private String col18;
	private String col19;
	private String col20;
	private String fnFactory;
	private String fnEngineer;
	private String fnAdvise;
	private BigDecimal qtyOrdered;
	private Integer status;
	private String tag;
	private String dimension;
	private Integer visibleLineNumber;

	public Joscheduledetail() {
	}

	public Joscheduledetail(Integer joSubmittalDetailId, Integer joLineNumber,
			Integer joScheduleModelId, BigDecimal quantity,
			BigDecimal unitCost, BigDecimal priceMultiplier, String col01,
			String col02, String col03, String col04, String col05,
			String col06, String col07, String col08, String col09,
			String col10, String col11, String col12, String col13,
			String col14, String col15, String col16, String col17,
			String col18, String col19, String col20, String fnFactory,
			String fnEngineer, String fnAdvise, BigDecimal qtyOrdered,
			Integer status, String tag, String dimension, Integer visibleLineNumber) {
		this.joSubmittalDetailId = joSubmittalDetailId;
		this.joLineNumber = joLineNumber;
		this.joScheduleModelId = joScheduleModelId;
		this.quantity = quantity;
		this.unitCost = unitCost;
		this.priceMultiplier = priceMultiplier;
		this.col01 = col01;
		this.col02 = col02;
		this.col03 = col03;
		this.col04 = col04;
		this.col05 = col05;
		this.col06 = col06;
		this.col07 = col07;
		this.col08 = col08;
		this.col09 = col09;
		this.col10 = col10;
		this.col11 = col11;
		this.col12 = col12;
		this.col13 = col13;
		this.col14 = col14;
		this.col15 = col15;
		this.col16 = col16;
		this.col17 = col17;
		this.col18 = col18;
		this.col19 = col19;
		this.col20 = col20;
		this.fnFactory = fnFactory;
		this.fnEngineer = fnEngineer;
		this.fnAdvise = fnAdvise;
		this.qtyOrdered = qtyOrdered;
		this.status = status;
		this.tag = tag;
		this.dimension = dimension;
		this.visibleLineNumber = visibleLineNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "joScheduleDetailID", unique = true, nullable = false)
	public Integer getJoScheduleDetailId() {
		return this.joScheduleDetailId;
	}

	public void setJoScheduleDetailId(Integer joScheduleDetailId) {
		this.joScheduleDetailId = joScheduleDetailId;
	}

	@Column(name = "joSubmittalDetailID")
	public Integer getJoSubmittalDetailId() {
		return this.joSubmittalDetailId;
	}

	public void setJoSubmittalDetailId(Integer joSubmittalDetailId) {
		this.joSubmittalDetailId = joSubmittalDetailId;
	}

	@Column(name = "joLineNumber")
	public Integer getJoLineNumber() {
		return this.joLineNumber;
	}

	public void setJoLineNumber(Integer joLineNumber) {
		this.joLineNumber = joLineNumber;
	}

	@Column(name = "joScheduleModelID")
	public Integer getJoScheduleModelId() {
		return this.joScheduleModelId;
	}

	public void setJoScheduleModelId(Integer joScheduleModelId) {
		this.joScheduleModelId = joScheduleModelId;
	}

	@Column(name = "Quantity", scale = 4)
	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	@Column(name = "UnitCost", scale = 4)
	public BigDecimal getUnitCost() {
		return this.unitCost;
	}

	public void setUnitCost(BigDecimal unitCost) {
		this.unitCost = unitCost;
	}

	@Column(name = "PriceMultiplier", scale = 4)
	public BigDecimal getPriceMultiplier() {
		return this.priceMultiplier;
	}

	public void setPriceMultiplier(BigDecimal priceMultiplier) {
		this.priceMultiplier = priceMultiplier;
	}

	@Column(name = "Col01")
	public String getCol01() {
		return this.col01;
	}

	public void setCol01(String col01) {
		this.col01 = col01;
	}

	@Column(name = "Col02")
	public String getCol02() {
		return this.col02;
	}

	public void setCol02(String col02) {
		this.col02 = col02;
	}

	@Column(name = "Col03")
	public String getCol03() {
		return this.col03;
	}

	public void setCol03(String col03) {
		this.col03 = col03;
	}

	@Column(name = "Col04")
	public String getCol04() {
		return this.col04;
	}

	public void setCol04(String col04) {
		this.col04 = col04;
	}

	@Column(name = "Col05")
	public String getCol05() {
		return this.col05;
	}

	public void setCol05(String col05) {
		this.col05 = col05;
	}

	@Column(name = "Col06")
	public String getCol06() {
		return this.col06;
	}

	public void setCol06(String col06) {
		this.col06 = col06;
	}

	@Column(name = "Col07")
	public String getCol07() {
		return this.col07;
	}

	public void setCol07(String col07) {
		this.col07 = col07;
	}

	@Column(name = "Col08")
	public String getCol08() {
		return this.col08;
	}

	public void setCol08(String col08) {
		this.col08 = col08;
	}

	@Column(name = "Col09")
	public String getCol09() {
		return this.col09;
	}

	public void setCol09(String col09) {
		this.col09 = col09;
	}

	@Column(name = "Col10")
	public String getCol10() {
		return this.col10;
	}

	public void setCol10(String col10) {
		this.col10 = col10;
	}

	@Column(name = "Col11")
	public String getCol11() {
		return this.col11;
	}

	public void setCol11(String col11) {
		this.col11 = col11;
	}

	@Column(name = "Col12")
	public String getCol12() {
		return this.col12;
	}

	public void setCol12(String col12) {
		this.col12 = col12;
	}

	@Column(name = "Col13")
	public String getCol13() {
		return this.col13;
	}

	public void setCol13(String col13) {
		this.col13 = col13;
	}

	@Column(name = "Col14")
	public String getCol14() {
		return this.col14;
	}

	public void setCol14(String col14) {
		this.col14 = col14;
	}

	@Column(name = "Col15")
	public String getCol15() {
		return this.col15;
	}

	public void setCol15(String col15) {
		this.col15 = col15;
	}

	@Column(name = "Col16")
	public String getCol16() {
		return this.col16;
	}

	public void setCol16(String col16) {
		this.col16 = col16;
	}

	@Column(name = "Col17")
	public String getCol17() {
		return this.col17;
	}

	public void setCol17(String col17) {
		this.col17 = col17;
	}

	@Column(name = "Col18")
	public String getCol18() {
		return this.col18;
	}

	public void setCol18(String col18) {
		this.col18 = col18;
	}

	@Column(name = "Col19")
	public String getCol19() {
		return this.col19;
	}

	public void setCol19(String col19) {
		this.col19 = col19;
	}

	@Column(name = "Col20")
	public String getCol20() {
		return this.col20;
	}

	public void setCol20(String col20) {
		this.col20 = col20;
	}

	@Column(name = "FN_Factory")
	public String getFnFactory() {
		return this.fnFactory;
	}

	public void setFnFactory(String fnFactory) {
		this.fnFactory = fnFactory;
	}

	@Column(name = "FN_Engineer")
	public String getFnEngineer() {
		return this.fnEngineer;
	}

	public void setFnEngineer(String fnEngineer) {
		this.fnEngineer = fnEngineer;
	}

	@Column(name = "FN_Advise")
	public String getFnAdvise() {
		return this.fnAdvise;
	}

	public void setFnAdvise(String fnAdvise) {
		this.fnAdvise = fnAdvise;
	}

	@Column(name = "QtyOrdered", scale = 4)
	public BigDecimal getQtyOrdered() {
		return this.qtyOrdered;
	}

	public void setQtyOrdered(BigDecimal qtyOrdered) {
		this.qtyOrdered = qtyOrdered;
	}

	@Column(name = "Status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "TAG", length = 50)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Column(name = "Dimension", length = 50)
	public String getDimension() {
		return dimension;
	}

	public void setDimension(String dimension) {
		this.dimension = dimension;
	}

	@Column(name = "VisibleLineNumber", length = 5)
	public Integer getVisibleLineNumber() {
		return visibleLineNumber;
	}

	public void setVisibleLineNumber(Integer visibleLineNumber) {
		this.visibleLineNumber = visibleLineNumber;
	}

}
