package com.turborep.turbotracker.job.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Quickjob generated by hbm2java
 */
@Entity
@Table(name = "quickjob", catalog = "")
public class Quickjob implements java.io.Serializable {

	private Integer quickJobId;
	private String jobNumber;
	private String description;
	private Integer rxMasterId;
	private Date bookDate;
	private BigDecimal priorCost;
	private BigDecimal priorRevenue;
	private BigDecimal contractAmount;
	private BigDecimal estimatedProfit;

	public Quickjob() {
	}

	public Quickjob(String jobNumber, String description, Integer rxMasterId,
			Date bookDate, BigDecimal priorCost, BigDecimal priorRevenue,
			BigDecimal contractAmount, BigDecimal estimatedProfit) {
		this.jobNumber = jobNumber;
		this.description = description;
		this.rxMasterId = rxMasterId;
		this.bookDate = bookDate;
		this.priorCost = priorCost;
		this.priorRevenue = priorRevenue;
		this.contractAmount = contractAmount;
		this.estimatedProfit = estimatedProfit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "QuickJobID", unique = true, nullable = false)
	public Integer getQuickJobId() {
		return this.quickJobId;
	}

	public void setQuickJobId(Integer quickJobId) {
		this.quickJobId = quickJobId;
	}

	@Column(name = "JobNumber", length = 10)
	public String getJobNumber() {
		return this.jobNumber;
	}

	public void setJobNumber(String jobNumber) {
		this.jobNumber = jobNumber;
	}

	@Column(name = "Description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "rxMasterID")
	public Integer getRxMasterId() {
		return this.rxMasterId;
	}

	public void setRxMasterId(Integer rxMasterId) {
		this.rxMasterId = rxMasterId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BookDate", length = 0)
	public Date getBookDate() {
		return this.bookDate;
	}

	public void setBookDate(Date bookDate) {
		this.bookDate = bookDate;
	}

	@Column(name = "PriorCost", scale = 4)
	public BigDecimal getPriorCost() {
		return this.priorCost;
	}

	public void setPriorCost(BigDecimal priorCost) {
		this.priorCost = priorCost;
	}

	@Column(name = "PriorRevenue", scale = 4)
	public BigDecimal getPriorRevenue() {
		return this.priorRevenue;
	}

	public void setPriorRevenue(BigDecimal priorRevenue) {
		this.priorRevenue = priorRevenue;
	}

	@Column(name = "ContractAmount", scale = 4)
	public BigDecimal getContractAmount() {
		return this.contractAmount;
	}

	public void setContractAmount(BigDecimal contractAmount) {
		this.contractAmount = contractAmount;
	}

	@Column(name = "EstimatedProfit", scale = 4)
	public BigDecimal getEstimatedProfit() {
		return this.estimatedProfit;
	}

	public void setEstimatedProfit(BigDecimal estimatedProfit) {
		this.estimatedProfit = estimatedProfit;
	}

}
