package com.turborep.turbotracker.employee.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ecinvoiceperiod generated by hbm2java
 */
@Entity
@Table(name = "ecInvoicePeriod", catalog = "")
public class Ecinvoiceperiod implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer ecInvoicePeriodId;
	private Integer cuInvoiceId;
	private Integer ecPeriodId;
	private Boolean modified;
	private Integer rxCustomerId;
	private Byte releaseType;
	private String reference;
	private Date datePaid;
	private BigDecimal sales;
	private BigDecimal profit;
	private Integer joReleaseID;
	private Integer expJoMasterID;
	private Integer expRxMasterID;
	private Date enteredDate;
	private String ecType;
	public Ecinvoiceperiod() {
	}

	public Ecinvoiceperiod(Integer cuInvoiceId, Integer ecPeriodId,
			Boolean modified, Integer rxCustomerId, Byte releaseType,
			String reference, Date datePaid, BigDecimal sales, BigDecimal profit) {
		this.cuInvoiceId = cuInvoiceId;
		this.ecPeriodId = ecPeriodId;
		this.modified = modified;
		this.rxCustomerId = rxCustomerId;
		this.releaseType = releaseType;
		this.reference = reference;
		this.datePaid = datePaid;
		this.sales = sales;
		this.profit = profit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ecInvoicePeriodID", unique = true, nullable = false)
	public Integer getEcInvoicePeriodId() {
		return this.ecInvoicePeriodId;
	}

	public void setEcInvoicePeriodId(Integer ecInvoicePeriodId) {
		this.ecInvoicePeriodId = ecInvoicePeriodId;
	}

	@Column(name = "cuInvoiceID")
	public Integer getCuInvoiceId() {
		return this.cuInvoiceId;
	}

	public void setCuInvoiceId(Integer cuInvoiceId) {
		this.cuInvoiceId = cuInvoiceId;
	}

	@Column(name = "ecPeriodID")
	public Integer getEcPeriodId() {
		return this.ecPeriodId;
	}

	public void setEcPeriodId(Integer ecPeriodId) {
		this.ecPeriodId = ecPeriodId;
	}

	@Column(name = "Modified")
	public Boolean getModified() {
		return this.modified;
	}

	public void setModified(Boolean modified) {
		this.modified = modified;
	}

	@Column(name = "rxCustomerID")
	public Integer getRxCustomerId() {
		return this.rxCustomerId;
	}

	public void setRxCustomerId(Integer rxCustomerId) {
		this.rxCustomerId = rxCustomerId;
	}

	@Column(name = "ReleaseType")
	public Byte getReleaseType() {
		return this.releaseType;
	}

	public void setReleaseType(Byte releaseType) {
		this.releaseType = releaseType;
	}

	@Column(name = "Reference", length = 30)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatePaid", length = 0)
	public Date getDatePaid() {
		return this.datePaid;
	}

	public void setDatePaid(Date datePaid) {
		this.datePaid = datePaid;
	}

	@Column(name = "Sales", scale = 4)
	public BigDecimal getSales() {
		return this.sales;
	}

	public void setSales(BigDecimal sales) {
		this.sales = sales;
	}

	@Column(name = "Profit", scale = 4)
	public BigDecimal getProfit() {
		return this.profit;
	}

	public void setProfit(BigDecimal profit) {
		this.profit = profit;
	}

	@Column(name = "joReleaseID")
	public Integer getJoReleaseID() {
		return joReleaseID;
	}

	public void setJoReleaseID(Integer joReleaseID) {
		this.joReleaseID = joReleaseID;
	}

	@Column(name = "ExpjoMasterID")
	public Integer getExpJoMasterID() {
		return expJoMasterID;
	}

	public void setExpJoMasterID(Integer expJoMasterID) {
		this.expJoMasterID = expJoMasterID;
	}

	@Column(name = "ExprxMasterID")
	public Integer getExpRxMasterID() {
		return expRxMasterID;
	}

	public void setExpRxMasterID(Integer expRxMasterID) {
		this.expRxMasterID = expRxMasterID;
	}

	@Column(name = "enteredDate")
	public Date getEnteredDate() {
		return enteredDate;
	}

	public void setEnteredDate(Date enteredDate) {
		this.enteredDate = enteredDate;
	}

	@Column(name = "ecType")
	public String getEcType() {
		return ecType;
	}

	public void setEcType(String ecType) {
		this.ecType = ecType;
	}

}
