package com.turborep.turbotracker.employee.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ecjobs generated by hbm2java
 */
@Entity
@Table(name = "ecJobs", catalog = "")
public class Ecjobs implements java.io.Serializable {

	private Integer ecJobsId;
	private Integer joMasterId;
	private Integer ecStatementId;
	private BigDecimal profitToDate;
	private BigDecimal profitPaidOnToDate;
	private BigDecimal commissionRate;
	private BigDecimal commissionToDate;
	private BigDecimal paidToDate;
	private BigDecimal amountDue;

	public Ecjobs() {
	}

	public Ecjobs(Integer joMasterId, Integer ecStatementId,
			BigDecimal profitToDate, BigDecimal profitPaidOnToDate,
			BigDecimal commissionRate, BigDecimal commissionToDate,
			BigDecimal paidToDate, BigDecimal amountDue) {
		this.joMasterId = joMasterId;
		this.ecStatementId = ecStatementId;
		this.profitToDate = profitToDate;
		this.profitPaidOnToDate = profitPaidOnToDate;
		this.commissionRate = commissionRate;
		this.commissionToDate = commissionToDate;
		this.paidToDate = paidToDate;
		this.amountDue = amountDue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ecJobsID", unique = true, nullable = false)
	public Integer getEcJobsId() {
		return this.ecJobsId;
	}

	public void setEcJobsId(Integer ecJobsId) {
		this.ecJobsId = ecJobsId;
	}

	@Column(name = "joMasterID")
	public Integer getJoMasterId() {
		return this.joMasterId;
	}

	public void setJoMasterId(Integer joMasterId) {
		this.joMasterId = joMasterId;
	}

	@Column(name = "ecStatementID")
	public Integer getEcStatementId() {
		return this.ecStatementId;
	}

	public void setEcStatementId(Integer ecStatementId) {
		this.ecStatementId = ecStatementId;
	}

	@Column(name = "ProfitToDate", scale = 4)
	public BigDecimal getProfitToDate() {
		return this.profitToDate;
	}

	public void setProfitToDate(BigDecimal profitToDate) {
		this.profitToDate = profitToDate;
	}

	@Column(name = "ProfitPaidOnToDate", scale = 4)
	public BigDecimal getProfitPaidOnToDate() {
		return this.profitPaidOnToDate;
	}

	public void setProfitPaidOnToDate(BigDecimal profitPaidOnToDate) {
		this.profitPaidOnToDate = profitPaidOnToDate;
	}

	@Column(name = "CommissionRate", scale = 4)
	public BigDecimal getCommissionRate() {
		return this.commissionRate;
	}

	public void setCommissionRate(BigDecimal commissionRate) {
		this.commissionRate = commissionRate;
	}

	@Column(name = "CommissionToDate", scale = 4)
	public BigDecimal getCommissionToDate() {
		return this.commissionToDate;
	}

	public void setCommissionToDate(BigDecimal commissionToDate) {
		this.commissionToDate = commissionToDate;
	}

	@Column(name = "PaidToDate", scale = 4)
	public BigDecimal getPaidToDate() {
		return this.paidToDate;
	}

	public void setPaidToDate(BigDecimal paidToDate) {
		this.paidToDate = paidToDate;
	}

	@Column(name = "AmountDue", scale = 4)
	public BigDecimal getAmountDue() {
		return this.amountDue;
	}

	public void setAmountDue(BigDecimal amountDue) {
		this.amountDue = amountDue;
	}

}
