package com.turborep.turbotracker.employee.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Ecperiod generated by hbm2java
 */
@Entity
@Table(name = "ecPeriod", catalog = "")
public class Ecperiod implements java.io.Serializable {

	private Integer ecPeriodId;
	private Date periodEndingDate;
    private String endDate;
    
	public Ecperiod() {
	}

	public Ecperiod(Date periodEndingDate) {
		this.periodEndingDate = periodEndingDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ecPeriodID", unique = true, nullable = false)
	public Integer getEcPeriodId() {
		return this.ecPeriodId;
	}

	public void setEcPeriodId(Integer ecPeriodId) {
		this.ecPeriodId = ecPeriodId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PeriodEndingDate", length = 0)
	public Date getPeriodEndingDate() {
		return this.periodEndingDate;
	}

	public void setPeriodEndingDate(Date periodEndingDate) {
		this.periodEndingDate = periodEndingDate;
	}

	@Transient
	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

}
