package com.turborep.turbotracker.employee.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ecsalesmgroverride generated by hbm2java
 */
@Entity
@Table(name = "ecSalesMgrOverride", catalog = "")
public class Ecsalesmgroverride implements java.io.Serializable {

	private Integer ecSalesMgrOverrideId;
	private Integer repLoginId;
	private Integer ecStatementId;
	private BigDecimal profit;
	private BigDecimal commissionRate;
	private BigDecimal amountDue;
	private BigDecimal jobProfit;
	public Ecsalesmgroverride() {
	}

	public Ecsalesmgroverride(Integer repLoginId, Integer ecStatementId,
			BigDecimal profit, BigDecimal commissionRate, BigDecimal amountDue) {
		this.repLoginId = repLoginId;
		this.ecStatementId = ecStatementId;
		this.profit = profit;
		this.commissionRate = commissionRate;
		this.amountDue = amountDue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ecSalesMgrOverrideID", unique = true, nullable = false)
	public Integer getEcSalesMgrOverrideId() {
		return this.ecSalesMgrOverrideId;
	}

	public void setEcSalesMgrOverrideId(Integer ecSalesMgrOverrideId) {
		this.ecSalesMgrOverrideId = ecSalesMgrOverrideId;
	}

	@Column(name = "RepLoginID")
	public Integer getRepLoginId() {
		return this.repLoginId;
	}

	public void setRepLoginId(Integer repLoginId) {
		this.repLoginId = repLoginId;
	}

	@Column(name = "ecStatementID")
	public Integer getEcStatementId() {
		return this.ecStatementId;
	}

	public void setEcStatementId(Integer ecStatementId) {
		this.ecStatementId = ecStatementId;
	}

	@Column(name = "Profit", scale = 4)
	public BigDecimal getProfit() {
		return this.profit;
	}

	public void setProfit(BigDecimal profit) {
		this.profit = profit;
	}

	@Column(name = "CommissionRate", scale = 4)
	public BigDecimal getCommissionRate() {
		return this.commissionRate;
	}

	public void setCommissionRate(BigDecimal commissionRate) {
		this.commissionRate = commissionRate;
	}

	@Column(name = "AmountDue", scale = 4)
	public BigDecimal getAmountDue() {
		return this.amountDue;
	}

	public void setAmountDue(BigDecimal amountDue) {
		this.amountDue = amountDue;
	}
	
	@Column(name = "JobProfit")
	public BigDecimal getJobProfit() {
		return jobProfit;
	}

	public void setJobProfit(BigDecimal jobProfit) {
		this.jobProfit = jobProfit;
	}

}
