package com.turborep.turbotracker.employee.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ecstatement generated by hbm2java
 */
@Entity
@Table(name = "ecStatement", catalog = "")
public class Ecstatement implements java.io.Serializable {

	private Integer ecStatementId;
	private Integer ecPeriodId;
	private Integer repLoginId;
	private BigDecimal openingBalance;
	private BigDecimal jobCommissions;
	private BigDecimal otherCommissions;
	private BigDecimal overrides;
	private BigDecimal adjustments;
	private BigDecimal payment;
	private BigDecimal repDeduct1;
	private BigDecimal repDeduct2;
	private BigDecimal repDeduct3;
	private BigDecimal repDeduct4;
	private String comment;
	private BigDecimal custom1;
	private BigDecimal custom2;
	private BigDecimal custom3;
	private BigDecimal custom4;
	private BigDecimal custom5;
	private BigDecimal custom6;
	private BigDecimal custom7;
	private BigDecimal custom8;
	private BigDecimal custom9;
	private BigDecimal custom10;
	private String flags;
	private BigDecimal profit;
	private String calculatedDate;
	private String repName;
	private Date ecStatementEnteredDate;
	public Ecstatement() {
	}

	public Ecstatement(Integer ecPeriodId, Integer repLoginId,
			BigDecimal openingBalance, BigDecimal jobCommissions,
			BigDecimal otherCommissions, BigDecimal overrides,
			BigDecimal adjustments, BigDecimal payment, BigDecimal repDeduct1,
			BigDecimal repDeduct2, BigDecimal repDeduct3,
			BigDecimal repDeduct4, String comment, BigDecimal custom1,
			BigDecimal custom2, BigDecimal custom3, BigDecimal custom4,
			BigDecimal custom5, BigDecimal custom6, BigDecimal custom7,
			BigDecimal custom8, BigDecimal custom9, BigDecimal custom10,
			String flags,BigDecimal profit) {
		this.ecPeriodId = ecPeriodId;
		this.repLoginId = repLoginId;
		this.openingBalance = openingBalance;
		this.jobCommissions = jobCommissions;
		this.otherCommissions = otherCommissions;
		this.overrides = overrides;
		this.adjustments = adjustments;
		this.payment = payment;
		this.repDeduct1 = repDeduct1;
		this.repDeduct2 = repDeduct2;
		this.repDeduct3 = repDeduct3;
		this.repDeduct4 = repDeduct4;
		this.comment = comment;
		this.custom1 = custom1;
		this.custom2 = custom2;
		this.custom3 = custom3;
		this.custom4 = custom4;
		this.custom5 = custom5;
		this.custom6 = custom6;
		this.custom7 = custom7;
		this.custom8 = custom8;
		this.custom9 = custom9;
		this.custom10 = custom10;
		this.flags = flags;
		this.profit = profit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ecStatementID", unique = true, nullable = false)
	public Integer getEcStatementId() {
		return this.ecStatementId;
	}

	public void setEcStatementId(Integer ecStatementId) {
		this.ecStatementId = ecStatementId;
	}

	@Column(name = "ecPeriodID")
	public Integer getEcPeriodId() {
		return this.ecPeriodId;
	}

	public void setEcPeriodId(Integer ecPeriodId) {
		this.ecPeriodId = ecPeriodId;
	}

	@Column(name = "RepLoginID")
	public Integer getRepLoginId() {
		return this.repLoginId;
	}

	public void setRepLoginId(Integer repLoginId) {
		this.repLoginId = repLoginId;
	}

	@Column(name = "OpeningBalance", scale = 4)
	public BigDecimal getOpeningBalance() {
		return this.openingBalance;
	}

	public void setOpeningBalance(BigDecimal openingBalance) {
		this.openingBalance = openingBalance;
	}

	@Column(name = "JobCommissions", scale = 4)
	public BigDecimal getJobCommissions() {
		return this.jobCommissions;
	}

	public void setJobCommissions(BigDecimal jobCommissions) {
		this.jobCommissions = jobCommissions;
	}

	@Column(name = "OtherCommissions", scale = 4)
	public BigDecimal getOtherCommissions() {
		return this.otherCommissions;
	}

	public void setOtherCommissions(BigDecimal otherCommissions) {
		this.otherCommissions = otherCommissions;
	}

	@Column(name = "Overrides", scale = 4)
	public BigDecimal getOverrides() {
		return this.overrides;
	}

	public void setOverrides(BigDecimal overrides) {
		this.overrides = overrides;
	}

	@Column(name = "Adjustments", scale = 4)
	public BigDecimal getAdjustments() {
		return this.adjustments;
	}

	public void setAdjustments(BigDecimal adjustments) {
		this.adjustments = adjustments;
	}

	@Column(name = "Payment", scale = 4)
	public BigDecimal getPayment() {
		return this.payment;
	}

	public void setPayment(BigDecimal payment) {
		this.payment = payment;
	}

	@Column(name = "RepDeduct1", scale = 4)
	public BigDecimal getRepDeduct1() {
		return this.repDeduct1;
	}

	public void setRepDeduct1(BigDecimal repDeduct1) {
		this.repDeduct1 = repDeduct1;
	}

	@Column(name = "RepDeduct2", scale = 4)
	public BigDecimal getRepDeduct2() {
		return this.repDeduct2;
	}

	public void setRepDeduct2(BigDecimal repDeduct2) {
		this.repDeduct2 = repDeduct2;
	}

	@Column(name = "RepDeduct3", scale = 4)
	public BigDecimal getRepDeduct3() {
		return this.repDeduct3;
	}

	public void setRepDeduct3(BigDecimal repDeduct3) {
		this.repDeduct3 = repDeduct3;
	}

	@Column(name = "RepDeduct4", scale = 4)
	public BigDecimal getRepDeduct4() {
		return this.repDeduct4;
	}

	public void setRepDeduct4(BigDecimal repDeduct4) {
		this.repDeduct4 = repDeduct4;
	}

	@Column(name = "Comment")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "Custom1", scale = 4)
	public BigDecimal getCustom1() {
		return this.custom1;
	}

	public void setCustom1(BigDecimal custom1) {
		this.custom1 = custom1;
	}

	@Column(name = "Custom2", scale = 4)
	public BigDecimal getCustom2() {
		return this.custom2;
	}

	public void setCustom2(BigDecimal custom2) {
		this.custom2 = custom2;
	}

	@Column(name = "Custom3", scale = 4)
	public BigDecimal getCustom3() {
		return this.custom3;
	}

	public void setCustom3(BigDecimal custom3) {
		this.custom3 = custom3;
	}

	@Column(name = "Custom4", scale = 4)
	public BigDecimal getCustom4() {
		return this.custom4;
	}

	public void setCustom4(BigDecimal custom4) {
		this.custom4 = custom4;
	}

	@Column(name = "Custom5", scale = 4)
	public BigDecimal getCustom5() {
		return this.custom5;
	}

	public void setCustom5(BigDecimal custom5) {
		this.custom5 = custom5;
	}

	@Column(name = "Custom6", scale = 4)
	public BigDecimal getCustom6() {
		return this.custom6;
	}

	public void setCustom6(BigDecimal custom6) {
		this.custom6 = custom6;
	}

	@Column(name = "Custom7", scale = 4)
	public BigDecimal getCustom7() {
		return this.custom7;
	}

	public void setCustom7(BigDecimal custom7) {
		this.custom7 = custom7;
	}

	@Column(name = "Custom8", scale = 4)
	public BigDecimal getCustom8() {
		return this.custom8;
	}

	public void setCustom8(BigDecimal custom8) {
		this.custom8 = custom8;
	}

	@Column(name = "Custom9", scale = 4)
	public BigDecimal getCustom9() {
		return this.custom9;
	}

	public void setCustom9(BigDecimal custom9) {
		this.custom9 = custom9;
	}

	@Column(name = "Custom10", scale = 4)
	public BigDecimal getCustom10() {
		return this.custom10;
	}

	public void setCustom10(BigDecimal custom10) {
		this.custom10 = custom10;
	}

	@Column(name = "Flags", length = 20)
	public String getFlags() {
		return this.flags;
	}

	public void setFlags(String flags) {
		this.flags = flags;
	}

	@Column(name = "Profit")
	public BigDecimal getProfit() {
		return profit;
	}

	public void setProfit(BigDecimal profit) {
		this.profit = profit;
	}
	
	@Column(name = "CalculatedDate")
	public String getCalculatedDate() {
		return calculatedDate;
	}

	public void setCalculatedDate(String calculatedDate) {
		this.calculatedDate = calculatedDate;
	}
	
	@Transient
	public String getRepName() {
		return repName;
	}

	public void setRepName(String repName) {
		this.repName = repName;
	}
	
	@Column(name = "ecStatementEnteredDate")
	public Date getEcStatementEnteredDate() {
		return ecStatementEnteredDate;
	}

	public void setEcStatementEnteredDate(Date ecStatementEnteredDate) {
		this.ecStatementEnteredDate = ecStatementEnteredDate;
	}

}
