package com.turborep.turbotracker.employee.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Emmaster generated by hbm2java
 */
@Entity
@Table(name = "emMaster", catalog = "")
public class Emmaster implements java.io.Serializable {

	private int emMasterId;
	private BigDecimal commissionJobProfit;
	private BigDecimal commissionInvoiceProfit;
	private Integer userLoginId;
	private Boolean getsCommission=false;
	private BigDecimal quota;
	private BigDecimal repDeduct1;
	private BigDecimal repDeduct2;
	private BigDecimal repDeduct3;
	private BigDecimal repDeduct4;
	private Boolean showDirectory;
	private String location;
	private String position;
	private String photoName;
	private String phone;
	private String email;
	private String comment;
	private String webName;
	private Byte employmentStatus;
	private Byte employmentType;
	private Byte maritalStatus;
	private String sex;
	private String ssn;
	private Date birthDate;
	private Date hireDate;
	private Date nextReviewDate;
	private Date lastRaiseDate;
	private Date terminationDate;
	private Byte vacaType;
	private Date vacaStartDate;
	private BigDecimal vacaHoursPerYear;
	private BigDecimal vacaHoursMaximum;
	private BigDecimal vacaHoursAvailable;
	private Boolean vacaCarryOverYear;
	private Byte sickType;
	private Date sickStartDate;
	private BigDecimal sickHoursPerYear;
	private BigDecimal sickHoursMaximum;
	private BigDecimal sickHoursAvailable;
	private Boolean sickCarryOverYear;
	private Byte payFrequency;
	private Boolean retirementPlan;
	private Boolean statutoryEmployee;
	private Integer coStateId;
	private Integer epCoDepartmentId;
	private Byte ftMaritalStatus;
	private Byte ftExemptions;
	private BigDecimal ftSupWh;
	private String ftSpecialCode;
	private Byte stMaritalStatus;
	private Byte stExemptions;
	private BigDecimal stSupWh;
	private String stSpecialCode;
	private Byte ltMaritalStatus;
	private Byte ltExemptions;
	private BigDecimal ltSupWh;
	private String ltSpecialCode;
	private String jobNumberPrefix;
	private String jobNumberSequence;
	private Boolean jobNumberGenerate=false;
	private boolean directDeposit=false;
	private Integer coDivisionId;
	private BigDecimal commissionBuySellProfit;
	private BigDecimal commissionFactory;
	private Byte getsBonus=0;
	private BigDecimal enginComm;
	private Integer paymentPeriod;
	private BigDecimal bonusLevel1;
	private BigDecimal bonusComm1;
	private BigDecimal bonusLevel2;
	private BigDecimal bonusComm2;
	private BigDecimal bonusLevel3;
	private BigDecimal bonusComm3;
	private BigDecimal bonusLevel4;
	private BigDecimal bonusComm4;
	private BigDecimal bonusLevel5;
	private BigDecimal bonusComm5;
	private BigDecimal bonusLevel6;
	private BigDecimal bonusComm6;
	private BigDecimal bonusLevel7;
	private BigDecimal bonusComm7;
	private BigDecimal bonusLevel8;
	private BigDecimal bonusComm8;
	private Byte profitBonus=0;
	private Integer dayAfter;
	private Integer commAfterPayment;
	private Integer commPayOn;
	public Emmaster() {
	}

	public Emmaster(int emMasterId, boolean directDeposit) {
		this.emMasterId = emMasterId;
		this.directDeposit = directDeposit;
	}

	public Emmaster(int emMasterId, BigDecimal commissionJobProfit,
			BigDecimal commissionInvoiceProfit, Integer userLoginId,
			Boolean getsCommission, BigDecimal quota, BigDecimal repDeduct1,
			BigDecimal repDeduct2, BigDecimal repDeduct3,
			BigDecimal repDeduct4, Boolean showDirectory, String location,
			String position, String photoName, String phone, String email,
			String comment, String webName, Byte employmentStatus,
			Byte employmentType, Byte maritalStatus, String sex, String ssn,
			Date birthDate, Date hireDate, Date nextReviewDate,
			Date lastRaiseDate, Date terminationDate, Byte vacaType,
			Date vacaStartDate, BigDecimal vacaHoursPerYear,
			BigDecimal vacaHoursMaximum, BigDecimal vacaHoursAvailable,
			Boolean vacaCarryOverYear, Byte sickType, Date sickStartDate,
			BigDecimal sickHoursPerYear, BigDecimal sickHoursMaximum,
			BigDecimal sickHoursAvailable, Boolean sickCarryOverYear,
			Byte payFrequency, Boolean retirementPlan,
			Boolean statutoryEmployee, Integer coStateId,
			Integer epCoDepartmentId, Byte ftMaritalStatus, Byte ftExemptions,
			BigDecimal ftSupWh, String ftSpecialCode, Byte stMaritalStatus,
			Byte stExemptions, BigDecimal stSupWh, String stSpecialCode,
			Byte ltMaritalStatus, Byte ltExemptions, BigDecimal ltSupWh,
			String ltSpecialCode, String jobNumberPrefix,
			String jobNumberSequence, Boolean jobNumberGenerate,
			boolean directDeposit, Integer coDivisionId, BigDecimal commissionBuySellProfit, BigDecimal commissionFactory, Integer paymentPeriod, Byte profitBonus) {
		this.emMasterId = emMasterId;
		this.commissionJobProfit = commissionJobProfit;
		this.commissionInvoiceProfit = commissionInvoiceProfit;
		this.userLoginId = userLoginId;
		this.getsCommission = getsCommission;
		this.quota = quota;
		this.repDeduct1 = repDeduct1;
		this.repDeduct2 = repDeduct2;
		this.repDeduct3 = repDeduct3;
		this.repDeduct4 = repDeduct4;
		this.showDirectory = showDirectory;
		this.location = location;
		this.position = position;
		this.photoName = photoName;
		this.phone = phone;
		this.email = email;
		this.comment = comment;
		this.webName = webName;
		this.employmentStatus = employmentStatus;
		this.employmentType = employmentType;
		this.maritalStatus = maritalStatus;
		this.sex = sex;
		this.ssn = ssn;
		this.birthDate = birthDate;
		this.hireDate = hireDate;
		this.nextReviewDate = nextReviewDate;
		this.lastRaiseDate = lastRaiseDate;
		this.terminationDate = terminationDate;
		this.vacaType = vacaType;
		this.vacaStartDate = vacaStartDate;
		this.vacaHoursPerYear = vacaHoursPerYear;
		this.vacaHoursMaximum = vacaHoursMaximum;
		this.vacaHoursAvailable = vacaHoursAvailable;
		this.vacaCarryOverYear = vacaCarryOverYear;
		this.sickType = sickType;
		this.sickStartDate = sickStartDate;
		this.sickHoursPerYear = sickHoursPerYear;
		this.sickHoursMaximum = sickHoursMaximum;
		this.sickHoursAvailable = sickHoursAvailable;
		this.sickCarryOverYear = sickCarryOverYear;
		this.payFrequency = payFrequency;
		this.retirementPlan = retirementPlan;
		this.statutoryEmployee = statutoryEmployee;
		this.coStateId = coStateId;
		this.epCoDepartmentId = epCoDepartmentId;
		this.ftMaritalStatus = ftMaritalStatus;
		this.ftExemptions = ftExemptions;
		this.ftSupWh = ftSupWh;
		this.ftSpecialCode = ftSpecialCode;
		this.stMaritalStatus = stMaritalStatus;
		this.stExemptions = stExemptions;
		this.stSupWh = stSupWh;
		this.stSpecialCode = stSpecialCode;
		this.ltMaritalStatus = ltMaritalStatus;
		this.ltExemptions = ltExemptions;
		this.ltSupWh = ltSupWh;
		this.ltSpecialCode = ltSpecialCode;
		this.jobNumberPrefix = jobNumberPrefix;
		this.jobNumberSequence = jobNumberSequence;
		this.jobNumberGenerate = jobNumberGenerate;
		this.directDeposit = directDeposit;
		this.coDivisionId = coDivisionId;
		this.commissionBuySellProfit = commissionBuySellProfit;
		this.commissionFactory = commissionFactory;
		this.profitBonus = profitBonus;
	}

	@Id
	@Column(name = "emMasterID", unique = true, nullable = false)
	public int getEmMasterId() {
		return this.emMasterId;
	}

	public void setEmMasterId(int emMasterId) {
		this.emMasterId = emMasterId;
	}

	@Column(name = "CommissionJobProfit", scale = 4)
	public BigDecimal getCommissionJobProfit() {
		return this.commissionJobProfit;
	}

	public void setCommissionJobProfit(BigDecimal commissionJobProfit) {
		this.commissionJobProfit = commissionJobProfit;
	}

	@Column(name = "CommissionInvoiceProfit", scale = 4)
	public BigDecimal getCommissionInvoiceProfit() {
		return this.commissionInvoiceProfit;
	}

	public void setCommissionInvoiceProfit(BigDecimal commissionInvoiceProfit) {
		this.commissionInvoiceProfit = commissionInvoiceProfit;
	}

	@Column(name = "UserLoginID")
	public Integer getUserLoginId() {
		return this.userLoginId;
	}

	public void setUserLoginId(Integer userLoginId) {
		this.userLoginId = userLoginId;
	}

	@Column(name = "GetsCommission")
	public Boolean getGetsCommission() {
		return this.getsCommission;
	}

	public void setGetsCommission(Boolean getsCommission) {
		this.getsCommission = getsCommission;
	}

	@Column(name = "Quota", scale = 4)
	public BigDecimal getQuota() {
		return this.quota;
	}

	public void setQuota(BigDecimal quota) {
		this.quota = quota;
	}

	@Column(name = "RepDeduct1", scale = 4)
	public BigDecimal getRepDeduct1() {
		return this.repDeduct1;
	}

	public void setRepDeduct1(BigDecimal repDeduct1) {
		this.repDeduct1 = repDeduct1;
	}

	@Column(name = "RepDeduct2", scale = 4)
	public BigDecimal getRepDeduct2() {
		return this.repDeduct2;
	}

	public void setRepDeduct2(BigDecimal repDeduct2) {
		this.repDeduct2 = repDeduct2;
	}

	@Column(name = "RepDeduct3", scale = 4)
	public BigDecimal getRepDeduct3() {
		return this.repDeduct3;
	}

	public void setRepDeduct3(BigDecimal repDeduct3) {
		this.repDeduct3 = repDeduct3;
	}

	@Column(name = "RepDeduct4", scale = 4)
	public BigDecimal getRepDeduct4() {
		return this.repDeduct4;
	}

	public void setRepDeduct4(BigDecimal repDeduct4) {
		this.repDeduct4 = repDeduct4;
	}

	@Column(name = "ShowDirectory")
	public Boolean getShowDirectory() {
		return this.showDirectory;
	}

	public void setShowDirectory(Boolean showDirectory) {
		this.showDirectory = showDirectory;
	}

	@Column(name = "Location", length = 20)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "Position", length = 20)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "PhotoName", length = 20)
	public String getPhotoName() {
		return this.photoName;
	}

	public void setPhotoName(String photoName) {
		this.photoName = photoName;
	}

	@Column(name = "Phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "Email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Comment", length = 50)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "WebName", length = 35)
	public String getWebName() {
		return this.webName;
	}

	public void setWebName(String webName) {
		this.webName = webName;
	}

	@Column(name = "EmploymentStatus")
	public Byte getEmploymentStatus() {
		return this.employmentStatus;
	}

	public void setEmploymentStatus(Byte employmentStatus) {
		this.employmentStatus = employmentStatus;
	}

	@Column(name = "EmploymentType")
	public Byte getEmploymentType() {
		return this.employmentType;
	}

	public void setEmploymentType(Byte employmentType) {
		this.employmentType = employmentType;
	}

	@Column(name = "MaritalStatus")
	public Byte getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(Byte maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	@Column(name = "Sex", length = 1)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "SSN", length = 11)
	public String getSsn() {
		return this.ssn;
	}

	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BirthDate", length = 0)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HireDate", length = 0)
	public Date getHireDate() {
		return this.hireDate;
	}

	public void setHireDate(Date hireDate) {
		this.hireDate = hireDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NextReviewDate", length = 0)
	public Date getNextReviewDate() {
		return this.nextReviewDate;
	}

	public void setNextReviewDate(Date nextReviewDate) {
		this.nextReviewDate = nextReviewDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastRaiseDate", length = 0)
	public Date getLastRaiseDate() {
		return this.lastRaiseDate;
	}

	public void setLastRaiseDate(Date lastRaiseDate) {
		this.lastRaiseDate = lastRaiseDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TerminationDate", length = 0)
	public Date getTerminationDate() {
		return this.terminationDate;
	}

	public void setTerminationDate(Date terminationDate) {
		this.terminationDate = terminationDate;
	}

	@Column(name = "VacaType")
	public Byte getVacaType() {
		return this.vacaType;
	}

	public void setVacaType(Byte vacaType) {
		this.vacaType = vacaType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VacaStartDate", length = 0)
	public Date getVacaStartDate() {
		return this.vacaStartDate;
	}

	public void setVacaStartDate(Date vacaStartDate) {
		this.vacaStartDate = vacaStartDate;
	}

	@Column(name = "VacaHoursPerYear", scale = 4)
	public BigDecimal getVacaHoursPerYear() {
		return this.vacaHoursPerYear;
	}

	public void setVacaHoursPerYear(BigDecimal vacaHoursPerYear) {
		this.vacaHoursPerYear = vacaHoursPerYear;
	}

	@Column(name = "VacaHoursMaximum", scale = 4)
	public BigDecimal getVacaHoursMaximum() {
		return this.vacaHoursMaximum;
	}

	public void setVacaHoursMaximum(BigDecimal vacaHoursMaximum) {
		this.vacaHoursMaximum = vacaHoursMaximum;
	}

	@Column(name = "VacaHoursAvailable", scale = 4)
	public BigDecimal getVacaHoursAvailable() {
		return this.vacaHoursAvailable;
	}

	public void setVacaHoursAvailable(BigDecimal vacaHoursAvailable) {
		this.vacaHoursAvailable = vacaHoursAvailable;
	}

	@Column(name = "VacaCarryOverYear")
	public Boolean getVacaCarryOverYear() {
		return this.vacaCarryOverYear;
	}

	public void setVacaCarryOverYear(Boolean vacaCarryOverYear) {
		this.vacaCarryOverYear = vacaCarryOverYear;
	}

	@Column(name = "SickType")
	public Byte getSickType() {
		return this.sickType;
	}

	public void setSickType(Byte sickType) {
		this.sickType = sickType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SickStartDate", length = 0)
	public Date getSickStartDate() {
		return this.sickStartDate;
	}

	public void setSickStartDate(Date sickStartDate) {
		this.sickStartDate = sickStartDate;
	}

	@Column(name = "SickHoursPerYear", scale = 4)
	public BigDecimal getSickHoursPerYear() {
		return this.sickHoursPerYear;
	}

	public void setSickHoursPerYear(BigDecimal sickHoursPerYear) {
		this.sickHoursPerYear = sickHoursPerYear;
	}

	@Column(name = "SickHoursMaximum", scale = 4)
	public BigDecimal getSickHoursMaximum() {
		return this.sickHoursMaximum;
	}

	public void setSickHoursMaximum(BigDecimal sickHoursMaximum) {
		this.sickHoursMaximum = sickHoursMaximum;
	}

	@Column(name = "SickHoursAvailable", scale = 4)
	public BigDecimal getSickHoursAvailable() {
		return this.sickHoursAvailable;
	}

	public void setSickHoursAvailable(BigDecimal sickHoursAvailable) {
		this.sickHoursAvailable = sickHoursAvailable;
	}

	@Column(name = "SickCarryOverYear")
	public Boolean getSickCarryOverYear() {
		return this.sickCarryOverYear;
	}

	public void setSickCarryOverYear(Boolean sickCarryOverYear) {
		this.sickCarryOverYear = sickCarryOverYear;
	}

	@Column(name = "PayFrequency")
	public Byte getPayFrequency() {
		return this.payFrequency;
	}

	public void setPayFrequency(Byte payFrequency) {
		this.payFrequency = payFrequency;
	}

	@Column(name = "RetirementPlan")
	public Boolean getRetirementPlan() {
		return this.retirementPlan;
	}

	public void setRetirementPlan(Boolean retirementPlan) {
		this.retirementPlan = retirementPlan;
	}

	@Column(name = "StatutoryEmployee")
	public Boolean getStatutoryEmployee() {
		return this.statutoryEmployee;
	}

	public void setStatutoryEmployee(Boolean statutoryEmployee) {
		this.statutoryEmployee = statutoryEmployee;
	}

	@Column(name = "coStateID")
	public Integer getCoStateId() {
		return this.coStateId;
	}

	public void setCoStateId(Integer coStateId) {
		this.coStateId = coStateId;
	}

	@Column(name = "epCoDepartmentID")
	public Integer getEpCoDepartmentId() {
		return this.epCoDepartmentId;
	}

	public void setEpCoDepartmentId(Integer epCoDepartmentId) {
		this.epCoDepartmentId = epCoDepartmentId;
	}

	@Column(name = "FT_MaritalStatus")
	public Byte getFtMaritalStatus() {
		return this.ftMaritalStatus;
	}

	public void setFtMaritalStatus(Byte ftMaritalStatus) {
		this.ftMaritalStatus = ftMaritalStatus;
	}

	@Column(name = "FT_Exemptions")
	public Byte getFtExemptions() {
		return this.ftExemptions;
	}

	public void setFtExemptions(Byte ftExemptions) {
		this.ftExemptions = ftExemptions;
	}

	@Column(name = "FT_SupWH", scale = 4)
	public BigDecimal getFtSupWh() {
		return this.ftSupWh;
	}

	public void setFtSupWh(BigDecimal ftSupWh) {
		this.ftSupWh = ftSupWh;
	}

	@Column(name = "FT_SpecialCode", length = 5)
	public String getFtSpecialCode() {
		return this.ftSpecialCode;
	}

	public void setFtSpecialCode(String ftSpecialCode) {
		this.ftSpecialCode = ftSpecialCode;
	}

	@Column(name = "ST_MaritalStatus")
	public Byte getStMaritalStatus() {
		return this.stMaritalStatus;
	}

	public void setStMaritalStatus(Byte stMaritalStatus) {
		this.stMaritalStatus = stMaritalStatus;
	}

	@Column(name = "ST_Exemptions")
	public Byte getStExemptions() {
		return this.stExemptions;
	}

	public void setStExemptions(Byte stExemptions) {
		this.stExemptions = stExemptions;
	}

	@Column(name = "ST_SupWH", scale = 4)
	public BigDecimal getStSupWh() {
		return this.stSupWh;
	}

	public void setStSupWh(BigDecimal stSupWh) {
		this.stSupWh = stSupWh;
	}

	@Column(name = "ST_SpecialCode", length = 5)
	public String getStSpecialCode() {
		return this.stSpecialCode;
	}

	public void setStSpecialCode(String stSpecialCode) {
		this.stSpecialCode = stSpecialCode;
	}

	@Column(name = "LT_MaritalStatus")
	public Byte getLtMaritalStatus() {
		return this.ltMaritalStatus;
	}

	public void setLtMaritalStatus(Byte ltMaritalStatus) {
		this.ltMaritalStatus = ltMaritalStatus;
	}

	@Column(name = "LT_Exemptions")
	public Byte getLtExemptions() {
		return this.ltExemptions;
	}

	public void setLtExemptions(Byte ltExemptions) {
		this.ltExemptions = ltExemptions;
	}

	@Column(name = "LT_SupWH", scale = 4)
	public BigDecimal getLtSupWh() {
		return this.ltSupWh;
	}

	public void setLtSupWh(BigDecimal ltSupWh) {
		this.ltSupWh = ltSupWh;
	}

	@Column(name = "LT_SpecialCode", length = 5)
	public String getLtSpecialCode() {
		return this.ltSpecialCode;
	}

	public void setLtSpecialCode(String ltSpecialCode) {
		this.ltSpecialCode = ltSpecialCode;
	}

	@Column(name = "JobNumberPrefix", length = 3)
	public String getJobNumberPrefix() {
		return this.jobNumberPrefix;
	}

	public void setJobNumberPrefix(String jobNumberPrefix) {
		this.jobNumberPrefix = jobNumberPrefix;
	}

	@Column(name = "JobNumberSequence")
	public String getJobNumberSequence() {
		return this.jobNumberSequence;
	}

	public void setJobNumberSequence(String jobNumberSequence) {
		this.jobNumberSequence = jobNumberSequence;
	}

	@Column(name = "JobNumberGenerate")
	public Boolean getJobNumberGenerate() {
		return this.jobNumberGenerate;
	}

	public void setJobNumberGenerate(Boolean jobNumberGenerate) {
		this.jobNumberGenerate = jobNumberGenerate;
	}

	@Column(name = "DirectDeposit", nullable = false)
	public boolean isDirectDeposit() {
		return this.directDeposit;
	}

	public void setDirectDeposit(boolean directDeposit) {
		this.directDeposit = directDeposit;
	}

	@Column(name = "coDivisionID")
	public Integer getCoDivisionId() {
		return this.coDivisionId;
	}

	public void setCoDivisionId(Integer coDivisionId) {
		this.coDivisionId = coDivisionId;
	}

	@Column(name = "CommissionBuySellProfit", scale = 4)
	public BigDecimal getCommissionBuySellProfit() {
		return commissionBuySellProfit;
	}

	public void setCommissionBuySellProfit(BigDecimal commissionBuySellProfit) {
		this.commissionBuySellProfit = commissionBuySellProfit;
	}
	
	@Column(name = "CommissionFactory", scale = 4)
	public BigDecimal getCommissionFactory() {
		return commissionFactory;
	}

	public void setCommissionFactory(BigDecimal commissionFactory) {
		this.commissionFactory = commissionFactory;
	}

	@Column(name = "GetsBonus")
	public Byte getGetsBonus() {
		return getsBonus;
	}

	public void setGetsBonus(Byte getsBonus) {
		this.getsBonus = getsBonus;
	}

	@Column(name = "enginComm", scale = 4)
	public BigDecimal getEnginComm() {
		return enginComm;
	}

	public void setEnginComm(BigDecimal enginComm) {
		this.enginComm = enginComm;
	}

	@Column(name = "paymentPeriod")
	public Integer getPaymentPeriod() {
		return paymentPeriod;
	}

	public void setPaymentPeriod(Integer paymentPeriod) {
		this.paymentPeriod = paymentPeriod;
	}

	@Column(name = "BonusLevel1", scale = 4)
	public BigDecimal getBonusLevel1() {
		return bonusLevel1;
	}

	public void setBonusLevel1(BigDecimal bonusLevel1) {
		this.bonusLevel1 = bonusLevel1;
	}

	@Column(name = "BonusComm1", scale = 4)
	public BigDecimal getBonusComm1() {
		return bonusComm1;
	}

	public void setBonusComm1(BigDecimal bonusComm1) {
		this.bonusComm1 = bonusComm1;
	}

	@Column(name = "BonusLevel2", scale = 4)
	public BigDecimal getBonusLevel2() {
		return bonusLevel2;
	}

	public void setBonusLevel2(BigDecimal bonusLevel2) {
		this.bonusLevel2 = bonusLevel2;
	}

	@Column(name = "BonusComm2", scale = 4)
	public BigDecimal getBonusComm2() {
		return bonusComm2;
	}

	public void setBonusComm2(BigDecimal bonusComm2) {
		this.bonusComm2 = bonusComm2;
	}

	@Column(name = "BonusLevel3", scale = 4)
	public BigDecimal getBonusLevel3() {
		return bonusLevel3;
	}

	public void setBonusLevel3(BigDecimal bonusLevel3) {
		this.bonusLevel3 = bonusLevel3;
	}

	@Column(name = "BonusComm3", scale = 4)
	public BigDecimal getBonusComm3() {
		return bonusComm3;
	}

	public void setBonusComm3(BigDecimal bonusComm3) {
		this.bonusComm3 = bonusComm3;
	}

	@Column(name = "BonusLevel4", scale = 4)
	public BigDecimal getBonusLevel4() {
		return bonusLevel4;
	}

	public void setBonusLevel4(BigDecimal bonusLevel4) {
		this.bonusLevel4 = bonusLevel4;
	}

	@Column(name = "BonusComm4", scale = 4)
	public BigDecimal getBonusComm4() {
		return bonusComm4;
	}

	public void setBonusComm4(BigDecimal bonusComm4) {
		this.bonusComm4 = bonusComm4;
	}

	@Column(name = "BonusLevel5", scale = 4)
	public BigDecimal getBonusLevel5() {
		return bonusLevel5;
	}

	public void setBonusLevel5(BigDecimal bonusLevel5) {
		this.bonusLevel5 = bonusLevel5;
	}

	@Column(name = "BonusComm5", scale = 4)
	public BigDecimal getBonusComm5() {
		return bonusComm5;
	}

	public void setBonusComm5(BigDecimal bonusComm5) {
		this.bonusComm5 = bonusComm5;
	}

	@Column(name = "BonusLevel6", scale = 4)
	public BigDecimal getBonusLevel6() {
		return bonusLevel6;
	}

	public void setBonusLevel6(BigDecimal bonusLevel6) {
		this.bonusLevel6 = bonusLevel6;
	}

	@Column(name = "BonusComm6", scale = 4)
	public BigDecimal getBonusComm6() {
		return bonusComm6;
	}

	public void setBonusComm6(BigDecimal bonusComm6) {
		this.bonusComm6 = bonusComm6;
	}

	@Column(name = "BonusLevel7", scale = 4)
	public BigDecimal getBonusLevel7() {
		return bonusLevel7;
	}

	public void setBonusLevel7(BigDecimal bonusLevel7) {
		this.bonusLevel7 = bonusLevel7;
	}

	@Column(name = "BonusComm7", scale = 4)
	public BigDecimal getBonusComm7() {
		return bonusComm7;
	}

	public void setBonusComm7(BigDecimal bonusComm7) {
		this.bonusComm7 = bonusComm7;
	}

	@Column(name = "BonusLevel8", scale = 4)
	public BigDecimal getBonusLevel8() {
		return bonusLevel8;
	}

	public void setBonusLevel8(BigDecimal bonusLevel8) {
		this.bonusLevel8 = bonusLevel8;
	}

	@Column(name = "BonusComm8", scale = 4)
	public BigDecimal getBonusComm8() {
		return bonusComm8;
	}

	public void setBonusComm8(BigDecimal bonusComm8) {
		this.bonusComm8 = bonusComm8;
	}

	@Column(name = "ProfitBonus")
	public Byte getProfitBonus() {
		return profitBonus;
	}

	public void setProfitBonus(Byte profitBonus) {
		this.profitBonus = profitBonus;
	}
	
	@Column(name = "dayAfter")
	public Integer getDayAfter() {
		return dayAfter;
	}

	public void setDayAfter(Integer dayAfter) {
		this.dayAfter = dayAfter;
	}
	
	@Column(name = "CommAfterPayment")
	public Integer getCommAfterPayment() {
		return commAfterPayment;
	}

	public void setCommAfterPayment(Integer commAfterPayment) {
		this.commAfterPayment = commAfterPayment;
	}

	@Column(name = "CommPayOn")
	public Integer getCommPayOn() {
		return commPayOn;
	}

	public void setCommPayOn(Integer commPayOn) {
		this.commPayOn = commPayOn;
	}
}
