package com.turborep.turbotracker.employee.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ep1099workfile generated by hbm2java
 */
@Entity
@Table(name = "ep1099workfile", catalog = "")
public class Ep1099workfile implements java.io.Serializable {

	private Integer ep1099workFileId;
	private String payer1;
	private String payer2;
	private String payer3;
	private String payer4;
	private String payerFin;
	private String recipFin;
	private String recipName;
	private String recipAddress1;
	private String recipAddress2;
	private String recipCityStateZip;
	private String controlNo;
	private String box7;

	public Ep1099workfile() {
	}

	public Ep1099workfile(String payer1, String payer2, String payer3,
			String payer4, String payerFin, String recipFin, String recipName,
			String recipAddress1, String recipAddress2,
			String recipCityStateZip, String controlNo, String box7) {
		this.payer1 = payer1;
		this.payer2 = payer2;
		this.payer3 = payer3;
		this.payer4 = payer4;
		this.payerFin = payerFin;
		this.recipFin = recipFin;
		this.recipName = recipName;
		this.recipAddress1 = recipAddress1;
		this.recipAddress2 = recipAddress2;
		this.recipCityStateZip = recipCityStateZip;
		this.controlNo = controlNo;
		this.box7 = box7;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ep1099WorkFileID", unique = true, nullable = false)
	public Integer getEp1099workFileId() {
		return this.ep1099workFileId;
	}

	public void setEp1099workFileId(Integer ep1099workFileId) {
		this.ep1099workFileId = ep1099workFileId;
	}

	@Column(name = "Payer1", length = 50)
	public String getPayer1() {
		return this.payer1;
	}

	public void setPayer1(String payer1) {
		this.payer1 = payer1;
	}

	@Column(name = "Payer2", length = 50)
	public String getPayer2() {
		return this.payer2;
	}

	public void setPayer2(String payer2) {
		this.payer2 = payer2;
	}

	@Column(name = "Payer3", length = 50)
	public String getPayer3() {
		return this.payer3;
	}

	public void setPayer3(String payer3) {
		this.payer3 = payer3;
	}

	@Column(name = "Payer4", length = 50)
	public String getPayer4() {
		return this.payer4;
	}

	public void setPayer4(String payer4) {
		this.payer4 = payer4;
	}

	@Column(name = "PayerFIN", length = 50)
	public String getPayerFin() {
		return this.payerFin;
	}

	public void setPayerFin(String payerFin) {
		this.payerFin = payerFin;
	}

	@Column(name = "RecipFIN", length = 50)
	public String getRecipFin() {
		return this.recipFin;
	}

	public void setRecipFin(String recipFin) {
		this.recipFin = recipFin;
	}

	@Column(name = "RecipName", length = 50)
	public String getRecipName() {
		return this.recipName;
	}

	public void setRecipName(String recipName) {
		this.recipName = recipName;
	}

	@Column(name = "RecipAddress1", length = 50)
	public String getRecipAddress1() {
		return this.recipAddress1;
	}

	public void setRecipAddress1(String recipAddress1) {
		this.recipAddress1 = recipAddress1;
	}

	@Column(name = "RecipAddress2", length = 50)
	public String getRecipAddress2() {
		return this.recipAddress2;
	}

	public void setRecipAddress2(String recipAddress2) {
		this.recipAddress2 = recipAddress2;
	}

	@Column(name = "RecipCityStateZip", length = 50)
	public String getRecipCityStateZip() {
		return this.recipCityStateZip;
	}

	public void setRecipCityStateZip(String recipCityStateZip) {
		this.recipCityStateZip = recipCityStateZip;
	}

	@Column(name = "ControlNo", length = 50)
	public String getControlNo() {
		return this.controlNo;
	}

	public void setControlNo(String controlNo) {
		this.controlNo = controlNo;
	}

	@Column(name = "Box7", length = 50)
	public String getBox7() {
		return this.box7;
	}

	public void setBox7(String box7) {
		this.box7 = box7;
	}

}
