package com.turborep.turbotracker.employee.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Epcodeduction generated by hbm2java
 */
@Entity
@Table(name = "epcodeduction", catalog = "")
public class Epcodeduction implements java.io.Serializable {

	private Integer epCoDeductionId;
	private Boolean inActive;
	private String description;
	private String w2code;
	private boolean builtIn;
	private Byte calculationType;
	private BigDecimal amount;
	private BigDecimal maximum;
	private Boolean federalIncomeTaxExempt;
	private Boolean socialSecurityExempt;
	private Boolean medicareExempt;
	private Boolean stateIncomeTaxExempt;
	private Boolean localIncomeTaxExempt;
	private Boolean otherExempt;
	private Integer sortOrder;

	public Epcodeduction() {
	}

	public Epcodeduction(boolean builtIn) {
		this.builtIn = builtIn;
	}

	public Epcodeduction(Boolean inActive, String description, String w2code,
			boolean builtIn, Byte calculationType, BigDecimal amount,
			BigDecimal maximum, Boolean federalIncomeTaxExempt,
			Boolean socialSecurityExempt, Boolean medicareExempt,
			Boolean stateIncomeTaxExempt, Boolean localIncomeTaxExempt,
			Boolean otherExempt, Integer sortOrder) {
		this.inActive = inActive;
		this.description = description;
		this.w2code = w2code;
		this.builtIn = builtIn;
		this.calculationType = calculationType;
		this.amount = amount;
		this.maximum = maximum;
		this.federalIncomeTaxExempt = federalIncomeTaxExempt;
		this.socialSecurityExempt = socialSecurityExempt;
		this.medicareExempt = medicareExempt;
		this.stateIncomeTaxExempt = stateIncomeTaxExempt;
		this.localIncomeTaxExempt = localIncomeTaxExempt;
		this.otherExempt = otherExempt;
		this.sortOrder = sortOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "epCoDeductionID", unique = true, nullable = false)
	public Integer getEpCoDeductionId() {
		return this.epCoDeductionId;
	}

	public void setEpCoDeductionId(Integer epCoDeductionId) {
		this.epCoDeductionId = epCoDeductionId;
	}

	@Column(name = "InActive")
	public Boolean getInActive() {
		return this.inActive;
	}

	public void setInActive(Boolean inActive) {
		this.inActive = inActive;
	}

	@Column(name = "Description", length = 20)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "W2Code", length = 1)
	public String getW2code() {
		return this.w2code;
	}

	public void setW2code(String w2code) {
		this.w2code = w2code;
	}

	@Column(name = "BuiltIn", nullable = false)
	public boolean isBuiltIn() {
		return this.builtIn;
	}

	public void setBuiltIn(boolean builtIn) {
		this.builtIn = builtIn;
	}

	@Column(name = "CalculationType")
	public Byte getCalculationType() {
		return this.calculationType;
	}

	public void setCalculationType(Byte calculationType) {
		this.calculationType = calculationType;
	}

	@Column(name = "Amount", scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "Maximum", scale = 4)
	public BigDecimal getMaximum() {
		return this.maximum;
	}

	public void setMaximum(BigDecimal maximum) {
		this.maximum = maximum;
	}

	@Column(name = "FederalIncomeTaxExempt")
	public Boolean getFederalIncomeTaxExempt() {
		return this.federalIncomeTaxExempt;
	}

	public void setFederalIncomeTaxExempt(Boolean federalIncomeTaxExempt) {
		this.federalIncomeTaxExempt = federalIncomeTaxExempt;
	}

	@Column(name = "SocialSecurityExempt")
	public Boolean getSocialSecurityExempt() {
		return this.socialSecurityExempt;
	}

	public void setSocialSecurityExempt(Boolean socialSecurityExempt) {
		this.socialSecurityExempt = socialSecurityExempt;
	}

	@Column(name = "MedicareExempt")
	public Boolean getMedicareExempt() {
		return this.medicareExempt;
	}

	public void setMedicareExempt(Boolean medicareExempt) {
		this.medicareExempt = medicareExempt;
	}

	@Column(name = "StateIncomeTaxExempt")
	public Boolean getStateIncomeTaxExempt() {
		return this.stateIncomeTaxExempt;
	}

	public void setStateIncomeTaxExempt(Boolean stateIncomeTaxExempt) {
		this.stateIncomeTaxExempt = stateIncomeTaxExempt;
	}

	@Column(name = "LocalIncomeTaxExempt")
	public Boolean getLocalIncomeTaxExempt() {
		return this.localIncomeTaxExempt;
	}

	public void setLocalIncomeTaxExempt(Boolean localIncomeTaxExempt) {
		this.localIncomeTaxExempt = localIncomeTaxExempt;
	}

	@Column(name = "OtherExempt")
	public Boolean getOtherExempt() {
		return this.otherExempt;
	}

	public void setOtherExempt(Boolean otherExempt) {
		this.otherExempt = otherExempt;
	}

	@Column(name = "SortOrder")
	public Integer getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

}
