package com.turborep.turbotracker.employee.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Epcodepartment generated by hbm2java
 */
@Entity
@Table(name = "epcodepartment", catalog = "")
public class Epcodepartment implements java.io.Serializable {

	private Integer epCoDepartmentId;
	private Boolean inActive;
	private String description;

	public Epcodepartment() {
	}

	public Epcodepartment(Boolean inActive, String description) {
		this.inActive = inActive;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "epCoDepartmentID", unique = true, nullable = false)
	public Integer getEpCoDepartmentId() {
		return this.epCoDepartmentId;
	}

	public void setEpCoDepartmentId(Integer epCoDepartmentId) {
		this.epCoDepartmentId = epCoDepartmentId;
	}

	@Column(name = "InActive")
	public Boolean getInActive() {
		return this.inActive;
	}

	public void setInActive(Boolean inActive) {
		this.inActive = inActive;
	}

	@Column(name = "Description", length = 20)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
