package com.turborep.turbotracker.employee.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Epcoearning generated by hbm2java
 */
@Entity
@Table(name = "epcoearning", catalog = "")
public class Epcoearning implements java.io.Serializable {

	private Integer epCoEarningId;
	private Boolean inActive;
	private String description;
	private Byte payType;
	private Integer sortOrder;

	public Epcoearning() {
	}

	public Epcoearning(Boolean inActive, String description, Byte payType,
			Integer sortOrder) {
		this.inActive = inActive;
		this.description = description;
		this.payType = payType;
		this.sortOrder = sortOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "epCoEarningID", unique = true, nullable = false)
	public Integer getEpCoEarningId() {
		return this.epCoEarningId;
	}

	public void setEpCoEarningId(Integer epCoEarningId) {
		this.epCoEarningId = epCoEarningId;
	}

	@Column(name = "InActive")
	public Boolean getInActive() {
		return this.inActive;
	}

	public void setInActive(Boolean inActive) {
		this.inActive = inActive;
	}

	@Column(name = "Description", length = 20)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "PayType")
	public Byte getPayType() {
		return this.payType;
	}

	public void setPayType(Byte payType) {
		this.payType = payType;
	}

	@Column(name = "SortOrder")
	public Integer getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

}
