package com.turborep.turbotracker.employee.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Epdepdeduction generated by hbm2java
 */
@Entity
@Table(name = "epdepdeduction", catalog = "")
public class Epdepdeduction implements java.io.Serializable {

	private Integer epDepDeductionId;
	private Integer epCoDepartmentId;
	private Integer epCoDeductionId;
	private Integer coAccountId;

	public Epdepdeduction() {
	}

	public Epdepdeduction(Integer epCoDepartmentId, Integer epCoDeductionId,
			Integer coAccountId) {
		this.epCoDepartmentId = epCoDepartmentId;
		this.epCoDeductionId = epCoDeductionId;
		this.coAccountId = coAccountId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "epDepDeductionID", unique = true, nullable = false)
	public Integer getEpDepDeductionId() {
		return this.epDepDeductionId;
	}

	public void setEpDepDeductionId(Integer epDepDeductionId) {
		this.epDepDeductionId = epDepDeductionId;
	}

	@Column(name = "epCoDepartmentID")
	public Integer getEpCoDepartmentId() {
		return this.epCoDepartmentId;
	}

	public void setEpCoDepartmentId(Integer epCoDepartmentId) {
		this.epCoDepartmentId = epCoDepartmentId;
	}

	@Column(name = "epCoDeductionID")
	public Integer getEpCoDeductionId() {
		return this.epCoDeductionId;
	}

	public void setEpCoDeductionId(Integer epCoDeductionId) {
		this.epCoDeductionId = epCoDeductionId;
	}

	@Column(name = "coAccountID")
	public Integer getCoAccountId() {
		return this.coAccountId;
	}

	public void setCoAccountId(Integer coAccountId) {
		this.coAccountId = coAccountId;
	}

}
