package com.turborep.turbotracker.employee.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Eptransaction generated by hbm2java
 */
@Entity
@Table(name = "eptransaction", catalog = "")
public class Eptransaction implements java.io.Serializable {

	private Integer epTransactionId;
	private Integer rxMasterId;
	private Integer moTransactionId;
	private Integer coStateId;
	private Date postDate;
	private Date payPeriodEnding;
	private Byte periodFrequency;
	private BigDecimal grossWages;
	private BigDecimal fitwages;
	private BigDecimal socialSecurityWages;
	private BigDecimal medicareWages;
	private BigDecimal otherWages;
	private BigDecimal netWages;
	private Boolean openBalance;

	public Eptransaction() {
	}

	public Eptransaction(Integer rxMasterId, Integer moTransactionId,
			Integer coStateId, Date postDate, Date payPeriodEnding,
			Byte periodFrequency, BigDecimal grossWages, BigDecimal fitwages,
			BigDecimal socialSecurityWages, BigDecimal medicareWages,
			BigDecimal otherWages, BigDecimal netWages, Boolean openBalance) {
		this.rxMasterId = rxMasterId;
		this.moTransactionId = moTransactionId;
		this.coStateId = coStateId;
		this.postDate = postDate;
		this.payPeriodEnding = payPeriodEnding;
		this.periodFrequency = periodFrequency;
		this.grossWages = grossWages;
		this.fitwages = fitwages;
		this.socialSecurityWages = socialSecurityWages;
		this.medicareWages = medicareWages;
		this.otherWages = otherWages;
		this.netWages = netWages;
		this.openBalance = openBalance;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "epTransactionID", unique = true, nullable = false)
	public Integer getEpTransactionId() {
		return this.epTransactionId;
	}

	public void setEpTransactionId(Integer epTransactionId) {
		this.epTransactionId = epTransactionId;
	}

	@Column(name = "rxMasterID")
	public Integer getRxMasterId() {
		return this.rxMasterId;
	}

	public void setRxMasterId(Integer rxMasterId) {
		this.rxMasterId = rxMasterId;
	}

	@Column(name = "moTransactionID")
	public Integer getMoTransactionId() {
		return this.moTransactionId;
	}

	public void setMoTransactionId(Integer moTransactionId) {
		this.moTransactionId = moTransactionId;
	}

	@Column(name = "coStateID")
	public Integer getCoStateId() {
		return this.coStateId;
	}

	public void setCoStateId(Integer coStateId) {
		this.coStateId = coStateId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PostDate", length = 0)
	public Date getPostDate() {
		return this.postDate;
	}

	public void setPostDate(Date postDate) {
		this.postDate = postDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PayPeriodEnding", length = 0)
	public Date getPayPeriodEnding() {
		return this.payPeriodEnding;
	}

	public void setPayPeriodEnding(Date payPeriodEnding) {
		this.payPeriodEnding = payPeriodEnding;
	}

	@Column(name = "PeriodFrequency")
	public Byte getPeriodFrequency() {
		return this.periodFrequency;
	}

	public void setPeriodFrequency(Byte periodFrequency) {
		this.periodFrequency = periodFrequency;
	}

	@Column(name = "GrossWages", scale = 4)
	public BigDecimal getGrossWages() {
		return this.grossWages;
	}

	public void setGrossWages(BigDecimal grossWages) {
		this.grossWages = grossWages;
	}

	@Column(name = "FITWages", scale = 4)
	public BigDecimal getFitwages() {
		return this.fitwages;
	}

	public void setFitwages(BigDecimal fitwages) {
		this.fitwages = fitwages;
	}

	@Column(name = "SocialSecurityWages", scale = 4)
	public BigDecimal getSocialSecurityWages() {
		return this.socialSecurityWages;
	}

	public void setSocialSecurityWages(BigDecimal socialSecurityWages) {
		this.socialSecurityWages = socialSecurityWages;
	}

	@Column(name = "MedicareWages", scale = 4)
	public BigDecimal getMedicareWages() {
		return this.medicareWages;
	}

	public void setMedicareWages(BigDecimal medicareWages) {
		this.medicareWages = medicareWages;
	}

	@Column(name = "OtherWages", scale = 4)
	public BigDecimal getOtherWages() {
		return this.otherWages;
	}

	public void setOtherWages(BigDecimal otherWages) {
		this.otherWages = otherWages;
	}

	@Column(name = "NetWages", scale = 4)
	public BigDecimal getNetWages() {
		return this.netWages;
	}

	public void setNetWages(BigDecimal netWages) {
		this.netWages = netWages;
	}

	@Column(name = "OpenBalance")
	public Boolean getOpenBalance() {
		return this.openBalance;
	}

	public void setOpenBalance(Boolean openBalance) {
		this.openBalance = openBalance;
	}

}
