package com.turborep.turbotracker.employee.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Formscratch generated by hbm2java
 */
@Entity
@Table(name = "formscratch", catalog = "")
public class Formscratch implements java.io.Serializable {

	private FormscratchId id;

	public Formscratch() {
	}

	public Formscratch(FormscratchId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "formHeaderId", column = @Column(name = "FormHeaderID", nullable = false)),
			@AttributeOverride(name = "tempSort", column = @Column(name = "TempSort", scale = 4)),
			@AttributeOverride(name = "formNo", column = @Column(name = "FormNo")),
			@AttributeOverride(name = "section", column = @Column(name = "Section", length = 50)),
			@AttributeOverride(name = "name", column = @Column(name = "Name", length = 50)),
			@AttributeOverride(name = "caption", column = @Column(name = "Caption")),
			@AttributeOverride(name = "hide", column = @Column(name = "Hide")),
			@AttributeOverride(name = "show", column = @Column(name = "Show")),
			@AttributeOverride(name = "useTopOffset", column = @Column(name = "UseTopOffset")),
			@AttributeOverride(name = "locTop", column = @Column(name = "locTop")),
			@AttributeOverride(name = "locLeft", column = @Column(name = "locLeft")),
			@AttributeOverride(name = "sizeHeight", column = @Column(name = "sizeHeight")),
			@AttributeOverride(name = "sizeWidth", column = @Column(name = "sizeWidth")),
			@AttributeOverride(name = "borderStyle", column = @Column(name = "BorderStyle")),
			@AttributeOverride(name = "style", column = @Column(name = "Style")) })
	public FormscratchId getId() {
		return this.id;
	}

	public void setId(FormscratchId id) {
		this.id = id;
	}

}
