package com.turborep.turbotracker.employee.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rxmaster generated by hbm2java
 */
@Entity
@Table(name = "rxMaster", catalog = "")
public class Rxmaster implements java.io.Serializable {

	private Integer rxMasterId;
	private Integer createdById;
	private Date createdOn;
	private Integer changedById;
	private Date changedOn;
	private Boolean inActive;
	private String name;
	private String searchName;
	private String firstName;
	private String middleInitial;
	private String phone1;
	private String phone2;
	private String phone3;
	private String fax;
	private boolean isCustomer;
	private boolean isVendor;
	private boolean isEmployee;
	private boolean isCategory1;
	private boolean isCategory2;
	private boolean isCategory3;
	private boolean isCategory4;
	private boolean isCategory5;
	private boolean isCategory6;
	private boolean isCategory7;
	private boolean isCategory8;
	private String note;
	private boolean isProspect;
	private String websight;

	public Rxmaster() {
	}

	public Rxmaster(String searchName, String firstName, boolean isCustomer,
			boolean isVendor, boolean isEmployee, boolean isCategory1,
			boolean isCategory2, boolean isCategory3, boolean isCategory4,
			boolean isCategory5, boolean isCategory6, boolean isProspect) {
		this.searchName = searchName;
		this.firstName = firstName;
		this.isCustomer = isCustomer;
		this.isVendor = isVendor;
		this.isEmployee = isEmployee;
		this.isCategory1 = isCategory1;
		this.isCategory2 = isCategory2;
		this.isCategory3 = isCategory3;
		this.isCategory4 = isCategory4;
		this.isCategory5 = isCategory5;
		this.isCategory6 = isCategory6;
		this.isProspect = isProspect;
	}

	public Rxmaster(Integer createdById, Date createdOn, Integer changedById,
			Date changedOn, Boolean inActive, String name, String searchName,
			String firstName, String middleInitial, String phone1,
			String phone2, String phone3, String fax, boolean isCustomer,
			boolean isVendor, boolean isEmployee, boolean isCategory1,
			boolean isCategory2, boolean isCategory3, boolean isCategory4,
			boolean isCategory5, boolean isCategory6, String note,
			boolean isProspect/*, String websight*/) {
		this.createdById = createdById;
		this.createdOn = createdOn;
		this.changedById = changedById;
		this.changedOn = changedOn;
		this.inActive = inActive;
		this.name = name;
		this.searchName = searchName;
		this.firstName = firstName;
		this.middleInitial = middleInitial;
		this.phone1 = phone1;
		this.phone2 = phone2;
		this.phone3 = phone3;
		this.fax = fax;
		this.isCustomer = isCustomer;
		this.isVendor = isVendor;
		this.isEmployee = isEmployee;
		this.isCategory1 = isCategory1;
		this.isCategory2 = isCategory2;
		this.isCategory3 = isCategory3;
		this.isCategory4 = isCategory4;
		this.isCategory5 = isCategory5;
		this.isCategory6 = isCategory6;
		this.note = note;
		this.isProspect = isProspect;
		//this.websight = websight;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "rxMasterID", unique = true, nullable = false)
	public Integer getRxMasterId() {
		return this.rxMasterId;
	}

	public void setRxMasterId(Integer rxMasterId) {
		this.rxMasterId = rxMasterId;
	}

	@Column(name = "CreatedByID")
	public Integer getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(Integer createdById) {
		this.createdById = createdById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 0)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "ChangedByID")
	public Integer getChangedById() {
		return this.changedById;
	}

	public void setChangedById(Integer changedById) {
		this.changedById = changedById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ChangedOn", length = 0)
	public Date getChangedOn() {
		return this.changedOn;
	}

	public void setChangedOn(Date changedOn) {
		this.changedOn = changedOn;
	}

	@Column(name = "InActive")
	public Boolean getInActive() {
		return this.inActive;
	}

	public void setInActive(Boolean inActive) {
		this.inActive = inActive;
	}

	@Column(name = "Name", length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SearchName", nullable = false, length = 10)
	public String getSearchName() {
		return this.searchName;
	}

	public void setSearchName(String searchName) {
		this.searchName = searchName;
	}

	@Column(name = "FirstName", nullable = false, length = 25)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "MiddleInitial", length = 1)
	public String getMiddleInitial() {
		return this.middleInitial;
	}

	public void setMiddleInitial(String middleInitial) {
		this.middleInitial = middleInitial;
	}

	@Column(name = "Phone1", length = 30)
	public String getPhone1() {
		return this.phone1;
	}

	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	@Column(name = "Phone2", length = 30)
	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	@Column(name = "Phone3", length = 30)
	public String getPhone3() {
		return this.phone3;
	}

	public void setPhone3(String phone3) {
		this.phone3 = phone3;
	}

	@Column(name = "Fax", length = 30)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "IsCustomer", nullable = false)
	public boolean isIsCustomer() {
		return this.isCustomer;
	}

	public void setIsCustomer(boolean isCustomer) {
		this.isCustomer = isCustomer;
	}

	@Column(name = "IsVendor", nullable = false)
	public boolean isIsVendor() {
		return this.isVendor;
	}

	public void setIsVendor(boolean isVendor) {
		this.isVendor = isVendor;
	}

	@Column(name = "IsEmployee", nullable = false)
	public boolean isIsEmployee() {
		return this.isEmployee;
	}

	public void setIsEmployee(boolean isEmployee) {
		this.isEmployee = isEmployee;
	}

	@Column(name = "IsCategory1", nullable = false)
	public boolean isIsCategory1() {
		return this.isCategory1;
	}

	public void setIsCategory1(boolean isCategory1) {
		this.isCategory1 = isCategory1;
	}

	@Column(name = "IsCategory2", nullable = false)
	public boolean isIsCategory2() {
		return this.isCategory2;
	}

	public void setIsCategory2(boolean isCategory2) {
		this.isCategory2 = isCategory2;
	}

	@Column(name = "IsCategory3", nullable = false)
	public boolean isIsCategory3() {
		return this.isCategory3;
	}

	public void setIsCategory3(boolean isCategory3) {
		this.isCategory3 = isCategory3;
	}

	@Column(name = "IsCategory4", nullable = false)
	public boolean isIsCategory4() {
		return this.isCategory4;
	}

	public void setIsCategory4(boolean isCategory4) {
		this.isCategory4 = isCategory4;
	}

	@Column(name = "IsCategory5", nullable = false)
	public boolean isIsCategory5() {
		return this.isCategory5;
	}

	public void setIsCategory5(boolean isCategory5) {
		this.isCategory5 = isCategory5;
	}

	@Column(name = "IsCategory6", nullable = false)
	public boolean isIsCategory6() {
		return this.isCategory6;
	}

	public void setIsCategory6(boolean isCategory6) {
		this.isCategory6 = isCategory6;
	}

	@Column(name = "Note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}
	
	@Column(name = "IsProspect", nullable = false)
	public boolean isIsProspect() {
		return this.isProspect;
	}

	public void setIsProspect(boolean isProspect) {
		this.isProspect = isProspect;
	}

	@Column(name = "Websight", length = 200)
	public String getWebsight() {
		return this.websight;
	}

	public void setWebsight(String websight) {
		this.websight = websight;
	}
	@Column(name = "IsCategory7", nullable = false)
	public boolean isIsCategory7() {
		return isCategory7;
	}

	public void setIsCategory7(boolean isCategory7) {
		this.isCategory7 = isCategory7;
	}
	@Column(name = "IsCategory8", nullable = false)
	public boolean isIsCategory8() {
		return isCategory8;
	}

	public void setIsCategory8(boolean isCategory8) {
		this.isCategory8 = isCategory8;
	}

}
