package com.turborep.turbotracker.employee.dao;

// Generated Jul 9, 2014 5:57:18 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Rxmastercategory2 generated by hbm2java
 */
@Entity
@Table(name = "rxMasterCategory2", catalog = "BacheCompany")
public class Rxmastercategory2 implements java.io.Serializable {

	private int rxMasterCategory2id;
	private Integer cuAssignmentId0;
	private Integer cuAssignmentId1;
	private Integer cuAssignmentId2;
	private Integer cuAssignmentId3;
	private Integer cuAssignmentId4;
	private String cuAssignmentName0;
	private String cuAssignmentName1;
	private String cuAssignmentName2;
	private String cuAssignmentName3;
	private String cuAssignmentName4;
	public Rxmastercategory2() {
	}

	public Rxmastercategory2(int rxMasterCategory2id) {
		this.rxMasterCategory2id = rxMasterCategory2id;
	}

	public Rxmastercategory2(int rxMasterCategory2id, Integer cuAssignmentId0,
			Integer cuAssignmentId1, Integer cuAssignmentId2,
			Integer cuAssignmentId3, Integer cuAssignmentId4) {
		this.rxMasterCategory2id = rxMasterCategory2id;
		this.cuAssignmentId0 = cuAssignmentId0;
		this.cuAssignmentId1 = cuAssignmentId1;
		this.cuAssignmentId2 = cuAssignmentId2;
		this.cuAssignmentId3 = cuAssignmentId3;
		this.cuAssignmentId4 = cuAssignmentId4;
	}

	@Id
	@Column(name = "rxMasterCategory2ID", unique = true, nullable = false)
	public int getRxMasterCategory2id() {
		return this.rxMasterCategory2id;
	}

	public void setRxMasterCategory2id(int rxMasterCategory2id) {
		this.rxMasterCategory2id = rxMasterCategory2id;
	}

	@Column(name = "cuAssignmentID0")
	public Integer getCuAssignmentId0() {
		return this.cuAssignmentId0;
	}

	public void setCuAssignmentId0(Integer cuAssignmentId0) {
		this.cuAssignmentId0 = cuAssignmentId0;
	}

	@Column(name = "cuAssignmentID1")
	public Integer getCuAssignmentId1() {
		return this.cuAssignmentId1;
	}

	public void setCuAssignmentId1(Integer cuAssignmentId1) {
		this.cuAssignmentId1 = cuAssignmentId1;
	}

	@Column(name = "cuAssignmentID2")
	public Integer getCuAssignmentId2() {
		return this.cuAssignmentId2;
	}

	public void setCuAssignmentId2(Integer cuAssignmentId2) {
		this.cuAssignmentId2 = cuAssignmentId2;
	}

	@Column(name = "cuAssignmentID3")
	public Integer getCuAssignmentId3() {
		return this.cuAssignmentId3;
	}

	public void setCuAssignmentId3(Integer cuAssignmentId3) {
		this.cuAssignmentId3 = cuAssignmentId3;
	}

	@Column(name = "cuAssignmentID4")
	public Integer getCuAssignmentId4() {
		return this.cuAssignmentId4;
	}

	public void setCuAssignmentId4(Integer cuAssignmentId4) {
		this.cuAssignmentId4 = cuAssignmentId4;
	}
	@Transient
	public String getCuAssignmentName0() {
		return cuAssignmentName0;
	}

	public void setCuAssignmentName0(String cuAssignmentName0) {
		this.cuAssignmentName0 = cuAssignmentName0;
	}
	@Transient
	public String getCuAssignmentName1() {
		return cuAssignmentName1;
	}

	public void setCuAssignmentName1(String cuAssignmentName1) {
		this.cuAssignmentName1 = cuAssignmentName1;
	}
	@Transient
	public String getCuAssignmentName2() {
		return cuAssignmentName2;
	}

	public void setCuAssignmentName2(String cuAssignmentName2) {
		this.cuAssignmentName2 = cuAssignmentName2;
	}
	@Transient
	public String getCuAssignmentName3() {
		return cuAssignmentName3;
	}

	public void setCuAssignmentName3(String cuAssignmentName3) {
		this.cuAssignmentName3 = cuAssignmentName3;
	}
	@Transient
	public String getCuAssignmentName4() {
		return cuAssignmentName4;
	}

	public void setCuAssignmentName4(String cuAssignmentName4) {
		this.cuAssignmentName4 = cuAssignmentName4;
	}

}
