package com.turborep.turbotracker.user.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tsaccessmodule generated by hbm2java
 */
@Entity
@Table(name = "tsAccessProcedure", catalog = "")
public class TsAccessProcedure implements java.io.Serializable {

	private Integer accessProcedureID;
	private Integer accessModuleID;
	private String procedureName;
	private String procedureInfo;

	public TsAccessProcedure() {
	}

	public TsAccessProcedure(Integer theAccessProcedureID, Integer theAccessModuleID, String theProcedureName, String theProcedureInfo) {
	     this.accessProcedureID = theAccessProcedureID;
	     this.accessModuleID = theAccessModuleID;
	     this.procedureName = theProcedureName;
	     this.procedureInfo = theProcedureInfo;
	}


	@Id
	@Column(name = "AccessProcedureID", unique = true, nullable = false)
	public Integer getAccessProcedureID() {
		return accessProcedureID;
	}

	public void setAccessProcedureID(Integer accessProcedureID) {
		this.accessProcedureID = accessProcedureID;
	}

	@Column(name = "AccessModuleID")
	public Integer getAccessModuleID() {
		return accessModuleID;
	}

	public void setAccessModuleID(Integer accessModuleID) {
		this.accessModuleID = accessModuleID;
	}

	@Column(name = "ProcedureName", length = 60)
	public String getProcedureName() {
		return procedureName;
	}

	public void setProcedureName(String procedureName) {
		this.procedureName = procedureName;
	}

	@Column(name = "ProcedureInfo", length = 350)
	public String getProcedureInfo() {
		return procedureInfo;
	}

	public void setProcedureInfo(String procedureInfo) {
		this.procedureInfo = procedureInfo;
	}
}