package com.turborep.turbotracker.user.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tsaccessmodule generated by hbm2java
 */
@Entity
@Table(name = "tsAccessModule", catalog = "")
public class TsAccessModule implements java.io.Serializable {

	private Integer accessModuleID;
	private String moduleName;

	public TsAccessModule() {
	}

	public TsAccessModule(String moduleName) {
		this.setModuleName(moduleName);
	}
	
	public TsAccessModule(Integer accessModuleID,String moduleName) {
		this.accessModuleID=accessModuleID;
		this.moduleName=moduleName;
	}

	@Id
	@Column(name = "AccessModuleID", unique = true, nullable = false)
	public Integer getAccessModuleID() {
		return accessModuleID;
	}

	public void setAccessModuleID(Integer accessModuleID) {
		this.accessModuleID = accessModuleID;
	}

	@Column(name = "ModuleName", length = 50)
	public String getModuleName() {
		return moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}
}