package com.turborep.turbotracker.user.dao;

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Blob;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * TsUserSetting generated by hbm2java
 */
@Entity
@Table(name="tsUserSetting",catalog="")
public class TsUserSetting {
	
	private Integer itsCompanyId;
	private Integer itsLoginId;
	private byte itsQuote;
	private byte itsQuickQuote;
	private byte itsInvoices;
	private byte itsPurchaseOrders;
	private byte itsHeaderQuote;
	private byte itsHeaderQuickQuote;
	private byte itsHeaderInvoices;
	private byte itsHeaderPurchaseOrders;
	private byte itsTermsQuote;
	private byte itsTermsQuickQuote;
	private byte itsTermsInvoices;
	private byte itsTermsPurchaseOrders;
	private String itsHeaderText;
	private String itsTerms;
	private byte itsBillTo;
	private String billToDescription;
	private String billToAddress1;
	private String billToAddress2;
	private String billToCity;
	private String billToState;
	private String billToZip;
	private Blob itsCompanyLogo;
	private String quotesFooter;
	private String soFooterText;
	private byte itslogYN;
	private byte itsmailYN;
	
	private String remitToDescription;
	private String remitToAddress1;
	private String remitToAddress2;
	private String remitToCity;
	private String remitToState;
	private String remitToZip;
	private Integer vendorProductID;
	private Integer vendorProductDeptID;
	@Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="CompanyID", unique=true, nullable=false)
    public Integer getCompanyId() {
        return this.itsCompanyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.itsCompanyId = companyId;
    }
    
    @Column(name="LoginID")
	public Integer getLoginId() {
		return this.itsLoginId;
	}
	
	public void setLoginId(Integer loginId) {
	    this.itsLoginId = loginId;
	}
	
	@Column(name="Quote", nullable=false)
	public byte getQuote() {
	    return this.itsQuote;
	}
	
	public void setQuote(byte quote) {
		this.itsQuote = quote;
	}
	
	@Column(name="QuickQuote", nullable=false)
	public byte getQuickQuote() {
	    return this.itsQuickQuote;
	}
	
	public void setQuickQuote(byte quickQuote) {
		this.itsQuickQuote = quickQuote;
	}
	
	@Column(name="Invoices", nullable=false)
	public byte getInvoices() {
	    return this.itsInvoices;
	}
	
	public void setInvoices(byte invoices) {
		this.itsInvoices = invoices;
	}
	
	@Column(name="PurchaseOrders", nullable=false)
	public byte getPurchaseOrders() {
	    return this.itsPurchaseOrders;
	}
	
	public void setPurchaseOrders(byte purchaseOrders) {
		this.itsPurchaseOrders = purchaseOrders;
	}
	
	@Column(name="HeaderText")
    public String getHeaderText() {
        return this.itsHeaderText;
    }
    
    public void setHeaderText(String headerText) {
        this.itsHeaderText = headerText;
    }
    
    @Column(name="quotesFooter")
    public String getQuotesFooter() {
        return this.quotesFooter;
    }
    
    public void setQuotesFooter(String quotesFooter) {
        this.quotesFooter = quotesFooter;
    }
    
    @Column(name="Terms")
    public String getTerms() {
        return this.itsTerms;
    }
    
    public void setTerms(String terms) {
        this.itsTerms = terms;
    }

    @Column(name="headerQuote", nullable=false)
	public byte getHeaderQuote() {
		return itsHeaderQuote;
	}

	public void setHeaderQuote(byte headerQuote) {
		this.itsHeaderQuote = headerQuote;
	}

	@Column(name="headerQuickQuote", nullable=false)
	public byte getHeaderQuickQuote() {
		return itsHeaderQuickQuote;
	}

	public void setHeaderQuickQuote(byte headerQuickQuote) {
		this.itsHeaderQuickQuote = headerQuickQuote;
	}

	@Column(name="headerInvoices", nullable=false)
	public byte getHeaderInvoices() {
		return itsHeaderInvoices;
	}

	public void setHeaderInvoices(byte headerInvoices) {
		this.itsHeaderInvoices = headerInvoices;
	}

	@Column(name="headerPurchaseOrders", nullable=false)
	public byte getHeaderPurchaseOrders() {
		return itsHeaderPurchaseOrders;
	}

	public void setHeaderPurchaseOrders(byte headerPurchaseOrders) {
		this.itsHeaderPurchaseOrders = headerPurchaseOrders;
	}

	@Column(name="termsQuote", nullable=false)
	public byte getTermsQuote() {
		return itsTermsQuote;
	}

	public void setTermsQuote(byte termsQuote) {
		this.itsTermsQuote = termsQuote;
	}

	@Column(name="termsQuickQuote", nullable=false)
	public byte getTermsQuickQuote() {
		return itsTermsQuickQuote;
	}

	public void setTermsQuickQuote(byte termsQuickQuote) {
		this.itsTermsQuickQuote = termsQuickQuote;
	}

	@Column(name="termsInvoices", nullable=false)
	public byte getTermsInvoices() {
		return itsTermsInvoices;
	}

	public void setTermsInvoices(byte termsInvoices) {
		this.itsTermsInvoices = termsInvoices;
	}

	@Column(name="termsPurchaseOrders", nullable=false)
	public byte getTermsPurchaseOrders() {
		return itsTermsPurchaseOrders;
	}

	public void setTermsPurchaseOrders(byte termsPurchaseOrders) {
		this.itsTermsPurchaseOrders = termsPurchaseOrders;
	}

	@Column(name="IsBillTo", nullable=false)
	public byte getItsBillTo() {
		return itsBillTo;
	}

	public void setItsBillTo(byte itsBillTo) {
		this.itsBillTo = itsBillTo;
	}

	@Column(name = "billToDescription", length = 45)
	public String getBillToDescription() {
		return billToDescription;
	}

	public void setBillToDescription(String billToDescription) {
		this.billToDescription = billToDescription;
	}

	@Column(name = "billToAddress1", length = 45)
	public String getBillToAddress1() {
		return billToAddress1;
	}

	public void setBillToAddress1(String itsBillToAddress1) {
		this.billToAddress1 = itsBillToAddress1;
	}

	@Column(name = "billToAddress2", length = 45)
	public String getBillToAddress2() {
		return billToAddress2;
	}

	public void setBillToAddress2(String itsBillToAddress2) {
		this.billToAddress2 = itsBillToAddress2;
	}

	@Column(name = "billToCity", length = 45)
	public String getBillToCity() {
		return billToCity;
	}

	public void setBillToCity(String itsBillToCity) {
		this.billToCity = itsBillToCity;
	}

	@Column(name = "billToState", length = 45)
	public String getBillToState() {
		return billToState;
	}

	public void setBillToState(String itsBillToState) {
		this.billToState = itsBillToState;
	}

	@Column(name = "billToZip", length = 45)
	public String getBillToZip() {
		return billToZip;
	}

	public void setBillToZip(String itsBillToZip) {
		this.billToZip = itsBillToZip;
	}

	@Column(name="companyLogo", columnDefinition = "LONGBLOB")
	public Blob getCompanyLogo() {
		return itsCompanyLogo;
	}

	public void setCompanyLogo(Blob itsCompanyLogo) {
		this.itsCompanyLogo = itsCompanyLogo;
	}
	@Column(name="IsLogYN", nullable=false)
	public byte getItslogYN() {
		return itslogYN;
	}

	public void setItslogYN(byte itslogYN) {
		this.itslogYN = itslogYN;
	}
	@Column(name="IsMailYN", nullable=false)
	public byte getItsmailYN() {
		return itsmailYN;
	}

	public void setItsmailYN(byte itsmailYN) {
		this.itsmailYN = itsmailYN;
	}

	@Column(name = "remitToDescription", length = 45)
	public String getRemitToDescription() {
		return remitToDescription;
	}

	public void setRemitToDescription(String remitToDescription) {
		this.remitToDescription = remitToDescription;
	}

	@Column(name = "remitToAddress1", length = 45)
	public String getRemitToAddress1() {
		return remitToAddress1;
	}

	public void setRemitToAddress1(String remitToAddress1) {
		this.remitToAddress1 = remitToAddress1;
	}
	@Column(name = "remitToAddress2", length = 45)
	public String getRemitToAddress2() {
		return remitToAddress2;
	}

	public void setRemitToAddress2(String remitToAddress2) {
		this.remitToAddress2 = remitToAddress2;
	}

	@Column(name = "remitToCity", length = 45)
	public String getRemitToCity() {
		return remitToCity;
	}

	public void setRemitToCity(String remitToCity) {
		this.remitToCity = remitToCity;
	}

	@Column(name = "remitToState", length = 10)
	public String getRemitToState() {
		return remitToState;
	}

	public void setRemitToState(String remitToState) {
		this.remitToState = remitToState;
	}

	@Column(name = "remitToZip", length = 11)
	public String getRemitToZip() {
		return remitToZip;
	}

	public void setRemitToZip(String remitToZip) {
		this.remitToZip = remitToZip;
	}
	
	@Column(name = "vendorProductID")
	public Integer getVendorProductID() {
		return vendorProductID;
	}

	public void setVendorProductID(Integer vendorProductID) {
		this.vendorProductID = vendorProductID;
	}
	
	@Column(name = "vendorProductDeptID")
	public Integer getVendorProductDeptID() {
		return vendorProductDeptID;
	}

	public void setVendorProductDeptID(Integer vendorProductDeptID) {
		this.vendorProductDeptID = vendorProductDeptID;
	}

	@Column(name="SofooterText")
	public String getSoFooterText() {
		return soFooterText;
	}

	public void setSoFooterText(String soFooterText) {
		this.soFooterText = soFooterText;
	}
	
	
}
