package com.turborep.turbotracker.user.dao;
// Generated May 16, 2012 6:04:11 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TsUserGroupLink generated by hbm2java
 */
@Entity
@Table(name="tsUserGroupLink",catalog="")
public class TsUserGroupLink  implements java.io.Serializable {


	private Integer userGroupLinkId;
	private Integer userLoginID;
	private Integer userGroupID;

	public TsUserGroupLink() {
	}

	public TsUserGroupLink(Integer tsUserLogin, Integer tsUserGroup) {
		this.userLoginID = tsUserLogin;
		this.userGroupID = tsUserGroup;
	}
   
	@Id @GeneratedValue(strategy=IDENTITY)
	@Column(name="UserGroupLinkID", unique=true, nullable=false)
	public Integer getUserGroupLinkId() {
		return this.userGroupLinkId;
	}
    
	public void setUserGroupLinkId(Integer userGroupLinkId) {
		this.userGroupLinkId = userGroupLinkId;
	}

	@Column(name="UserLoginID")
	public Integer getUserLoginID() {
		return this.userLoginID;
	}
    
	public void setUserLoginID(Integer userLoginID) {
		this.userLoginID = userLoginID;
	}

	@Column(name="UserGroupID")
	public Integer getUserGroupID() {
		return this.userGroupID;
	}
    
	public void setUserGroupID(Integer userGroupID) {
		this.userGroupID = userGroupID;
	}
}


