package com.turborep.turbotracker.user.dao;
// Generated May 16, 2012 6:04:11 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TsUserGroup generated by hbm2java
 */
@Entity
@Table(name="tsUserGroup",catalog="")
public class TsUserGroup  implements java.io.Serializable {


     private Integer userGroupId;
     private String groupName;

    public TsUserGroup() {
    }

    public TsUserGroup(String groupName, Set tsUserGroupLinks, Set tsMessages) {
       this.groupName = groupName;
    }
   
    public TsUserGroup(int userGroupId, String groupName) {
		// TODO Auto-generated constructor stub
    	this.userGroupId=userGroupId;
    	this.groupName=groupName;
	}

	@Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="UserGroupID", unique=true, nullable=false)
    public Integer getUserGroupId() {
        return this.userGroupId;
    }
    
    public void setUserGroupId(Integer userGroupId) {
        this.userGroupId = userGroupId;
    }

    
    @Column(name="GroupName", length=15)
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
}


