package com.turborep.turbotracker.user.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Webaccount generated by hbm2java
 */
@Entity
@Table(name = "webaccount", catalog = "")
public class Webaccount implements java.io.Serializable {

	private Integer webAccountId;
	private String loginName;
	private String loginPassword;
	private String companyName;
	private Boolean approved;
	private Integer rxMasterId;

	public Webaccount() {
	}

	public Webaccount(String loginName, String loginPassword,
			String companyName, Boolean approved, Integer rxMasterId) {
		this.loginName = loginName;
		this.loginPassword = loginPassword;
		this.companyName = companyName;
		this.approved = approved;
		this.rxMasterId = rxMasterId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "WebAccountID", unique = true, nullable = false)
	public Integer getWebAccountId() {
		return this.webAccountId;
	}

	public void setWebAccountId(Integer webAccountId) {
		this.webAccountId = webAccountId;
	}

	@Column(name = "LoginName", length = 15)
	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	@Column(name = "LoginPassword", length = 50)
	public String getLoginPassword() {
		return this.loginPassword;
	}

	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword;
	}

	@Column(name = "CompanyName", length = 40)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "Approved")
	public Boolean getApproved() {
		return this.approved;
	}

	public void setApproved(Boolean approved) {
		this.approved = approved;
	}

	@Column(name = "rxMasterID")
	public Integer getRxMasterId() {
		return this.rxMasterId;
	}

	public void setRxMasterId(Integer rxMasterId) {
		this.rxMasterId = rxMasterId;
	}

}
