package com.turborep.turbotracker.customer.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ConvertCustomers generated by hbm2java
 */
@Entity
@Table(name = "convert_customers", catalog = "")
public class ConvertCustomers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ConvertCustomersId id;

	public ConvertCustomers() {
	}

	public ConvertCustomers(ConvertCustomersId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "name", column = @Column(name = "Name")),
			@AttributeOverride(name = "address1", column = @Column(name = "Address1")),
			@AttributeOverride(name = "address2", column = @Column(name = "Address2")),
			@AttributeOverride(name = "cityStateZip", column = @Column(name = "CityStateZip")),
			@AttributeOverride(name = "city", column = @Column(name = "City")),
			@AttributeOverride(name = "state", column = @Column(name = "State")),
			@AttributeOverride(name = "zip", column = @Column(name = "Zip")),
			@AttributeOverride(name = "phone", column = @Column(name = "Phone")),
			@AttributeOverride(name = "fax", column = @Column(name = "Fax")),
			@AttributeOverride(name = "attention", column = @Column(name = "Attention")) })
	public ConvertCustomersId getId() {
		return this.id;
	}

	public void setId(ConvertCustomersId id) {
		this.id = id;
	}

}
