package com.turborep.turbotracker.customer.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Cuinvoice generated by hbm2java
 */
@Entity
@Table(name = "cuInvoice", catalog = "")
public class Cuinvoice implements java.io.Serializable {

	private Integer cuInvoiceId;
	private Integer createdById;
	private Date createdOn;
	private Integer changedById;
	private Date changedOn;
	private Integer transactionStatus;
	private Boolean applied;
	private Integer joReleaseDetailId;
	private Integer cuSoid;
	private Integer rxCustomerId;
	private Integer rxBillToId;
	private Integer rxBillToAddressId;
	private Integer rxShipToId;
	private Integer rxShipToAddressId;
	private Integer veShipViaId;
	private Integer prFromWarehouseId;
	private Integer prToWarehouseId;
	private Integer cuTermsId;
	private Integer rxContactId;
	private byte shipToMode;
	private Integer coTaxTerritoryId;
	private String invoiceNumber;
	private String customerPonumber;
	private String quickJobName;
	private Date invoiceDate;
	private Date shipDate;
	private Date dueDate;
	private Date printDate;
	private BigDecimal invoiceAmount;
	private BigDecimal appliedAmount;
	private BigDecimal taxAmount;
	private BigDecimal freight;
	private BigDecimal costTotal;
	private BigDecimal subtotal;
	private BigDecimal taxTotal;
	private BigDecimal taxRate;
	private Integer cuAssignmentId0;
	private Integer cuAssignmentId1;
	private Integer cuAssignmentId2;
	private Integer cuAssignmentId3;
	private Integer cuAssignmentId4;
	private String trackingNumber;
	private Boolean surtaxOverrideCap;
	private BigDecimal surtaxTotal;
	private BigDecimal surtaxRate;
	private BigDecimal surtaxAmount;
	private BigDecimal singleItemTaxAmount;
	private Integer coDivisionId;
	private BigDecimal freightCost;
	private byte doNotMail;
	private String jobname;
	private BigDecimal discountApplied;
	private Integer creditmemo;
	private Integer iscredit;
	private String description;
	private String note;
	private Integer joMasterID;
	private Integer joReleaseType;
	private BigDecimal discountAmt;
	
	private Integer memoStatus;
	private String jobnoDescription;
	private Integer customerId;
	
	private String cuAssignmentName0;
	private String cuAssignmentName1;
	private String cuAssignmentName2;
	private String cuAssignmentName3;
	private String cuAssignmentName4;
	private String cotaxdescription;
	private boolean cIopenStatus=true;
	private String reason;
	private String chkNo;
	private Date datePaid;
	private String releaseType;
	
	private BigDecimal whseCostTotal;
	private BigDecimal marginCost;
	
	
	private String customerName;
	private Integer coAccountID;
	private Integer taxAdjustmentStatus;
	
	private String userName;
	private byte taxfreight;
	private BigDecimal taxSum;
	private Date emailDate;
	private String sentEmailDate;
	private Date statementEmailDate;
	private String sentstatementEmailDate;
	private Integer emailCheckBox;

	private String emailList;
	private Integer emailStatus;
	private Integer statementEmailStatus;
	private BigDecimal taxableSales;
	private BigDecimal nonTaxableSales;
	
	public Cuinvoice() {
		this.surtaxOverrideCap = false;
	}

	public Cuinvoice(byte shipToMode, BigDecimal invoiceAmount,
			BigDecimal appliedAmount, BigDecimal taxAmount, byte doNotMail) {
		this.shipToMode = shipToMode;
		this.setDoNotMail(doNotMail);
		this.invoiceAmount = invoiceAmount;
		this.appliedAmount = appliedAmount;
		this.taxAmount = taxAmount;
	}

	public Cuinvoice(Integer createdById, Date createdOn, Integer changedById,
			Date changedOn, Integer transactionStatus, Boolean applied,
			Integer joReleaseDetailId, Integer cuSoid, Integer rxCustomerId,
			Integer rxBillToId, Integer rxBillToAddressId, Integer rxShipToId,
			Integer rxShipToAddressId, Integer veShipViaId,
			Integer prFromWarehouseId, Integer prToWarehouseId,
			Integer cuTermsId, byte shipToMode, Integer coTaxTerritoryId,
			String invoiceNumber, String customerPonumber, String quickJobName,
			Date invoiceDate, Date shipDate, Date dueDate, Date printDate,
			BigDecimal invoiceAmount, BigDecimal appliedAmount,
			BigDecimal taxAmount, BigDecimal freight, BigDecimal costTotal,
			BigDecimal subtotal, BigDecimal taxTotal, BigDecimal taxRate,
			Integer cuAssignmentId0, Integer cuAssignmentId1,
			Integer cuAssignmentId2, Integer cuAssignmentId3,
			Integer cuAssignmentId4, String trackingNumber,
			Boolean surtaxOverrideCap, BigDecimal surtaxTotal,
			BigDecimal surtaxRate, BigDecimal surtaxAmount,
			BigDecimal singleItemTaxAmount, Integer coDivisionId, byte doNotMail,
			BigDecimal freightCost) {
		this.createdById = createdById;
		this.createdOn = createdOn;
		this.changedById = changedById;
		this.changedOn = changedOn;
		this.transactionStatus = transactionStatus;
		this.applied = applied;
		this.joReleaseDetailId = joReleaseDetailId;
		this.cuSoid = cuSoid;
		this.rxCustomerId = rxCustomerId;
		this.rxBillToId = rxBillToId;
		this.rxBillToAddressId = rxBillToAddressId;
		this.rxShipToId = rxShipToId;
		this.rxShipToAddressId = rxShipToAddressId;
		this.veShipViaId = veShipViaId;
		this.prFromWarehouseId = prFromWarehouseId;
		this.prToWarehouseId = prToWarehouseId;
		this.cuTermsId = cuTermsId;
		this.shipToMode = shipToMode;
		this.coTaxTerritoryId = coTaxTerritoryId;
		this.invoiceNumber = invoiceNumber;
		this.customerPonumber = customerPonumber;
		this.quickJobName = quickJobName;
		this.invoiceDate = invoiceDate;
		this.shipDate = shipDate;
		this.dueDate = dueDate;
		this.printDate = printDate;
		this.invoiceAmount = invoiceAmount;
		this.appliedAmount = appliedAmount;
		this.taxAmount = taxAmount;
		this.freight = freight;
		this.costTotal = costTotal;
		this.subtotal = subtotal;
		this.taxTotal = taxTotal;
		this.taxRate = taxRate;
		this.cuAssignmentId0 = cuAssignmentId0;
		this.cuAssignmentId1 = cuAssignmentId1;
		this.cuAssignmentId2 = cuAssignmentId2;
		this.cuAssignmentId3 = cuAssignmentId3;
		this.cuAssignmentId4 = cuAssignmentId4;
		this.trackingNumber = trackingNumber;
		this.surtaxOverrideCap = surtaxOverrideCap;
		this.surtaxTotal = surtaxTotal;
		this.surtaxRate = surtaxRate;
		this.surtaxAmount = surtaxAmount;
		this.singleItemTaxAmount = singleItemTaxAmount;
		this.coDivisionId = coDivisionId;
		this.freightCost = freightCost;
		this.shipToMode = shipToMode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cuInvoiceID", unique = true, nullable = false)
	public Integer getCuInvoiceId() {
		return this.cuInvoiceId;
	}

	public void setCuInvoiceId(Integer cuInvoiceId) {
		this.cuInvoiceId = cuInvoiceId;
	}

	@Column(name = "CreatedByID")
	public Integer getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(Integer createdById) {
		this.createdById = createdById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 0)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "ChangedByID")
	public Integer getChangedById() {
		return this.changedById;
	}

	public void setChangedById(Integer changedById) {
		this.changedById = changedById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ChangedOn", length = 0)
	public Date getChangedOn() {
		return this.changedOn;
	}

	public void setChangedOn(Date changedOn) {
		this.changedOn = changedOn;
	}

	@Column(name = "TransactionStatus")
	public Integer getTransactionStatus() {
		return this.transactionStatus;
	}

	public void setTransactionStatus(Integer transactionStatus) {
		this.transactionStatus = transactionStatus;
	}

	@Column(name = "Applied")
	public Boolean getApplied() {
		return this.applied;
	}

	public void setApplied(Boolean applied) {
		this.applied = applied;
	}

	@Column(name = "joReleaseDetailID")
	public Integer getJoReleaseDetailId() {
		return this.joReleaseDetailId;
	}

	public void setJoReleaseDetailId(Integer joReleaseDetailId) {
		this.joReleaseDetailId = joReleaseDetailId;
	}

	@Column(name = "cuSOID")
	public Integer getCuSoid() {
		return this.cuSoid;
	}

	public void setCuSoid(Integer cuSoid) {
		this.cuSoid = cuSoid;
	}

	@Column(name = "rxCustomerID")
	public Integer getRxCustomerId() {
		return this.rxCustomerId;
	}

	public void setRxCustomerId(Integer rxCustomerId) {
		this.rxCustomerId = rxCustomerId;
	}

	@Column(name = "rxBillToID")
	public Integer getRxBillToId() {
		return this.rxBillToId;
	}

	public void setRxBillToId(Integer rxBillToId) {
		this.rxBillToId = rxBillToId;
	}

	@Column(name = "rxBillToAddressID")
	public Integer getRxBillToAddressId() {
		return this.rxBillToAddressId;
	}

	public void setRxBillToAddressId(Integer rxBillToAddressId) {
		this.rxBillToAddressId = rxBillToAddressId;
	}

	@Column(name = "rxShipToID")
	public Integer getRxShipToId() {
		return this.rxShipToId;
	}

	public void setRxShipToId(Integer rxShipToId) {
		this.rxShipToId = rxShipToId;
	}

	@Column(name = "rxShipToAddressID")
	public Integer getRxShipToAddressId() {
		return this.rxShipToAddressId;
	}

	public void setRxShipToAddressId(Integer rxShipToAddressId) {
		this.rxShipToAddressId = rxShipToAddressId;
	}

	@Column(name = "veShipViaID")
	public Integer getVeShipViaId() {
		return this.veShipViaId;
	}

	public void setVeShipViaId(Integer veShipViaId) {
		this.veShipViaId = veShipViaId;
	}

	@Column(name = "prFromWarehouseID")
	public Integer getPrFromWarehouseId() {
		return this.prFromWarehouseId;
	}

	public void setPrFromWarehouseId(Integer prFromWarehouseId) {
		this.prFromWarehouseId = prFromWarehouseId;
	}

	@Column(name = "prToWarehouseID")
	public Integer getPrToWarehouseId() {
		return this.prToWarehouseId;
	}

	public void setPrToWarehouseId(Integer prToWarehouseId) {
		this.prToWarehouseId = prToWarehouseId;
	}

	@Column(name = "cuTermsID")
	public Integer getCuTermsId() {
		return this.cuTermsId;
	}

	public void setCuTermsId(Integer cuTermsId) {
		this.cuTermsId = cuTermsId;
	}

	@Column(name = "ShipToMode", nullable = false)
	public byte getShipToMode() {
		return this.shipToMode;
	}

	public void setShipToMode(byte shipToMode) {
		this.shipToMode = shipToMode;
	}

	@Column(name = "coTaxTerritoryID")
	public Integer getCoTaxTerritoryId() {
		return this.coTaxTerritoryId;
	}

	public void setCoTaxTerritoryId(Integer coTaxTerritoryId) {
		this.coTaxTerritoryId = coTaxTerritoryId;
	}

	@Column(name = "InvoiceNumber", length = 20)
	public String getInvoiceNumber() {
		return this.invoiceNumber;
	}

	public void setInvoiceNumber(String invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	@Column(name = "CustomerPONumber", length = 20)
	public String getCustomerPonumber() {
		return this.customerPonumber;
	}

	public void setCustomerPonumber(String customerPonumber) {
		this.customerPonumber = customerPonumber;
	}

	@Column(name = "QuickJobName", length = 40)
	public String getQuickJobName() {
		return this.quickJobName;
	}

	public void setQuickJobName(String quickJobName) {
		this.quickJobName = quickJobName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InvoiceDate", length = 0)
	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ShipDate", length = 0)
	public Date getShipDate() {
		return this.shipDate;
	}

	public void setShipDate(Date shipDate) {
		this.shipDate = shipDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DueDate", length = 0)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PrintDate", length = 0)
	public Date getPrintDate() {
		return this.printDate;
	}

	public void setPrintDate(Date printDate) {
		this.printDate = printDate;
	}

	@Column(name = "InvoiceAmount", nullable = false, scale = 4)
	public BigDecimal getInvoiceAmount() {
		return this.invoiceAmount;
	}

	public void setInvoiceAmount(BigDecimal invoiceAmount) {
		this.invoiceAmount = invoiceAmount;
	}

	@Column(name = "AppliedAmount", nullable = false, scale = 4)
	public BigDecimal getAppliedAmount() {
		return this.appliedAmount;
	}

	public void setAppliedAmount(BigDecimal appliedAmount) {
		this.appliedAmount = appliedAmount;
	}

	@Column(name = "TaxAmount", nullable = false, scale = 4)
	public BigDecimal getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(BigDecimal taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Column(name = "Freight", scale = 4)
	public BigDecimal getFreight() {
		return this.freight;
	}

	public void setFreight(BigDecimal freight) {
		this.freight = freight;
	}

	@Column(name = "CostTotal", scale = 4)
	public BigDecimal getCostTotal() {
		return this.costTotal;
	}

	public void setCostTotal(BigDecimal costTotal) {
		this.costTotal = costTotal;
	}

	@Column(name = "Subtotal", scale = 4)
	public BigDecimal getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(BigDecimal subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "TaxTotal", scale = 4)
	public BigDecimal getTaxTotal() {
		return this.taxTotal;
	}

	public void setTaxTotal(BigDecimal taxTotal) {
		this.taxTotal = taxTotal;
	}

	@Column(name = "TaxRate", scale = 4)
	public BigDecimal getTaxRate() {
		return this.taxRate;
	}

	public void setTaxRate(BigDecimal taxRate) {
		this.taxRate = taxRate;
	}

	@Column(name = "cuAssignmentID0")
	public Integer getCuAssignmentId0() {
		return this.cuAssignmentId0;
	}

	public void setCuAssignmentId0(Integer cuAssignmentId0) {
		this.cuAssignmentId0 = cuAssignmentId0;
	}

	@Column(name = "cuAssignmentID1")
	public Integer getCuAssignmentId1() {
		return this.cuAssignmentId1;
	}

	public void setCuAssignmentId1(Integer cuAssignmentId1) {
		this.cuAssignmentId1 = cuAssignmentId1;
	}

	@Column(name = "cuAssignmentID2")
	public Integer getCuAssignmentId2() {
		return this.cuAssignmentId2;
	}

	public void setCuAssignmentId2(Integer cuAssignmentId2) {
		this.cuAssignmentId2 = cuAssignmentId2;
	}

	@Column(name = "cuAssignmentID3")
	public Integer getCuAssignmentId3() {
		return this.cuAssignmentId3;
	}

	public void setCuAssignmentId3(Integer cuAssignmentId3) {
		this.cuAssignmentId3 = cuAssignmentId3;
	}

	@Column(name = "cuAssignmentID4")
	public Integer getCuAssignmentId4() {
		return this.cuAssignmentId4;
	}

	public void setCuAssignmentId4(Integer cuAssignmentId4) {
		this.cuAssignmentId4 = cuAssignmentId4;
	}

	@Column(name = "TrackingNumber", length = 30)
	public String getTrackingNumber() {
		return this.trackingNumber;
	}

	public void setTrackingNumber(String trackingNumber) {
		this.trackingNumber = trackingNumber;
	}

	@Column(name = "SurtaxOverrideCap")
	public Boolean getSurtaxOverrideCap() {
		return this.surtaxOverrideCap;
	}

	public void setSurtaxOverrideCap(Boolean surtaxOverrideCap) {
		this.surtaxOverrideCap = surtaxOverrideCap;
	}

	@Column(name = "SurtaxTotal", scale = 4)
	public BigDecimal getSurtaxTotal() {
		return this.surtaxTotal;
	}

	public void setSurtaxTotal(BigDecimal surtaxTotal) {
		this.surtaxTotal = surtaxTotal;
	}

	@Column(name = "SurtaxRate", scale = 4)
	public BigDecimal getSurtaxRate() {
		return this.surtaxRate;
	}

	public void setSurtaxRate(BigDecimal surtaxRate) {
		this.surtaxRate = surtaxRate;
	}

	@Column(name = "SurtaxAmount", scale = 4)
	public BigDecimal getSurtaxAmount() {
		return this.surtaxAmount;
	}

	public void setSurtaxAmount(BigDecimal surtaxAmount) {
		this.surtaxAmount = surtaxAmount;
	}

	@Column(name = "SingleItemTaxAmount", scale = 4)
	public BigDecimal getSingleItemTaxAmount() {
		return this.singleItemTaxAmount;
	}

	public void setSingleItemTaxAmount(BigDecimal singleItemTaxAmount) {
		this.singleItemTaxAmount = singleItemTaxAmount;
	}

	@Column(name = "coDivisionID")
	public Integer getCoDivisionId() {
		return this.coDivisionId;
	}

	public void setCoDivisionId(Integer coDivisionId) {
		this.coDivisionId = coDivisionId;
	}

	@Column(name = "FreightCost", scale = 4)
	public BigDecimal getFreightCost() {
		return this.freightCost;
	}

	public void setFreightCost(BigDecimal freightCost) {
		this.freightCost = freightCost;
	}

	@Column(name = "DoNotMail", nullable = false)
	public byte getDoNotMail() {
		return doNotMail;
	}

	public void setDoNotMail(byte doNotMail) {
		this.doNotMail = doNotMail;
	}
	@Transient
	public String getJobname() {
		return jobname;
	}

	public void setJobname(String jobname) {
		this.jobname = jobname;
	}

	@Transient
	public BigDecimal getDiscountApplied() {
		return discountApplied;
	}

	public void setDiscountApplied(BigDecimal discountApplied) {
		this.discountApplied = discountApplied;
	}

	@Column(name = "CreditMemo")
	public Integer getCreditmemo() {
		return creditmemo;
	}

	public void setCreditmemo(Integer creditmemo) {
		this.creditmemo = creditmemo;
	}

	@Column(name = "IsCredit")
	public Integer getIscredit() {
		return iscredit;
	}

	public void setIscredit(Integer iscredit) {
		this.iscredit = iscredit;
	}

	@Column(name = "Description")
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Note")
	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}
	
	@Transient
	public Integer getJoMasterID() {
		return joMasterID;
	}

	public void setJoMasterID(Integer joMasterID) {
		this.joMasterID = joMasterID;
	}

	@Transient
	public Integer getJoReleaseType() {
		return joReleaseType;
	}

	public void setJoReleaseType(Integer joReleaseType) {
		this.joReleaseType = joReleaseType;
	}

	@Column(name = "DiscountAmt")
	public BigDecimal getDiscountAmt() {
		return discountAmt;
	}

	public void setDiscountAmt(BigDecimal discountAmt) {
		this.discountAmt = discountAmt;
	}

	@Column(name = "memoStatus")
	public Integer getMemoStatus() {
		return memoStatus;
	}

	public void setMemoStatus(Integer memoStatus) {
		this.memoStatus = memoStatus;
	}

	@Column(name = "rxContactID")
	public Integer getRxContactId() {
		return rxContactId;
	}

	public void setRxContactId(Integer rxContactId) {
		this.rxContactId = rxContactId;
	}

	@Column(name = "jobnodescription")
	public String getJobnoDescription() {
		return jobnoDescription;
	}

	public void setJobnoDescription(String jobnoDescription) {
		this.jobnoDescription = jobnoDescription;
	}

	@Transient
	public Integer getCustomerId() {
		return customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}
	@Transient
	public String getCuAssignmentName0() {
		return cuAssignmentName0;
	}

	public void setCuAssignmentName0(String cuAssignmentName0) {
		this.cuAssignmentName0 = cuAssignmentName0;
	}
	@Transient
	public String getCuAssignmentName1() {
		return cuAssignmentName1;
	}

	public void setCuAssignmentName1(String cuAssignmentName1) {
		this.cuAssignmentName1 = cuAssignmentName1;
	}
	@Transient
	public String getCuAssignmentName2() {
		return cuAssignmentName2;
	}

	public void setCuAssignmentName2(String cuAssignmentName2) {
		this.cuAssignmentName2 = cuAssignmentName2;
	}
	@Transient
	public String getCuAssignmentName3() {
		return cuAssignmentName3;
	}

	public void setCuAssignmentName3(String cuAssignmentName3) {
		this.cuAssignmentName3 = cuAssignmentName3;
	}
	@Transient
	public String getCuAssignmentName4() {
		return cuAssignmentName4;
	}

	public void setCuAssignmentName4(String cuAssignmentName4) {
		this.cuAssignmentName4 = cuAssignmentName4;
	}
	
	@Transient
	public String getCotaxdescription() {
		return cotaxdescription;
	}

	public void setCotaxdescription(String cotaxdescription) {
		this.cotaxdescription = cotaxdescription;
	}

	@Column(name = "cIopenStatus")
	public boolean getcIopenStatus() {
		return cIopenStatus;
	}

	public void setcIopenStatus(boolean cIopenStatus) {
		this.cIopenStatus = cIopenStatus;
	}
	
	@Column(name = "reason")
	public String getReason() {
		return reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Transient
	public String getChkNo() {
		return chkNo;
	}

	public void setChkNo(String chkNo) {
		this.chkNo = chkNo;
	}
	
	@Transient
	public Date getDatePaid() {
		return datePaid;
	}

	public void setDatePaid(Date datePaid) {
		this.datePaid = datePaid;
	}
	@Transient
	public String getReleaseType() {
		return releaseType;
	}

	public void setReleaseType(String releaseType) {
		this.releaseType = releaseType;
	}
	
	@Column(name = "whseCostTotal")
	public BigDecimal getWhseCostTotal() {
		return whseCostTotal;
	}

	public void setWhseCostTotal(BigDecimal whseCostTotal) {
		this.whseCostTotal = whseCostTotal;
	}

	@Transient
	public BigDecimal getMarginCost() {
		return marginCost;
	}

	public void setMarginCost(BigDecimal marginCost) {
		this.marginCost = marginCost;
	}

	@Transient
	public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Transient
	public Integer getCoAccountID() {
		return coAccountID;
	}

	public void setCoAccountID(Integer coAccountID) {
		this.coAccountID = coAccountID;
	}

	@Column(name = "taxAdjustmentStatus")
	public Integer getTaxAdjustmentStatus() {
		return taxAdjustmentStatus;
	}

	public void setTaxAdjustmentStatus(Integer taxAdjustmentStatus) {
		this.taxAdjustmentStatus = taxAdjustmentStatus;
	}

	@Transient
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "taxfreight")
	public byte getTaxfreight() {
		return taxfreight;
	}

	public void setTaxfreight(byte taxfreight) {
		this.taxfreight = taxfreight;
	}
	@Transient
	public BigDecimal getTaxSum() {
		return taxSum;
	}

	public void setTaxSum(BigDecimal taxSum) {
		this.taxSum = taxSum;
	}
	@Column(name = "EmailDate")
	public Date getEmailDate() {
		return emailDate;
	}

	public void setEmailDate(Date emailDate) {
		this.emailDate = emailDate;
	}
	@Transient
	public Integer getEmailCheckBox() {
		return emailCheckBox;
	}

	public void setEmailCheckBox(Integer emailCheckBox) {
		this.emailCheckBox = emailCheckBox;
	}
    
	@Transient
	public String getEmailList() {
		return emailList;
	}

	public void setEmailList(String emailList) {
		this.emailList = emailList;
	}
	@Column(name = "StatementEmailDate")
	public Date getStatementEmailDate() {
		return statementEmailDate;
	}

	public void setStatementEmailDate(Date statementEmailDate) {
		this.statementEmailDate = statementEmailDate;
	}
	
	@Column(name="EmailStatus")
	public Integer getEmailStatus() {
		return emailStatus;
	}

	public void setEmailStatus(Integer emailStatus) {
		this.emailStatus = emailStatus;
	}
	@Transient
	public String getSentEmailDate() {
		return sentEmailDate;
	}

	public void setSentEmailDate(String sentEmailDate) {
		this.sentEmailDate = sentEmailDate;
	}
	@Transient
	public String getSentstatementEmailDate() {
		return sentstatementEmailDate;
	}

	public void setSentstatementEmailDate(String sentstatementEmailDate) {
		this.sentstatementEmailDate = sentstatementEmailDate;
	}
	@Transient
	public Integer getStatementEmailStatus() {
		return statementEmailStatus;
	}

	public void setStatementEmailStatus(Integer statementEmailStatus) {
		this.statementEmailStatus = statementEmailStatus;
	}

	
	@Column(name="TaxableSales")
	public BigDecimal getTaxableSales() {
		return taxableSales;
	}

	public void setTaxableSales(BigDecimal taxableSales) {
		this.taxableSales = taxableSales;
	}
	@Column(name="NonTaxableSales")
	public BigDecimal getNonTaxableSales() {
		return nonTaxableSales;
	}

	public void setNonTaxableSales(BigDecimal nonTaxableSales) {
		this.nonTaxableSales = nonTaxableSales;
	}
}
