package com.turborep.turbotracker.customer.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cuinvoicepayworkfile generated by hbm2java
 */
@Entity
@Table(name = "cuinvoicepayworkfile", catalog = "")
public class Cuinvoicepayworkfile implements java.io.Serializable {

	private Integer cuInvoicePayWorkFileId;
	private Integer cuInvoiceId;
	private String invoiceNumber;
	private String customerPonumber;
	private Date invoiceDate;
	private BigDecimal invoiceBalance;
	private BigDecimal discountUsed;
	private BigDecimal paymentApplied;
	private BigDecimal remaining;
	private BigDecimal invoiceAmount;
	private BigDecimal prevDiscountUsed;
	private BigDecimal prevPaymentApplied;

	public Cuinvoicepayworkfile() {
	}

	public Cuinvoicepayworkfile(BigDecimal invoiceBalance,
			BigDecimal discountUsed, BigDecimal paymentApplied,
			BigDecimal remaining, BigDecimal invoiceAmount,
			BigDecimal prevDiscountUsed, BigDecimal prevPaymentApplied) {
		this.invoiceBalance = invoiceBalance;
		this.discountUsed = discountUsed;
		this.paymentApplied = paymentApplied;
		this.remaining = remaining;
		this.invoiceAmount = invoiceAmount;
		this.prevDiscountUsed = prevDiscountUsed;
		this.prevPaymentApplied = prevPaymentApplied;
	}

	public Cuinvoicepayworkfile(Integer cuInvoiceId, String invoiceNumber,
			String customerPonumber, Date invoiceDate,
			BigDecimal invoiceBalance, BigDecimal discountUsed,
			BigDecimal paymentApplied, BigDecimal remaining,
			BigDecimal invoiceAmount, BigDecimal prevDiscountUsed,
			BigDecimal prevPaymentApplied) {
		this.cuInvoiceId = cuInvoiceId;
		this.invoiceNumber = invoiceNumber;
		this.customerPonumber = customerPonumber;
		this.invoiceDate = invoiceDate;
		this.invoiceBalance = invoiceBalance;
		this.discountUsed = discountUsed;
		this.paymentApplied = paymentApplied;
		this.remaining = remaining;
		this.invoiceAmount = invoiceAmount;
		this.prevDiscountUsed = prevDiscountUsed;
		this.prevPaymentApplied = prevPaymentApplied;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cuInvoicePayWorkFileID", unique = true, nullable = false)
	public Integer getCuInvoicePayWorkFileId() {
		return this.cuInvoicePayWorkFileId;
	}

	public void setCuInvoicePayWorkFileId(Integer cuInvoicePayWorkFileId) {
		this.cuInvoicePayWorkFileId = cuInvoicePayWorkFileId;
	}

	@Column(name = "cuInvoiceID")
	public Integer getCuInvoiceId() {
		return this.cuInvoiceId;
	}

	public void setCuInvoiceId(Integer cuInvoiceId) {
		this.cuInvoiceId = cuInvoiceId;
	}

	@Column(name = "InvoiceNumber", length = 20)
	public String getInvoiceNumber() {
		return this.invoiceNumber;
	}

	public void setInvoiceNumber(String invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	@Column(name = "CustomerPONumber", length = 20)
	public String getCustomerPonumber() {
		return this.customerPonumber;
	}

	public void setCustomerPonumber(String customerPonumber) {
		this.customerPonumber = customerPonumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InvoiceDate", length = 0)
	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	@Column(name = "InvoiceBalance", nullable = false, scale = 4)
	public BigDecimal getInvoiceBalance() {
		return this.invoiceBalance;
	}

	public void setInvoiceBalance(BigDecimal invoiceBalance) {
		this.invoiceBalance = invoiceBalance;
	}

	@Column(name = "DiscountUsed", nullable = false, scale = 4)
	public BigDecimal getDiscountUsed() {
		return this.discountUsed;
	}

	public void setDiscountUsed(BigDecimal discountUsed) {
		this.discountUsed = discountUsed;
	}

	@Column(name = "PaymentApplied", nullable = false, scale = 4)
	public BigDecimal getPaymentApplied() {
		return this.paymentApplied;
	}

	public void setPaymentApplied(BigDecimal paymentApplied) {
		this.paymentApplied = paymentApplied;
	}

	@Column(name = "Remaining", nullable = false, scale = 4)
	public BigDecimal getRemaining() {
		return this.remaining;
	}

	public void setRemaining(BigDecimal remaining) {
		this.remaining = remaining;
	}

	@Column(name = "InvoiceAmount", nullable = false, scale = 4)
	public BigDecimal getInvoiceAmount() {
		return this.invoiceAmount;
	}

	public void setInvoiceAmount(BigDecimal invoiceAmount) {
		this.invoiceAmount = invoiceAmount;
	}

	@Column(name = "PrevDiscountUsed", nullable = false, scale = 4)
	public BigDecimal getPrevDiscountUsed() {
		return this.prevDiscountUsed;
	}

	public void setPrevDiscountUsed(BigDecimal prevDiscountUsed) {
		this.prevDiscountUsed = prevDiscountUsed;
	}

	@Column(name = "PrevPaymentApplied", nullable = false, scale = 4)
	public BigDecimal getPrevPaymentApplied() {
		return this.prevPaymentApplied;
	}

	public void setPrevPaymentApplied(BigDecimal prevPaymentApplied) {
		this.prevPaymentApplied = prevPaymentApplied;
	}

}
