package com.turborep.turbotracker.customer.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cuinvoicedetail generated by hbm2java
 */
@Entity
@Table(name = "cuInvoiceDetail", catalog = "")
public class Cuinvoicedetail implements java.io.Serializable {

	private Integer cuInvoiceDetailId;
	private Integer cuInvoiceId;
	private Integer cuSodetailId;
	private Integer prMasterId;
	private String description;
	private String note;
	private BigDecimal quantityBilled;
	private BigDecimal unitCost;
	private BigDecimal unitPrice;
	private BigDecimal priceMultiplier;
	private Byte taxable;
	private boolean hasSingleItemTaxAmount;
	private String itemCode;
	private BigDecimal TaxTotal;
	
	private Integer coAccountID;
	private String noteImage;
	
	private BigDecimal whseCost;
	private Integer userID;
	private String userName;
	private BigDecimal taxSum;
	public Cuinvoicedetail() {
	}

	public Cuinvoicedetail(boolean hasSingleItemTaxAmount) {
		this.hasSingleItemTaxAmount = hasSingleItemTaxAmount;
	}

	public Cuinvoicedetail(Integer cuInvoiceId, Integer cuSodetailId,
			Integer prMasterId, String description, String note,
			BigDecimal quantityBilled, BigDecimal unitCost,
			BigDecimal unitPrice, BigDecimal priceMultiplier, Byte taxable,
			boolean hasSingleItemTaxAmount) {
		this.cuInvoiceId = cuInvoiceId;
		this.cuSodetailId = cuSodetailId;
		this.prMasterId = prMasterId;
		this.description = description;
		this.note = note;
		this.quantityBilled = quantityBilled;
		this.unitCost = unitCost;
		this.unitPrice = unitPrice;
		this.priceMultiplier = priceMultiplier;
		this.taxable = taxable;
		this.hasSingleItemTaxAmount = hasSingleItemTaxAmount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cuInvoiceDetailID", unique = true, nullable = false)
	public Integer getCuInvoiceDetailId() {
		return this.cuInvoiceDetailId;
	}

	public void setCuInvoiceDetailId(Integer cuInvoiceDetailId) {
		this.cuInvoiceDetailId = cuInvoiceDetailId;
	}

	@Column(name = "cuInvoiceID")
	public Integer getCuInvoiceId() {
		return this.cuInvoiceId;
	}

	public void setCuInvoiceId(Integer cuInvoiceId) {
		this.cuInvoiceId = cuInvoiceId;
	}

	@Column(name = "cuSODetailID")
	public Integer getCuSodetailId() {
		return this.cuSodetailId;
	}

	public void setCuSodetailId(Integer cuSodetailId) {
		this.cuSodetailId = cuSodetailId;
	}

	@Column(name = "prMasterID")
	public Integer getPrMasterId() {
		return this.prMasterId;
	}

	public void setPrMasterId(Integer prMasterId) {
		this.prMasterId = prMasterId;
	}

	@Column(name = "Description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "QuantityBilled", scale = 4)
	public BigDecimal getQuantityBilled() {
		return this.quantityBilled;
	}

	public void setQuantityBilled(BigDecimal quantityBilled) {
		this.quantityBilled = quantityBilled;
	}

	@Column(name = "UnitCost", scale = 4)
	public BigDecimal getUnitCost() {
		return this.unitCost;
	}

	public void setUnitCost(BigDecimal unitCost) {
		this.unitCost = unitCost;
	}

	@Column(name = "UnitPrice", scale = 4)
	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "PriceMultiplier", scale = 4)
	public BigDecimal getPriceMultiplier() {
		return this.priceMultiplier;
	}

	public void setPriceMultiplier(BigDecimal priceMultiplier) {
		this.priceMultiplier = priceMultiplier;
	}

	@Column(name = "Taxable")
	public Byte getTaxable() {
		return this.taxable;
	}

	public void setTaxable(Byte aObj) {
		this.taxable = aObj;
	}

	@Column(name = "HasSingleItemTaxAmount", nullable = false)
	public boolean isHasSingleItemTaxAmount() {
		return this.hasSingleItemTaxAmount;
	}

	public void setHasSingleItemTaxAmount(boolean hasSingleItemTaxAmount) {
		this.hasSingleItemTaxAmount = hasSingleItemTaxAmount;
	}
	@Transient
	public String getItemCode() {
		return itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}
	@Transient
	public BigDecimal getTaxTotal() {
		return TaxTotal;
	}

	public void setTaxTotal(BigDecimal taxTotal) {
		TaxTotal = taxTotal;
	}

	@Column(name = "coAccountID")
	public Integer getCoAccountID() {
		return coAccountID;
	}

	public void setCoAccountID(Integer coAccountID) {
		this.coAccountID = coAccountID;
	}
	
	@Transient
	public String getNoteImage() {
		return noteImage;
	}

	public void setNoteImage(String noteImage) {
		this.noteImage = noteImage;
	}

	@Column(name = "whseCost")
	public BigDecimal getWhseCost() {
		return whseCost;
	}

	public void setWhseCost(BigDecimal whseCost) {
		this.whseCost = whseCost;
	}

	@Transient
	public Integer getUserID() {
		return userID;
	}

	public void setUserID(Integer userID) {
		this.userID = userID;
	}

	@Transient
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}
	
	public boolean comparetwoobjects(Cuinvoicedetail o,Cuinvoicedetail e) {
	    if(e == null)
	    {
	        return false;
	    }
	   
		
	    if(o.cuInvoiceDetailId!=e.getCuInvoiceDetailId()){
	    	return false;
	    }
	    System.out.println((o.prMasterId.intValue()!= e.getPrMasterId().intValue())+"=================>"+o.prMasterId +"!="+e.getPrMasterId());
	    if(o.prMasterId.intValue()!= e.getPrMasterId().intValue()){
	    	return true;
	    }
	    /*if(o.description!=null && o.description.equals(e.getDescription())){
	    	return false;
	    }
	    if(o.note!=null && o.note.equals(e.note)){
	    	return false;
	    }*/
	    if(o.quantityBilled!=null && !(o.quantityBilled.compareTo(e.getQuantityBilled()==null?BigDecimal.ZERO:e.getQuantityBilled())==0)){
	    	return true;
	    }
	    if(o.unitCost!=null && !(o.unitCost.compareTo(e.getUnitCost()==null?BigDecimal.ZERO:e.getUnitCost())==0)){
	    	return true;
	    }
	    if(o.unitPrice!=null && !(o.unitPrice.compareTo(e.getUnitPrice()==null?BigDecimal.ZERO:e.getUnitPrice())==0)){
	    	return true;
	    }
	    if(o.priceMultiplier!=null && !(o.priceMultiplier.compareTo(e.getPriceMultiplier())==0)){
	    	return true;
	    }
	    /*if(o.taxable!=e.getTaxable()){
	    	return false;
	    }*/
	    /*if(o.whseCost!=e.getWhseCost()){
	    	return false;
	    }*/
	    
	     return false;
	}
@Transient
	public BigDecimal getTaxSum() {
		return taxSum;
	}

	public void setTaxSum(BigDecimal taxSum) {
		this.taxSum = taxSum;
	}

}
