package com.turborep.turbotracker.customer.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Culinkagedetail generated by hbm2java
 */
@Entity
@Table(name = "cuReversePaymentsInv", catalog = "")
public class CuReversePaymentsInv implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer cuReversePaymentInvID;
	private Integer cuLinkageDetailId;
	private Integer cuInvoiceId;
	private Integer cuReceiptId;
	private Integer rxCustomerId, refInvoiceID;
	private BigDecimal paymentApplied;
	private BigDecimal discountUsed;
	private BigDecimal creditUsage,invoiceApplied,creditAmount;
	private Date reciptDate;
	private BigDecimal invoiceAmount;
	private BigDecimal amtApplied;
	private Integer statusCheck;
	private Date datePaid;
	
	
	public CuReversePaymentsInv() {
	}

	public CuReversePaymentsInv(Integer cuInvoiceId, Integer cuReceiptId,
			Integer rxCustomerId,Integer refInvoiceID, BigDecimal paymentApplied,
			BigDecimal discountUsed,BigDecimal creditAmount,BigDecimal invoiceAmount) {
		this.cuInvoiceId = cuInvoiceId;
		this.cuReceiptId = cuReceiptId;
		this.rxCustomerId = rxCustomerId;
		this.paymentApplied = paymentApplied;
		this.discountUsed = discountUsed;
		this.refInvoiceID = refInvoiceID;
		this.creditAmount = creditAmount;
		this.invoiceAmount = invoiceAmount;
	}

	@Column(name = "cuLinkageDetailID")
	public Integer getCuLinkageDetailId() {
		return this.cuLinkageDetailId;
	}

	public void setCuLinkageDetailId(Integer cuLinkageDetailId) {
		this.cuLinkageDetailId = cuLinkageDetailId;
	}

	@Column(name = "cuInvoiceID")
	public Integer getCuInvoiceId() {
		return this.cuInvoiceId;
	}

	public void setCuInvoiceId(Integer cuInvoiceId) {
		this.cuInvoiceId = cuInvoiceId;
	}

	@Column(name = "cuReceiptID")
	public Integer getCuReceiptId() {
		return this.cuReceiptId;
	}

	public void setCuReceiptId(Integer cuReceiptId) {
		this.cuReceiptId = cuReceiptId;
	}

	@Column(name = "rxCustomerID")
	public Integer getRxCustomerId() {
		return this.rxCustomerId;
	}

	public void setRxCustomerId(Integer rxCustomerId) {
		this.rxCustomerId = rxCustomerId;
	}

	@Column(name = "PaymentApplied", scale = 4)
	public BigDecimal getPaymentApplied() {
		return this.paymentApplied;
	}

	public void setPaymentApplied(BigDecimal paymentApplied) {
		this.paymentApplied = paymentApplied;
	}

	@Column(name = "DiscountUsed", scale = 4)
	public BigDecimal getDiscountUsed() {
		return this.discountUsed;
	}

	public void setDiscountUsed(BigDecimal discountUsed) {
		this.discountUsed = discountUsed;
	}
	@Transient
	public BigDecimal getCreditUsage() {
		return creditUsage;
	}

	public void setCreditUsage(BigDecimal creditUsage) {
		this.creditUsage = creditUsage;
	}
	@Transient
	public BigDecimal getInvoiceApplied() {
		return invoiceApplied;
	}

	public void setInvoiceApplied(BigDecimal invoiceApplied) {
		this.invoiceApplied = invoiceApplied;
	}

	@Column(name = "refInvoiceID")
	public Integer getRefInvoiceID() {
		return refInvoiceID;
	}

	public void setRefInvoiceID(Integer refInvoiceID) {
		this.refInvoiceID = refInvoiceID;
	}

	@Column(name = "creditAmount")
	public BigDecimal getCreditAmount() {
		return creditAmount;
	}

	public void setCreditAmount(BigDecimal creditAmount) {
		this.creditAmount = creditAmount;
	}
	
	@Transient
	public Date getReciptDate() {
		return reciptDate;
	}

	public void setReciptDate(Date reciptDate) {
		this.reciptDate = reciptDate;
	}

	@Transient
	public BigDecimal getInvoiceAmount() {
		return invoiceAmount;
	}

	public void setInvoiceAmount(BigDecimal invoiceAmount) {
		this.invoiceAmount = invoiceAmount;
	}

	@Column(name = "amtApplied")
	public BigDecimal getAmtApplied() {
		return amtApplied;
	}

	public void setAmtApplied(BigDecimal amtApplied) {
		this.amtApplied = amtApplied;
	}

	@Column(name = "statusCheck")
	public Integer getStatusCheck() {
		return statusCheck;
	}

	public void setStatusCheck(Integer statusCheck) {
		this.statusCheck = statusCheck;
	}
	
	@Column(name = "datePaid")
	public Date getDatePaid() {
		return datePaid;
	}

	public void setDatePaid(Date datePaid) {
		this.datePaid = datePaid;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cuReversePaymentInvID", unique = true, nullable = false)
	public Integer getCuReversePaymentInvID() {
		return cuReversePaymentInvID;
	}

	public void setCuReversePaymentInvID(Integer cuReversePaymentInvID) {
		this.cuReversePaymentInvID = cuReversePaymentInvID;
	}	
	
	

}
