package com.turborep.turbotracker.customer.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cuship generated by hbm2java
 */
@Entity
@Table(name = "cuship", catalog = "")
public class Cuship implements java.io.Serializable {

	private Integer cuShipId;
	private Integer rxMasterId;
	private Integer cuSoid;
	private Date shipDate;

	public Cuship() {
	}

	public Cuship(Integer rxMasterId, Integer cuSoid, Date shipDate) {
		this.rxMasterId = rxMasterId;
		this.cuSoid = cuSoid;
		this.shipDate = shipDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cuShipID", unique = true, nullable = false)
	public Integer getCuShipId() {
		return this.cuShipId;
	}

	public void setCuShipId(Integer cuShipId) {
		this.cuShipId = cuShipId;
	}

	@Column(name = "rxMasterID")
	public Integer getRxMasterId() {
		return this.rxMasterId;
	}

	public void setRxMasterId(Integer rxMasterId) {
		this.rxMasterId = rxMasterId;
	}

	@Column(name = "cuSOID")
	public Integer getCuSoid() {
		return this.cuSoid;
	}

	public void setCuSoid(Integer cuSoid) {
		this.cuSoid = cuSoid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ShipDate", length = 0)
	public Date getShipDate() {
		return this.shipDate;
	}

	public void setShipDate(Date shipDate) {
		this.shipDate = shipDate;
	}

}
