package com.turborep.turbotracker.customer.dao;

// Generated Jul 9, 2014 5:57:18 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cusotemplate generated by hbm2java
 */
@Entity
@Table(name = "cuSOTemplate", catalog = "")
public class Cusotemplate implements java.io.Serializable {

	private Integer cuSoid;
	private Integer createdById;
	private Date createdOn;
	private Integer changedById;
	private Date changedOn;
	private Short transactionStatus;
	private Integer joReleaseId;
	private Integer rxCustomerId;
	private Integer rxBillToId;
	private Integer rxBillToAddressId;
	private Integer rxShipToId;
	private Integer rxShipToAddressId;
	private Integer veShipViaId;
	private Integer prFromWarehouseId;
	private Integer prToWarehouseId;
	private Integer cuTermsId;
	private short shipToMode;
	private Integer coTaxTerritoryId;
	private String sonumber;
	private String customerPonumber;
	private String datePromised;
	private String quickJobName;
	private Date orderDate;
	private Date shipDate;
	private BigDecimal costTotal;
	private BigDecimal subTotal;
	private BigDecimal taxTotal;
	private BigDecimal freight;
	private BigDecimal taxRate;
	private Integer cuAssignmentId0;
	private Integer cuAssignmentId1;
	private Integer cuAssignmentId2;
	private Integer cuAssignmentId3;
	private Integer cuAssignmentId4;
	private String trackingNumber;
	private Byte surtaxOverrideCap;
	private BigDecimal surtaxTotal;
	private BigDecimal surtaxRate;
	private BigDecimal surtaxAmount;
	private BigDecimal singleItemTaxAmount;
	private Integer joSchedDetailId;
	private String tag;
	private BigDecimal freightCost;
	private Integer coDivisionId;
	private byte taxExempt1;
	private byte taxExempt2;
	private byte taxExempt3;
	private byte taxExempt4;
	private byte taxExempt5;
	private byte taxExempt6;
	private byte taxExempt7;
	private byte taxExempt8;
	private byte taxExempt0;
	private String templateDescription;

	public Cusotemplate() {
	}

	public Cusotemplate(short shipToMode, byte taxExempt1, byte taxExempt2,
			byte taxExempt3, byte taxExempt4, byte taxExempt5, byte taxExempt6,
			byte taxExempt7, byte taxExempt8, byte taxExempt0) {
		this.shipToMode = shipToMode;
		this.taxExempt1 = taxExempt1;
		this.taxExempt2 = taxExempt2;
		this.taxExempt3 = taxExempt3;
		this.taxExempt4 = taxExempt4;
		this.taxExempt5 = taxExempt5;
		this.taxExempt6 = taxExempt6;
		this.taxExempt7 = taxExempt7;
		this.taxExempt8 = taxExempt8;
		this.taxExempt0 = taxExempt0;
	}

	public Cusotemplate(Integer createdById, Date createdOn,
			Integer changedById, Date changedOn, Short transactionStatus,
			Integer joReleaseId, Integer rxCustomerId, Integer rxBillToId,
			Integer rxBillToAddressId, Integer rxShipToId,
			Integer rxShipToAddressId, Integer veShipViaId,
			Integer prFromWarehouseId, Integer prToWarehouseId,
			Integer cuTermsId, short shipToMode, Integer coTaxTerritoryId,
			String sonumber, String customerPonumber, String datePromised,
			String quickJobName, Date orderDate, Date shipDate,
			BigDecimal costTotal, BigDecimal subTotal, BigDecimal taxTotal,
			BigDecimal freight, BigDecimal taxRate, Integer cuAssignmentId0,
			Integer cuAssignmentId1, Integer cuAssignmentId2,
			Integer cuAssignmentId3, Integer cuAssignmentId4,
			String trackingNumber, Byte surtaxOverrideCap,
			BigDecimal surtaxTotal, BigDecimal surtaxRate,
			BigDecimal surtaxAmount, BigDecimal singleItemTaxAmount,
			Integer joSchedDetailId, String tag, BigDecimal freightCost,
			Integer coDivisionId, byte taxExempt1, byte taxExempt2,
			byte taxExempt3, byte taxExempt4, byte taxExempt5, byte taxExempt6,
			byte taxExempt7, byte taxExempt8, byte taxExempt0,
			String templateDescription) {
		this.createdById = createdById;
		this.createdOn = createdOn;
		this.changedById = changedById;
		this.changedOn = changedOn;
		this.transactionStatus = transactionStatus;
		this.joReleaseId = joReleaseId;
		this.rxCustomerId = rxCustomerId;
		this.rxBillToId = rxBillToId;
		this.rxBillToAddressId = rxBillToAddressId;
		this.rxShipToId = rxShipToId;
		this.rxShipToAddressId = rxShipToAddressId;
		this.veShipViaId = veShipViaId;
		this.prFromWarehouseId = prFromWarehouseId;
		this.prToWarehouseId = prToWarehouseId;
		this.cuTermsId = cuTermsId;
		this.shipToMode = shipToMode;
		this.coTaxTerritoryId = coTaxTerritoryId;
		this.sonumber = sonumber;
		this.customerPonumber = customerPonumber;
		this.datePromised = datePromised;
		this.quickJobName = quickJobName;
		this.orderDate = orderDate;
		this.shipDate = shipDate;
		this.costTotal = costTotal;
		this.subTotal = subTotal;
		this.taxTotal = taxTotal;
		this.freight = freight;
		this.taxRate = taxRate;
		this.cuAssignmentId0 = cuAssignmentId0;
		this.cuAssignmentId1 = cuAssignmentId1;
		this.cuAssignmentId2 = cuAssignmentId2;
		this.cuAssignmentId3 = cuAssignmentId3;
		this.cuAssignmentId4 = cuAssignmentId4;
		this.trackingNumber = trackingNumber;
		this.surtaxOverrideCap = surtaxOverrideCap;
		this.surtaxTotal = surtaxTotal;
		this.surtaxRate = surtaxRate;
		this.surtaxAmount = surtaxAmount;
		this.singleItemTaxAmount = singleItemTaxAmount;
		this.joSchedDetailId = joSchedDetailId;
		this.tag = tag;
		this.freightCost = freightCost;
		this.coDivisionId = coDivisionId;
		this.taxExempt1 = taxExempt1;
		this.taxExempt2 = taxExempt2;
		this.taxExempt3 = taxExempt3;
		this.taxExempt4 = taxExempt4;
		this.taxExempt5 = taxExempt5;
		this.taxExempt6 = taxExempt6;
		this.taxExempt7 = taxExempt7;
		this.taxExempt8 = taxExempt8;
		this.taxExempt0 = taxExempt0;
		this.templateDescription = templateDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cuSOID", unique = true, nullable = false)
	public Integer getCuSoid() {
		return this.cuSoid;
	}

	public void setCuSoid(Integer cuSoid) {
		this.cuSoid = cuSoid;
	}

	@Column(name = "CreatedByID")
	public Integer getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(Integer createdById) {
		this.createdById = createdById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "ChangedByID")
	public Integer getChangedById() {
		return this.changedById;
	}

	public void setChangedById(Integer changedById) {
		this.changedById = changedById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ChangedOn", length = 19)
	public Date getChangedOn() {
		return this.changedOn;
	}

	public void setChangedOn(Date changedOn) {
		this.changedOn = changedOn;
	}

	@Column(name = "TransactionStatus")
	public Short getTransactionStatus() {
		return this.transactionStatus;
	}

	public void setTransactionStatus(Short transactionStatus) {
		this.transactionStatus = transactionStatus;
	}

	@Column(name = "joReleaseID")
	public Integer getJoReleaseId() {
		return this.joReleaseId;
	}

	public void setJoReleaseId(Integer joReleaseId) {
		this.joReleaseId = joReleaseId;
	}

	@Column(name = "rxCustomerID")
	public Integer getRxCustomerId() {
		return this.rxCustomerId;
	}

	public void setRxCustomerId(Integer rxCustomerId) {
		this.rxCustomerId = rxCustomerId;
	}

	@Column(name = "rxBillToID")
	public Integer getRxBillToId() {
		return this.rxBillToId;
	}

	public void setRxBillToId(Integer rxBillToId) {
		this.rxBillToId = rxBillToId;
	}

	@Column(name = "rxBillToAddressID")
	public Integer getRxBillToAddressId() {
		return this.rxBillToAddressId;
	}

	public void setRxBillToAddressId(Integer rxBillToAddressId) {
		this.rxBillToAddressId = rxBillToAddressId;
	}

	@Column(name = "rxShipToID")
	public Integer getRxShipToId() {
		return this.rxShipToId;
	}

	public void setRxShipToId(Integer rxShipToId) {
		this.rxShipToId = rxShipToId;
	}

	@Column(name = "rxShipToAddressID")
	public Integer getRxShipToAddressId() {
		return this.rxShipToAddressId;
	}

	public void setRxShipToAddressId(Integer rxShipToAddressId) {
		this.rxShipToAddressId = rxShipToAddressId;
	}

	@Column(name = "veShipViaID")
	public Integer getVeShipViaId() {
		return this.veShipViaId;
	}

	public void setVeShipViaId(Integer veShipViaId) {
		this.veShipViaId = veShipViaId;
	}

	@Column(name = "prFromWarehouseID")
	public Integer getPrFromWarehouseId() {
		return this.prFromWarehouseId;
	}

	public void setPrFromWarehouseId(Integer prFromWarehouseId) {
		this.prFromWarehouseId = prFromWarehouseId;
	}

	@Column(name = "prToWarehouseID")
	public Integer getPrToWarehouseId() {
		return this.prToWarehouseId;
	}

	public void setPrToWarehouseId(Integer prToWarehouseId) {
		this.prToWarehouseId = prToWarehouseId;
	}

	@Column(name = "cuTermsID")
	public Integer getCuTermsId() {
		return this.cuTermsId;
	}

	public void setCuTermsId(Integer cuTermsId) {
		this.cuTermsId = cuTermsId;
	}

	@Column(name = "ShipToMode", nullable = false)
	public short getShipToMode() {
		return this.shipToMode;
	}

	public void setShipToMode(short shipToMode) {
		this.shipToMode = shipToMode;
	}

	@Column(name = "coTaxTerritoryID")
	public Integer getCoTaxTerritoryId() {
		return this.coTaxTerritoryId;
	}

	public void setCoTaxTerritoryId(Integer coTaxTerritoryId) {
		this.coTaxTerritoryId = coTaxTerritoryId;
	}

	@Column(name = "SONumber", length = 20)
	public String getSonumber() {
		return this.sonumber;
	}

	public void setSonumber(String sonumber) {
		this.sonumber = sonumber;
	}

	@Column(name = "CustomerPONumber", length = 20)
	public String getCustomerPonumber() {
		return this.customerPonumber;
	}

	public void setCustomerPonumber(String customerPonumber) {
		this.customerPonumber = customerPonumber;
	}

	@Column(name = "DatePromised", length = 12)
	public String getDatePromised() {
		return this.datePromised;
	}

	public void setDatePromised(String datePromised) {
		this.datePromised = datePromised;
	}

	@Column(name = "QuickJobName", length = 40)
	public String getQuickJobName() {
		return this.quickJobName;
	}

	public void setQuickJobName(String quickJobName) {
		this.quickJobName = quickJobName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OrderDate", length = 19)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ShipDate", length = 19)
	public Date getShipDate() {
		return this.shipDate;
	}

	public void setShipDate(Date shipDate) {
		this.shipDate = shipDate;
	}

	@Column(name = "CostTotal", scale = 4)
	public BigDecimal getCostTotal() {
		return this.costTotal;
	}

	public void setCostTotal(BigDecimal costTotal) {
		this.costTotal = costTotal;
	}

	@Column(name = "SubTotal", scale = 4)
	public BigDecimal getSubTotal() {
		return this.subTotal;
	}

	public void setSubTotal(BigDecimal subTotal) {
		this.subTotal = subTotal;
	}

	@Column(name = "TaxTotal", scale = 4)
	public BigDecimal getTaxTotal() {
		return this.taxTotal;
	}

	public void setTaxTotal(BigDecimal taxTotal) {
		this.taxTotal = taxTotal;
	}

	@Column(name = "Freight", scale = 4)
	public BigDecimal getFreight() {
		return this.freight;
	}

	public void setFreight(BigDecimal freight) {
		this.freight = freight;
	}

	@Column(name = "TaxRate", scale = 4)
	public BigDecimal getTaxRate() {
		return this.taxRate;
	}

	public void setTaxRate(BigDecimal taxRate) {
		this.taxRate = taxRate;
	}

	@Column(name = "cuAssignmentID0")
	public Integer getCuAssignmentId0() {
		return this.cuAssignmentId0;
	}

	public void setCuAssignmentId0(Integer cuAssignmentId0) {
		this.cuAssignmentId0 = cuAssignmentId0;
	}

	@Column(name = "cuAssignmentID1")
	public Integer getCuAssignmentId1() {
		return this.cuAssignmentId1;
	}

	public void setCuAssignmentId1(Integer cuAssignmentId1) {
		this.cuAssignmentId1 = cuAssignmentId1;
	}

	@Column(name = "cuAssignmentID2")
	public Integer getCuAssignmentId2() {
		return this.cuAssignmentId2;
	}

	public void setCuAssignmentId2(Integer cuAssignmentId2) {
		this.cuAssignmentId2 = cuAssignmentId2;
	}

	@Column(name = "cuAssignmentID3")
	public Integer getCuAssignmentId3() {
		return this.cuAssignmentId3;
	}

	public void setCuAssignmentId3(Integer cuAssignmentId3) {
		this.cuAssignmentId3 = cuAssignmentId3;
	}

	@Column(name = "cuAssignmentID4")
	public Integer getCuAssignmentId4() {
		return this.cuAssignmentId4;
	}

	public void setCuAssignmentId4(Integer cuAssignmentId4) {
		this.cuAssignmentId4 = cuAssignmentId4;
	}

	@Column(name = "TrackingNumber", length = 30)
	public String getTrackingNumber() {
		return this.trackingNumber;
	}

	public void setTrackingNumber(String trackingNumber) {
		this.trackingNumber = trackingNumber;
	}

	@Column(name = "SurtaxOverrideCap")
	public Byte getSurtaxOverrideCap() {
		return this.surtaxOverrideCap;
	}

	public void setSurtaxOverrideCap(Byte surtaxOverrideCap) {
		this.surtaxOverrideCap = surtaxOverrideCap;
	}

	@Column(name = "SurtaxTotal", scale = 4)
	public BigDecimal getSurtaxTotal() {
		return this.surtaxTotal;
	}

	public void setSurtaxTotal(BigDecimal surtaxTotal) {
		this.surtaxTotal = surtaxTotal;
	}

	@Column(name = "SurtaxRate", scale = 4)
	public BigDecimal getSurtaxRate() {
		return this.surtaxRate;
	}

	public void setSurtaxRate(BigDecimal surtaxRate) {
		this.surtaxRate = surtaxRate;
	}

	@Column(name = "SurtaxAmount", scale = 4)
	public BigDecimal getSurtaxAmount() {
		return this.surtaxAmount;
	}

	public void setSurtaxAmount(BigDecimal surtaxAmount) {
		this.surtaxAmount = surtaxAmount;
	}

	@Column(name = "SingleItemTaxAmount", scale = 4)
	public BigDecimal getSingleItemTaxAmount() {
		return this.singleItemTaxAmount;
	}

	public void setSingleItemTaxAmount(BigDecimal singleItemTaxAmount) {
		this.singleItemTaxAmount = singleItemTaxAmount;
	}

	@Column(name = "joSchedDetailID")
	public Integer getJoSchedDetailId() {
		return this.joSchedDetailId;
	}

	public void setJoSchedDetailId(Integer joSchedDetailId) {
		this.joSchedDetailId = joSchedDetailId;
	}

	@Column(name = "Tag")
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Column(name = "FreightCost", scale = 4)
	public BigDecimal getFreightCost() {
		return this.freightCost;
	}

	public void setFreightCost(BigDecimal freightCost) {
		this.freightCost = freightCost;
	}

	@Column(name = "coDivisionID")
	public Integer getCoDivisionId() {
		return this.coDivisionId;
	}

	public void setCoDivisionId(Integer coDivisionId) {
		this.coDivisionId = coDivisionId;
	}

	@Column(name = "TaxExempt1", nullable = false)
	public byte getTaxExempt1() {
		return this.taxExempt1;
	}

	public void setTaxExempt1(byte taxExempt1) {
		this.taxExempt1 = taxExempt1;
	}

	@Column(name = "TaxExempt2", nullable = false)
	public byte getTaxExempt2() {
		return this.taxExempt2;
	}

	public void setTaxExempt2(byte taxExempt2) {
		this.taxExempt2 = taxExempt2;
	}

	@Column(name = "TaxExempt3", nullable = false)
	public byte getTaxExempt3() {
		return this.taxExempt3;
	}

	public void setTaxExempt3(byte taxExempt3) {
		this.taxExempt3 = taxExempt3;
	}

	@Column(name = "TaxExempt4", nullable = false)
	public byte getTaxExempt4() {
		return this.taxExempt4;
	}

	public void setTaxExempt4(byte taxExempt4) {
		this.taxExempt4 = taxExempt4;
	}

	@Column(name = "TaxExempt5", nullable = false)
	public byte getTaxExempt5() {
		return this.taxExempt5;
	}

	public void setTaxExempt5(byte taxExempt5) {
		this.taxExempt5 = taxExempt5;
	}

	@Column(name = "TaxExempt6", nullable = false)
	public byte getTaxExempt6() {
		return this.taxExempt6;
	}

	public void setTaxExempt6(byte taxExempt6) {
		this.taxExempt6 = taxExempt6;
	}

	@Column(name = "TaxExempt7", nullable = false)
	public byte getTaxExempt7() {
		return this.taxExempt7;
	}

	public void setTaxExempt7(byte taxExempt7) {
		this.taxExempt7 = taxExempt7;
	}

	@Column(name = "TaxExempt8", nullable = false)
	public byte getTaxExempt8() {
		return this.taxExempt8;
	}

	public void setTaxExempt8(byte taxExempt8) {
		this.taxExempt8 = taxExempt8;
	}

	@Column(name = "TaxExempt0", nullable = false)
	public byte getTaxExempt0() {
		return this.taxExempt0;
	}

	public void setTaxExempt0(byte taxExempt0) {
		this.taxExempt0 = taxExempt0;
	}

	@Column(name = "TemplateDescription", length = 50)
	public String getTemplateDescription() {
		return this.templateDescription;
	}

	public void setTemplateDescription(String templateDescription) {
		this.templateDescription = templateDescription;
	}

}
