package com.turborep.turbotracker.customer.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cuterms generated by hbm2java
 */
@Entity
@Table(name = "cuTerms", catalog = "")
public class CuTerms implements java.io.Serializable {

	private Integer cuTermsId;
	private String description;
	private boolean inActive;
	private int dueDays;
	private int discountDays;
	private BigDecimal discountPercent;
	private boolean dueOnDay;
	private boolean discOnDay;
	private String orderNote;
	private String pickTicketNote1;
	private String pickTicketNote2;
	private String pickTicketNote3;
	private String pickTicketNote4;
	private String pickTicketNote5;
	private boolean isGlobal;
	
	public CuTerms() {
	}

	public CuTerms(boolean inActive, int dueDays, int discountDays, boolean dueOnDay, boolean discOnDay, boolean isGlobal) {
		this.inActive = inActive;
		this.dueDays = dueDays;
		this.discountDays = discountDays;
		this.dueOnDay = dueOnDay;
		this.discOnDay = discOnDay;
		this.isGlobal = isGlobal;
	}

	public CuTerms(String description, boolean inActive, int dueDays,
			int discountDays, BigDecimal discountPercent, boolean dueOnDay,
			boolean discOnDay, String orderNote, String pickTicketNote1, 
			String pickTicketNote2,	String pickTicketNote3, String pickTicketNote4,
			String pickTicketNote5, boolean isGlobal) {
		this.description = description;
		this.inActive = inActive;
		this.dueDays = dueDays;
		this.discountDays = discountDays;
		this.discountPercent = discountPercent;
		this.dueOnDay = dueOnDay;
		this.discOnDay = discOnDay;
		this.orderNote = orderNote;
		this.pickTicketNote1 = pickTicketNote1;
		this.pickTicketNote2 = pickTicketNote2;
		this.pickTicketNote3 = pickTicketNote3;
		this.pickTicketNote4 = pickTicketNote4;
		this.pickTicketNote5 = pickTicketNote5;
		this.isGlobal = isGlobal;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cuTermsID", unique = true, nullable = false)
	public Integer getCuTermsId() {
		return this.cuTermsId;
	}

	public void setCuTermsId(Integer cuTermsId) {
		this.cuTermsId = cuTermsId;
	}

	@Column(name = "Description", length = 35)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "InActive", nullable = false)
	public boolean isInActive() {
		return this.inActive;
	}

	public void setInActive(boolean inActive) {
		this.inActive = inActive;
	}

	@Column(name = "DueDays", nullable = false)
	public int getDueDays() {
		return this.dueDays;
	}

	public void setDueDays(int dueDays) {
		this.dueDays = dueDays;
	}

	@Column(name = "DiscountDays", nullable = false)
	public int getDiscountDays() {
		return this.discountDays;
	}

	public void setDiscountDays(int discountDays) {
		this.discountDays = discountDays;
	}

	@Column(name = "DiscountPercent", scale = 4)
	public BigDecimal getDiscountPercent() {
		return this.discountPercent;
	}

	public void setDiscountPercent(BigDecimal discountPercent) {
		this.discountPercent = discountPercent;
	}

	@Column(name = "DueOnDay", nullable = false)
	public boolean isDueOnDay() {
		return this.dueOnDay;
	}

	public void setDueOnDay(boolean dueOnDay) {
		this.dueOnDay = dueOnDay;
	}

	@Column(name = "DiscOnDay", nullable = false)
	public boolean isDiscOnDay() {
		return this.discOnDay;
	}

	public void setDiscOnDay(boolean discOnDay) {
		this.discOnDay = discOnDay;
	}

	@Column(name = "OrderNote")
	public String getOrderNote() {
		return this.orderNote;
	}

	public void setOrderNote(String orderNote) {
		this.orderNote = orderNote;
	}

	@Column(name = "PickTicketNote1", length = 31)
	public String getPickTicketNote1() {
		return this.pickTicketNote1;
	}

	public void setPickTicketNote1(String pickTicketNote1) {
		this.pickTicketNote1 = pickTicketNote1;
	}

	@Column(name = "PickTicketNote2", length = 31)
	public String getPickTicketNote2() {
		return this.pickTicketNote2;
	}

	public void setPickTicketNote2(String pickTicketNote2) {
		this.pickTicketNote2 = pickTicketNote2;
	}

	@Column(name = "PickTicketNote3", length = 31)
	public String getPickTicketNote3() {
		return this.pickTicketNote3;
	}

	public void setPickTicketNote3(String pickTicketNote3) {
		this.pickTicketNote3 = pickTicketNote3;
	}

	@Column(name = "PickTicketNote4", length = 31)
	public String getPickTicketNote4() {
		return this.pickTicketNote4;
	}

	public void setPickTicketNote4(String pickTicketNote4) {
		this.pickTicketNote4 = pickTicketNote4;
	}

	@Column(name = "PickTicketNote5", length = 31)
	public String getPickTicketNote5() {
		return this.pickTicketNote5;
	}

	public void setPickTicketNote5(String pickTicketNote5) {
		this.pickTicketNote5 = pickTicketNote5;
	}

	@Column(name="IsGlobal", nullable=false)
    public boolean getIsGlobal() {
        return this.isGlobal;
    }
    
    public void setIsGlobal(boolean isGlobal) {
        this.isGlobal = isGlobal;
    }
}
