package com.turborep.turbotracker.customer.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Quickar generated by hbm2java
 */
@Entity
@Table(name = "quickar", catalog = "")
public class Quickar implements java.io.Serializable {

	private Integer quickArid;
	private Integer rxMasterId;
	private Date invoiceDate;
	private String invoiceNumber;
	private BigDecimal invoiceAmount;

	public Quickar() {
	}

	public Quickar(BigDecimal invoiceAmount) {
		this.invoiceAmount = invoiceAmount;
	}

	public Quickar(Integer rxMasterId, Date invoiceDate, String invoiceNumber,
			BigDecimal invoiceAmount) {
		this.rxMasterId = rxMasterId;
		this.invoiceDate = invoiceDate;
		this.invoiceNumber = invoiceNumber;
		this.invoiceAmount = invoiceAmount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "QuickARID", unique = true, nullable = false)
	public Integer getQuickArid() {
		return this.quickArid;
	}

	public void setQuickArid(Integer quickArid) {
		this.quickArid = quickArid;
	}

	@Column(name = "rxMasterID")
	public Integer getRxMasterId() {
		return this.rxMasterId;
	}

	public void setRxMasterId(Integer rxMasterId) {
		this.rxMasterId = rxMasterId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InvoiceDate", length = 0)
	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	@Column(name = "InvoiceNumber", length = 20)
	public String getInvoiceNumber() {
		return this.invoiceNumber;
	}

	public void setInvoiceNumber(String invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	@Column(name = "InvoiceAmount", nullable = false, scale = 4)
	public BigDecimal getInvoiceAmount() {
		return this.invoiceAmount;
	}

	public void setInvoiceAmount(BigDecimal invoiceAmount) {
		this.invoiceAmount = invoiceAmount;
	}

}
