package com.turborep.turbotracker.customer.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Quickap generated by hbm2java
 */
@Entity
@Table(name = "quickap", catalog = "")
public class Quickap implements java.io.Serializable {

	private Integer quickApid;
	private Integer rxMasterId;
	private Date invoiceDate;
	private String invoiceNumber;
	private BigDecimal invoiceAmount;

	public Quickap() {
	}

	public Quickap(BigDecimal invoiceAmount) {
		this.invoiceAmount = invoiceAmount;
	}

	public Quickap(Integer rxMasterId, Date invoiceDate, String invoiceNumber,
			BigDecimal invoiceAmount) {
		this.rxMasterId = rxMasterId;
		this.invoiceDate = invoiceDate;
		this.invoiceNumber = invoiceNumber;
		this.invoiceAmount = invoiceAmount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "QuickAPID", unique = true, nullable = false)
	public Integer getQuickApid() {
		return this.quickApid;
	}

	public void setQuickApid(Integer quickApid) {
		this.quickApid = quickApid;
	}

	@Column(name = "rxMasterID")
	public Integer getRxMasterId() {
		return this.rxMasterId;
	}

	public void setRxMasterId(Integer rxMasterId) {
		this.rxMasterId = rxMasterId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InvoiceDate", length = 0)
	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	@Column(name = "InvoiceNumber", length = 20)
	public String getInvoiceNumber() {
		return this.invoiceNumber;
	}

	public void setInvoiceNumber(String invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	@Column(name = "InvoiceAmount", nullable = false, scale = 4)
	public BigDecimal getInvoiceAmount() {
		return this.invoiceAmount;
	}

	public void setInvoiceAmount(BigDecimal invoiceAmount) {
		this.invoiceAmount = invoiceAmount;
	}

}
