package com.turborep.turbotracker.customer.dao;

// Generated Jan 23, 2012 5:39:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Cuinvoice generated by hbm2java
 */
@Entity
@Table(name = "tpCuInvoiceLogMaster", catalog = "")
public class TpCuinvoiceLogMaster implements java.io.Serializable {
	private Integer tpCuInvoiceLogMasterID;
	private Integer cuInvoiceId;
	private Integer changedById;
	private Date changedOn;
	private String changedByName;
	private Integer joReleaseDetailId;
	private Integer cuSoid;
	private Integer rxCustomerId;
	private Integer rxShipToId;
	private Integer rxShipToAddressId;
	private Integer prFromWarehouseId;
	private Integer prToWarehouseId;
	private Integer cuTermsId;
	private byte shipToMode;
	private Integer coTaxTerritoryId;
	private String invoiceNumber;
	private String customerPonumber;
	private Date invoiceDate;
	private Date shipDate;
	private Date dueDate;
	private Date printDate;	
	private Integer cuAssignmentId0;	
	private Integer cuAssignmentId1;
	private Integer creditmemo;
	private Integer iscredit;
	private Integer memoStatus;
	private String reason;
	private String cuAssignmentName0;
	private String cuAssignmentName1;
	private Integer createdById;
	private Date createdOn;
	private String createdByName;
	private String transType;
	
	private String state;
	private String county;
	private String countyCode;
	private String soNumber;
	private BigDecimal invoiceAmount;
	private BigDecimal lastInvoiceAmount;
	private BigDecimal appliedAmount;
	private BigDecimal lastAppliedAmount;
	private BigDecimal discountAmt;
	private BigDecimal lastDiscountAmt;
	private BigDecimal subtotal;
	private BigDecimal lastSubtotal;
	private BigDecimal freight;
	private BigDecimal lastFreight;
	private BigDecimal addCost;
	private BigDecimal lastAddCost;
	private BigDecimal costTotal;
	private BigDecimal lastCostTotal;
	private BigDecimal taxAmount;
	private BigDecimal lastTaxAmount;
	private BigDecimal taxableSales;
	private BigDecimal nonTaxableSales;
	private BigDecimal taxRate;
	private BigDecimal lastTaxRate;
	private byte isTaxShipping;
	private BigDecimal stateTax;
	private BigDecimal cityTax;
	private BigDecimal countyTax;
	private BigDecimal mTATax;
	private BigDecimal cCDTax;
	private BigDecimal otherTax;
	private BigDecimal taxDistribution1;
	private BigDecimal taxDistribution2;
	private BigDecimal taxDistribution3;
	private BigDecimal taxDistribution4;
	private BigDecimal taxDistribution5;
	private String description;
	private String note;
	private String pONumber;
	private String salesPerson;
	private Integer SalesPersionId;
	private String customerName;
	private Integer joReleaseID;
	private String JobNumber;
	private String JobName;
	private Integer transStatus;
	private Integer lastcoTaxTerritoryId;
	private String fyear;
	private Integer fperiod;
	
	public TpCuinvoiceLogMaster(){
		
	}
	
	public TpCuinvoiceLogMaster(byte shipToMode, BigDecimal invoiceAmount,
			BigDecimal appliedAmount, BigDecimal taxAmount) {
		this.shipToMode = shipToMode;
		this.invoiceAmount = invoiceAmount;
		this.appliedAmount = appliedAmount;
		this.taxAmount = taxAmount;
	}

	public TpCuinvoiceLogMaster(Integer changedById,
			Date changedOn,	Integer joReleaseDetailId, Integer cuSoid, Integer rxCustomerId,
			Integer rxShipToId,Integer rxShipToAddressId,Integer prFromWarehouseId, Integer prToWarehouseId,
			Integer cuTermsId, byte shipToMode, Integer coTaxTerritoryId,
			String invoiceNumber, String customerPonumber, Date invoiceDate, Date shipDate, Date dueDate, Date printDate,
			BigDecimal invoiceAmount, BigDecimal appliedAmount,BigDecimal taxAmount, BigDecimal freight, BigDecimal costTotal,
			BigDecimal subtotal, BigDecimal taxRate,Integer cuAssignmentId0, Integer cuAssignmentId1) {
		this.changedById = changedById;
		this.changedOn = changedOn;
		this.joReleaseDetailId = joReleaseDetailId;
		this.cuSoid = cuSoid;
		this.rxCustomerId = rxCustomerId;
		this.rxShipToId = rxShipToId;
		this.rxShipToAddressId = rxShipToAddressId;
		this.prFromWarehouseId = prFromWarehouseId;
		this.prToWarehouseId = prToWarehouseId;
		this.cuTermsId = cuTermsId;
		this.shipToMode = shipToMode;
		this.coTaxTerritoryId = coTaxTerritoryId;
		this.invoiceNumber = invoiceNumber;
		this.customerPonumber = customerPonumber;
		this.invoiceDate = invoiceDate;
		this.shipDate = shipDate;
		this.dueDate = dueDate;
		this.printDate = printDate;
		this.invoiceAmount = invoiceAmount;
		this.appliedAmount = appliedAmount;
		this.taxAmount = taxAmount;
		this.freight = freight;
		this.costTotal = costTotal;
		this.subtotal = subtotal;
		this.taxRate = taxRate;
		this.cuAssignmentId0 = cuAssignmentId0;
		this.cuAssignmentId1 = cuAssignmentId1;
		this.shipToMode = shipToMode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tpCuInvoiceLogMasterID", unique = true, nullable = false)
	public Integer getTpCuInvoiceLogMasterID() {
		return tpCuInvoiceLogMasterID;
	}

	public void setTpCuInvoiceLogMasterID(Integer tpCuInvoiceLogMasterID) {
		this.tpCuInvoiceLogMasterID = tpCuInvoiceLogMasterID;
	}
	
	@Column(name = "cuInvoiceID")
	public Integer getCuInvoiceId() {
		return this.cuInvoiceId;
	}

	public void setCuInvoiceId(Integer cuInvoiceId) {
		this.cuInvoiceId = cuInvoiceId;
	}

	@Column(name = "ChangedByID")
	public Integer getChangedById() {
		return this.changedById;
	}

	public void setChangedById(Integer changedById) {
		this.changedById = changedById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ChangedOn", length = 0)
	public Date getChangedOn() {
		return this.changedOn;
	}

	public void setChangedOn(Date changedOn) {
		this.changedOn = changedOn;
	}

	@Column(name = "joReleaseDetailID")
	public Integer getJoReleaseDetailId() {
		return this.joReleaseDetailId;
	}

	public void setJoReleaseDetailId(Integer joReleaseDetailId) {
		this.joReleaseDetailId = joReleaseDetailId;
	}

	@Column(name = "cuSOID")
	public Integer getCuSoid() {
		return this.cuSoid;
	}

	public void setCuSoid(Integer cuSoid) {
		this.cuSoid = cuSoid;
	}

	@Column(name = "rxCustomerID")
	public Integer getRxCustomerId() {
		return this.rxCustomerId;
	}

	public void setRxCustomerId(Integer rxCustomerId) {
		this.rxCustomerId = rxCustomerId;
	}


	@Column(name = "rxShipToID")
	public Integer getRxShipToId() {
		return this.rxShipToId;
	}

	public void setRxShipToId(Integer rxShipToId) {
		this.rxShipToId = rxShipToId;
	}

	@Column(name = "rxShipToAddressID")
	public Integer getRxShipToAddressId() {
		return this.rxShipToAddressId;
	}

	public void setRxShipToAddressId(Integer rxShipToAddressId) {
		this.rxShipToAddressId = rxShipToAddressId;
	}

	@Column(name = "prFromWarehouseID")
	public Integer getPrFromWarehouseId() {
		return this.prFromWarehouseId;
	}

	public void setPrFromWarehouseId(Integer prFromWarehouseId) {
		this.prFromWarehouseId = prFromWarehouseId;
	}

	@Column(name = "prToWarehouseID")
	public Integer getPrToWarehouseId() {
		return this.prToWarehouseId;
	}

	public void setPrToWarehouseId(Integer prToWarehouseId) {
		this.prToWarehouseId = prToWarehouseId;
	}

	@Column(name = "cuTermsID")
	public Integer getCuTermsId() {
		return this.cuTermsId;
	}

	public void setCuTermsId(Integer cuTermsId) {
		this.cuTermsId = cuTermsId;
	}

	@Column(name = "ShipToMode", nullable = false)
	public byte getShipToMode() {
		return this.shipToMode;
	}

	public void setShipToMode(byte shipToMode) {
		this.shipToMode = shipToMode;
	}

	@Column(name = "coTaxTerritoryID")
	public Integer getCoTaxTerritoryId() {
		return this.coTaxTerritoryId;
	}

	public void setCoTaxTerritoryId(Integer coTaxTerritoryId) {
		this.coTaxTerritoryId = coTaxTerritoryId;
	}

	@Column(name = "InvoiceNumber", length = 20)
	public String getInvoiceNumber() {
		return this.invoiceNumber;
	}

	public void setInvoiceNumber(String invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	@Column(name = "CustomerPONumber", length = 20)
	public String getCustomerPonumber() {
		return this.customerPonumber;
	}

	public void setCustomerPonumber(String customerPonumber) {
		this.customerPonumber = customerPonumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InvoiceDate", length = 0)
	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ShipDate", length = 0)
	public Date getShipDate() {
		return this.shipDate;
	}

	public void setShipDate(Date shipDate) {
		this.shipDate = shipDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DueDate", length = 0)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PrintDate", length = 0)
	public Date getPrintDate() {
		return this.printDate;
	}

	public void setPrintDate(Date printDate) {
		this.printDate = printDate;
	}

	@Column(name = "InvoiceAmount", nullable = false, scale = 4)
	public BigDecimal getInvoiceAmount() {
		return this.invoiceAmount;
	}

	public void setInvoiceAmount(BigDecimal invoiceAmount) {
		this.invoiceAmount = invoiceAmount;
	}

	@Column(name = "AppliedAmount", nullable = false, scale = 4)
	public BigDecimal getAppliedAmount() {
		return this.appliedAmount;
	}

	public void setAppliedAmount(BigDecimal appliedAmount) {
		this.appliedAmount = appliedAmount;
	}

	@Column(name = "TaxAmount", nullable = false, scale = 4)
	public BigDecimal getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(BigDecimal taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Column(name = "Freight", scale = 4)
	public BigDecimal getFreight() {
		return this.freight;
	}

	public void setFreight(BigDecimal freight) {
		this.freight = freight;
	}

	@Column(name = "CostTotal", scale = 4)
	public BigDecimal getCostTotal() {
		return this.costTotal;
	}

	public void setCostTotal(BigDecimal costTotal) {
		this.costTotal = costTotal;
	}

	@Column(name = "Subtotal", scale = 4)
	public BigDecimal getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(BigDecimal subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "TaxRate", scale = 4)
	public BigDecimal getTaxRate() {
		return this.taxRate;
	}

	public void setTaxRate(BigDecimal taxRate) {
		this.taxRate = taxRate;
	}

	@Column(name = "cuAssignmentID0")
	public Integer getCuAssignmentId0() {
		return this.cuAssignmentId0;
	}

	public void setCuAssignmentId0(Integer cuAssignmentId0) {
		this.cuAssignmentId0 = cuAssignmentId0;
	}

	@Column(name = "cuAssignmentID1")
	public Integer getCuAssignmentId1() {
		return this.cuAssignmentId1;
	}

	public void setCuAssignmentId1(Integer cuAssignmentId1) {
		this.cuAssignmentId1 = cuAssignmentId1;
	}

	@Column(name = "CreditMemo")
	public Integer getCreditmemo() {
		return creditmemo;
	}

	public void setCreditmemo(Integer creditmemo) {
		this.creditmemo = creditmemo;
	}

	@Column(name = "IsCredit")
	public Integer getIscredit() {
		return iscredit;
	}

	public void setIscredit(Integer iscredit) {
		this.iscredit = iscredit;
	}

	@Column(name = "memoStatus")
	public Integer getMemoStatus() {
		return memoStatus;
	}

	public void setMemoStatus(Integer memoStatus) {
		this.memoStatus = memoStatus;
	}
	
	@Transient
	public String getCuAssignmentName0() {
		return cuAssignmentName0;
	}

	public void setCuAssignmentName0(String cuAssignmentName0) {
		this.cuAssignmentName0 = cuAssignmentName0;
	}
	@Transient
	public String getCuAssignmentName1() {
		return cuAssignmentName1;
	}

	public void setCuAssignmentName1(String cuAssignmentName1) {
		this.cuAssignmentName1 = cuAssignmentName1;
	}
	
	
	@Column(name = "reason")
	public String getReason() {
		return reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "ChangedByName")	
	public String getChangedByName() {
		return changedByName;
	}

	public void setChangedByName(String changedByName) {
		this.changedByName = changedByName;
	}

	@Column(name = "CreatedByID")
	public Integer getCreatedById() {
		return createdById;
	}

	public void setCreatedById(Integer createdById) {
		this.createdById = createdById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn")	
	public Date getCreatedOn() {
		return createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "CreatedByName")
	public String getCreatedByName() {
		return createdByName;
	}

	public void setCreatedByName(String createdByName) {
		this.createdByName = createdByName;
	}

	@Column(name = "transType")
	public String getTransType() {
		return transType;
	}

	public void setTransType(String transType) {
		this.transType = transType;
	}

	@Column(name = "State")
	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "County")
	public String getCounty() {
		return county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "CountyCode")
	public String getCountyCode() {
		return countyCode;
	}

	public void setCountyCode(String countyCode) {
		this.countyCode = countyCode;
	}

	@Column(name = "SONumber")
	public String getSoNumber() {
		return soNumber;
	}

	public void setSoNumber(String soNumber) {
		this.soNumber = soNumber;
	}

	@Column(name = "LastInvoiceAmount")
	public BigDecimal getLastInvoiceAmount() {
		return lastInvoiceAmount;
	}

	public void setLastInvoiceAmount(BigDecimal lastInvoiceAmount) {
		this.lastInvoiceAmount = lastInvoiceAmount;
	}

	@Column(name = "LastAppliedAmount")
	public BigDecimal getLastAppliedAmount() {
		return lastAppliedAmount;
	}

	public void setLastAppliedAmount(BigDecimal lastAppliedAmount) {
		this.lastAppliedAmount = lastAppliedAmount;
	}

	@Column(name = "DiscountAmt")
	public BigDecimal getDiscountAmt() {
		return discountAmt;
	}

	public void setDiscountAmt(BigDecimal discountAmt) {
		this.discountAmt = discountAmt;
	}

	@Column(name = "LastDiscountAmt")
	public BigDecimal getLastDiscountAmt() {
		return lastDiscountAmt;
	}

	public void setLastDiscountAmt(BigDecimal lastDiscountAmt) {
		this.lastDiscountAmt = lastDiscountAmt;
	}

	@Column(name = "LastSubtotal")
	public BigDecimal getLastSubtotal() {
		return lastSubtotal;
	}

	public void setLastSubtotal(BigDecimal lastSubtotal) {
		this.lastSubtotal = lastSubtotal;
	}

	@Column(name = "LastFreight")
	public BigDecimal getLastFreight() {
		return lastFreight;
	}

	public void setLastFreight(BigDecimal lastFreight) {
		this.lastFreight = lastFreight;
	}

	@Column(name = "AddCost")
	public BigDecimal getAddCost() {
		return addCost;
	}

	public void setAddCost(BigDecimal addCost) {
		this.addCost = addCost;
	}

	@Column(name = "LastAddCost")
	public BigDecimal getLastAddCost() {
		return lastAddCost;
	}

	public void setLastAddCost(BigDecimal lastAddCost) {
		this.lastAddCost = lastAddCost;
	}

	@Column(name = "LastCostTotal")
	public BigDecimal getLastCostTotal() {
		return lastCostTotal;
	}

	public void setLastCostTotal(BigDecimal lastCostTotal) {
		this.lastCostTotal = lastCostTotal;
	}

	@Column(name = "LastTaxAmount")
	public BigDecimal getLastTaxAmount() {
		return lastTaxAmount;
	}

	public void setLastTaxAmount(BigDecimal lastTaxAmount) {
		this.lastTaxAmount = lastTaxAmount;
	}

	@Column(name = "TaxableSales")
	public BigDecimal getTaxableSales() {
		return taxableSales;
	}

	public void setTaxableSales(BigDecimal taxableSales) {
		this.taxableSales = taxableSales;
	}
	
	@Column(name = "NonTaxableSales")
	public BigDecimal getNonTaxableSales() {
		return nonTaxableSales;
	}

	public void setNonTaxableSales(BigDecimal nonTaxableSales) {
		this.nonTaxableSales = nonTaxableSales;
	}

	@Column(name = "IsTaxShipping")
	public byte getIsTaxShipping() {
		return isTaxShipping;
	}

	public void setIsTaxShipping(byte isTaxShipping) {
		this.isTaxShipping = isTaxShipping;
	}

	@Column(name = "StateTax")
	public BigDecimal getStateTax() {
		return stateTax;
	}

	public void setStateTax(BigDecimal stateTax) {
		this.stateTax = stateTax;
	}

	@Column(name = "CityTax")
	public BigDecimal getCityTax() {
		return cityTax;
	}

	public void setCityTax(BigDecimal cityTax) {
		this.cityTax = cityTax;
	}

	@Column(name = "CountyTax")
	public BigDecimal getCountyTax() {
		return countyTax;
	}

	public void setCountyTax(BigDecimal cuntyTax) {
		this.countyTax = cuntyTax;
	}

	@Column(name = "MTATax")
	public BigDecimal getMTATax() {
		return mTATax;
	}

	public void setMTATax(BigDecimal mTATax) {
		this.mTATax = mTATax;
	}

	@Column(name = "CCDTax")
	public BigDecimal getCCDTax() {
		return cCDTax;
	}

	public void setCCDTax(BigDecimal cCDTax) {
		this.cCDTax = cCDTax;
	}

	@Column(name = "OtherTax")
	public BigDecimal getOtherTax() {
		return otherTax;
	}

	public void setOtherTax(BigDecimal otherTax) {
		this.otherTax = otherTax;
	}

	@Column(name = "TaxDistribution1")
	public BigDecimal getTaxDistribution1() {
		return taxDistribution1;
	}

	public void setTaxDistribution1(BigDecimal taxDistribution1) {
		this.taxDistribution1 = taxDistribution1;
	}

	@Column(name = "TaxDistribution2")
	public BigDecimal getTaxDistribution2() {
		return taxDistribution2;
	}

	public void setTaxDistribution2(BigDecimal taxDistribution2) {
		this.taxDistribution2 = taxDistribution2;
	}

	@Column(name = "TaxDistribution3")
	public BigDecimal getTaxDistribution3() {
		return taxDistribution3;
	}

	public void setTaxDistribution3(BigDecimal taxDistribution3) {
		this.taxDistribution3 = taxDistribution3;
	}

	@Column(name = "TaxDistribution4")
	public BigDecimal getTaxDistribution4() {
		return taxDistribution4;
	}

	public void setTaxDistribution4(BigDecimal taxDistribution4) {
		this.taxDistribution4 = taxDistribution4;
	}

	@Column(name = "TaxDistribution5")
	public BigDecimal getTaxDistribution5() {
		return taxDistribution5;
	}

	public void setTaxDistribution5(BigDecimal taxDistribution5) {
		this.taxDistribution5 = taxDistribution5;
	}

	@Column(name = "Description")
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Note")
	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "PONumber")
	public String getPONumber() {
		return pONumber;
	}

	public void setPONumber(String pONumber) {
		this.pONumber = pONumber;
	}

	@Column(name = "SalesPerson")
	public String getSalesPerson() {
		return salesPerson;
	}

	public void setSalesPerson(String salesPerson) {
		this.salesPerson = salesPerson;
	}

	@Column(name = "SalesPersionId")
	public Integer getSalesPersionId() {
		return SalesPersionId;
	}

	public void setSalesPersionId(Integer salesPersionId) {
		SalesPersionId = salesPersionId;
	}

	@Column(name = "CustomerName")
	public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "joReleaseID")
	public Integer getJoReleaseID() {
		return joReleaseID;
	}

	public void setJoReleaseID(Integer joReleaseID) {
		this.joReleaseID = joReleaseID;
	}

	@Column(name = "JobNumber")
	public String getJobNumber() {
		return JobNumber;
	}

	public void setJobNumber(String jobNumber) {
		JobNumber = jobNumber;
	}

	@Column(name = "JobName")
	public String getJobName() {
		return JobName;
	}

	public void setJobName(String jobName) {
		JobName = jobName;
	}

	@Column(name = "LastTaxRate")
	public BigDecimal getLastTaxRate() {
		return lastTaxRate;
	}

	public void setLastTaxRate(BigDecimal lastTaxRate) {
		this.lastTaxRate = lastTaxRate;
	}

	@Column(name = "transStatus")
	public Integer getTransStatus() {
		return transStatus;
	}

	public void setTransStatus(Integer transStatus) {
		this.transStatus = transStatus;
	}

	@Column(name = "LastcoTaxTerritoryID")
	public Integer getLastcoTaxTerritoryId() {
		return lastcoTaxTerritoryId;
	}

	public void setLastcoTaxTerritoryId(Integer lastcoTaxTerritoryId) {
		this.lastcoTaxTerritoryId = lastcoTaxTerritoryId;
	}

	@Column(name = "fyear")
	public String getFyear() {
		return fyear;
	}

	public void setFyear(String fyear) {
		this.fyear = fyear;
	}

	@Column(name = "fperiod")
	public Integer getFperiod() {
		return fperiod;
	}

	public void setFperiod(Integer fperiod) {
		this.fperiod = fperiod;
	}

	
	
	
}
