ALTER TABLE `joMaster` CHANGE COLUMN `JobNumber` `JobNumber` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL  ;

ALTER TABLE `joMaster` CHANGE COLUMN `QuoteNumber` `QuoteNumber` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL  ;